### ISSUE TITLE
Iris seems to conflict with CMI and cannot be enabled together

### ISSUE THREAD

**Issue by yukaling** [VolmitSoftware/Iris#1006]
### Problem

1. Download and put the latest Iris-2.7.3-1.20.1 jar file to directory 'plugins' , 'plugins' also have CMI-9.6.1.3 and CMILib-1.4.0.1
2. Use shell script and run server
3. Waiting for downloading library and loading other resources
4. Got a problem on console which caused Iris and CMI & CMILib cannot be enabled together.

### Solution

Initially, I am going to run my server with Iris, CMI and other plugins but then I found this error that made Iris cannot be enabled but CMI can be, so I removed all plugins except Iris and run server again then it was correctly loaded.

I wonder that how can I solve the problem or waiting for bug fix? Appreciate your reply, thanks.  :D

* CORRECT * Minecraft Version should be 1.20.1
But here is not this option.

### Minecraft Version

1.19

### Iris Version

2.7.3-1.20.1

### Log

* Plugin conflict checking over here ↓ (In this test, I just reserved Iris and CMI & CMILib)
https://mclo.gs/HScSO2y
* Problem first found over here ↓
https://mclo.gs/QToiD7a
These two different log has same version of iris and Minecraft, but server running on linux has more plugins.

**Comment by RePixelatedMC** [comment]
Is this a joke

**Comment by svdgoor** [comment]
Good question. This isn't Iris related at all lol. Iris has 0 errors and if CMI is getting errors when used with Iris I really don't think we're the problem when all the exceptions are thrown from their software.

**Comment by RePixelatedMC** [comment]
Its probably due to it being a cracked cmi jar what is illegal btw from the website directleaks

**Comment by RePixelatedMC** [comment]
So @yukaling that should answer ur question feel free to come back when you own a legal version of the cmi plugin

**Comment by yukaling** [comment]
Got the point thank u for patient answers :D
I appreciate u can make this awesome world generator and I hope it can be better !
Best wishes!
