### ISSUE TITLE
Feature request: (Required for nether generation + could solve water issues in overworld) Update liquids

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#101]
It would be required to make lava-falls to be able to update fluids by a toggle. I understand this is laggy, but it is absolutely required for the nether.

**Comment by svdgoor** [comment]
Perhaps adding a check that if the water block has a normal block on the horisontal plane next to it, only to update it then, would be better

**Comment by svdgoor** [comment]
No longer required because of Sliver stuff coming up
