### ISSUE TITLE
Objects spawn strangely 

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#1012]
### Problem

![image](https://github.com/VolmitSoftware/Iris/assets/107539181/bcd4b5d0-1e52-4b9e-a0f4-3c631cec4cb2)

very noticeable when you have multiple columns in ur objects column 

### Minecraft Version

1.21

### Iris Version

2.7.6

### Log

*

**Comment by RePixelatedMC** [comment]
![2023-09-06_18 09 03](https://github.com/VolmitSoftware/Iris/assets/107539181/44f55b33-0831-402d-8ad0-1db337c3af72)

**Comment by NextdoorPsycho** [comment]
You have used these same pictures over and over again. to describe different issues, closing this
