### ISSUE TITLE
Jigsaw rarity broken/weird

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#1020]
### Problem

![image](https://github.com/VolmitSoftware/Iris/assets/107539181/9aa5315d-2dcb-4979-abc4-490bfebb05a5)
Rarity: 2400 

like there is a very long time nearly nothing and then random groups of buildings or oddly close to each other / not guaranteed but still a bit strange 

### Solution

*

### Minecraft Version

1.21

### Iris Version

2.7.5

### Log

*

**Comment by NextdoorPsycho** [comment]
its deeded random iirc, if you change the seed its different. if you are in the studio its always 1337. Id need to see the jigsaw, and what/how you are spawning it
