### ISSUE TITLE
Jigsaw > starting piece always rotates even when not allowed to

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#1024]
### Problem

![2023-09-06_17 31 44](https://github.com/VolmitSoftware/Iris/assets/107539181/eeb3a7c5-5ae7-4109-80b0-da53408cc7f4)
starting piece always rotates even when not allowed to with jigsaw

### Minecraft Version

1.21

### Iris Version

2.7.6

### Log

*

**Comment by NextdoorPsycho** [comment]
should be fixed in coco's PR
