### ISSUE TITLE
Jigsaw > when rotated pieces completely misalign 

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#1025]
### Problem

when rotated pieces completely misalign 
![2023-09-06_17 32 28](https://github.com/VolmitSoftware/Iris/assets/107539181/5a7f8d91-230c-453a-8af1-10d8344c161c)

### Minecraft Version

1.14.X

### Iris Version

2.7.6

### Log

*

**Comment by NextdoorPsycho** [comment]
This title makes no sense, not does the image help, this is the 5th time seeing it. Stop wasting my time
