### ISSUE TITLE
Bug: /iris create (without parameters after) causes error

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#103]
![afbeelding](https://user-images.githubusercontent.com/65736624/96620154-5b285200-1307-11eb-8939-4dfa791e1ab6.png)

Should print command description instead

**Comment by svdgoor** [comment]
Correction, it does print command description but it also prints the error

**Comment by cyberpwnn** [comment]
Fixed in 1.0.22
