### ISSUE TITLE
Ores should match with vanilla

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#104]
![afbeelding](https://user-images.githubusercontent.com/65736624/96621093-7b0c4580-1308-11eb-86d9-006f629aaab7.png)

Here you see the results of some tests.
The right hand column indicates the percentage increase from the expected amount.
>100% means too many, <100% means too little.
Especially coal and iron ore are affected, but redstone is halved as well.
Too many diamond and lapiz ores

**Comment by svdgoor** [comment]
Props to @ Deadlykill#4026 for test results

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96621535-05ed4000-1309-11eb-87c1-19f7959f737c.png)

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96622209-ee628700-1309-11eb-8c47-ab8695dbe45d.png)

Note: Iris' world height is 50 blocks above vanilla.
Multiplying by 1.6-1.7 would give a more accurate percentage
(if %<100 then devide by 1.6-1.7)

**Comment by svdgoor** [comment]
Tested in the same biomes on vanilla and Iris (Plains and Forest)
Screenshot of iris:
![afbeelding](https://user-images.githubusercontent.com/65736624/96622387-279af700-130a-11eb-8685-3a4154589f21.png)

Screenshot of vanilla:
![afbeelding](https://user-images.githubusercontent.com/65736624/96622590-6f218300-130a-11eb-9fc6-e8c9004ad3dc.png)

**Comment by cyberpwnn** [comment]
Ores can be tweaked here: https://github.com/IrisDimensions/overworld/blob/master/dimensions/overworld.json. We diddnt intend for them to perfectly line up with vanilla, however if somemone wouldnt mind putting in a pr for it, i would accept it.

**Comment by svdgoor** [comment]
I'll work on this

**Comment by NextdoorPsycho** [comment]
> Ores can be tweaked here: https://github.com/IrisDimensions/overworld/blob/master/dimensions/overworld.json. We diddnt intend for them to perfectly line up with vanilla, however if somemone wouldnt mind putting in a pr for it, i would accept it.

same

**Comment by NextdoorPsycho** [comment]
The community does not want this btw

**Comment by NextdoorPsycho** [comment]
****
![image](https://user-images.githubusercontent.com/29320316/97119195-c4bfac00-16cb-11eb-8df3-452cabc95196.png)

**Comment by svdgoor** [comment]
I didn't make them vanilla either, I made them half of vanilla. If you don't agree with that let's continue the conversation lmao.
I don't exactly know what would be preffered, just that IMO 15% of vanilla gold in the world is just too little

**Comment by svdgoor** [comment]
Discussed, changed stuff. Closing for now until someone new complains :)
