### ISSUE TITLE
Collection of world-gen stuff

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#105]
![afbeelding](https://user-images.githubusercontent.com/65736624/96628985-405bda80-1313-11eb-9448-45d7d573c4a8.png)
?

Notes:
Plains biomes seem too rare

**Comment by CocoTheOwner** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96630182-f1af4000-1314-11eb-90b6-d450ff3251a7.png)
Lava layers not matching

**Comment by CocoTheOwner** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96631300-6e8ee980-1316-11eb-937d-2cfdb8a2ff65.png)
![afbeelding](https://user-images.githubusercontent.com/65736624/96631322-751d6100-1316-11eb-87f1-19d3a97f062c.png)

**Comment by CocoTheOwner** [comment]
@NextdoorPsycho

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96729402-65a12500-13b5-11eb-902e-f129be5ee915.png)

Leaves in the center don't make sense there

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96901067-16312680-1493-11eb-9609-1a32dfb0f3c1.png)
All sugarcanes are 4 or 5 high, no shorter

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96901879-1d0c6900-1494-11eb-917e-39e5938654e7.png)
Very straight line and no overlap between desert and mosaic biomes

**Comment by CocoTheOwner** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96902837-4f6a9600-1495-11eb-85a2-cd552e03ed30.png)
![afbeelding](https://user-images.githubusercontent.com/65736624/96902860-55f90d80-1495-11eb-8047-cb922de266a6.png)

**Comment by CocoTheOwner** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96904255-264b0500-1497-11eb-99fa-bcc752e80489.png)
floating trees ontop of caves

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96904921-0bc55b80-1498-11eb-867b-8ba217d71c16.png)

coincidence? I think not

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96905885-54c9df80-1499-11eb-9a16-a6e0adb7f05b.png)

Perhaps they still spawn somewhat too frequently?

**Comment by CocoTheOwner** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96906065-935f9a00-1499-11eb-9a3e-52148e3d3014.png)

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96906995-e7b74980-149a-11eb-84a1-4c0c9bf47b4e.png)

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96907889-24d00b80-149c-11eb-98a3-409ef95481eb.png)

**Comment by NextdoorPsycho** [comment]
All resolved but this: i dont know what you want from me // what this is // what the problem is
![afbeelding](https://user-images.githubusercontent.com/65736624/96906995-e7b74980-149a-11eb-84a1-4c0c9bf47b4e.png)

_Originally posted by @CocoTheOwner in https://github.com/VolmitSoftware/Iris/issues/105#issuecomment-714637658_
