### ISSUE TITLE
Seed Randomness

### ISSUE THREAD

**Issue by SirDank** [VolmitSoftware/Iris#1086]
### Adding, Removing, or Changing

Changing

### Type of Modification

I want seeds to be random if not specified

### What are you trying to modify

The way I would implement this is by using a random 10 digit number instead of the default `1337`

### Alternatives

If this could not be implemented I would like an alternative implementation that allows `seed=random` or `seed=*` and for it to have the same result

**Comment by RePixelatedMC** [comment]
Long story, but its planned
