### ISSUE TITLE
it doesn't start the server

### ISSUE THREAD

**Issue by Lele289** [VolmitSoftware/Iris#1089]
### Problem

1. Install Iris
2. start the server, in my case I use purpur-1.20.4-2172.
3. the following error should appear in the console, which does not start the server and continues to restart the machine
4. error: https://pastebin.com/VEBffmiv

### Solution

I think the problem is in the code, but I don't know how to give a possible solution.
 I tried starting it on another server with different settings, but it still won't start
 
Java version 21, with the old versions, however they started in the java 21 version, from 3.2.+ it started to cause problems

### Minecraft Version

1.2

### Iris Version

Iris-3.2.0-1.19.2-1.20.4

### Log

https://pastebin.com/VEBffmiv

**Comment by CrazyDev05** [comment]
please provide the full log

**Comment by Lele289** [comment]
here is the complete log, in addition to the various iris warnings, don't pay attention to other plugins, since the server is new and I was configuring it now 
https://pastebin.com/TKzQsTuC

**Comment by CrazyDev05** [comment]
this is intended as iris needs to restart the server so that the datapack for custom biome colors and dimension height gets loaded

**Comment by CrazyDev05** [comment]
just start the server again and everything should be fine

**Comment by Lele289** [comment]
ok thanks now it works, before I tried to do it again, but it didn't start, however I solved it thanks to your support
