### ISSUE TITLE
Bad loot and no structures

### ISSUE THREAD

**Issue by xFireYTReal** [VolmitSoftware/Iris#1116]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to have Better loots and more spawn

### What are you trying to modify

The way I would implement this is a Better loot, maybe a customizable one with the config.yml.
And i would like a Better structure spawn, more villages and outpost. Since i've flyed for 3 hours and there was no One villages.

**Comment by RePixelatedMC** [comment]
I mean… you can already config it and secondly its not a iris issue. And you can also increase the village spawning rate

**Comment by xFireYTReal** [comment]
How can I increase the village spawning rate.

**Comment by NextdoorPsycho** [comment]
pick the structure you’re trying to increase, go to the folder where it’s
generating and then increase the rarity
