### ISSUE TITLE
1.21.3 Purpur version support | Update plugin

### ISSUE THREAD

**Issue by Futodama** [VolmitSoftware/Iris#1122]
### Problem

1. Install Iris latest
2. Start server 1.21.3
3. Wait server start
4. See the error and spam.

### Solution

In recent versions of the game, there have been multiple changes in the code, most likely this prevents the plugin from working, since everything works on version 1.21.1.

### Minecraft Version

1.21

### Iris Version

Iris-3.4.2

### Log

https://mclo.gs/OK0Hl7p

**Comment by CrazyDev05** [comment]
please take a moment to look at the only open PR #1115
it supports 1.21.3 but it isn't released as the default pack doesn't support it yet
