### ISSUE TITLE
Wrong block generation

### ISSUE THREAD

**Issue by yxc0915** [VolmitSoftware/Iris#1127]
### Problem

seed is 1337
Wrong chest generated
![QQ20241222-130248](https://github.com/user-attachments/assets/442cfc9a-9095-44c6-9530-bed5a53ead10)

### Minecraft Version

1.21

### Iris Version

3.4.2-1.19.2-1.21.1-f

### Log

unnecessary

**Comment by AvianAeternum** [comment]
Not related to seed, will fix in 3.5
