### ISSUE TITLE
Ravines do not follow colour pattern

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#115]
![afbeelding](https://user-images.githubusercontent.com/65736624/96624205-b872d200-130c-11eb-85ec-1535df6fa8a2.png)
 (recommend removing them altogether)
Also - lava in ravenes can be non-aligned with cave lava

**Comment by svdgoor** [comment]
Semi-intended since ravines and caves are vanilla features and should thus not be messed with. There may have been some improvement, but the general idea now is that one would create ravines with the caves and having access to customization that way.
