### ISSUE TITLE
A collection of errors related to iris commands

### ISSUE THREAD

**Issue by Seyarada** [VolmitSoftware/Iris#12]
This was perfomed with a clean Iris install using latest Iris & Paper

[latest.log](https://github.com/VolmitSoftware/Iris/files/5394927/latest.log)

Relevant lines:
102 -> java.io.IOException | /iris studio create TestDimension
169 -> ArrayIndexOutOfBoundsException: 0 | /iris ctc | This one is probably missing a has arguments check
200 -> NullPointerException | /iris studio open TestDimension
746 -> java.io.IOException | /iris create TestWorld TestDimension
805 -> NullPointerException | /iris studio loot 100
891 -> NullPointerException | Error when disabling Iris

Special mentions:
/iris studio editbiome | Doesn't throws an error but doesn't seems to do anything?

**Comment by cyberpwnn** [comment]
Thank you ill get these pushed out in 1.0.17

**Comment by cyberpwnn** [comment]
**Error when disabling Iris**: I need the exception for this one
**/iris create TestWorld TestDimension** : I need the actual exception for this one too
**/iris studio create TestDimension**: Pretty sure this was fixed, if not, I need the exception
**/iris studio open TestDimension**: I need the exception for this one

Fixed **/iris ctc**
Fixed **/iris studio loot 100**

**Comment by cyberpwnn** [comment]
oh the link
