### ISSUE TITLE
spawners with no meta

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#121]
![afbeelding](https://user-images.githubusercontent.com/65736624/96631300-6e8ee980-1316-11eb-937d-2cfdb8a2ff65.png)
![afbeelding](https://user-images.githubusercontent.com/65736624/96631322-751d6100-1316-11eb-87f1-19d3a97f062c.png)

**Comment by svdgoor** [comment]
procedural structure? (not sure, not reported by me)

**Comment by svdgoor** [comment]
@cyberpwnn Is this a config error or bug?
Assigning both of you.

**Comment by NextdoorPsycho** [comment]
@CocoTheOwner  is this a meta issue?
What is the ID of the spawner they are trying to spawn?

**Comment by svdgoor** [comment]
This is default overworld pack a couple versions ago (but I assume this has not been modified in the meanwhile).
I did not report this, but I have contacted the individual who did. Awaiting an answer, will keep you posted.

**Comment by svdgoor** [comment]
It's in a snow biome which has (as underlying minecraft biome) "Taiga_hills"
This can be any of:
![afbeelding](https://user-images.githubusercontent.com/65736624/96987691-a28b2a00-1523-11eb-8498-aab1e35138e1.png)

After eliminating non-ice/snow biomes with ice caves that leaves:
Frozen-mountains-cliffs
Frozen-peak
Frozen-pines
Frozen-redwoods-forest
Frozen-vander

**Comment by svdgoor** [comment]
@NextdoorPsycho I found a structure with an issue in it, which seems to be the same structure as this one:
![afbeelding](https://user-images.githubusercontent.com/65736624/96989732-63aaa380-1526-11eb-9e53-77c4d26c7948.png)

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96989835-89d04380-1526-11eb-9d52-04b8e7130ead.png)
With the help of the original reported we found another one

**Comment by svdgoor** [comment]
Pig spawner, like previously shown, in the frozen-ice-caverns

**Comment by svdgoor** [comment]
There appear to be two separate structures.
One looks like this:
![afbeelding](https://user-images.githubusercontent.com/65736624/96990635-a8830a00-1527-11eb-9ee9-cb2687f8ceff.png)

The other looks like the original post.


The former looks normal, but never has: campfire, shulker, spawner
The latter appears to not overwrite air blocks, but does have: campfire, shulker, spawner

The former and the latter seem to have that weird issue where some of the glass from the procedural structure creator is still showing.

**Comment by svdgoor** [comment]
Still unsure if this is a plugin or configuration error, so re-adding plugin.

**Comment by NextdoorPsycho** [comment]
This was resolved by adding the data to the block,and all the structs are working but prismarine, but thats in another issue
