### ISSUE TITLE
In general, biomes do not fade together well.

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#125]
**Describe the bug**
Biomes in Iris do not seem to fade well. Very straight lines, etc.
Unlike EWG (which makes EWG look better IMO)

**To Reproduce**
1. Find any biome in an Iris world and find where it becomes another

**Expected behavior + screenshots**
Better fading, example:
![afbeelding](https://user-images.githubusercontent.com/65736624/96971216-1c67e700-1515-11eb-826e-87caffa4ff69.png)
![afbeelding](https://user-images.githubusercontent.com/65736624/96971225-1f62d780-1515-11eb-87dd-a7626b51a319.png)

**Server and Plugin Informations**
 - Installed plugins: Iris, React, WorldEdit, MVCore, Essentials
 - Iris Version: 1.24
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Paper #240
 - Operating System (if applicable): Win10 64x

**Additional context**
This would make (in my opinion) Iris better or equally as good across the board.
Perhaps the biome sizes can be decreased alongside this change, as the current set-up has two issues:
1 - You have to really try (probably with /iris std goto) to find all biomes
2 - Very large biomes do not look nice (IMO)

**Comment by cyberpwnn** [comment]
I have a few ideas on how to get biomes to blend a bit better including dropping the biome size, however getting to exactly where you want it, along with village will require that core rewrite, which i'm fine with but cannot start on yet (so early in release) and given my schedule. I'm going to try to blend biomes a bit better (frozen into hot biomes for example) but the other features such as in that screenshot will be a bit later.

I dont think this is low or high priority. Its in the middle.

**Comment by svdgoor** [comment]
Take your time on this one. It's better to have this take long and do it properly than deliver some mediocre bandaid fix.
Already looking forward to the result

**Comment by svdgoor** [comment]
Looks to have been improved in V2 by a lot. Quite happy at this time.
