### ISSUE TITLE
Procedural structures, oak logs or wood blocks rotations not working

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#139]
**Describe the bug**
Rotation of the part of the structure does not also rotate the wood blocks

**To Reproduce**
1. Make a new procedural structure and place a directional wood block
2. Find a rotated version of that part and notice the oak did not change directions

**Expected behavior**
The wood changes directions accordingly

**Screenshots or Video Recordings**
Correct:
![afbeelding](https://user-images.githubusercontent.com/65736624/97124104-16e5e900-172f-11eb-8f59-bf719d1044fb.png)
Incorrect:
![afbeelding](https://user-images.githubusercontent.com/65736624/97124115-1fd6ba80-172f-11eb-9ad6-451f7be6ab16.png)

**Server and Plugin Informations**
 - Installed plugins: Nothing that interferes
 - Iris Version: .26
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Paper #240
 - Operating System (if applicable): Win10 64x

**Comment by svdgoor** [comment]
The same happens with walls and their connections. Only stairs seem to not show this issue. I presume glass panes have the same. Also doors and rails might

**Comment by cyberpwnn** [comment]
This might be a bug with the live view of the structure builder. These objects do properly rotate (ignoring portals, and rail tracks which actually do not work). Ill see if i can sync it better.

**Comment by svdgoor** [comment]
You're saying this is a live-view only issue?
I'll test if it happens when actually placing them as well later today.

**Comment by cyberpwnn** [comment]
Well... If the live view is showing it i think its going to save the problem. Test it on 1.0.30 because there was a lot of changes to stuff dealing with block data

**Comment by svdgoor** [comment]
Resolved in .30
