### ISSUE TITLE
Procedural structures add continuous generation

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#141]
**Is your feature request related to a problem? Please describe.**
When just enjoying my piece of art of a structure I want to never find an edge

**Describe the solution you'd like**
Make a toggle like /iris str constant where if you near an edge, it automatically expands in that direction (just like /iris str expand would do)

**Describe alternatives you've considered**
running the command by hand every single time (plz no)

**Comment by cyberpwnn** [comment]
The structure builder is terrrrrrrrrrribly slow. Instead, in your dimension, tell a biome to generate a structure at max density basically forever, then basically keep editing your structure (floating above the terrain). 

Once you make any change, iris hotloads, fly into the new terrain to see it.

You can then use /iris str ++ to "move" the structure to your new position (like a shitty workbench)

Pssst. If you use /iris str +++, it will expand the size of the structure builder. It already exists, it just takes a good second to generate large sizes.
