### ISSUE TITLE
[Feature] Tab-complete support

### ISSUE THREAD

**Issue by NightPrimez** [VolmitSoftware/Iris#143]
**Is your feature request related to a problem? Please describe.**
Tab-complete is useful because it's only press TAB to complete parameters, etc.
so I think it's useful for Iris too because Iris has many parameters.

**Describe the solution you'd like**
/iris [TAB]

**Comment by svdgoor** [comment]
👍

**Comment by svdgoor** [comment]
@cyberpwnn If you can explain me how this would work I'll do it for all the commands, if you'd like.

**Comment by cyberpwnn** [comment]
Yeah...................................................... lol. Either i spend 6 hours doing it for each command or spend 20 minutes automating it through the existing system :P

**Comment by Frerduro** [comment]
Added in 1.0.30.
