### ISSUE TITLE
Structures make it so that not all structures are updated when editing a certain one

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#146]
**Is your feature request related to a problem? Please describe.**
Thicc lag when making procedural structures large

**Describe the solution you'd like**
Currently all tiles in the procedural structures editor are being updated every time you edit a single block.
This causes massive lag.
Implementing either or all of:
 - Do not update all tiles every time you edit something (or make a toggle like #145 )
 - Do not update every block you place (add a timer like 5 or 10 seconds between updates, perhaps configurable?)

**Describe alternatives you've considered**
Making schematics outside of the editor and then pasting them.

**Comment by svdgoor** [comment]
https://timings.aikar.co/?id=f31ac76f1d7c4971aa38a27feb6c2592

**Comment by svdgoor** [comment]
Update:
After testing we found that the updates are actually a bug caused by just updating all tiles every time.
There is something wrong with Bukkit's tileentity fix that makes Iris update all its tiles continuously

**Comment by svdgoor** [comment]
Caused by VolmitSoftware/IrisPlugin#207
