### ISSUE TITLE
Vanilla generator takes over at the /iris pregen border

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#148]
**Describe the bug**
Vanilla terrain appears after the radius defined in /iris pregen

**To Reproduce**
1. Pregen a world fly to the border

**Expected behavior**
Iris keeps going

**Screenshots or Video Recordings**
http://mc.friendlysun.de:8123/#

**Server and Plugin Informations**
 - Installed plugins:  Plugins (32): AConomy, AreaShop, BungeeTabListPlus, ChestCommands, ClearLag, CommandSpy, DinoVoteRewards, dynmap, GriefPrevention, InsaneAnnouncer, Insights, InventoryPages, Iris, ItemFrameShops, MaSuiteCore, MaSuiteHomes, MaSuiteTeleports, MaSuiteWarps, PhysicsToGo, PreventPortBypass*, RandomBox, RandomTeleport, Reports, TempFly, UltraPermissions, UltraRegions, Vault, VoidGenerator, Votifier, WorldBorder, WorldEdit, WorldGuard
 - Iris Version: 1.0.25
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: 1.16.3 Paper build 245

**Additional context**
Reported by Discord user Hoshiko#1234

**Comment by Dichte-Fichte** [comment]
.

**Comment by svdgoor** [comment]
Iris does not seem to recognise the world as an Iris world anymore

**Comment by svdgoor** [comment]
Could be an issue with /iris create pregen=distance
Could be that this only occurs with that and not with /iris pregen

**Comment by svdgoor** [comment]
Update:
This was caused by not using MultiverseCore.
I will add a warning and we will create a feature request for hooking into ultraregions (A plugin equivalent to Multiverse)
