### ISSUE TITLE
Object conversion from .ewg to .iob not behaving

### ISSUE THREAD

**Issue by Swede37** [VolmitSoftware/Iris#149]
**Describe the bug**
Does not convert files, when loading server it's looking for /plugins/Iris/rock.ewg that isn't there.  (The pic below explains best). 

**To Reproduce**
1. Start server with v1.0.29
2. Test out file conversion by pasting .ewg files into the /plugins/iris/convert folder, and test out the ./iris studio convert command
3. "0 files converted"
4. Scroll up, to see error message when the server started. It's looking for a file called "rock.ewg" that isn't there.  I copied a random EWG file & renamed it to rock.ewg, and stuck it in the /plugins/Iris folder.  The message at startup went away, but it still doesn't convert anything yet.

**Expected behavior**
Conversion of .ewg files to .iob files 

**Screenshots or Video Recordings**
![Screenshot (3)](https://user-images.githubusercontent.com/27977842/97370067-30e11200-187c-11eb-85d1-9e84eb071782.png)

**Server and Plugin Informations**
 - Installed plugins: Multiverse-Core-4.2.2
 - Iris Version: Iris-1.0.29
 - Server Platform and Version PaperSpigot 1.16.3 #246
 - Operating System (if applicable): Windows 10 x64

**Additional context**
Just want to add that your effort in this is very much appreciated!

**Comment by cyberpwnn** [comment]
Sorry, i had a test that looked for MY ewg rock file in the server. Its just a test, EWG conversion should still work. Thanks for pointing that out! Fixed in 1.0.30

**Comment by Swede37** [comment]
Odd... it just isn't working for me. I tried both from console & in game, I always get the "Converted 0 Files" and nothing converts. No error messages in console.  At first I thought maybe the .ewg files needed to be changed to an Iris friendly format with no Caps & no underscores, but that didn't seem to make any difference.
The one thing I did notice on startup was that it was `Locating NMS Binding for v1_16_R2` and `Craftbukkit v1_16_R2 <-> NMSBinding16_2 Successfully Bound` when I'm using 1.16.3 - would that make any difference?

**Comment by svdgoor** [comment]
That happens with everyone. It's supposed to tell you that.

**Comment by svdgoor** [comment]
Will test this later. Reopening until results.

**Comment by svdgoor** [comment]
Confirm bug. No objects converted, object in folder.

**Comment by svdgoor** [comment]
Waiting for update from @cyberpwnn

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [.ewg to .iob conversion](https://trello.com/c/wITVY700/15-ewg-to-iob-conversion)

**Comment by svdgoor** [comment]
I don't think anyone cares about EWG anymore so I'm just going to close this.
If anyone really wants this let me know
