### ISSUE TITLE
papermc locking up because it's behind

### ISSUE THREAD

**Issue by FluffyDiscord** [VolmitSoftware/Iris#15]
![image](https://user-images.githubusercontent.com/10332247/96347821-77788480-10a4-11eb-8f20-8829584bcc54.png)

it get stuck and user has to manually type something random in the server console, or else its just stuck

notice the 2h difference

**Comment by cyberpwnn** [comment]
Iris does this for more performance. It intentionally steals more cpu from the server tick. If your server is mindlessly ticking mobs and blocks, thats less time spent generating chunks. And on large pregens every little bit counts.

Ill add an option for a more gentle pregen.
