### ISSUE TITLE
[Improvement] Tab-complete improvement

### ISSUE THREAD

**Issue by ArtifactyNight** [VolmitSoftware/Iris#150]
I see tab-complete adding in update **[1.0.30](https://www.spigotmc.org/resources/iris-world-gen-the-dimension-engine.84586/update?update=367980)**.
it's so very useful for me but it's have something not work correctly at the same time.

for now, Iris can't type some word to search tab-complete argument instead other plugins with having tab-complete options can searching argument like **CMI** plugin

If you are confused by what I mean.. please see this video.
https://youtu.be/Ryvx9FdFRsM

**Comment by Frerduro** [comment]
CMI is doing that not iris.

**Comment by ArtifactyNight** [comment]
but...
I want something like that
Could you keep this suggestion to consider, please? 😢

**Comment by svdgoor** [comment]
Basically this is to complete suggestions after adding one or multiple letters, instead of only with 0.

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tab-completion improvement](https://trello.com/c/X6pTZ0YL/33-tab-completion-improvement)

**Comment by svdgoor** [comment]
VolmitSoftware/IrisPlugin#69 is better

**Comment by svdgoor** [comment]
(Nothing personal)
