### ISSUE TITLE
Trapped chests without loot in procedural structure

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#151]
**Describe the bug**
One of the structures of the main overworld pack has trapped chests, which spawn without loot

**To Reproduce**
1. Find the procedurally generated structure in an overworld world

**Expected behavior**
The chest contains items like other structures do

**Screenshots or Video Recordings**
![afbeelding](https://user-images.githubusercontent.com/65736624/97433164-5a9e4580-191d-11eb-8256-f93f3e71170e.png)
![afbeelding](https://user-images.githubusercontent.com/65736624/97433171-5d993600-191d-11eb-820f-ead7908e866c.png)

**Server and Plugin Informations**
 - Installed plugins: Nothing that interferes
 - Iris Version: .30
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Paper #240
 - Operating System (if applicable): Win10 64x

**Comment by NextdoorPsycho** [comment]
noted, ill fix this

**Comment by svdgoor** [comment]
@NextdoorPsycho Has this been resolved?

**Comment by NextdoorPsycho** [comment]
Loot system will get an update to fix these problems

**Comment by CocoTheOwner** [comment]
@NextdoorPsycho Is that done by you or Dan? Please add/remove tags & assignees correspondingly.

**Comment by NextdoorPsycho** [comment]
Loot system needs to change for this, after 3 attempts and editing rerolls. i cant fix this with configuration

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Trapped chests without loot](https://trello.com/c/UrCRlqF0/14-trapped-chests-without-loot)

**Comment by svdgoor** [comment]
Structures were removed
