### ISSUE TITLE
Bug: Structures spawning in trees & creepers hate me & structure cutting off bottom half of grass

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#152]
Actual bug (the creeper is in the middle of the grass)
![afbeelding](https://user-images.githubusercontent.com/65736624/96474478-22b74400-1233-11eb-936c-7d2c35b62a69.png)

Creepers hate me
![afbeelding](https://user-images.githubusercontent.com/65736624/96474489-25b23480-1233-11eb-884b-d97d18f14bb1.png)

**Comment by NextdoorPsycho** [comment]
Less shading, and this is just something that can just happen
