### ISSUE TITLE
error when create world

### ISSUE THREAD

**Issue by thanhbadaodz** [VolmitSoftware/Iris#154]
**Server and Plugin Informations**
 - Installed plugins: 1
 - Iris Version: 1.0.30
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #251]:
 - Operating System (if applicable): Window10.0
16gb RAM
2 Core

**Additional context**
Download and unpacked overworld
then create IRIS world but get crash when creating
Error Log:
- https://pastebin.com/bfEzpS9z

**Comment by cyberpwnn** [comment]
This is not an error. Iris took longer than 30s to generate the world, becasue the server was frozen, paperspigot shut it down. You need to tell paper to stop shutting your server down.

Change watchdog to   
```yml
watchdog:
    early-warning-every: 5000
    early-warning-delay: 30000
```

Also try increasing `min-chunk-load-threads` maybe to 16 or even 32 if you have the cpu cores for it to make a difference.

Finally in the spigot yml increase your timeout time so it stops shutting your server down 
```yml
timeout-time: 600
```
