### ISSUE TITLE
Additions to focus editing biomes

### ISSUE THREAD

**Issue by Astrashh** [VolmitSoftware/Iris#157]
### Region focus
Similar to the focus option for dimensions which is specific to biomes, would allow you to focus on edition a region without fiddling with your current settings. Would make easier to see per region settings changes.

### Maintain child biomes on focus
Added as a togglable option, would allow biomes to contain their children when focused on, so that it is easier to edit and visualize parent-child biome settings.

**Comment by cyberpwnn** [comment]
Added support for region focusing, 1.0.32

Wont be possible (with the current system) to show child biomes while focusing a biome due to how the biome system works. Ill add this in v2
