### ISSUE TITLE
Set grass blocks to use the snowy blockstate automatically when snow is placed on top of it

### ISSUE THREAD

**Issue by Astrashh** [VolmitSoftware/Iris#165]
**Describe the bug**
When snow is used as a decorator, grass blocks that snow is placed on gets turned into dirt over time, rather than using the 'snowy' blockstate. Additionally, if the grass blocks are set in the config to be snowy, it still gets converted to dirt over time.

**To Reproduce**
1. Use grass_block in the top layer for the palette (with or without snowy set to true)
2. Use snow as a decorator
3. Generate terrain

**Expected behavior**
The grass blocks should ideally be set to be snowy if snow is on top of it, and manually set snowy grass blocks should retain their state, rather than converting to dirt as though a full block is on top of it.

**Screenshots**

How grass blocks initially spawn with snow on top of it
![image](https://user-images.githubusercontent.com/73215501/98218887-697d9b80-1fa0-11eb-89a2-7f4f6f43b186.png)

How grass blocks configured with snowy initially spawn with snow on top of it
![image](https://user-images.githubusercontent.com/73215501/98218936-79957b00-1fa0-11eb-964a-10b212d7ae00.png)

How both of the above end up over time
![image](https://user-images.githubusercontent.com/73215501/98218612-14da2080-1fa0-11eb-802d-5670cba821a7.png)

**Server Information**
- Iris Version: 1.0.34
- Paper-247 (MC: 1.16.3)

**Comment by svdgoor** [comment]
Configuration error where the datatags of the blocks are not set properly.

**Comment by astrsh** [comment]
Also note this is in a custom biome - not the overworld pack

**Comment by svdgoor** [comment]
Try using the f3 screen in vanilla on a snow block that looks properly and copy the datatag into the "data": for the block you're trying to place. This can perhaps be done automatically so re-assigning this to Dan for surface blocks.

**Comment by astrsh** [comment]
The data is correct since grass blocks only have one blockstate, however I believe the issue is that the snow blocks see snow layers as opaque and as such turn into dirt. Not sure if every grass block would then need to be updated to recognize that it is below a snow layer in order to fix this, or if there's some better way

**Comment by NextdoorPsycho** [comment]
Had a conversation with Ashtray was doing it wrong, and it was a vanilla issue
