### ISSUE TITLE
Two block high decorations spawning incorrectly on walls

### ISSUE THREAD

**Issue by Astrashh** [VolmitSoftware/Iris#167]
**Describe the bug**
Decorations that are two blocks high such as tall grass get cut off when spawning on top of walls.

**Expected behavior**
The top half should either not generate or the entire decoration should generate with it.

**Screenshots**
![image](https://user-images.githubusercontent.com/73215501/98245209-b4a9a580-1fc4-11eb-8a83-7e08682f7f75.png)

**Server Informations**

- Iris Version: 1.0.34
- Paper-247 (MC: 1.16.3)

**Comment by svdgoor** [comment]
Might be the walls spawning 1 block lower than they're supposed to or, alternatively, the decorations spawning one block too high.

**Comment by svdgoor** [comment]
I do not think this is configuration related either way, so I'm adding Dan and making it a plugin-related issue, rather than an overworld one.

**Comment by cyberpwnn** [comment]
Hmmm they shouldnt even be spawning on walls

**Comment by svdgoor** [comment]
Still happening with V2?

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Two block high decorations not spawning](https://trello.com/c/wPVd0S1y/41-two-block-high-decorations-not-spawning)

**Comment by ghost** [comment]
Haven’t seen this one since a long time. If anyone run into this again. This will be reopened.
