### ISSUE TITLE
Minor bug - focus region auto completes biomes instead of regions

### ISSUE THREAD

**Issue by Astrashh** [VolmitSoftware/Iris#168]
**Describe the bug**
In VSCode, the dimension setting focusRegion autocompletes a biome instead of a region

**Screenshots**
If applicable, add screenshots or video recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/73215501/98431101-c004ea00-2106-11eb-8b47-950a85c58cec.png)

**Comment by NextdoorPsycho** [comment]
@Frerduro  Dont assign people, they can assign themselves.
@Astrashh  Temperate is a region.
https://i.imgur.com/nHVeFnH.png
