### ISSUE TITLE
Generation Bug [tuinity]

### ISSUE THREAD

**Issue by Birsenberg** [VolmitSoftware/Iris#17]
I have a lot of errors on 1.16.3 tuinity core when a world is generated. 
https://paste.ofcode.org/f8RWG2ieGR2whyH2qHXWsf

I tried all the ways. Mvc, iris create and through a file bukkit

**Comment by Birsenberg** [comment]
Its work if i have world-container: gameworlds in bukkit.yml

**Comment by cyberpwnn** [comment]
Looks like Iris cant find the dimension object its supposed to generate. Could you please turn on verbose (iris settings.json) and paste what happens before this in the log?

**Comment by svdgoor** [comment]
@Birsenberg Please let us know is this is still happening.

**Comment by svdgoor** [comment]
Still happens in latest
[latest.log](https://github.com/VolmitSoftware/Iris/files/5451419/latest.log)

**Comment by NextdoorPsycho** [comment]
Is this happening on latest? @CocoTheOwner  / @Birsenberg

**Comment by svdgoor** [comment]
Resolved in Iris V1.1
