### ISSUE TITLE
Overworld repeating biomes 

### ISSUE THREAD

**Issue by jfrelik** [VolmitSoftware/Iris#179]
**Describe the bug**
Overworld type of world produces a lot of oceans and islands. And it repeats the same biomes
No lava can be seen anywhere. 

World pregenerated size 10k by 10k

Major biome seen: lukewarm_ocean

**To Reproduce**
Just generated a new world without multiverse using bukkit.yml
Example seed used "2137"

**Expected behavior**
Produce not repeated biomes and less oceans

**Screenshots or Video Recordings**
https://imgur.com/a/WOtIC2g

**Server and Plugin Informations**
 - Installed plugins: https://imgur.com/a/5RAF8Wu
 - Iris Version: 1.1.1
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: PaperSpigot 1.16.4 #288
 - Operating System (if applicable): Ubuntu Server 18.04

**Comment by NextdoorPsycho** [comment]
Have you tested this with another seed? like 1337, or 5793, or any other numbers?

**Comment by jfrelik** [comment]
Generated world without providing a seed and can see the same behaviour of gen even the biomes are spreaden out in the same locations on map. On 1337 after 1k blocks the land starts to generate. Seems like I'm not that lucky with seeds
