### ISSUE TITLE
Files are not updated in the workspace Beyond 3 folders Deep

### ISSUE THREAD

**Issue by NextdoorPsycho** [VolmitSoftware/Iris#180]
Files are not updated in the workspace Beyond 3 folders Deep

![image](https://user-images.githubusercontent.com/29320316/99860645-81c8eb00-2b48-11eb-9ee7-651371124dad.png)
Files that are 3 deep or further are not updated in the workspace.

This can be recreated. Just do whats in the picture

**Comment by Frerduro** [comment]
Isn't this VolmitSoftware/IrisPlugin#234 that you closed?

**Comment by astrsh** [comment]
Was a misunderstanding regarding it being a bug or an issue - but Brian made this after confirming it was indeed a bug

**Comment by svdgoor** [comment]
Probably slightly better to re-open the previous issue but this works well enough.

**Comment by svdgoor** [comment]
Still an issue with recent changes & V2?

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Files are not updated 3 deep](https://trello.com/c/HVhIeI0M/40-files-are-not-updated-3-deep)

**Comment by svdgoor** [comment]
9/10 certain this is due to the maximum registered file depth of VSCode's workspace file. We can increase this number to prevent issues such as this, but it may have to be increased repeatedly over time. 
Hopefully resolved in 1.3.2
