### ISSUE TITLE
Crash on opening studio world, related to land chance

### ISSUE THREAD

**Issue by Astrashh** [VolmitSoftware/Iris#184]
**Describe the bug**
When trying to open a studio world, the server will crash if land chance is below a certain threshold. Setting to 0 seems to be a guaranteed crash, while setting to 1 doesn't seem to cause a crash. Not sure if this is specific to my current WIP pack (Brian has access, but I can provide access to the private repo if anyone else needs to test), but I haven't thoroughly tested it.

**To Reproduce**
Set the land chance of a dimension below a certain amount
Open up a studio world for that dimension

**Crash Log**
https://pastebin.com/PHgqu1g6

**Comment by svdgoor** [comment]
Happened to me too.

**Comment by svdgoor** [comment]
No longer causes a crash. Tested with landchance 0 on overworld pack. Let me know if this re-occurs with another pack and we'll re-open the issue.
