### ISSUE TITLE
Re-add /iris regen

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#185]
**Is your feature request related to a problem? Please describe.**
It was there before, was probably removed because of issues with V2.
Quite the required feature.

**Describe the solution you'd like**
Having the command be added back

**Describe alternatives you've considered**
Going back to "primate" methods like removing the region file manually (bleh)

**Comment by ghost** [comment]
Yes please readd it. This was one of the most important reasons why I bought Iris.

**Comment by svdgoor** [comment]
VolmitSoftware/IrisPlugin#110 should be fixed with this. I will close both this and that (or Cyber can) if they are resolved.

**Comment by svdgoor** [comment]
Will be re-added in 1.1.5

**Comment by svdgoor** [comment]
Due to technical difficulties with readding this system, and thus not re-adding it, re-opening this.
