### ISSUE TITLE
Iris uses too much ram on my server

### ISSUE THREAD

**Issue by TheDevelon** [VolmitSoftware/Iris#19]
Iris uses too much ram on my server. 
The ram usage grows to a point the server just does not respond anymore.

My server currently has access to 8GB RAM. Happens currently only with pre generating and non studio worlds.

**Comment by TheDevelon** [comment]
Tried using Chunky, same result after a while.

**Comment by NextdoorPsycho** [comment]
you are the only one with this issue as of now, can you please send your plugin list

**Comment by TheDevelon** [comment]
Plugin List: MultiVerse Core, Iris v.17

**Comment by TheDevelon** [comment]
Going to re-install my whole server. Maybe that changes something.

**Comment by TheDevelon** [comment]
After re-installation the same result after a while

**Comment by TheDevelon** [comment]
Only plugins: Iris .17 and MV Core

Last thing I am trying is using normal spigot. After this I don’t have any clue what it could cause

**Comment by TheDevelon** [comment]
After purchasinga new server with an Intel® Core™ i9-9900K with 2 dedicated cores and 10GB RAM i can say that the issue isnt happening anymore. Seems to be a problem with the old server. CLOSED
