### ISSUE TITLE
No vanilla structures spawning

### ISSUE THREAD

**Issue by ArMiN231** [VolmitSoftware/Iris#190]
**Describe the bug**
Vanilla Structures like villages, strongholds, etc doesn't spawn while using the bukkit.yml method for Iris generation.

**To Reproduce**
1. Pick the bukkit.yml method
2. Start and join the server
3. Use /locate village and tp to that position
4. No vanilla structure at the given coordinates

**Expected behavior**
Having vanilla structures spawn at the given coordinates of /locate

**Server and Plugin Informations**
 - Installed plugins: Iris
 - Iris Version: V1.1.2
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Spigot 1.16.4 dated 26.11.2020

**Comment by svdgoor** [comment]
Duplicate of VolmitSoftware/IrisPlugin#246 but this one is using the proper format so I'm closing the other one. Thanks for the report.

**Comment by svdgoor** [comment]
Creating the world with /mvc <worldname> NORMAL -g Iris shows the same issue.

**Comment by dimactek96** [comment]
Iris: V1.1.3 not fix

**Comment by Frerduro** [comment]
> Iris: V1.1.3 not fix

It never said it was fixed in that update. No need to tell us.

**Comment by svdgoor** [comment]
Bypass:
You can avoid it by using paper or the most recent spigot as well as creating the world with multiverse through /iris create <yourworldname>

**Comment by svdgoor** [comment]
Since there is a bypass this isn't high priority anymore. Though still quite annoying so...

**Comment by svdgoor** [comment]
Duplicate-ish of VolmitSoftware/Iris#222 but this one covers additional ground

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Vanilla structures bukkit](https://trello.com/c/BgtjQPwg/12-vanilla-structures-bukkit)

**Comment by ghost** [comment]
No vanilla structures support (cause of upcoming jigsaw system) anymore so this bug kinda got fixed lol.
