### ISSUE TITLE
Generate structures with mythicmobs inside

### ISSUE THREAD

**Issue by Darkdeviousdevil** [VolmitSoftware/Iris#191]
This is a feature that other generator plugins seem to plan on having, because well it would be a cool feature. Regular mob spawning is great but being able to summon in custom entities made from the MythicMobs plugin would be a nice thing to see.

Similar to how villagers are spawned in with villages, or how guardians are spawned in with sea temples, server owners would be able to spawn in their own bosses and such with this feature.

**Comment by svdgoor** [comment]
We *should* already have a system *somewhere* that can do this, but I have not noticed it anywhere. I will shoot Psycho a DM to find if he knows, then, if not, Dan, then I will remove the tag and assign assignees.

**Comment by svdgoor** [comment]
Also please use the template next time. It helps us make the suggestion as easily as possible, thus adding it faster.

**Comment by svdgoor** [comment]
We already have this in our plugin. Here is a quick guide:
Make a new folder called "entities" inside the pack folder
Add a new file in the folder and enter the following:
```
{
    "type": "UNKNOWN",
    "mythicalType": "SkeletalKnight"
}
```
Then add the mob like any other mob overwrite, for example in the dimension file:
```
    "entitySpawnOverrides": [
        {
            "trigger": "SKELETON",
            "entity": "skelly"
        }
    ]
```
This will then overwrite (some) skeletons with the MythicMob "SkeletalKnight".
This should be enough to let you make any MythicMob you want spawn. Let support know in the Discord support if you need more help.

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/100377568-c43f6b80-3011-11eb-96f8-4396a8b6c441.png)
(Proof)
