### ISSUE TITLE
Toggling what vanilla structures spawn

### ISSUE THREAD

**Issue by ArMiN231** [VolmitSoftware/Iris#193]
**Describe the solution you'd like**
A feature that enables or disables independently e.g. village, strongholds, mansions, etc spawn

**Describe alternatives you've considered**
In the current overworld pack its only possible to enable or disables all vanilla structures, not individual ones.

**Comment by svdgoor** [comment]
In each of the biomes there is a setting called "vanillaDerivative".
The biome you specify here dictates which set of vanilla structures can spawn in that biome, and which type of vanilla village would spawn (if vanilla villages can spawn there)
Using swamp will give witch huts,
Using desert will give desert temples (if they work) and desert villages,
Using jungle will give jungle temples (if they work),
and so on.
You can find a full list here: (look in the second column, "Features" to see which structures can spawn in that biome)
https://minecraft.gamepedia.com/Biome#Snowy_biomes
