### ISSUE TITLE
Dust of Revealing isn't working

### ISSUE THREAD

**Issue by ArMiN231** [VolmitSoftware/Iris#194]
**Describe the bug**
When trying to apply the Dust of Revealing to any Iris object nothing is happening.

**To Reproduce**
1. Start a Studio World
2. Click with the Dust of Revealing on a Tree/etc

**Expected behavior**
Get the information of the right clicked structure as well as highlight it.

**Server and Plugin Informations**
 - Installed plugins: Iris
 - Iris Version: V1.1.3
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Spigot 1.16.4

**Comment by svdgoor** [comment]
Doesn't work on latest paper either.

It plays the sound but does not do anything else

Shows the same behaviour on normal worlds

**Comment by svdgoor** [comment]
It works on 1.1.2

**Comment by cyberpwnn** [comment]
Interesting. Does it work in studio worlds?

**Comment by ghost** [comment]
> Interesting. Does it work in studio worlds?

As for V1.1.2 and V1.1.3 no it doesn’t work in studio mode. Haven’t tested it in a normal one though.

**Comment by svdgoor** [comment]
Still doesn't work on latest.

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dust of revelation](https://trello.com/c/bAke9oXJ/11-dust-of-revelation)

**Comment by CocoTheOwner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dust of revelation](https://trello.com/c/bAke9oXJ/11-dust-of-revelation)

**Comment by ghost** [comment]
is fixed on version 1.2.1
