### ISSUE TITLE
Issue with decorators not using the whole palette

### ISSUE THREAD

**Issue by coloredwax** [VolmitSoftware/Iris#197]
**Describe the bug**
Seems like the decorators palettes for blocks don't loop properly causing only the first block to be placed.

**To Reproduce**
1. **Make a _"decorators"_ with a palette array put in multiple blocks**
2. **Open up the world in iris studio**
3. **Fly around and see only one block is being placed**

**Expected behavior**
**There are suppose to be multiple blocks placed by the decorator**

**Server and Plugin Informations**
 - Installed plugins: **Iris, Multiverse Core**
 - Iris Version: **v1.1.4**
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: **CraftBukkit git-Spigot-a19903d-5b74714 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT) [AKA LATEST]**
 - Operating System (if applicable): **Windows**
 - Server Logs: **None**

**Comment by Frerduro** [comment]
Could you give us your config and some screenshots?

**Comment by NextdoorPsycho** [comment]
This is for sure a bug. i can validate that this is happening with the overworld too.
https://i.imgur.com/UYNbCSm.png <- thats an overview of the tropical ocean, its only spawning blue coral tubes amidst 30 or so variants. 
here is an example file (overworld tropical ocean.): https://pastebin.com/GmdFLiN6 Give it a look yourself ingame too, the only thing I can think of is its a looping issue (thanks to crayon for bringing this up) Its only looking at the first/first 2 iterations in a list of decorators, and this might explain other issues. whatever is causing this then.

**Comment by bryiac** [comment]
When the chance for decorators is higher there doesn't seem to be an issue placing blocks from the palette

**Comment by svdgoor** [comment]
According to Cyber this issue was due to the variance being static and / or having a zoom function on the static gen. This will be prevented in future updates by ignoring the zoom when using static noise.
Please let us know if this happens again with the 1.1.5 update and we will take a look again.
