### ISSUE TITLE
Issue with decorators not using the full palette #2

### ISSUE THREAD

**Issue by coloredwax** [VolmitSoftware/Iris#199]
**Describe the bug**
**Decorators are still not using the full palette**

**To Reproduce**
1. **Use `/iris studio goto tropical-ocean`**
2. **There is only blue coral with a palette full of 5 options**

**Expected behavior**
**Expected there to be more variety of coral.**

**Screenshots or Video Recordings**
![image](https://user-images.githubusercontent.com/38088988/101393324-ed26f280-3894-11eb-9a60-c1798b3eedb9.png)
![image](https://user-images.githubusercontent.com/38088988/101393336-f2843d00-3894-11eb-9019-e2c76417b21f.png)

**Server and Plugin Informations**
 - Installed plugins: **Multiverse Core, Iris**
 - Iris Version: **1.1.5**
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: **git-Spigot-a19903d-5b74714 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)**
 - Operating System (if applicable): **Windows**
 - Server Logs: **None**

**Additional context**
**Seems as the issue is still here not sure what cyberpwn did to make it work or if maybe it just wasn't included in the update**

**Comment by svdgoor** [comment]
VolmitSoftware/IrisPlugin#254

**Comment by bryiac** [comment]
Even though the patch notes say it's been fixed it's still and issue as this was tested on 1.1.5

**Comment by svdgoor** [comment]
Was merely mentioning the previous thread. I would have called this a duplicate and closed this one if I thought it'd been fixed already. Sorry if I was confusing.

**Comment by bryiac** [comment]
yeah oopsie I saw the link to the last post before you assigned it

**Comment by NextdoorPsycho** [comment]
should have been fixed like 3 days ago, if not tag me and ill reopen  ♥

**Comment by NextdoorPsycho** [comment]
fok

**Comment by svdgoor** [comment]
nice

**Comment by svdgoor** [comment]
Not the most essential thing atm

**Comment by bryiac** [comment]
I dont see how this wouldn't be considered essential though cause it's like hindering decorating biomes completely

**Comment by svdgoor** [comment]
It's using 2 out of X if I understand correctly.
That's more than nothing and way less essential than having a nether without either layers of bedrock or stone layers or even overworld mobs like cows and pigs in the nether. This is not not essential, it's less essential. If it wasn't essential I'd have given it low priority.

**Comment by winnipeg21** [comment]
No genius myself. But a custom generator plugin that's suppose to make biomes look pretty and a key aspect to that plugin is broken, was reported, reported fix, wasn't fixed then took 4+ days to actually update the ticket, is kinda important. I speak for myself and maybe others but I feel more attention should be placed in this rather than updating a ticket every few days. My 2 cents

**Comment by HAV0C101** [comment]
imp gonna bump this as I think this is a high priority issue its gonna cause issues with things not being decorated correctly and quite frankly I don't think you (CoCo) is quite qualified to say what is high priority and what isn't that job should be the devs job as they are the ones working on the program so unless the dev says the same thing about this not being high priority when it should be as its something that's causing issues then it shouldn't be taken off high priority especially since the dev **did quite literally set it as a high priority issue**

**Comment by NextdoorPsycho** [comment]
Literally not a single person via development, or consumer can experience the overworld the way it was intended too. additionally this poses other issues that im aware of that im not going to bother posting. point being, if people get IRIS for the overworld they will not be experiencing it the way they should. and as the maker of the overworld (more or less) if people are not able to experience it they way intended, or use anything as intended this is a large issue. this also corrupts non-affected worlds, into broken decorator worlds. this is a problem that needs to be resolved asap

**Comment by svdgoor** [comment]
Talked with Psycho and discussed it, found myself agreeing more. Still wouldn't do this myself, but it's acceptable this way, not everyone feels the same way about everything.

@HAV0C101 can you send your Discord name here please? Would like to have a talk with you about your comment here. Would rather not do that here.

**Comment by HAV0C101** [comment]
@CocoTheOwner ive sent you a dm on discord my user is HAVOC#0001

**Comment by cyberpwnn** [comment]
Wasnt this fixed? It was the static noise generator?

**Comment by bryiac** [comment]
bugs still present with my testing and I think a few othe s have been experiencing it I reopened this after I tested 1.1.5

**Comment by cyberpwnn** [comment]
Ah, it's not single-palette that's the problem. I see the problem now.

**Comment by cyberpwnn** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/10619135/102015805-bb49dc00-3d2b-11eb-9ec1-35d5705e0420.png)
![image](https://user-images.githubusercontent.com/10619135/102015820-cf8dd900-3d2b-11eb-9c05-26a5c861b513.png)

Will be released today.
