### ISSUE TITLE
Vanilla Caves Do Not Generate At All

### ISSUE THREAD

**Issue by Gaukh** [VolmitSoftware/Iris#209]
Using Iris 1.1.5

The issue I face in the overworld.json (dimensions) is that if the following is set true:

    "vanillaCaves": true,

it doesn't generate anything vanilla at all. 

    "caves": true,

^ This does nothing either, turning it off disables ALL cave generation. If it is enabled Iris generates. No vanilla. So it's either Iris, Iris or Nothing.

**Comment by Frerduro** [comment]
How are running the world? Bukkit.yml, multiverse or other?

**Comment by astrsh** [comment]
Have managed to recreate this by trying to get vanilla caves working in a studio world using a mostly unchanged flat pack

**Comment by svdgoor** [comment]
Tested on example:
Download example /w /ir download example
Create studio /w /ir std o example
Disable ravines (doesn't matter but makes finding no caves easier) and enable vanilla caves

Dimension file:
```
{
    "postProcessing": false,
    "environment": "NORMAL",
    "regions": [
        "hot",
        "temperate",
        "temperate",
        "cold"
    ],
    "caves": false,
    "name": "Example",
    "fluidHeight": 63,
    "carving": false,
    "version": 1,
    "vanillaCaves": true,
    "ravines": false
}
```

Same problem

**Comment by svdgoor** [comment]
VolmitSoftware/Iris#224

Since this is not using the official format I'm closing this one. My bad for opening another one, I thought this one didn't exists.
