### ISSUE TITLE
Suggestion: option to tick liquid once

### ISSUE THREAD

**Issue by FluffyDiscord** [VolmitSoftware/Iris#21]
It would be nice to have water and lava to tick just once, enough to be updated the next time chunk is loaded. With this many broken water > surface transitions would not be so harsh and look like it was just purely carved

![image](https://user-images.githubusercontent.com/10332247/96374285-18814100-1172-11eb-8fcc-c877bcd03ca0.png)

**Comment by ghost** [comment]
I’ll close this cause no one is complaining about it anymore and I haven’t seen a use case of that. Cause that cave opening in fluid isn’t the case anymore.
