### ISSUE TITLE
While Pregen It  Starts To Use Too Much Ram And CPU

### ISSUE THREAD

**Issue by Inxity** [VolmitSoftware/Iris#214]
**Describe the bug**
While pregenerating a 20kx20k map with overworld package after 30 minutes of pregen it startes dropping and giving out of memory error on my 16 gb r9 3900x 12 core server (i only run my render server and give it 13gb of ram) i have 16gb swap

**To Reproduce**
Start the server
/iris create WorldName normal pregen=20000 
wait for 20 or 30 mins there are memory leaks
**Expected behavior**
Too much usage on cpu and ram

**Screenshots or Video Recordings**

**Server and Plugin Informations**
 - Installed plugins: MultiverseCore Chunky Chunk Master EssentialsX Iris WorldEdit
 - Iris Version: 1.1.6
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Paper version git-Paper-325 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
 - Operating System (if applicable): Centos 7
 - Server Logs: https://paste.md-5.net/oqimubuhiv.md

**Additional context**
https://timings.aikar.co/?id=b3271c86991a4f63ab96e36e728a46e1

**Comment by svdgoor** [comment]
Seconded by multiple users. Leaving this to Cyber because I have no RAM tracking tools that perform as well as his.

**Comment by Inxity** [comment]
After the Iris 1.1.7 Update there are some improves but problem still exists after 18-22% of pregeneration.

**Comment by UserDerezzed** [comment]
Fixed in 1.1.10. Please reopen if this is still an issue.

**Comment by svdgoor** [comment]
https://paste.gg/p/anonymous/e267f0fc9abe4c1db0fe423c76085f12

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pregen RAM overload](https://trello.com/c/gztQ9Q6m/48-pregen-ram-overload)

**Comment by cyberpwnn** [comment]
Why is this open? Memory? Looks fine to me.

**Comment by svdgoor** [comment]
https://paste.gg/p/anonymous/e267f0fc9abe4c1db0fe423c76085f12

Froze at the end of that log.

**Comment by svdgoor** [comment]
https://discord.com/channels/189665083817852928/666290834878234647/794537102884864010

**Comment by cyberpwnn** [comment]
If you want iris to be efficient & use the least amount of resources, make sure MCA gen is disabled. The pregenerator is much better now.
