### ISSUE TITLE
Server thread/WARN]: [Iris] Task #XXXXXXX for Iris v1.1.6 generated an exception

### ISSUE THREAD

**Issue by Fyrinlight** [VolmitSoftware/Iris#220]
**Describe the bug**
Randomly when running this plugin, it will start spamming console with the following:
[09:14:25] [Server thread/WARN]: [Iris] Task #1545736 for Iris v1.1.6 generated an exception
java.lang.NullPointerException: null

**To Reproduce**
Unknown at this time. The world is fully generated with world border fill and all players are near the center, no new chunks should be being generated.

**Expected behavior**
N/A

**Screenshots or Video Recordings**
[09:14:25] [Server thread/WARN]: [Iris] Task #1545905 for Iris v1.1.6 generated an exception
java.lang.NullPointerException: null
[09:14:25] [Server thread/WARN]: [Iris] Task #1545972 for Iris v1.1.6 generated an exception
java.lang.NullPointerException: null
[09:14:25] [Server thread/WARN]: [Iris] Task #1546064 for Iris v1.1.6 generated an exception
java.lang.NullPointerException: null
[09:14:25] [Server thread/WARN]: [Iris] Task #1546094 for Iris v1.1.6 generated an exception
java.lang.NullPointerException: null
[09:14:26] [Server thread/WARN]: [Iris] Task #1546163 for Iris v1.1.6 generated an exception
java.lang.NullPointerException: null

**Server and Plugin Informations**
 - Installed plugins: 
ActionBarAPI, ArmorEquipEvent, BanManager, Brewery, Cannons, ChestShop, ChopTree2, Citizens, Denizen, dynmap, Essentials, EssentialsSpawn, FarmLimiter, ForceResourcepacks (WorldResourcepacks), GSit, HolographicDisplays, Iris, LibsDisguises, Lift, LuckPerms, Movecraft, MystianMagic, MythicMobs, NametagEdit, PluginManager, Prism, ProtocolLib, Quests, Vault, WorldBorder, WorldEdit, WorldGuard

 - Iris Version: 1.1.6
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]:  paper-1.16.4-324.jar
 - Operating System (if applicable): Windows Server 2016 Server
 - Server Logs: N/A

**Additional context**
There does not seem

**Comment by svdgoor** [comment]
@Fyrinlight Can you leave a full latest.log please?

**Comment by Fyrinlight** [comment]
[latest.log](https://github.com/VolmitSoftware/Iris/files/5720729/latest.log)

**Comment by svdgoor** [comment]
@Fyrinlight Can you send your configuration file here (`*/plugins/iris/settings.json`)

**Comment by svdgoor** [comment]
(@cyberpwnn reason I'm asking is because I think this individual disabled the EffectsSystem and is now finding himself in the situation where the effects are still being played somewhere and the engine doesn't exist so it's throwing NPE's every tick)

**Comment by svdgoor** [comment]
Sort-of-fixed-but-not-really-kinda-just-prevent-errors

**Comment by Fyrinlight** [comment]
Here is the settings. Had to change to .txt to upload here

[settings.txt](https://github.com/VolmitSoftware/Iris/files/5721617/settings.txt)

**Comment by svdgoor** [comment]
Thanks for the settings. It turns out my initial thoughts were incorrect and it's something else. We'll be looking into the issue.

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Thread exception](https://trello.com/c/nS7tKmQU/2-thread-exception)

**Comment by cyberpwnn** [comment]
Im going to assume it has to do with a biome effect. Please run your server with `-XX:-OmitStackTraceInFastThrow` so java doesnt trim the exceptions.

**Comment by ghost** [comment]
This is older than 3 weeks and hasn’t occurred since than. So I’ll close this till someone run into it again.
