### ISSUE TITLE
No vanilla caves

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#224]
**Describe the bug**
Turning on vanilla caves does nothing

**To Reproduce**
1. Turn on vanilla caves in a fresh "example"-pack world
2. See no vanilla caves

**Expected behavior**
Turning on vanilla caves spawns vanilla caves

**Server and Plugin Informations**
 - Installed plugins: MVCore Iris Worldedit
 - Iris Version: 1.1.7
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Latest paper

**Additional context**
Split off from #195

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [No vanilla caves](https://trello.com/c/hRx9UGd1/24-no-vanilla-caves)

**Comment by CocoTheOwner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [No vanilla caves](https://trello.com/c/15t4oNsC/5-no-vanilla-caves)

**Comment by cyberpwnn** [comment]
The cave rewrite will support this. But we arent planning on supporting direct vanilla caves due to how it affects deposits
