### ISSUE TITLE
Generate flat areas in the world

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#226]
**Is your feature request related to a problem? Please describe.**
Add a configuration option to the dimension to generate flat spaces of land in the world.
It can be useful to have something like this if you have, for example, a schematic of a spawn and want to paste that into your new Iris world.

**Describe the solution you'd like**
A configuration setting where:
1. There is an array of flat areas like this:
```json
    "flatAreas": [
        {   "minimal": "settings",
            "xPosition": 0,
            "yPosition": 0
        },
        {   "all": "settings",
            "xPosition": 0,
            "yPosition": 0,
            "zPosition": 60,
            "radius": 50,
            "transitionRadius": 50
        }
    ]
```

xPosition: Speaks for itself (must be specified)
yPosition: Speaks for itself (must be specified)
zPosition: Speaks for itself (can alternatively be "height", specifying -1 or omitting will make it use the fluidHeight)
radius:     Speaks for itself (default 20)
transitionRadius: Radius added to "radius" which basically transitions the flat area into the terrain outside with a cone.
If the terrain outside the flat area is lower, make a downward "line" of blocks with the proper "layer" from the flat area to the terrain. Same thing for higher, but upward instead. (default 15)

**Describe alternatives you've considered**
Map drawing feature + flat biome which is excluded from the rest of the gen.

**Comment by MassiveLag** [comment]
Yea, this should def be a thing. I really need it to paste in my spawns!

**Comment by cyberpwnn** [comment]
This is not how procedural world generators work typically. I would highly suggest making a flat biome or two, and let off the noise overlays (in the dimension file). Also, we might have a better time using "terminators" basically regions/biomes can only show up within a certain distance of spawn maybe? 

What im trying to say is Iris doesnt just pick where things go based off of RNG, its more like the reverse. So i cant just randomly flatten areas. I will look for some solutions for this.

**Comment by cyberpwnn** [comment]
Next update supports noise effect zones, which can do what was asked

```json
"noiseEffectZones": [
    {
        "x": 0,
        "z": 0,
        "strength": 0.77,
        "interpolator": "BILINEAR_STARCAST_9",
        "convergeToHeight": 66,
        "interpolationRadius": 16,
        "blockRadius": 64
    }
],
```
Before 
![image](https://user-images.githubusercontent.com/10619135/103462239-cd4ae900-4cf1-11eb-890a-03b193b308b1.png)

After
![image](https://user-images.githubusercontent.com/10619135/103462221-b99f8280-4cf1-11eb-8482-b6731cd97b5a.png)

**Comment by MassiveLag** [comment]
Nice
