### ISSUE TITLE
Parallax generation issue (java.lang.ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by coloredwax** [VolmitSoftware/Iris#228]
### **Describe the bug**
Array index is exceeding bounds for parallax layers? 

### **To Reproduce**
1. **Use version (1.2 -> 1.2.1)**
2. **Run server**
3. **Error occurs in iris worlds**

### **Image**
![image](https://user-images.githubusercontent.com/38088988/103476406-447c8d80-4d83-11eb-80e2-2880c4dc2781.png)

### **Server and Plugin Informations**
 - Installed plugins: **Iris, WorldEdit, Multiverse**
 - Iris Version: **1.2.1**
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: **Tuinity version git-Tuinity-"8056d13" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)**
 - Operating System (if applicable): **Windows**
 - Server Logs: **https://mclo.gs/aoSsubp**

**Comment by cyberpwnn** [comment]
Saw this once, and have not been able to recreate it ever since. Does restarting / reloading fix this?

**Comment by Tyllux-Nexus** [comment]
Reproduced on my server with all versions 1.2.1 and up, restarting/reloading fixes it until someone goes and loads those specific chunks again.. causing a server crash.

Crash report:
https://justpaste.it/4e0c1

**Comment by bryiac** [comment]
@AZFire1 I believe this was fixed in the newer version but there are still issues in 1.2->1.2.3 prob just gonna have to be patient and wait for update he is usually pretty fast tho if you're just trying to make packs and not generate maybe try a older version

**Comment by cyberpwnn** [comment]
Seems to be fixed. Ill close this for now. If it happens again, either reopen/comment or create a new issue.
