### ISSUE TITLE
noiseEffectZones feature

### ISSUE THREAD

**Issue by JoelDeadMach** [VolmitSoftware/Iris#229]
**Is your feature request related to a problem? Please describe.**
It's really annoying when you have to remove all trees manually to past in a spawn. My warzone is around 300x300.

**Describe the solution you'd like**
I would like to have a feature to turn of trees spawning in the flat areas.

- [ ] A feature to disable trees
- [ ] A feature to set a specific biome(s) to the noiceEffects

**Comment by cyberpwnn** [comment]
So like an option to reduce the chances of trees to a value (even 0) and slowly add them back as you approach the edge of the zone, I like it.

**Comment by MassiveLag** [comment]
> So like an option to reduce the chances of trees to a value (even 0) and slowly add them back as you approach the edge of the zone, I like it.

Exactly. And i can always readd objects myself with the aweosme iris feature

**Comment by cyberpwnn** [comment]
Biomes & Push up terrain place styles will be added in the future. This suggestion is complete.
