### ISSUE TITLE
unable to create iris world

### ISSUE THREAD

**Issue by FluffyDiscord** [VolmitSoftware/Iris#231]
**Describe the bug**
can't use /iris create <worldname>

**To Reproduce**
1. start server
2. join
3. type `/iris create sanic`

**Server and Plugin Informations**
 - Installed plugins: Multiverse-Core-4.2.2
 - Iris Version: Iris-1.2.3, Iris-1.2.4
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: paper-1.16.4-350, paper-1.16.4-389
 - Operating System (if applicable): win10
 - Server Logs: https://hastebin.com/ezumopeden.java https://hastebin.com/edugayikuj.sql

**Additional context**
clean server, settings.json deleted

**Comment by FluffyDiscord** [comment]
![image](https://user-images.githubusercontent.com/10332247/103581897-26c33b80-4edd-11eb-9a32-59b0f95bd3fb.png)

**Comment by FluffyDiscord** [comment]
![Uploading image.png…]()

**Comment by ghost** [comment]
Still present in 1.2.4 as reported by FluffyDiscord

**Comment by cyberpwnn** [comment]
Try /iris download overworld first before using that command. See if that fixes it.

**Comment by FluffyDiscord** [comment]
> 
> 
> Try /iris download overworld first before using that command. See if that fixes it.

Tried, same result.

**Comment by cyberpwnn** [comment]
Pushed 1.2.4-hotfix1. See if that does the trick

**Comment by cyberpwnn** [comment]
This was technically fixed, but there are still issues with multiverse. I'll be making a new issue for the Invalid Generator bug

**Comment by cyberpwnn** [comment]
(continued) https://github.com/VolmitSoftware/Iris/issues/234
