### ISSUE TITLE
very hot and very cold biomes like each other just too much

### ISSUE THREAD

**Issue by Pinkdulin** [VolmitSoftware/Iris#235]
**Describe the bug**
at example warm beach and snowy taiga are very often spawning directly beside each other, which is extramly unnatural

**To Reproduce**
just open a normal world, cant be too hard to find the bug

**Expected behavior**
natural biome neighbours; or at least make it customizable

**Screenshots or Video Recordings**
![grafik](https://user-images.githubusercontent.com/50804350/103793585-59d40f00-5044-11eb-8ce8-90f69e2102a3.png)

**Server and Plugin Informations**
 - Iris Version:  1.2.2
 - Server Platform and Version [eg: PaperSpigot 1.16.4 #240]: 1.16.4 #390

**Comment by astrsh** [comment]
Not really a bug - can be avoided using gradient based styles for regionStyle. Could also be mitigated if VolmitSoftware/IrisPlugin#33 were to be implemented.

**Comment by ghost** [comment]
As a User suggest it also help rearranging the regions like here: https://discord.com/channels/189665083817852928/768582615078010910/796436067947118592

**Comment by Fantabaum** [comment]
> 
> 
> As a User suggest it also help rearranging the regions like here: https://discord.com/channels/189665083817852928/768582615078010910/796436067947118592

Probably the collegue just had luck or used an older version but thats sadly not working

**Comment by Pinkdulin** [comment]
> 
> 
> Not really a bug - can be avoided using gradient based styles for regionStyle. Could also be mitigated if #210 were to be implemented.

Interesting, thank you! What do i have to change to what? Is there a explaination for it somewhere? Couldnt find exactly this in the wiki

**Comment by Pinkdulin** [comment]
> 
> 
> > Not really a bug - can be avoided using gradient based styles for regionStyle. Could also be mitigated if #210 were to be implemented.
> 
> Interesting, thank you! What do i have to change to what? Is there a explaination for it somewhere? Couldnt find exactly this in the wiki

if someone needs help with this too, that can be found here: https://discord.com/channels/189665083817852928/768582615078010910/797369630090985492

**Comment by ghost** [comment]
This will be resolved with child regions VolmitSoftware/IrisPlugin#33 as Astrash already said. Therefor is closed and reopened if child regions won’t fix this.
