### ISSUE TITLE
Snow layer getting generated incorrectly (since 1.2.5)

### ISSUE THREAD

**Issue by Pinkdulin** [VolmitSoftware/Iris#237]
**Describe the bug**
snopw layers spawn flying above the ground

**To Reproduce**
search frozen vander or snwy moutain biome

**Expected behavior**
normal snowlayers in the landscape

**Screenshots or Video Recordings**
![grafik](https://user-images.githubusercontent.com/50804350/104045379-c2ef8a00-51de-11eb-8392-f286e38d21ed.png)

**Server and Plugin Informations**
 - Iris Version: **1.2.5** ( I think its since that version!) <---------------------------------------------------
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: 1.16.3 #390

**Comment by svdgoor** [comment]
Can you send your settings for this, please?

**Comment by Fantabaum** [comment]
@CocoTheOwner Theyre nearly default, i just added rarity and removed effects and non-nature-structures;

> {
>     "vanillaDerivative": "SNOWY_MOUNTAINS",
>     "biomeSkyScatter": [
>         "SNOWY_TAIGA",
>         "SNOWY_MOUNTAINS"
>     ],
>     "objects": [
>         {
>             "chance": 0.02,
>             "density": 3,
>             "snow": 0.35,
>             "rotation": {
>                 "yAxis": {
>                     "min": 0,
>                     "max": 0,
>                     "interval": 90,
>                     "enabled": true
>                 },
>                 "enabled": true
>             },
>             "place": [
>                 "ice-spikes/ic-1",
>                 "ice-spikes/ic-2",
>                 "ice-spikes/ic-3",
>                 "ice-spikes/ic-4",
>                 "ice-spikes/ic-5",
>                 "ice-spikes/ic-6",
>                 "ice-spikes/ic-7",
>                 "ice-spikes/ic-8",
>                 "ice-spikes/ic-9",
>                 "ice-spikes/ic-10",
>                 "ice-spikes/ic-11",
>                 "ice-spikes/sp-1",
>                 "ice-spikes/sp-2",
>                 "ice-spikes/sp-3",
>                 "ice-spikes/sp-4",
>                 "ice-spikes/sp-5",
>                 "ice-spikes/tp-1",
>                 "ice-spikes/tp-2",
>                 "ice-spikes/tp-3",
>                 "ice-spikes/tp-4"
>             ],
>             "translate": {
>                 "x": 0,
>                 "y": -4,
>                 "z": 0
>             }
>         },
>         {
>             "chance": 0.5,
>             "density": 3,
>             "rotation": {
>                 "yAxis": {
>                     "min": 0,
>                     "max": 0,
>                     "interval": 90,
>                     "enabled": true
>                 },
>                 "enabled": true
>             },
>             "place": [
>                 "frosted-spruce/large-5",
>                 "frosted-spruce/large-6",
>                 "frosted-spruce/large-7",
>                 "frosted-spruce/large-8",
>                 "frosted-spruce/large-9",
>                 "frosted-spruce/large-12",
>                 "frosted-spruce/large-13",
>                 "frosted-spruce/large-14",
>                 "frosted-spruce/large-15",
>                 "frosted-spruce/large-16",
>                 "frosted-spruce/large-17",
>                 "frosted-spruce/large-18",
>                 "frosted-spruce/large-19",
>                 "frosted-spruce/large-20",
>                 "frosted-spruce/large-21",
>                 "frosted-spruce/large-22",
>                 "frosted-spruce/large-23",
>                 "frosted-spruce/large-24",
>                 "frosted-spruce/large-25"
>             ],
>             "translate": {
>                 "x": 0,
>                 "y": -1,
>                 "z": 0
>             }
>         },
>         {
>             "chance": 0.0125,
>             "density": 1,
>             "place": [
>                 "snowy/snowulder"
>             ],
>             "translate": {
>                 "x": 0,
>                 "y": 0,
>                 "z": 0
>             }
>         },
>         {
>             "chance": 0.05,
>             "density": 3,
>             "snow": 0.35,
>             "rotation": {
>                 "yAxis": {
>                     "min": 0,
>                     "max": 0,
>                     "interval": 90,
>                     "enabled": true
>                 },
>                 "enabled": true
>             },
>             "place": [
>                 "ice-spikes/ice-spec-1",
>                 "ice-spikes/ice-spec-2",
>                 "ice-spikes/ice-spec-3",
>                 "ice-spikes/ice-spec-4",
>                 "ice-spikes/ice-spec-5"
>             ],
>             "translate": {
>                 "x": 0,
>                 "y": 0,
>                 "z": 0
>             }
>         }
>     ],
>     "entityInitialSpawns": [
>     {"entity": "sheep", "maxSpawns": 1, "minSpawns": 1, "rarity": 6},
>     {"entity": "wolf", "maxSpawns": 1, "minSpawns": 1, "rarity": 6}
> ],
>     "biomeZoom": 30,
>     "derivative": "SNOWY_TAIGA_MOUNTAINS",
>     "biomeStyle": {
>         "style": "IRIS"
>     },
>     "decorators": [
>         {
>             "chance": 1,
>             "variance": {
>                 "style": "IRIS",
>                 "zoom": 0.25
>             },
>             "palette": [
>                 {
>                     "data": {
>                         "layers": 1
>                     },
>                     "block": "snow"
>                 },
>                 {
>                     "data": {
>                         "layers": 2
>                     },
>                     "block": "snow"
>                 },
>                 {
>                     "data": {
>                         "layers": 3
>                     },
>                     "block": "snow"
>                 },
>                 {
>                     "data": {
>                         "layers": 4
>                     },
>                     "block": "snow"
>                 }
>             ]
>         }
>     ],
>     "children": [
>         "frozen-peak",
>         "frozen-mountains",
>         "frozen-vander"
>     ],
>     "name": "Frozen Mountains",
>     "layers": [
>         {
>             "minHeight": 2,
>             "maxHeight": 3,
>             "palette": [
>                 {
>                     "block": "snow_block"
>                 }
>             ]
>         },
>         {
>             "minHeight": 2,
>             "maxHeight": 4,
>             "palette": [
>                 {
>                     "block": "packed_ice"
>                 }
>             ]
>         },
>         {
>             "minHeight": 6,
>             "maxHeight": 18,
>             "style": {
>                 "style": "STATIC"
>             },
>             "palette": [
>                 {
>                     "block": "andesite"
>                 },
>                 {
>                     "weight": 2,
>                     "block": "stone"
>                 }
>             ]
>         }
>     ],
>     "generators": [
>         {
>             "min": 3,
>             "max": 16,
>             "generator": "plain"
>         },
>         {
>             "min": 13,
>             "max": 48,
>             "generator": "mountain"
>         }
>     ],
>     "childShrinkFactor": 20,
>     "wall": {
>         "style": {
>             "style": "STATIC"
>         },
>         "palette": [
>             {
>                 "block": "andesite"
>             },
>             {
>                 "weight": 2,
>                 "block": "stone"
>             }
>         ]
>     },
>     "biomeScatter": [
>         "SNOWY_TAIGA_MOUNTAINS",
>         "TAIGA_HILLS",
>         "MOUNTAINS",
>         "ICE_SPIKES"
>     ],
>     "rarity": 13
> }

**Comment by astrsh** [comment]
This is caused by a configuration issue in the frozen vander biome having both a decorator for snow layers, as well as layer under "layers"

**Comment by svdgoor** [comment]
Once https://github.com/IrisDimensions/overworld/pull/6 is pulled this will be resolved. Let me know if there are other occurrences of this, I did not find any in the other snow biomes.
