### ISSUE TITLE
trees partitially cutted off at a side in 1.2.5

### ISSUE THREAD

**Issue by Pinkdulin** [VolmitSoftware/Iris#239]
**Describe the bug**
some trees at biomeborders are some times missing parts of the side, i only have seen it till now for birches

**To Reproduce**
search biomeborder birchforrest

**Screenshots or Video Recordings**
If applicable, add screenshots or video recordings to help explain your problem.
![grafik](https://user-images.githubusercontent.com/50804350/104089193-20321c80-526d-11eb-8f48-ccc9c0396bcb.png)
![grafik](https://user-images.githubusercontent.com/50804350/104089230-756e2e00-526d-11eb-87d2-983f171c8d2b.png)

**Server and Plugin Informations**
 - Iris Version: 1.2.5
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: paper 1.16.4

**Comment by svdgoor** [comment]
From the #news channel on Discord:

Cut off trees & objects issue
With our recent updates we have been trying our best to prevent issues such as this:
(https://github.com/VolmitSoftware/Iris/issues/239)
see attached screenshot

We would like to know if anyone still has this using the latest versions (1.3 or 1.3.1).

If you find this happening again, comment on the GitHub issue or send the screenshot in #iris-screenshots. Please also attach the log file of when this was generated so we can get more information.

Thank you for checking it out, have a nice day!

If this is found again, we will try again to resolve this.
