### ISSUE TITLE
Updating thread count during generation does not update the amount of threads used in that generation task

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#24]
running any /iris ctc during a pregen task does not update the threadcount.

**Comment by cyberpwnn** [comment]
This is intentional, it was meant to just change it in-memory for the current world you were in. I should just make a config reload command

**Comment by svdgoor** [comment]
Addition to this: Make sure that restarting doesn't reset the thread count set by /iris ctc to 8

**Comment by svdgoor** [comment]
Fixed in 1.22 or 1.23
