### ISSUE TITLE
(1.2.5) Server often crashes when generating new chunks; couldnt write parallax error

### ISSUE THREAD

**Issue by Pinkdulin** [VolmitSoftware/Iris#240]
**Describe the bug**
Server often crashes when generating new chunks; could write parallax error

**To Reproduce**
create new world, fly around or pregen; server should crash after some minutes

**Server and Plugin Informations**
 - Iris Version: 1.2.5
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: paper 1.16.5
 - Operating System (if applicable):
 - Server Logs: crash: https://pastebin.com/pWQCppuy 
 creation of new world: https://pastebin.com/gq27A0GK
 

white stopping the server is only using 50% Ram and 25% cpu

**Comment by Fantabaum** [comment]
second example: VolmitSoftware/Iris#241

**Comment by ghost** [comment]
Here is a copy of VolmitSoftware/Iris#241 that could have the same cause. If not VolmitSoftware/Iris#241 will be reopened.

Describe the bug
When new chunks are being generated in the world, from player exploration, the server lags and can crash.

To Reproduce

Create new world with Iris
Start Pregen or Fly through new chunks
Watch console/log for 'Malformed Input' spam
Server and Plugin Informations

Iris Version: Iris-1.2.5.jar
Server Platform and Version: Paper(398) 1.16.4-R0.1-SNAPSHOT
Server Logs: https://pastebin.com/2C0MqwD3

**Comment by cyberpwnn** [comment]
This should be fixed in the next update.

**Comment by cyberpwnn** [comment]
So i've resolved the issue where Iris is trying to place an object it cant load. Now it sends a single line error, but safe-fails (doesnt place the object or corrupt the chunk)

However i'd like to know the root cause of why this is happening in the overworld?

**Comment by ghost** [comment]
> So i've resolved the issue where Iris is trying to place an object it cant load. Now it sends a single line error, but safe-fails (doesnt place the object or corrupt the chunk)
> 
> However i'd like to know the root cause of why this is happening in the overworld?

BTW does this and VolmitSoftware/Iris#241 have the same issue?

**Comment by cyberpwnn** [comment]
> > So i've resolved the issue where Iris is trying to place an object it cant load. Now it sends a single line error, but safe-fails (doesnt place the object or corrupt the chunk)
> > However i'd like to know the root cause of why this is happening in the overworld?
> 
> BTW does this and VolmitSoftware/Iris#241 have the same issue?

Possibly but i doubt it. That may have had something to do with an old world updating to the newer version of parallax. Though its possible that not handling failing objects was causing malformed binary

**Comment by cyberpwnn** [comment]
This is fixed in 1.3 but 1.3 is not quite ready to release yet so im keeping this open

**Comment by ghost** [comment]
> This is fixed in 1.3 but 1.3 is not quite ready to release yet so im keeping this open
