### ISSUE TITLE
Server Crashing from New Chunks

### ISSUE THREAD

**Issue by Nildrak** [VolmitSoftware/Iris#241]
**Describe the bug**
When new chunks are being generated in the world, from player exploration, the server lags and can crash.

**To Reproduce**
- Create new world with Iris
- Start Pregen or Fly through new chunks
- Watch console/log for 'Malformed Input' spam

**Server and Plugin Informations**
 - Iris Version: Iris-1.2.5.jar
 - Server Platform and Version: Paper(398) 1.16.4-R0.1-SNAPSHOT
 - Server Logs: https://pastebin.com/2C0MqwD3

**Comment by Fantabaum** [comment]
youre not alone VolmitSoftware/IrisPlugin#287

**Comment by ghost** [comment]
Duplicate of VolmitSoftware/IrisPlugin#287. therefor it’s closed. See VolmitSoftware/IrisPlugin#287 for results.

**Comment by Tyllux-Nexus** [comment]
I compared the logs, it's displaying different errors.

**Comment by ghost** [comment]
I’ll add your logs to VolmitSoftware/IrisPlugin#287 and if it’s a different cause. Meaning if the fix for 240 isn’t fixing 241 it will be reopened. Are you okay with that?

**Comment by Tyllux-Nexus** [comment]
That's perfectly fine, I just wanted to make sure the issue was addressed from both angles if that makes sense, because I compared that log with mine before I posted and figured it was something different.

**Comment by ghost** [comment]
> That's perfectly fine, I just wanted to make sure the issue was addressed from both angles if that makes sense, because I compared that log with mine before I posted and figured it was something different.

Cyber is assuming this:
Possibly (the same issue as VolmitSoftware/IrisPlugin#287) but i doubt it. That may have had something to do with an old world updating to the newer version of parallax. Though its possible that not handling failing objects was causing malformed binary. @Nildrak

**Comment by cyberpwnn** [comment]
Im not sure how to fix this due to how Iris reads the data, there isnt a way to see what screwed up writing it... however, In 1.3 i will be adding more "enhanced" errors for this problem, and "softly fail" which means the object data wont place (sadly) but it wont break the entre world & server.  This should at the very least get us in the right direction to the root cause.

**Comment by svdgoor** [comment]
@Nildrak Can you send the enhanced errors if you still have this issue using v1.3 Iris? Will re-open once you do.
