### ISSUE TITLE
Option to give wand when pasting object

### ISSUE THREAD

**Issue by Astrashh** [VolmitSoftware/Iris#249]
**Is your feature request related to a problem? Please describe.**
When making edits to pre-existing objects, I will have to spawn in an Iris wand and go through the whole selection process - which can get tedious with some objects

**Describe the solution you'd like**
Adding a simple argument, for example `-o` to the `/iris object paste` command, which when specified gives you an Iris wand with the area of the pasted object already selected. For example, typing `/ir o paste buildings/houses/small-brick -o` would spawn in the brick house and put an Iris wand in your inventory with the house's bounding box selected. This would make tweaks to preexisting objects much quicker

**Comment by svdgoor** [comment]
Having this work the same way for Jigsaw objects with a preview like Structures currently do / used to have would be nice as well, but I can imagine this being quite challenging so definitely not required.

**Comment by cyberpwnn** [comment]
We used to have a command called `/iris object edit <object>`, it would give you a wand with the selection on it so you could save it back when you were done. I'll re-add this. Thanks!

**Comment by cyberpwnn** [comment]
Right... forgot Use `/iris o paste <object> -edit` while holding a wand
