### ISSUE TITLE
Customizable loot particles

### ISSUE THREAD

**Issue by LizardNetworkDevelopment** [VolmitSoftware/Iris#25]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Customizable particles above, under or around each chest / loot (like in the region settings).  
Would be fancy so players can guess the contents of each chest ("common", "special",...).

**Comment by NextdoorPsycho** [comment]
This is not something that isis is meant to do, if a plugin that is desined to manipulate loot, it should have a particle system, iris is a dimension gen that makes all the things needed for a dim, and this is a very niche request that should be added to a loot dependant plugin

**Comment by svdgoor** [comment]
We'll PR the system of you out anyone else makes it though
