### ISSUE TITLE
Enhanced post processing slab placement

### ISSUE THREAD

**Issue by astrsh** [VolmitSoftware/Iris#26]
## Current placement
While flying around the default overworld dimension, I noticed that the placement of slabs through the post processing slab option looked quite messy, and personally quite ugly. Currently with this feature, slabs are only able to be placed directly adjacent to block elevation changes, with the addition of being able to style it such that it looks less uniform.

![image](https://user-images.githubusercontent.com/73215501/97960467-aa8d7880-1e05-11eb-9902-e704494bc5ed.png)

## Proposed placement
As an improvement to the current slab placement system, I think slabs should be configured to how far they stem out from an elevation change. As an example, I tried visualizing what this might look like below.

![image](https://user-images.githubusercontent.com/73215501/97961057-ac0b7080-1e06-11eb-8582-6e10cb654494.png)

## How it might work
In the biomes slab option, a value from 0 - 1 could be specified to determine how far out slabs would be placed. That value could be compared to the height map, which would determine where a slab can be placed. For example below, a value of 0.5 would place slabs as such.

![Screenshot_3](https://user-images.githubusercontent.com/73215501/97960081-d0664d80-1e04-11eb-9f84-decf551bfe3b.png)
![Screenshot_4](https://user-images.githubusercontent.com/73215501/97960084-d2301100-1e04-11eb-8ed4-2358e8c84c42.png)

## Additional considerations
In addition to the above, I think it would be nice to be able to define different palettes based on the distance from block line. For example, a user might specify slabs to take up 60%, then have two separate palettes which are weighted as 2 and 1 as shown in the image below, which could open up for some nice looking transitions.

![Screenshot_7](https://user-images.githubusercontent.com/73215501/97961888-31435500-1e08-11eb-83cb-27fdbfcdb7f3.png)
![Screenshot_6](https://user-images.githubusercontent.com/73215501/97960176-0572a000-1e05-11eb-9b12-874ed14a391e.png)

Another thing I'd like to see in the same vein would be smooth snow layer transitions. Perhaps that would be made possible with this expansion of the current slab system with the ability to specify palettes based on the height.

![Screenshot_1](https://user-images.githubusercontent.com/73215501/97960088-d3f9d480-1e04-11eb-8761-cb906d67e882.png)

I am not entirely sure if this would be feasible to implement with how iris's internals currently work, or whether it would have any significant performance impact if it were to be implemented, though personally I'd be happy to have a bit of a slower generator for nicer looking slabs.

**Comment by cyberpwnn** [comment]
This was a very early design choice with Iris. This is why you dont see mountains that could be easily represented with a math function. Nature is messy. The second image looks fine, I think some biomes are using static for slabs instead of a better noise gen. Perhaps it could be improved but your last two images dont look like worlds from reality lol. Too perfect, too smooth.

**Comment by svdgoor** [comment]
So.... Close? (Reopen if wrong)
