### ISSUE TITLE
Unable to pregen more than 10k

### ISSUE THREAD

**Issue by FluffyDiscord** [VolmitSoftware/Iris#260]
**Describe the bug**
Anything above 10k pregen hangs the server for so long that it timeouts. The timeout I have it 360 in the config, that still is not enough for whatever iris is trying to do at the first "STARTUP" pregen step.

**To Reproduce**
iris pregen 20k

**Expected behavior**
Work. Show something is happening instead of strangling server cpu time, hanging it and killing it. I have no idea what the fist step "STARTUP" gen mode does, but if it takes even dozens of minutes on 16 thread cpu and 8G of ram to go to the actual generation step, there should be some kind of feedback to the user, that something is calculating, idk. Also it should be smart enough to leave some bare minimum of resources to the server, so it does not timeout (come on, don't tell me it's not possible), even when there are no players on it and it's being used just as a local pregen server.

**Server and Plugin Informations**
 - Installed plugins: Multiverse-Core-4.2.2(1), Iris-1.3.1
 - Iris Version: 1.3.1
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: paper-1.16.4-389
 - Operating System (if applicable): win10
 - Server Logs: https://pastebin.com/97MyyYkC

**Additional context**
Add any other context about the problem here, server timings reports, Iris dump information, complete console log etc. Please do not make Pastebin dumps or screenshot expire.

**Comment by ghost** [comment]
It depends on the hardware how long the preparation take to finish andiris starts with the pregeneration. Meaning it takes more time if you want to generate more chunks and therefor its more likely till the server is saying its timing out. So as you already mentioned on VolmitSoftware/IrisPlugin#56 would be the solution for this. Therefor i close this one.

**Comment by FluffyDiscord** [comment]
> 
> 
> It depends on the hardware how long the preparation take to finish andiris starts with the pregeneration.

Not quite true, as I said, my 16 threads are not being used while this step is in process, that means that the preparation must be single threaded, thus, any modern cpu will take the same time.

In the issue VolmitSoftware/IrisPlugin#56 I stated, that 30k pregen took whole 45 minutes to go from "STARTUP" to Direct gen mode, which means that it took 45 minutes to even start pregen process. This is less than optimal.

The VolmitSoftware/IrisPlugin#56 is more of a workaround rather than fix.
