### ISSUE TITLE
The ability to turn off ice formation for biomes

### ISSUE THREAD

**Issue by astrsh** [VolmitSoftware/Iris#27]
**Is your feature request related to a problem? Please describe.**
Currently I'm working on a frozen ocean biome, but ice formation wrecks the look when it generates over time

**Describe the solution you'd like**
A togglable option for turning off ice formation in biome configs

**Describe alternatives you've considered**
I could use a different derivative, however this is not ideal, as I would loose the blue hue of water that the cold ocean variants provide.

**Comment by svdgoor** [comment]
Doable with changing underlying vanillabiome. You can soon(tm) directly modify the sky colors of biomes so that's no problemo.
