### ISSUE TITLE
Parallax generation issue (java.lang.ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by bryiac** [VolmitSoftware/Iris#277]
### **Describe the bug**
Array index is exceeding bounds for parallax layers? 

### **To Reproduce**
1. **Use version (1.2 -> 1.2.1)**
2. **Run server**
3. **Error occurs in iris worlds**

### **Image**
![image](https://user-images.githubusercontent.com/38088988/103476406-447c8d80-4d83-11eb-80e2-2880c4dc2781.png)

### **Server and Plugin Informations**
 - Installed plugins: **Iris, WorldEdit, Multiverse**
 - Iris Version: **1.2.1**
 - Server Platform and Version [eg: PaperSpigot 1.16.3 VolmitSoftware/Iris#240]: **Tuinity version git-Tuinity-"8056d13" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)**
 - Operating System (if applicable): **Windows**
 - Server Logs: **https://mclo.gs/aoSsubp**

**Comment by AZFire1** [comment]
I have the same, or a similar issue here 

Crash Report: 
https://pastebin.com/0cwrpJJi
