### ISSUE TITLE
Bug: /iris what hand without holding anything prints nothing

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#28]
running /iris what hand without holding a block / other gives no command feedback

**Comment by svdgoor** [comment]
iris what block when looking up in the air gives an internal error

**Comment by svdgoor** [comment]
/iris what block when looking through water gives the block behind the water block
EDIT: same goes for lava

**Comment by svdgoor** [comment]
Resolved the first error (Fixed in 1.25)

Resolved the second error (Fixed in 1.25)

Not hitting fluids is intended.
