### ISSUE TITLE
Greyscale Noise Explorer

### ISSUE THREAD

**Issue by astrsh** [VolmitSoftware/Iris#28]
**Is your feature request related to a problem? Please describe.**
Currently, the noise explorer uses a rainbow-like gradient ramp to display noise generators. Sometimes this makes it a bit difficult to gauge how the generator will turn out.

**Describe the solution you'd like**
Optionally, the noise explorer could have a greyscale option as shown.

![image](https://user-images.githubusercontent.com/73215501/98502061-2c1d5480-22a5-11eb-9421-47ae5249289d.png)

**Comment by svdgoor** [comment]
Noise explorer is far better now, with the new `/iris map` feature you can do pretty much whatever you want.
Enjoy!
