### ISSUE TITLE
Block locate command in iris worlds

### ISSUE THREAD

**Issue by cyberpwnn** [VolmitSoftware/Iris#3]
its bad and it should feel bad

**Comment by ghost** [comment]
Is now a thing now again. Would be nice if it either got done like we had or VolmitSoftware/IrisPlugin#48 will fix this.

**Comment by svdgoor** [comment]
What is this? Literally /ir std goto [block]?

**Comment by ghost** [comment]
If you use /locate village for example the server crashes. Therefor the command should be either blocked or the command should link to the structures

**Comment by svdgoor** [comment]
Oh I thought it was a *Block* locate command, not block *Locate command*

**Comment by svdgoor** [comment]
Locating structures in an Iris world gives no error for me. It finds a location but there is no structure there. Blocking this command is not really required, but it is something we might want to have point to the structures as we place them in the world.

**Comment by svdgoor** [comment]
Should be fixed with VolmitSoftware/IrisPlugin#48
