### ISSUE TITLE
Pregen map GUI should show true colors

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#31]
![afbeelding](https://user-images.githubusercontent.com/65736624/96371182-bec44b00-1160-11eb-82d5-fbdb5f90d42d.png)
Even plain colors for the biomes would be enough

**Comment by cyberpwnn** [comment]
The reason for this is because im really just guessing. If its aquatic, some random shade of blue, if not, some random shade of green. 

I need to poll a list of colors for them using block derivatives

**Comment by svdgoor** [comment]
Since adding this would slow down pregen speed, I'm retracting my request.
If anyone really wants this to be added, they can reply here or make a new request.
