### ISSUE TITLE
events

### ISSUE THREAD

**Issue by RaydenKonig** [VolmitSoftware/Iris#31]
Hello! I haven't bought the plugin yet since I'm raising the money
from what I have seen, it is an incredible complement!

but I would like to give you a suggestion that would interest me a lot and I assume that many others

and it is the option to add events in the plugin, that is, when a player passes through a biome for the first time or not

commands can be set for that event

since I would like to make that when my players explore the map and find a new biome they will get an achievement poster telling them the name of the biome

this I assume will be difficult but also add Placeholders with the names of the biomes

Thank you very much for your attention, as soon as I can I will buy the complement
:D

pds: if you notice nonsensical things in my narration, I am using google translator xd

**Comment by svdgoor** [comment]
#364 dupe
