### ISSUE TITLE
Add support for custom-tree-from-sapling

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#32]
**Is your feature request related to a problem? Please describe.**
Saplings grow ugly vanilla trees

**Describe the solution you'd like**
A config in the dimension (At least, maybe also regions and *maybe* even biomes) where you can select a (set of) tree(s) per sapling in that biome.

**Describe alternatives you've considered**
An alternative plugin that does the same, but it takes more configuration, copying of structures to W/E structures. Much more effort. Also leaf decay with those plugins is bust.

(EWG can do this, so we must do it better)

**Comment by espen96** [comment]
for overworld:
my players have previously expressed that they are not fond of large or weird custom sapling trees, so any custom tree we want to spawn should probably be closer to a vanilla tree.

**Comment by svdgoor** [comment]
Per dimension -> region -> biome basis
In general -> per sapling type -> select a list of objects (perhaps with chances, perhaps for an x by x area of saplings (supporting more than 2x2 event))
Make sure to remember the placement of the object, such that #43 would actually be feasible
Option to check for existing blocks (i.e. can't place). 
Additional options to warn players using saplings they can't grow because of space restrictions:
- Warn when placing sapling
- Occasionally check and update display above sapling
- When using bonemeal only
-> Need to keep in mind scalability

Should also warn somehow when using bonemeal on a sapling, or perhaps already when placing the sapling or even constantly near every sapling

**Comment by ghost** [comment]
@CocoTheOwner implemented but not finished yet?

**Comment by svdgoor** [comment]
The system is inconsistent for unknown reasons.

**Comment by NextdoorPsycho** [comment]
Consistent as of latest, and with overworld implementation.
