### ISSUE TITLE
Adding vanilla bedrock

### ISSUE THREAD

**Issue by energooooo** [VolmitSoftware/Iris#329]
**Describe the solution you'd like**
Adding vanilla bedrock

**Comment by ghost** [comment]
Can you please describe your idea more detailed?

**Comment by energooooo** [comment]
So that when generating a world at height 1 there is a solid bedrock, and from height 2 to height 5 there is a bedrock as in the normal (Valny) world.
This feature can be turned on and off in the settings

> Can you please describe your idea more detailed?

**Comment by UserDerezzed** [comment]
This can already be done through the dimension packs.
