### ISSUE TITLE
Vacuum and Translate is not working well together

### ISSUE THREAD

**Issue by Inxity** [VolmitSoftware/Iris#330]
**Describe the bug**
When i enable Vacuum mode while using translate selected structure is spawning at top, bottom and land of the map

**To Reproduce**
		{
			"place": [
				"yourstructure"
			],
		    "chance": 0.5,
		    "mode": "VACUUM",
                    "translate": {
                         "x": 0,
                         "y": 1,
                         "z": 0
                    }
		},
paste this to any biome's objects section

**Expected behavior**
It should spawn the structure top of the world, or bottom

**Screenshots or Video Recordings**
https://hizliresim.com/31vJS1

**Server and Plugin Informations**
 - Installed plugins: Iris, EssentialsX, Worldedit, Multiverse-Core
 - Iris Version: 1.3.3.14D
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Paper 1.16.5 #554
 - Operating System (if applicable): Ubuntu 20.04
 - Server Logs: [2021-03-18-1.log.gz](https://github.com/VolmitSoftware/Iris/files/6166020/2021-03-18-1.log.gz)

**Additional context**
nope

**Comment by stijnb1234** [comment]
![image](https://user-images.githubusercontent.com/27051051/111752318-d6ca0300-8895-11eb-92bc-04b040827ad9.png)

*(Pasted image to GitHub for archival purposes)*

**Comment by NextdoorPsycho** [comment]
vacuum happesns after translation, what you are trying to do is have structures on top of peaks, and instead of using that placemode, generate proper mountains, and use clamp, with vaccum, and the objects will be placed at the clamp range, and terrain will be pushed or pulled to this.
