### ISSUE TITLE
VSCode Studio World

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#331]
VSCode only opens when a Studio World is created a second time

Project missing code-workspace: C:\Users\Armin\Desktop\dev\plugins\Iris\packs\overworld\overworld.code-workspace Re-creating code workspace.

**Comment by svdgoor** [comment]
Caused by workspace missing, then failing to open the file since it's not existant.
Fix: move vscode open to after create workspace

**Comment by ghost** [comment]
Okay i maybe now know why that is happening to me. The console freezes for some reason and if i press enter VSCode opens and everything is fine.
