### ISSUE TITLE
oceans and beaches by biome and not by region

### ISSUE THREAD

**Issue by RaydenKonig** [VolmitSoftware/Iris#333]
**Is your feature request related to a problem? Please describe.**
When creating the rivers, I have several problems, such as land bridges in biomes with certain heights, but these rivers in other biomes are generated well

In addition, to make beaches with land, a derivative biome must be assigned, which, if this beach is generated in a biome that has, for example, "JUNGLE"
it will contrast and condition the options to choose the colors of the biomes

**Describe the solution you would like**
the solution I have in mind would be to add the options
"shoreBiomes" and "seaBiomes" within the biome file and that these do not depend solely on the region
This will make it possible to put specific rivers and beaches for each biome, greatly opening the range of variety and customization within the dimension.

**Comment by svdgoor** [comment]
This would likely be a part of a full biome/region rewrite if anything. Would be a good bandaid fix, but doesn't really solve underlying problems (such as #283)
