### ISSUE TITLE
/iris fix command

### ISSUE THREAD

**Issue by patrikkoudelka** [VolmitSoftware/Iris#337]
**Describe the bug**

I used /iris fix <view-distance> so /iris fix 3, and it fixed 0 blocks, but when I do /iris fix it will fixed normally.

**Server and Plugin Informations**
 - Installed plugins:
 - Iris Version: Newest
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Paperspigot 1.16.5 newest
 - Operating System (if applicable):
 - Server Logs:

**Comment by UserDerezzed** [comment]
I've just tested this on 1.3.3 with the Overworld pack - cannot reproduce. Is this still happening for you?

**Comment by UserDerezzed** [comment]
Please reopen if this is still occurring.
