### ISSUE TITLE
Crash when creating pack with `-` in its name

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#338]
**Describe the bug**
See title

**To Reproduce**
1. Download overworld v2 pack
2. Rename it to overworld-v2
3. Try to create anything, studio, /ir c
4. See crash

**Expected behavior**
No crash

**Screenshots or Video Recordings**
https://pastebin.com/ftxxzwzz

**Server and Plugin Informations**
Happens to everyone

**Comment by UserDerezzed** [comment]
This should be fixed, it was an issue with the setup of the listing and packs. A bugfix will go out to reenable downloads of `overworld-legacy` and `overworld-factions`
