### ISSUE TITLE
Suggestion: make a toggle that prevents the world from being expanded by players beyond a boundary

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#34]
Title speaks for itself. Perhaps force this setting on during pregen as well

**Comment by cyberpwnn** [comment]
This isnt possible. When bukkit asks for a chunk, the server will freeze uninterruptibly until that chunk exists. The only alternative is to throw an exception and crash the server.

The best that could be done would be to teleport people back inside of the world.... however what about world borders? Like vanilla ones? Wouldnt that be fine?

I like the idea for the pregen though, try to stop people from teleporting or getting outside of the border. The only issue with this is i cant stop a chunk from generating so... there would still be some if you "really" tried to get out there.

**Comment by svdgoor** [comment]
A world border based on the generation setting would be fine as well.
Could you generate void chunks which you can then replace or would that be too resource intensive?
