### ISSUE TITLE
Allow styled cave layers 

### ISSUE THREAD

**Issue by astrsh** [VolmitSoftware/Iris#34]
Currently, cave layers are hardcoded to use the vascular style and have a set height. After some experimenting I've found that aside from manipulating the horizontal and vertical slopes (which work well), the base height and width (maybe the cave  thickness parameter is not working as intended?) cant be modified. 

The only ways I've managed to manipulate the shape of caves is through the zoom option, which is quite limiting. It would be nice to be able to have a finer control over cave generation by allowing styles to dictate the shape as well as being able to specify the thickness (basically thresholding the style) + the height (multiplying the style after it has been thresholded).

**Comment by ghost** [comment]
Cave rework soon ™️

**Comment by svdgoor** [comment]
Talking to Dan & Brian, we found pretty much everything is possible with caves with the current toolset. It could be more intuitive.
