### ISSUE TITLE
Low generation of animals/villagers

### ISSUE THREAD

**Issue by borjxrroyo** [VolmitSoftware/Iris#341]
**Describe the bug**
Hi there, today some users reported to me that there were only a few of mobs in the world, so I decided to test the latest version of Iris, 1.3.3 with OverWorld V2. It spawned a good quantity of animals at the beginning, but when I was walking around, the quantity was decreasing and there were almost no animals, but there were hostile mobs. There also were villagers, and some had dead suffocated in walls.

I tried a lot of options thanks to the Discord support, but I had no success.

**To Reproduce**
Explained above

**Expected behavior**
To have a normal quantity of animals in the world, and avoid bad villagers generation, preventing suffocations.

**Screenshots or Video Recordings**
That happened when trying to generate an Overworld V2 World into 1.3.3:
https://i.gyazo.com/5fd7e7b3eba791824bd996da2a2dff64.png

Some villages in v2, without villagers: https://i.gyazo.com/c4cfa6320ae2ae17edf0b692e84c4291.jpg

**Server and Plugin Informations**
 - Installed plugins: MultiVerse (important)
 - Iris Version: 1.3.3
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: PaperSpigot 1.16.5

**Comment by borjxrroyo** [comment]
PD: When feeding a dolphin, all the nearly fishes get frozen and the server gets lagged.

**Comment by Inxity** [comment]
I am not sure if feeding dolphine bug is from Iris but i have the same bug in my server too

**Comment by Inxity** [comment]
+ also zombies are not attacking to Iris Villagers

**Comment by svdgoor** [comment]
Is this still happening?

**Comment by cyberpwnn** [comment]
Yup

**Comment by svdgoor** [comment]
Can't reproduce on latest.
Overworld now has plenty of mobs, and feeding dolphins didn't freeze the server.
