### ISSUE TITLE
The smoothieMap 'illegal reflective access operation' is required and can be safely ignored

### ISSUE THREAD

**Issue by steven11304** [VolmitSoftware/Iris#342]
**Describe the bug**
[INFO] .... [Iris]: The smoothieMap 'illegal reflective access operation' is required and can be safely ignored

[WARNING] ....WARNING: An illegal reflective access operation has occurred

[WARNING] WARNING: Illegal reflective access by io.timeandspace.smoothie.ObjectSize (file:/home/gs-41507/plugins/Iris-1.3.3.jar) to field java.util.HashMap.table

[WARNING] WARNING: Please consider reporting this to the maintainers of io.timeandspace.smoothie.ObjectSize

[WARNING] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

[WARNING] WARNING: All illegal access operations will be denied in a future release

**To Reproduce**

**Expected behavior**

**Screenshots or Video Recordings**
If applicable, add screenshots or video recordings to help explain your problem.

**Server and Plugin Informations**
 - Installed plugins:
 - Iris Version:
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]:
 - Operating System (if applicable):
 - Server Logs:

**Additional context**
Add any other context about the problem here, server timings reports, Iris dump information, complete console log etc. Please do not make Pastebin dumps or screenshot expire.

**Comment by UserDerezzed** [comment]
The smoothieMap 'illegal reflective access operation' is required and can be safely ignored
