### ISSUE TITLE
Pregen bug "no radius specified"

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#343]
**Describe the bug**
When trying to pregen a world with iris using the command /iris pregen 5000 world you’ll get the message „no radius specified“. This only happens at the latest purpur version. Haven’t tested it on spigot or paper. It worked on an older version of purpur.

**To Reproduce**
1. Go to issue /iris pregen 5000 world

**Expected behavior**
Just do the pregen as expected.

**Screenshots or Video Recordings**
If applicable, add screenshots or video recordings to help explain your problem.

**Comment by xmorose** [comment]
Seems like this happens on paper as well (git-Paper-586)

**Comment by RaydenKonig** [comment]
I tried to install an older version of purpur and now I can pre-generate
purpurclip-1.16.5-959

**Comment by bakaschwarz** [comment]
Could reproduce on paper (v. 635)

**Comment by cyberpwnn** [comment]
Anyone having this issue, try 1.3.4 when it comes out, whoever edited this was suppressing the actual error which could have nothing to do with the radius. Next update you should see an error when you try this please paste it here.

**Comment by xmorose** [comment]
@cyberpwnn The error is this: https://pastebin.com/21xT2HEh (git-Paper-589)
Note: Logs are upside down, newest messages at the top

**Comment by ghost** [comment]
A user already submitted a pr for a temp fix for the pregen error

**Comment by cyberpwnn** [comment]
Oh that's the same issue? I cant merge that lol, there's changes in things that would break the build. I'll have to fix it then. Would have preferred a stack trace :P

**Comment by ghost** [comment]
As he said it’s just a temp fix but you’ll get the problem and probably a proper fix out of it

**Comment by covoge** [comment]
I went ahead and removed the build-breaking changes in my PR. What I meant when saying it is a temporary solution is that you might want to look into how Iris can use this new custom biome for new biome implementations going forward.
