### ISSUE TITLE
Loot table object in objects placement

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#344]
**Is your feature request related to a problem? Please describe.**
Adding loot tables are now done on a macro, biome level. Adding them to objects would make for far more customizability and make it easier to make changes to a specific objects' loot table everywhere.

**Describe the solution you'd like**
Make objects have a configuration setting for "loot", which works the same as the existing one in the biome.

**Describe alternatives you've considered**
Making separate biomes with the same settings for different objects each. Please no.

**Comment by NextdoorPsycho** [comment]
OBJECTS
- "Primative"
- Have Styles
- Object Priority Placement System
- Waterlogged
- Supports Bottom
- Have place modes
- Have density
- Have chance
- Have an Array of random objects that are placed on call
- Suport Edits (rotation, movement etc...)
- Supports Translation
- CarvingSupport


JIGSAW
----same as object----
- "Non-Primative"
- Have Styles
- Waterlogged
- *Object Priority Placement System *(Already implemented with jigsaw schema)
- Have place modes
- Does not Support Bottom should
- Have density
- Have chance
- Have an Array of random objects that are placed on call
- Suport Edits (rotation, movement etc...)
- Supports Translation
----same as object----
- Fallback pools (needs to be implemented)
- Connectors
- Loot
- Rarity implementation
- Names**
- CarvingSupport
