### ISSUE TITLE
Error while creating an object

### ISSUE THREAD

**Issue by energooooo** [VolmitSoftware/Iris#345]
**Describe the bug**
When creating an object with the command `/ir o save overworld test/testing_01` writes a message to the chat (See attachments) and gives an error in the console

**Expected behavior**

**Screenshots or Video Recordings**
https://prntscr.com/127v40t
https://prntscr.com/127v5w4
https://prntscr.com/127v6so
https://prntscr.com/127v7g9

Error: https://prnt.sc/127vadm

**Server and Plugin Informations**
 - Installed plugins: Iris
 - Last build github
 - PaperSpigot 1.16.5 #613]:
 - Operating System (if applicable): 7 gb RAB and Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
 - Server Logs: https://pastebin.com/0Jxbtczi

**Comment by cyberpwnn** [comment]
Would strongly suggest posting errors in text. Lightshot is super slow, gotta check the logs alone.

**Comment by cyberpwnn** [comment]
But it looks like iris was reloaded at runtime at some point. It's failing to load it's own classes because the jar changed, It's failing to load tile data.

**Comment by energooooo** [comment]
I tried to do this at different times on different servers and the error did not go away

> But it looks like iris was reloaded at runtime at some point. It's failing to load it's own classes because the jar changed, It's failing to load tile data.

**Comment by ghost** [comment]
> But it looks like iris was reloaded at runtime at some point. It's failing to load it's own classes because the jar changed, It's failing to load tile data.



> I tried to do this at different times on different servers and the error did not go away
> 
> > But it looks like iris was reloaded at runtime at some point. It's failing to load it's own classes because the jar changed, It's failing to load tile data.

Tested your command on an object and is working fine.

**Comment by energooooo** [comment]
> > But it looks like iris was reloaded at runtime at some point. It's failing to load it's own classes because the jar changed, It's failing to load tile data.
> 
> > I tried to do this at different times on different servers and the error did not go away
> > > But it looks like iris was reloaded at runtime at some point. It's failing to load it's own classes because the jar changed, It's failing to load tile data.
> 
> Tested your command on an object and is working fine.

I just took the compiled plugin from the github and repeated it again and the error is the same

**Comment by ghost** [comment]
> > > But it looks like iris was reloaded at runtime at some point. It's failing to load it's own classes because the jar changed, It's failing to load tile data.
> > 
> > 
> > > I tried to do this at different times on different servers and the error did not go away
> > > > But it looks like iris was reloaded at runtime at some point. It's failing to load it's own classes because the jar changed, It's failing to load tile data.
> > 
> > 
> > Tested your command on an object and is working fine.
> 
> I just took the compiled plugin from the github and repeated it again and the error is the same

Im currently working on a jigsaw structure for a user. I can easily create iris objects with that command and wand. Means you are somehow doing mistakes.

**Comment by energooooo** [comment]
> > > > But it looks like iris was reloaded at runtime at some point. It's failing to load it's own classes because the jar changed, It's failing to load tile data.
> > > 
> > > 
> > > > I tried to do this at different times on different servers and the error did not go away
> > > > > But it looks like iris was reloaded at runtime at some point. It's failing to load it's own classes because the jar changed, It's failing to load tile data.
> > > 
> > > 
> > > Tested your command on an object and is working fine.
> > 
> > 
> > I just took the compiled plugin from the github and repeated it again and the error is the same
> 
> Im currently working on a jigsaw structure for a user. I can easily create iris objects with that command and wand. Means you are somehow doing mistakes.

The server has just been created. The plugin is only compiled from the github, right now I will find out what the problem is. Funny situation
