### ISSUE TITLE
Omitted "required" tag on composite field

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#346]
**Describe the bug**
Omitted required tag on composite field in generator

**To Reproduce**
1. Open any generator
2. Remove the "composite" component
3. Observe VSCode not complaining about a missing item
4. Observe errors when generating using the generator

**Expected behavior**
VSCode indicates the object is required

**Server and Plugin Informations**
Nothing that interferes
[2021-05-01-9.log](https://github.com/VolmitSoftware/Iris/files/6410149/2021-05-01-9.log)

**Comment by cyberpwnn** [comment]
Composites are not required because if you choose to not use a composite at all, you never need to use the composite key. Only if you are using multidim setups you would need a composite.
