### ISSUE TITLE
Expose noise setting for caves

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#347]
**Is your feature request related to a problem? Please describe.**
Can't modify main cave noise layer

**Describe the solution you'd like**
Exposed cave object through a style. Preferably for each separate cave layer.

**Describe alternatives you've considered**
Mimicing another style through crazy fracturing. No please.

**Comment by cyberpwnn** [comment]
Caves setup the way they are are super sensitive and thats why i only added ways to bend it, i'll see if i can use a noise stream instead of locked noise
