### ISSUE TITLE
Bug: all buildings with chests in them have no loot

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#35]
Not sure if this is a configuration error or a bug, but I feel like this is the right place to mention this.

**Comment by cyberpwnn** [comment]
@CocoTheOwner is this only in structures? Do they generate in objects or dont know?

**Comment by svdgoor** [comment]
Don't know the difference between objects and structures.
I have seen this in village buildings, some 3x3 stone pylon with a chest in it, sunken boat.
Also in some structures with barrels in them have no items in the barrels
I have found no chests at all with items in them

**Comment by NextdoorPsycho** [comment]
This is inaccurate, the loot system is the real issue. the loot system has a chance to not put things in chests, but you can find chests with loot in them albeit uncommon

**Comment by svdgoor** [comment]
Based on Psycho's comment, I would recommend changing this into a suggestion and making it something like
"increase loot in structures' chests"

**Comment by cyberpwnn** [comment]
All loot tables now have a minLoot value (defaults to 1) so now each loot table must give 1 item unless otherwise specified. 1.0.19

**Comment by svdgoor** [comment]
I'm stupid, was in spectator mode. Fixed.
Making a new suggestion to add the "loot has not been generated yet" tag to the chests (like happens in vanilla structures when they are generated as a spectator)
