### ISSUE TITLE
Adding support for ItemsAdder

### ISSUE THREAD

**Issue by xalixilax** [VolmitSoftware/Iris#353]
**Is your feature request related to a problem? Please describe.**
Adding support for custom blocks from the plugin ItemsAdder

**Describe the solution you'd like**
Being able to use ItemsAdder block in the generation of the world and in custom structure. A public API is available at the link given below. This would allow the creation of entirely new biome containing new blocks similar to what modded could achieve. Multiple kind of blocks can be used as a base blocks for ItemsAdder like mushroom, note block, spawner and chorus. From my understanding, mushroom and chorus is likely to cause error, spawner is probably gonna be a laggy mess, but note block should not interfere and have pretty good performance. 

**Describe alternatives you've considered**
I think RealisticWorldGenerator is using Structure Block with text in it to generate the block in the structure. Not sure about how they achieve it for the world generation.
You can generate it pretty easily simply by writting itemadder:NAMESPACE:BLOCK

API
https://itemsadder.plugin.ga/compatibility-with-other-plugins/adding-compatibility
ItemsAdder
https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-itemsadder%E2%9C%A8custom-items-huds-guis-mobs-3dmodels-emojis-blocks-wings-hats-liquids.73355/

**Comment by NextdoorPsycho** [comment]
no, use Oraxen's mod. The developer for itemsadder refused to change how he makes hooks, and iris does not place blocks. thats stupid and slow, and the developer will not add support for other people's api's, and demands that we change out plugin to satisfy his lack of trust in his own systems
