### ISSUE TITLE
Bug: Barely any animals spawn anywhere in the world

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#36]
Where vanilla minecraft has animals in the weirdest location, Iris has barely any.
Note: this could be because I am also generating the world while exploring, but theres' also mobs spawning so I think that's not a reasonable assumption

**Comment by cyberpwnn** [comment]
I think the world generates with mobs in vanilla. The overworld dimension has this turned off. We will turn it on.

**Comment by NextdoorPsycho** [comment]
IN latest now, thank you
