### ISSUE TITLE
Entity spawns for objects

### ISSUE THREAD

**Issue by Darkdeviousdevil** [VolmitSoftware/Iris#36]
**Is your feature request related to a problem? Please describe.**
The feature request isn't related to a problem, just something I'd like to see. You can only have entity spawns in structures but the thing with structures is that you have to learn its complex system and inner workings. It'd be nice to be able to avoid having to learn about structures, and instead just have to setup entity data for an object.

**Describe the solution you'd like**
I am thinking of a `"entityInitialSpawns"` section with objects in biome files, seeing as you cannot edit object files directly themselves.

**Describe alternatives you've considered**
This to me seemed liked the most root way or narrowed down way to go about it, therefore haven't considered any alternatives. I thought about putting the section in region files, but going up to parent categories seems like a step backward. 

**Additional context**
No additional context.

**Comment by NextdoorPsycho** [comment]
Use a jigsaw
OBJECTS
- "Primative"
- Have Styles
- Object Priority Placement System
- Waterlogged
- Supports Bottom
- Have place modes
- Have density
- Have chance
- Have an Array of random objects that are placed on call
- Suport Edits (rotation, movement etc...)
- Supports Translation
- CarvingSupport


JIGSAW
----same as object----
- "Non-Primative"
- Have Styles
- Waterlogged
- *Object Priority Placement System *(Already implemented with jigsaw schema)
- Have place modes
- Does not Support Bottom should
- Have density
- Have chance
- Have an Array of random objects that are placed on call
- Suport Edits (rotation, movement etc...)
- Supports Translation
----same as object----
- Fallback pools (needs to be implemented)
- Connectors
- Loot
- Rarity implementation
- Names**
- CarvingSupport
