### ISSUE TITLE
Improvement of cave generation

### ISSUE THREAD

**Issue by espen96** [VolmitSoftware/Iris#362]
at the moment, making good caves can be a bit tricky, especially dead ends. 

I propose that allowing for some layers to be generated after the rest, completely solid, no air, would make it way easier to add dead ends. 

the lack of dead ends is probably the biggest issue today in my opinion.

In the future, adding 3D noise for caves would allow for smoother caves with less weirdness. 

cellular automata would be another option for making interesting caves.

**Comment by NextdoorPsycho** [comment]
All of this is more of a pragmatic overworld issue. if you know how to configure it properly, you can have way moredeadends than normal. (fill%) and this is already able to be done. sure its not easy with no understanding, but the system exists
