### ISSUE TITLE
Jigsaw Connectors misconnecting pieces

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#367]
## Description
Jigsaw structures sometimes do not correctly place jigsaw pieces together with their connectors. Sometimes a gap between the connectors, usually on the Y axis, occurs. However, this is not completely consistent and does not occur every time. I suspect it happens most often when the server is lagging, as it does not happen when you force a structure generation. E.g. `/iris jigsaw place stronghold`

I also suspect that this usually happens on the Y axis because pieces are usually rotated only on the Y axis in jigsaw structures.

### Example
I made a test structure, as seen below, that has connectors strictly on resource/ore blocks. Gaps can be seen in the yellow circled areas. This gap has observed to be 1-3 blocks, and usually is on the Y axis.

![](https://i.imgur.com/PtEFekW.jpg)

### Strongholds:

1. Generate a stronghold in a world with `/iris jigsaw place stronghold`. Notice how all the connectors to the portal room are 100% fine.
2. Open an Iris studio world and find a natural stronghold. The pieces connected to the portal room are sometimes offset by 1-3 blocks on the Y axis

### Test Structure:

1. Download the test jigaw structure here: https://mega.nz/file/g4EVxKxD#3uEMmfdMFuThb6rrkp6fs72B04vY4J1Hp7bCN9IXpWs
2. Generate the structure in a world with `/iris jigsaw place jigsaw-test`. Observe that the connectors (the resource blocks) are functioning as intended.
3. Add a natural spawning of the structure to a test world. I have been using ```"jigsawStructures": [
    {
        "rarity": 50,
        "structure": "jigsaw-test"
    }
],```in my spawn biome.
4. Find the structure
5. Look for places where resource blocks aren't connected. If you can not see any, continue looking for the structure with `/iris std goto` until you find it
6. If you are still having issues on the step above, try overload your server then try it. I suspect it may have to do with generation speed.

## Server and Plugin Informations
- Iris: v1.3.5-1.3.10
- Purpur 1.16.5 build 1111
- Windows 10

## Other
This is probably the same thing causing https://github.com/IrisDimensions/overworld/issues/39

**Comment by svdgoor** [comment]
I can't look at this, it's cursed.

**Comment by svdgoor** [comment]
Patched on latest, @StrangeOne101 ?

**Comment by StrangeOne101** [comment]
> Patched on latest, @StrangeOne101 ?

Can confirm that this is not fixed

**Comment by svdgoor** [comment]
Pretty sure this is related to placeCenterY in IrisObjects, which rounds x, y and z.

**Comment by NextdoorPsycho** [comment]
So like the small pick tweak that was made in the latest update just fundamentally changed how anything is picked, and may have fixed this, please check

**Comment by NextdoorPsycho** [comment]
No Complaints yet? Reopen if persisting
