### ISSUE TITLE
(Jigsaw) structures with vacuum close to eachother result in one failing to vacuum.

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#368]
**Describe the bug**

**To Reproduce**
See overworld villages that spawn on non near-flat terrain for reference

**Expected behavior**
Hard time figuring out a good way. But a good start would be to fallback to STILT placement mode (the one that makes a giant pillar below the building).

**Screenshots or Video Recordings**
![afbeelding](https://user-images.githubusercontent.com/65736624/121383816-0560f280-c948-11eb-9a90-f1c52aad9610.png)

**Server and Plugin Informations**
 - Installed plugins: Iris and MV with nothing else that matters
 - Iris Version: 1.3.8
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Latest purpur (build 1150 something, it's been happening for long tho)
 - Operating System (if applicable): Not applicable. Running on a mousepad.
 - Server Logs: Nothing in them that shows this. Again, been happening for a long time.

**Additional context**
Add any other context about the problem here, server timings reports, Iris dump information, complete console log etc. Please do not make Pastebin dumps or screenshot expire.

**Comment by NextdoorPsycho** [comment]
lol

**Comment by svdgoor** [comment]
Just. Do it

**Comment by svdgoor** [comment]
Please make STILT a fallback for a failing VACUUM so it looks halfway decent

**Comment by ghost** [comment]
@cyberpwnn fixed with your recent commits?

**Comment by svdgoor** [comment]
no

**Comment by NextdoorPsycho** [comment]
Fixed on latest
