### ISSUE TITLE
Absoulute height definition for BiomePalleteLayers and Decorators

### ISSUE THREAD

**Issue by astrsh** [VolmitSoftware/Iris#37]
**Is your feature request related to a problem? Please describe.**
Currently I'm trying to create a badlands biome, with layers of terrain having lines through it at specific Y levels, similar to this screenshot:

![image](https://user-images.githubusercontent.com/73215501/102703679-0df43c80-42c6-11eb-9028-0d41bc56ac91.png) 

With the current methods available, this is difficult to configure

**Describe the solution you'd like**
I think it would be very useful to introduce a setting similar to "slopeCondition", but for absolute height. For example, if I wanted a layer of red terracotta within the Y range [75, 80], I could add the following json onto a biome pallete layer, which would overwrite any blocks within that range for that biome.

```
            "heightCondition": {
                "minimumHeight": 75,
                "maximumHeight": 80
            },
```
If two layers both had overlapping height conditions, then the one defined first in the layer list would take priority

**Describe alternatives you've considered**
I've messed around with the lock layers option but that is very hard to work with because every single layer gets factored in when its enabled, and it's difficult to gauge what exactly the outcome will look like for any given area. I think this could be a very simple solution to the issue of absolute height palettes, and would make things like this much easier to work with

**Comment by svdgoor** [comment]
@NextdoorPsycho Is this currently achievable?

**Comment by NextdoorPsycho** [comment]
yes, this is possible
