### ISSUE TITLE
Decorator Block Place Requirements

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#372]
## Description 
I think a way for decorators to only place blocks when certain block conditions are met. For example, only place tall grass on grass blocks in a biome where sand and grass blocks spawn.

## Proposition 
Here is an example of how JSON syntax could be
```json
"decorators": [
    {
        "chance": 0.2,
        "palette": [
            {
                "block": "tall_grass",
            }
        ],
        "placeRequirements": [
            {
                "axis": "y",
                "amount": -1,
                "palette": [
                    {
                        "block": "grass_block"
                    }
                ],
                "invert": false,
            }
        ]
    }
]
```
### The objects and their types
`axis` - (Enum) Obvious, but either `x`, `y`, or `z`. Defaults to `y`. 
`amount` - (Integer) The amount of blocks it is checking relative to where the placed block would be. Defaults to `-1`
`palette` - (Array) An array of the blocks that are acceptable to place on. If `invert` is true, these are instead blocks that _cannot_ be placed on. Required.
`invert` - (Boolean) Whether the blocks listed in `palette` should be ones NOT to place on instead. Defaults to `false`

## Summary
This is still open to suggestion, as it is by no means perfect. So please suggest any changes you see necessary. But something like this needs be added to Iris to enhance the placability of decorators.

I also thought about making a way for decorators to only place blocks if the Y was above a certain level, but I also haven't figured out what that would look like. The current suggestion could also be implemented into things like object placement or Jigsaw placement, but I have not yet drafted what that would look like either

**Comment by svdgoor** [comment]
Suggest making the palette required, rather than have a default.

I don't really understand the `placeInLiquid` option. could you elaborate?

Perhaps you mean something like `mustBeInLiquid`?

**Comment by StrangeOne101** [comment]
> Suggest making the palette required, rather than have a default.

Very good point. It probably is better that way. Was just thinking if it had to have one, that'd be it.
> I don't really understand the `placeInLiquid` option. could you elaborate?

The idea _currently_ is whether it can place in liquids or not. But having one that requires it to be placed in a liquid is also something that could be useful.

Perhaps it's actually best to scrap the property and instead have 
```json
"placeRequirements": [
    {
        "axis": "y",
        "amount": -1,
        "palette": [
            {
                "block": "grass_block"
            }
        ],
        "invert": false
    },
    {
        "axis": "y",
        "amount": 0,
        "palette": [
            {
                "block": "water"
            }
        ],
        "invert": true
    }
 ]
```
I didn't think of what you said before so thanks for bringing it up

Edit: Post updated

**Comment by svdgoor** [comment]
What we could do is something along the lines of:
`inLiquid` default `true`
`onLand` default `true`
`inAir` default `true`
to give full configurability, while keeping it clear.

**Comment by svdgoor** [comment]
The only issue I see is defining the origin of the object. Which block(s) exactly have to be checked?
How do you handle trees for swamps? Say the bottom 10 block may spawn in water, but the leaves (everything above 10) must not be. How do you handle that with other non-vertical axis?

**Comment by svdgoor** [comment]
For example, what we can probably do, is that since the schematics are beams or cubes, we can add a setting that toggles full edge checks, or that it only checks the areas where there are non-air blocks.

**Comment by StrangeOne101** [comment]
> The only issue I see is defining the origin of the object. Which block(s) exactly have to be checked?
> How do you handle trees for swamps? Say the bottom 10 block may spawn in water, but the leaves (everything above 10) must not be. How do you handle that with other non-vertical axis?

Definitely a good point. For now, I've always considered the lowest center block to be the origin, but you're right. It isn't a simple solution.

> What we could do is something along the lines of:
> `inLiquid` default `true`
> `onLand` default `true`
> `inAir` default `true`
> to give full configurability, while keeping it clear.

The `onLand` bit confuses me. Would it be false for items meant to be placed inside a liquid (which would therefore have inLiquid also true)?

**Comment by svdgoor** [comment]
if `onLand` is false, objects must always be floating, or in water, unless either of those is disabled.

**Comment by StrangeOne101** [comment]
My understanding was that decorators only ever placed on the top block of the terrain. So what circumstances would it place midair without a block below it?

**Comment by svdgoor** [comment]
good point. I took an idea I had for a while in mind where you place objects on an absolute height, which I think is currently not implemented.
