### ISSUE TITLE
Mythic Mobs not spawning 

### ISSUE THREAD

**Issue by MaxLoadedGod** [VolmitSoftware/Iris#373]
**Describe the bug**
Mythic Mobs are not spawning when doing "type": "UNKNOWN",
    "mythicalType": "Piranha", in the entities file

**To Reproduce**
1. Go to entities and produce a new file, add a mythic mob, add the entity into a biome file using "entityInitialSpawns and attempt to spawn them in a biome.

**Expected behavior**
Mythic Mobs spawning in the world in certain biomes.

**Server and Plugin Informations**
 - Installed plugins:
 - Iris Version: 1.3.9
 - Server Version: 1.16.5 Paper
 - Server Platform: 32gb ddr4 ram, rx 6800 xt gpu, ryzen 7 5800x cpu, 1tb ssd, 5tb hdd, (no pc issues whatsoever)
 - Operating System: Win10
 - Server Logs: No Error

**Comment by svdgoor** [comment]
Can't reproduce. Mythic mobs are spawning as intended.
