### ISSUE TITLE
Edit setting on jigsaw placement

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#379]
**Is your feature request related to a problem? Please describe.**
Needing to make copies of jigsaw structures, each with their respective biome variations for a specific region.

**Describe the solution you'd like**
An `edit` setting (as already present in individual jig pieces and normal objects) in the jigsaw structure (the encompassing jigsaw thing you call when placing it) and/or placement in the `jigsawStructures` block in each biome.

**Describe alternatives you've considered**
As described in the problem: adding `edit`s to each individual structure, or rebuilding them by hand (which hurts even more).

**Comment by svdgoor** [comment]
I tried this and I couldn't manage.
I traced the normal per-piece `edit` back down to the place function on objects, but I can't easily concatenate object placement settings from the main structure piece because the actual main structure piece isn't readily available in the individual piece.

**Comment by cyberpwnn** [comment]
How insane... I like it!

**Comment by RePixelatedMC** [comment]
Cant wait till this gets implemented !
