### ISSUE TITLE
Allow the definition of slope condition lists

### ISSUE THREAD

**Issue by astrsh** [VolmitSoftware/Iris#38]
**Is your feature request related to a problem? Please describe.**
When defining slope conditions for blocks, sometimes I want to have several ranges defined, which requires duplicating the whole layer for every slope condition range. Adding another option like 'slopeConditionList' containing an array of slopeConditions would be nice, and could be configured as such:

```
            "slopeConditions": [
                {
                    "minimumSlope": 0,
                    "maximumSlope": 0.7
                },
                {
                    "minimumSlope": 3,
                    "maximumSlope": 4
                }
            ]
```

In addition - if VolmitSoftware/IrisPlugin#37 were to be added, I think it should also be handled the same way.

**Comment by svdgoor** [comment]
Both Iris and Jigsaw objects please
![afbeelding](https://user-images.githubusercontent.com/65736624/122655818-d9b6e700-d155-11eb-80bd-0e1b922f9516.png)

**Comment by svdgoor** [comment]
You can simply add multiple of the same object, instead of making a list (which increases complexity where not really needed imo. This type of requirement is very irregular)
