### ISSUE TITLE
Java 16 bug in object placement

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#382]
**Describe the bug**
Object placement bug with java 16

**To Reproduce**
Generate a world, have an object be placed automatically, observe the crash.
[message.txt](https://github.com/VolmitSoftware/Iris/files/6692773/message.txt)

**Expected behavior**
Not this :P

**Comment by NextdoorPsycho** [comment]
not a clear report, no idea what this means, but most problems are fixed on latest

**Comment by svdgoor** [comment]
It's indeed solved. I remember this bug, it's old
