### ISSUE TITLE
Unknown issue with java 16

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#383]
I have no idea what exactly caused it

I created a world before, which crashed the server:
[2021-06-22-4.log.gz](https://github.com/VolmitSoftware/Iris/files/6693787/2021-06-22-4.log.gz)

And then tried teleporting into an existing world and flying around:
[latest.log](https://github.com/VolmitSoftware/Iris/files/6693788/latest.log)

**Comment by NextdoorPsycho** [comment]
Caffeine was removed on latest! reopen if problem persists!
