### ISSUE TITLE
Changing generating Stronghold

### ISSUE THREAD

**Issue by energooooo** [VolmitSoftware/Iris#384]
**Is your feature request related to a problem? Please describe.**
Now there is a generation of strongholds that generates strongholds in the biome and with a chance. Stronghold can spawn at large coordinates, and this is a problem, I have an anarchy server and there is a 2000 by 2000 world, and a stronghold can be located on 5000+ blocks, and as you all understood this abroad. And before I start pre-generating the world, I need to check whether the stronghold spawned at large coordinates or not, if not, I have to create a new world and search for the stronghold through the / locate command, and if it is in the 2000 block limit, then the world is suitable for survival. And one more problem is that the stronghold is generated at large coordinates, and in order for two strongholds to be generated, a great chance is needed for this to spawn at the coordinates of 2000 x 2000 blocks, it needs even more chance

**Describe the solution you'd like**
I propose to make a separate generation of stronghold when creating the world, so that there is a vanilla or more similar vanilla stronghold spawn. So that within 2000 blocks there are 2+ strongholds, for 5000+ blocks there will no longer be two strongholds, but let there be 4 pieces, etc.

**Additional context**
This is a vanilla fortress spawn, do something similar
![image](https://user-images.githubusercontent.com/68811273/122939044-efa5f100-d37b-11eb-92af-f14e248a124e.png)

**Comment by svdgoor** [comment]
On stronghold spawns at the position /locate stronghold shows when used at 0,0 if I remember correctly.

**Comment by svdgoor** [comment]
(Configurable, default is 9 spawning)
