### ISSUE TITLE
Folder support for biomes

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#386]
**Is your feature request related to a problem? Please describe.**
My scroll wheel keeps flying off when I try to traverse the giant list of biomes in the overworld pack

**Describe the solution you'd like**
Folder support for biomes (i.e. we can make a folder called temperate for all temperate biomes)
Referencing biomes would then go similar to objects: `temperate/temperate-plateau`, for example.

**Describe alternatives you've considered**
Buying one of those mice with a scroll wheel that you can just spin and wait for.

**Comment by StrangeOne101** [comment]
Fantastic idea 👍

**Comment by StrangeOne101** [comment]
Okay, so I went to go implement this, but this already works. Just tried this now on 1.3.10 and it works fine
