### ISSUE TITLE
1.17 only: /ir s goto gives invalid generator

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#387]
**Describe the bug**
With any /iris studio goto, the command returns `Invalid Generator`. Console is this: 
```
[23:36:25 INFO]: cocodef9 issued server command: /ir s g swamp/swamp-beach
[23:36:25 INFO]: [Iris]: Couldn't find Generator: swamp/swamp-beach
```

**To Reproduce**
1. Install Iris
2. Open a studio world (or any iris world)
3. teleport to any biome with `/ir s g <biomepath>`

**Expected behavior**
Teleport to the biome

**Screenshots or Video Recordings**
![afbeelding](https://user-images.githubusercontent.com/65736624/123171747-7a6e1500-d47c-11eb-89b4-a79ad9ac21ac.png)

**Server and Plugin Informations**
 - Installed plugins: Plugins (7): Essentials, Iris, Multiverse-Core, ViaBackwards, ViaRewind, ViaVersion, WorldEdit
 - Iris Version: Iris 1.4.2
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: This server is running Paper version git-Paper-43 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: d50cc01)
 - Operating System (if applicable): Windows 10 Home
 - Server Logs:
[latest.log](https://github.com/VolmitSoftware/Iris/files/6705017/latest.log)

**Additional context**
Add any other context about the problem here, server timings reports, Iris dump information, complete console log etc. Please do not make Pastebin dumps or screenshot expire.

**Comment by svdgoor** [comment]
This may be related to a recent change where all biomes are now in folders.

**Comment by NextdoorPsycho** [comment]
patched on latest overworld
