### ISSUE TITLE
1.17 bug

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#389]
**Describe the bug**
Some stuff is null that should not be. Some functions are being called that shouldn't be able to. 

**To Reproduce**
Install latest Iris, replace bukkit to point Iris to the main overworld, observe.

**Expected behavior**
Not this, no crash, just work ;[

**Screenshots or Video Recordings**
https://paste.bristermitten.me/fivejoqyfi.yaml

**Server and Plugin Informations**
 - Installed plugins: See log (nothing that I see interfering)
 - Iris Version: 1.4.3
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: AirplanePurpur but it's also happening on normal paper (I've seen this happening often)
 - Operating System (if applicable): Not applicable
 - Server Logs: https://paste.bristermitten.me/fivejoqyfi.yaml

**Additional context**
Sent by a discord user asking for help, but I did see this happen before too.

**Comment by StrangeOne101** [comment]
Confirmed to be a PaperSpigot issue. Thought to possibly be a mapping issue
