### ISSUE TITLE
Leaf decay option for objects

### ISSUE THREAD

**Issue by astrsh** [VolmitSoftware/Iris#39]
**Is your feature request related to a problem? Please describe.**
When setting up trees / bushes / anything containing leaf blocks, I always find myself double checking leaf blocks within the object, and whether they're set to persistent or not. This can of course also be avoided by just having a blanket edit/replace config for the 6 leaf types, replacing each with their respective same type + persistent=true/false, but is not ideal. The goal of that would be to have fine tune control per object whether leaves decay or not.

**Describe the solution you'd like**
I propose a simple parameter for object configurations that determines control over how leaf persistence is handled. The option could be called something like "leafDecayMode" and could have 3 options:

- Don't change anything (current behavior)
- Set all leaves to persistent (equivalent to find/replace each leaf type to set persistent=true)
- Set all leaves to non-persistent (equivalent to find/replace each leaf type to set persistent=false)

The advantage of this solution and the main reason I think it would be useful (as opposed to just having the blanket edit/replace all leaves), would be ease of use - especially for those who don't want to meddle with using world edit to replace leaves when making objects, or for those who don't want to keep copy-pasting a edit/replace for each leaf type. It would make setting whether an object has leaf decay or not fairly straight forward, and standardize how leaf decay is handled (with the advantage of being per-object configurable)

**Comment by svdgoor** [comment]
@NextdoorPsycho Can you comment on this please? I'm not sure:
a. How we currently do it
b. How it could be done better
c. If this feature req is useful (if not, close)

**Comment by svdgoor** [comment]
Leafdecay is just off by default atm. :)
