### ISSUE TITLE
no World Generate on blank Spigot/Bukkit/Paper Server without Plugins 1.17

### ISSUE THREAD

**Issue by patrickwahler** [VolmitSoftware/Iris#395]
**Describe the bug**
no World Generate on blank Spigot/Bukkit/Paper Server without Plugins

**Screenshots or Video Recordings**
If applicable, add screenshots or video recordings to help explain your problem.

**Server and Plugin Informations**
 - Installed plugins:
 - Iris Version: 1.4.4 / 1.4.5
 - Server Platform and Version Spigot/Bukkit/Paper Server 1.17
 - Server Logs: https://paste.bristermitten.me/acaqunurut.cs

**Comment by patrickwahler** [comment]
on Error Log i find many places with "Iris v1.4.3" is this right for the Iris 1.4.5 Version?

**Comment by svdgoor** [comment]
Thanks for the report, don't know why you closed it, this is valid.
There are some weird issues with the version indicator while running the plugin. The name of the jar-file is correct. Please use Iris 1.4.2 for the time being.

**Comment by NextdoorPsycho** [comment]
Should be resolved on latest, if not feel free to repoen it!
be sure to also be using the latest Overworld.
additionally if its crashing, also send a FULL LOG, not just a crash report
