### ISSUE TITLE
Server crashes on 1.17

### ISSUE THREAD

**Issue by cades66** [VolmitSoftware/Iris#397]
**Describe the bug**
Trying to generate a bukkit.yml default world with Iris (or using a plugin like Multiverse) to generate a world will freeze the server / crash it.

**To Reproduce**
1. Go to bukkit.yml & change the world generator to Iris 
2. Check to make sure you're running Iris 1.4.5 on 1.17

**Expected behavior**
An Iris world is generated

**Screenshots or Video Recordings**
Error: https://paste.gg/p/anonymous/7760e47062034ddc84fe230d5ba8ccae

**Server and Plugin Informations**
 - Installed plugins: BileTools*, ChatSentinel, CoreProtect, CraftingStore, DeathMessages, DeluxeChat, Essentials, Harbor, HolographicDisplays, Hyperverse, Iris, LiteBans, LuckPerms, MythicMobs, PlaceholderAPI, PremiumVanish, ProtocolLib, SimpleRules, spark, Vault, WarpSystem, WorldEdit, WorldGuard
 - Iris Version: 1.4.5
 - Server Platform and Version: PaperSpigot 1.17 v-66
 - Operating System (if applicable): Windows 10
 - Server Logs: See Error

**Comment by svdgoor** [comment]
Duplicate of #395
