### ISSUE TITLE
Suggestion: run paper's light cleanup task for every generated chunk

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#40]
The generation leaves lava in caves to not give lights, some dark corners where they shouldn't be etc.
Paper's light fixer resolves these issues perfectly and (afaik) does so efficiently.
I think it would be worthwhile running these fixes for all chunks, or at least make it a toggleable option.

![afbeelding](https://user-images.githubusercontent.com/65736624/96373050-537f7680-116a-11eb-9a5e-1c6cdd043706.png)
![afbeelding](https://user-images.githubusercontent.com/65736624/96373066-5f6b3880-116a-11eb-8893-48c0ca27c4bf.png)

**Comment by cyberpwnn** [comment]
This would dramatically slow down chunk gen, but i might be able to do it lazily over time

**Comment by svdgoor** [comment]
Perhaps allowing this to be done through a flag (during generation) or through a separate command (after pregen) would be the way to go?

**Comment by cyberpwnn** [comment]
I can add an option in the config for pregenning when on paper

**Comment by svdgoor** [comment]
@cyberpwnn Has this been added?

**Comment by svdgoor** [comment]
Improved lighting updates upon chunk generation were added multiple versions ago, closing.
