### ISSUE TITLE
Iris regen freezing & ultimately timing out the server

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#40]
**Describe the bug**
Upon running /iris regen {number}, the server freezes and (after a while) times out.

**To Reproduce**
1. Create a new overworld with /iris create world2
2. Enter the world with /mvtp world2 -> /mvconfirm
3. Run /iris regen after say 2 minutes of waiting
4. Server freezes & times out

**Expected behavior**
Chunk regenerates at a reasonable speed

**Server and Plugin Informations**
 - Installed plugins: MVCore Iris
 - Iris Version: 1.1.10
 - Server Platform and Version [eg: PaperSpigot 1.16.3 VolmitSoftware/Iris#240]: Paper version git-Paper-352 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
 - Operating System (if applicable): Win10 64x
 - Server Logs: 
[latest.log](https://github.com/VolmitSoftware/Iris/files/5757163/latest.log)

VolmitSoftware/Iris#185 is now a duplicate of this. Since this is a bug (the command is actually implemented), I will close the other one.

**Comment by ghost** [comment]
As stated by the Discord User BLaKe (387176914273435649) worldedit regen is working and therefore can be used as a temp fix
