### ISSUE TITLE
Decorators on ceiling of caves.

### ISSUE THREAD

**Issue by MaxLoadedGod** [VolmitSoftware/Iris#400]
I was told by NextDoorPsycho that there used to be a mechanic to put blocks on the ceiling of caves can that be reimplemented? 
With 1.18 coming I think it'd be crucial for Iris dimension builders to have the ability to put stuff like dripstones or spore blossoms on the ceiling of caves allowing full creativity.

**Comment by StrangeOne101** [comment]
Yep, this has just been reimplemented with #408 👍

**Comment by MaxLoadedGod** [comment]
AMAZING!
