### ISSUE TITLE
The cave that came out to the surface walked along the coast, thereby worsened the appearance

### ISSUE THREAD

**Issue by energooooo** [VolmitSoftware/Iris#402]
**Describe the bug**
When generating the world, the cave came out of the dungeon and walked along the coast and greatly spoiled the appearance of the coast

**Expected behavior**
The best solutions to fix this problem is to make the entrance to the cave smoother as in vanilla minecraft, or to reduce the noise when entering the surface so that the cave is not generated on the surface.

**Screenshots or Video Recordings**
![image](https://user-images.githubusercontent.com/68811273/124665227-21a76f00-deb5-11eb-8f02-2b1f09b9e7fb.png)

**Server and Plugin Informations**
 - Iris Version: 1.4.9
 - Server Platform and Version [eg: purpurclip-1.17-1240]:
 - Operating System (if applicable): 4 cores, 11 gb ram

**Comment by StrangeOne101** [comment]
Vanilla Minecraft also has surface caves that ruin terrain that do not go underground like this. It's just that Iris's caves in the overworld pack are wider and larger. So I don't see this as a huge deal

Regardless, this isn't an issue with the Iris engine but with the overworld pack. This should be on https://github.com/IrisDimensions/overworld

**Comment by energooooo** [comment]
> Vanilla Minecraft also has surface caves that ruin terrain that do not go underground like this. It's just that Iris's caves in the overworld pack are wider and larger. So I don't see this as a huge deal
> 
> Regardless, this isn't an issue with the Iris engine but with the overworld pack. This should be on https://github.com/IrisDimensions/overworld

I thought that this should be dropped here due to the fact that to make the entrance to the cave like in vanilla it is done through the code and decided to drop it here.

P.S This is certainly not the topic of the problem, but the caves near the iris are not very convenient for at least, you walk through the cave and constantly hit the blocks

**Comment by StrangeOne101** [comment]
I have no idea what you mean. The carving for caves is done by configuring carving for a dimension in the pack. There is no manual code for making an entrance to caves.

Again, vanilla does this too

**Comment by NextdoorPsycho** [comment]
Caves are confidured in the overworld.json file, if you have an issye please make a report here:
https://github.com/IrisDimensions/overworld/issues/new/choose
