### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Fami6Xx** [VolmitSoftware/Iris#403]
**Describe the bug**
I don't know what it is, i just saw it in console. Sorry

**To Reproduce**
Don't know

**Expected behavior**
No error?

**Screenshots or Video Recordings**
![image](https://user-images.githubusercontent.com/87103935/124847657-a10f6e00-df9b-11eb-962d-e4fe2cd604ee.png)

**Server and Plugin Informations**
 - Installed plugins: AuthMe, CoordinatesHud, CoreProtect, dynmap, Graves, Iris, OnePlayerSleep, SkinsRestorer, SmoothTimber
 - Iris Version: 1.3.11
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: git-Paper-779 (MC: 1.16.5)
 - Operating System (if applicable): 6GB Ram i9 Processor

**Additional context**
https://timings.aikar.co/?id=b48826b3bdf64e699c92493e08469eaa#timings

**Comment by cyberpwnn** [comment]
It's not causing any issues, but we have it on our radar, been working on critical issues currently. Will fix soon.

**Comment by svdgoor** [comment]
Still happening to people. Plz fix :]

**Comment by cyberpwnn** [comment]
Fixed
