### ISSUE TITLE
Jigsaw connectors on multi-level structures are not respected

### ISSUE THREAD

**Issue by NextdoorPsycho** [VolmitSoftware/Iris#405]
**Describe the bug**
- Occationally jigsaw connectors will not connect properly, and will instead be offset by 1, the longer the chain, the more deviance. This seems to only happen when the tiers of the generation is more than 1, ie: more than 1 layer (stronghold, mineshaft etc)

**To Reproduce**
even tho you wont actually try to reproduce it, you can by pasting the murky-stronghold jigsaw, and look at it

**Expected behavior**
- Follow connector procedure

**Screenshots or Video Recordings**
If applicable, add screenshots or video recordings to help explain your problem.

![3i16XpD](https://user-images.githubusercontent.com/29320316/124888294-d069af00-df8a-11eb-8310-c0957067a9a7.png)

**Comment by StrangeOne101** [comment]
#367 :eyes:
