### ISSUE TITLE
Add a loot table id to the location a chest is placed upon chunk generation

### ISSUE THREAD

**Issue by bakaschwarz** [VolmitSoftware/Iris#407]
**Is your feature request related to a problem? Please describe.**

My server makes heavy use of Denizenscript. I have a lot of custom items i've created using it's language.
I'd like to add some of those items to the loot of Iris chests depending on the type of chest/loot.

The problem: Those items get way to big (nbt-wise) and defining them inside the loot table configs is not very feasable.
It's also not possible to check what kind of chest is being generated/opened for the first time.
So while i can mark locations as "already opened, don't add any more extra loot", i can not see what kind of loot 
i'd have to put in in the first place.

**Describe the solution you'd like**

When Iris generates a new chunk with a chest inside, when filling the chest, it also marks the location with a custom loot table id depending on the configuration that was used to fill the chest. That way, one can always know what kind of context the chest exists in.

**Describe alternatives you've considered**

Not using Iris and going with vanilla minecraft generation to get the "normal" loot generation behavior

(I'd rather not do that though, since Iris world generation is way more advanced and as per default prettier)

**Comment by NextdoorPsycho** [comment]
you can already specify custom loot in jigsaw structures, if you have a large structure, you can give it whatever loot you want. and you can add custom loot to any loot table, if its like a hoe, with some strange data tags, you can still add it via the editor. ive been able to accientally put things in a chest that were from another plugin (wansa's wands or whatever) which is just a hoe, with a random durability.  can you show me an example of some data that you are trying to put on an item?

**Comment by bakaschwarz** [comment]
That may be true. And i won't say it's not possible but one thing that i would not be able to do is make fine controlled conditions on which certain items get inserted into the loot chest. Think about an item the player is carying which adds a chance for an extra item to be added to a chest that was never opened before, but i want to control what kind of item based on the loot table of the chest.
Right now i can't show you an example of a specific item, but It's just that i would prefer to keep most of my logic inside Denizen, so that i only have to edit in one place if i want to change something.

At the end of the day my suggestion would add context to chests, that otherwise doesn't exist, that can be used by other plugins to do more customization based on that. It would help to bring the loot chests in Iris more in line with the way vanilla loot chests are, since those all have the location marked with a loot chest id.

**Comment by cyberpwnn** [comment]
That's all fair, Iris loot was made before the loot table api was robust enough to rely on, and when plugins werent using it very much. Loot system needs an upgrade.

**Comment by cyberpwnn** [comment]
The new Mantle system in 1.7 will support full tiles so this will be possible then.

**Comment by svdgoor** [comment]
You can now (using the Scripts feature) create automatic links to external sources to update them every time Iris generates a chest. This way you can maintain a list of naturally generated chests in your world and generate your loot accordingly.

If you need more help on this please try using the wiki first and then - if that didnt help enough - contact me or another support on Discord.
