### ISSUE TITLE
Regenerating Loot configurable every x amount of time

### ISSUE THREAD

**Issue by AZFire1** [VolmitSoftware/Iris#41]
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to any issues. This is just an idea, Paper has an option in their "paper.yml" to have vanilla loot regenerate after a specified amount of time. I think this would be a good feature to have in Iris if you have a small Iris world that is bordered off so players don't run out of treasure to find.

**Describe the solution you'd like**
An option to have loot regenerate in treasure all over an Iris world. This would not regenerate loot in chests that have been broken, and will not spawn the chests back in. If they have been removed, they're gone & won't be touched anymore. This only applies to chests that have been looted but not to ones that have also been broken. Not sure if this could easily be done, but this would be a really useful feature to have.

**Describe alternatives you've considered**
None

**Additional context**
Paper config section 
![image](https://user-images.githubusercontent.com/67762583/103600582-8d008c00-4ee6-11eb-9f56-4e668c4c5a29.png)

**Comment by ghost** [comment]
https://www.spigotmc.org/resources/lootin-1-14-1-17-no-more-already-looted-chests.90453/

**Comment by NextdoorPsycho** [comment]
Use that plugin^
