### ISSUE TITLE
Immersive ambient sounds for iris overworld biomes such as "crickets, frogs, wind" 

### ISSUE THREAD

**Issue by Coffe2Go** [VolmitSoftware/Iris#416]
Would be dope to have like more immersive ambient sounds for the iris overworld pack.. even if it means having to download like both data pack and recourse pack onto the server. 

I'm looking at you brian  :3

**Comment by svdgoor** [comment]
:]

**Comment by StrangeOne101** [comment]
How are you suggesting the current system be enhanced? Sounds can ready be played within biomes. And there is no such thing as making new sounds with a resource pack. You have to override existing sounds and get rid of them

So I'm not sure how the current system can be enhanced any further

**Comment by svdgoor** [comment]
At least not from within Iris. You could feature a resource pack for players to use to overwrite certain sounds, and then using Iris to play those sounds, but I think native support for this may be outside the scope of Iris. Perhaps we'll look into it at some point.
