### ISSUE TITLE
Pregen does not continue

### ISSUE THREAD

**Issue by Inxity** [VolmitSoftware/Iris#417]
**Describe the bug**
Pregen does not continue

**To Reproduce**
Use bukkit method and download multiverse
Use Paper-104 1.17.1 version
Run /iris pregen radius command

**Expected behavior**
Pregen should start and complete without stopping

**Screenshots or Video Recordings**
nop

**Server and Plugin Information**
 - Installed plugins: 
![image](https://user-images.githubusercontent.com/61350916/125701380-a5c7fcc9-5242-4576-b97f-a2a56e9128eb.png)

 - Iris Version: 1.3.14
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Paper 1.17.1 104
 - Operating System (if applicable): Ubuntu 20.04
 - Server Logs: https://hastebin.com/gosicesega.yaml

**Additional context**
-

**Comment by cyberpwnn** [comment]
Do you mean where it left off?

**Comment by Inxity** [comment]
[01:15:12] [Thread-35/INFO]: [Iris]: Pregeneration Progress: 0 of 102,400 (0%) | ETA: 9223372036854776000ms | Chunks/s: 0 | Memory: ...
[01:15:17] [Thread-35/INFO]: [Iris]: Pregeneration Progress: 0 of 102,400 (0%) | ETA: 9223372036854776000ms | Chunks/s: 0 | Memory: 1.17 GB (17%)

It just gives these 2 Info and not continueing giving more info

**Comment by Inxity** [comment]
Issue is not repreduceable in 1.5.3, I'm closing this
