### ISSUE TITLE
(biome) Rarity not affecting actual rates.

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#42]
Cantibra's report

Describe the bug:
If you change the rarity of the regions in a new package, this has no effect.

For example in the mushroom region, with a 2000x2000 world, there are always 3 mushroom regions. Whether the value is 1 or 100 is irrelevant.

To Reproduce
Edit packs/<name>/regions/mushroom.json

Expected behavior
With a value of 1, a maximum of one mushroom region should appear and not three.

Screenshots or Video Recordings
/

Server and Plugin Informations
 - Installed plugins: Iris
 - Iris Version: 1.2.5
 - Server Platform and Version [eg: PaperSpigot 1.16.3 VolmitSoftware/Iris#240]: PaperSpigot 1.16.4 #394
 - Operating System (if applicable): MacOS 11.1
 - Server Logs: /
_

**Comment by NextdoorPsycho** [comment]
This was fixed a while ago, thats how im able to do rarities with the shroom region

**Comment by svdgoor** [comment]
Don't think that's accurate. The reason mushroom regions spawn so little is because it's far away from the center of the list of regions.
