### ISSUE TITLE
Strange names above mobs

### ISSUE THREAD

**Issue by Yippu** [VolmitSoftware/Iris#420]
**Describe the bug**
Some mobs have strange names above their heads.

**To Reproduce**

1. Generate a world (via instructions here: [https://docs.volmit.com/iris/getting-started](url))
2. Find any mob, and look at its name tag above its head.

**Expected behavior**
Mobs should not have names above their heads, similar to vanilla.

**Screenshots or Video Recordings**
![image](https://user-images.githubusercontent.com/65360275/126005504-ac57fa0c-4897-4ce7-9db3-f2ef26cea381.png)

**Server and Plugin Information**

- Installed plugins:
![image](https://user-images.githubusercontent.com/65360275/126005911-a4e03637-9def-4c17-9a49-53ee6c90cec5.png)
- Iris Version: v1.4.14
- Server Platform and Version: Purpur version git-Purpur-1265 (MC: 1.17.1)
- Operating System (if applicable):
- Server Logs: [latest.log](https://github.com/VolmitSoftware/Iris/files/6833335/latest.log)

**Comment by ghost** [comment]
That’s to prevent entities (those with name tags) from unwanting despawning.
@NextdoorPsycho this can be closed

**Comment by Yippu** [comment]
is there a way to turn that off? nearly every mob has it.

**Comment by ghost** [comment]
> is there a way to turn that off? nearly every mob has it.

Yes but you need to turn it off in the plugin. It’s open source so nobody from doing so.

**Comment by Yippu** [comment]
> 
> 
> > is there a way to turn that off? nearly every mob has it.
> 
> Yes but you need to turn it off in the plugin. It’s open source so nobody from doing so.

so....theres not a setting anywhere i can change? i need to know java and program it in?

**Comment by ghost** [comment]
> > > is there a way to turn that off? nearly every mob has it.
> > 
> > 
> > Yes but you need to turn it off in the plugin. It’s open source so nobody from doing so.
> 
> so....theres not a setting anywhere i can change? i need to know java and program it in?

No there is no setting for it. And yes you need to know how to do things in Java for achieving that. Here is a example how it’s done. https://github.com/VolmitSoftware/Iris/pull/354/files
As i said that was made so entities like villagers or pillagers don’t despawn. It’s a ugly fix but nobody wants empty villages and pillager towers.

**Comment by svdgoor** [comment]
The alternative to the empty nametags is respawning mobs.
If you find a good alternative make a PR

**Comment by Yippu** [comment]
im not sure why it was said i had to go into the plugin and program it to turn off the name tags? i just went into the entity .json files and removed the "customName".
example:
`{"type": "OCELOT"}`

**Comment by Yippu** [comment]
thanks anyways guys, but i figured out what i was asking. solved!
