### ISSUE TITLE
Proper fix for despawning Entities

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#421]
Just as a reminder so it won’t get lost cause the fix (https://github.com/VolmitSoftware/Iris/pull/354/files) is a Dirty bandaid and It needs to be looked at in the future.

**Comment by svdgoor** [comment]
Dirty fix that works really well, perhaps we can just close this?

**Comment by svdgoor** [comment]
I improved it somewhat: #471

**Comment by StrangeOne101** [comment]
@CocoTheOwner Villagers should always never despawn, so I don't even know if the name tag did anything for them. 

Jigsaws contain a `keepEntity` tag now that adds an NBT tag top stop them from despawning (the one from vanilla called persistence required or something). However it's possible that this tag doesn't work with MCA

**Comment by ghost** [comment]
Didn’t know that name tags aren’t needed anymore. So I close this
