### ISSUE TITLE
Tile Entities aren't being set in 1.17 generation

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#422]
# Issue
Tile entities aren't being set in world gen in 1.17. They are still saved fine within objects, but when placed in worldgen in Jigsaws (have yet to test outside of jigsaws), they do not set properly.

This means banners, spawners and signs are not placed correctly.

Placing this here because the issue has kinda been forgotten about and would be good to have fixed by Iris 1.5

**Comment by cyberpwnn** [comment]
Fixed in 1.6
