### ISSUE TITLE
Couldn't generate a new world on Iris 1.5 and above

### ISSUE THREAD

**Issue by jdkeke142** [VolmitSoftware/Iris#424]
**Describe the bug**
On Iris 1.5 and above I couldn't generate a new world that's working.

Effectively, the plugin wouldn't generate that new world correctly and pop some errors: https://bin.bloom.host/lepiwipuje.sql

**To Reproduce**
1. Install a new server on the latest Paper 1.17.1 version
2. Install Iris 1.5.1 and the latest version of Multiverses
3. Installing the overworld pack using "/ir download overworld" and restart the server
4. Creating a new world using "/ir create IrisWorld" and getting the errors

**Expected behavior**
The world should generate and load correctly.

**Server and Plugin Information**
- Installed plugins: Iris, Multiverse-Core
- Iris Version: 1.5.1
- Server Platform and Version: git-Paper-110 (MC: 1.17.1)
- Operating System: Windows 10
- Server Logs: https://bin.bloom.host/evawahehat.makefile

**Comment by svdgoor** [comment]
Known error. Many people are experiencing the same error.
https://bin.bloom.host/lanevubome.sql
[latest(1).log](https://github.com/VolmitSoftware/Iris/files/6834937/latest.1.log)
https://hastebin.com/bosehomoca.rb
[latest(2).log](https://github.com/VolmitSoftware/Iris/files/6834941/latest.2.log)
https://pastebin.com/KDZZRC40 (https://pastebin.com/8sAVrs0S)

**Comment by svdgoor** [comment]
People can open studio worlds
People can create worlds without multiverse installed
https://hastebin.com/biceraluqa.yaml - Line 644 its generating (example of creating world as follows:
1. Install Iris
2. Restart Server
3. /ir create <name> - Let the world create
4. Stop the server and install Multiverse
5. /mvtp <name> done)

**Comment by svdgoor** [comment]
Same error using the bukkit method: 
[latest.log](https://github.com/VolmitSoftware/Iris/files/6835960/latest.log)

Creating a world with multiverse causes Iris not to recognise it as an Iris world

Interestingly enough, I managed to actually join the server with the bukkit method on the second try, but it died quickly after.
My guess here is that the datapacks aren't loaded properly and Iris is still trying to generate a world with those custom biome IDs
This then breaks

**Comment by svdgoor** [comment]
[Getting Started - Wiki](https://docs.volmit.com/iris/getting-started) updated tutorial that works
