### ISSUE TITLE
Custom Portals

### ISSUE THREAD

**Issue by MetooMango** [VolmitSoftware/Iris#425]
Custom portals where you could connect the a world to other worlds (like the nether with the overworld)

**Comment by cyberpwnn** [comment]
We had this kind of idea. Basically you could design a multiblock structure (portal) for any iris dimension, and it would "prepare" by loading the world async, then the portal would open when the world is ready. Nonetheless it would be nice for just custom portals for overworld / nether too.

**Comment by MetooMango** [comment]
It would be pretty slick, I don't think this has been done before either. So if you did do it, that would be awesome!

**Comment by svdgoor** [comment]
Wormholes 2.0

**Comment by NextdoorPsycho** [comment]
Needed more info so imma close this for now, since its not really a plausibility at the moment
