### ISSUE TITLE
Issue with biome base when opening studio world

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#426]
# Description
When creating an Iris studio world on the current overworld pack, and issue arises with an NPE to a missing biome base.
Looks like it's NMS messing up on 1.17.1
[latest.log](https://github.com/VolmitSoftware/Iris/files/6835146/latest.log)

**Comment by cyberpwnn** [comment]
Can this be reproduced after wiping the following folders?

```
world/datapacks/iris
plugins/Iris/cache
plugins/Iris/packs/overworld (or just git-pull you seem out of date)
```

Then start the server
then reboot the server (again)
Then try the same reproduction steps you did to cause that bug.

**Comment by svdgoor** [comment]
I tried and it seems to work better now, works on the second try.

**Comment by svdgoor** [comment]
After further testing I found that it seemingly works after a full restart, even with `/ir c world`, through multiverse.
It also works with bukkit, where you have to start the server, stop the server, edit bukkit.yml, and then start the server, all with Iris installed and without changing the pack
Is there a way for Iris to check if the datapacks were installed? Would that perhaps open a path to denying the use of the generator for that pack?
