### ISSUE TITLE
Pregen not working + more

### ISSUE THREAD

**Issue by CeeVeeR** [VolmitSoftware/Iris#427]
Sleepy Clara here,

I started running into this issue after the deadlock fix.

OS: Windows 7

My JVMs: OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (both hotspot and OpenJ9) + Official Java 16 JDK

Distro: Purpur 1.17.1-1283 (latest from the post's time)

Args: java -Xms6G -Xmx6G -DIReallyKnowWhatIAmDoingISwear -Xlog:gc*:file=W:\test\gc.log:tags,time,uptime,level:filecount=5,filesize=20M -jar purpur.jar nogui

The issue:

The pregen works for around 1 minute and freezes for eternity. (sample size, 10 hours)

It has enough time to generate 1 mca region, and stops on the second half way.
![java_2021-07-18_03-30-25](https://user-images.githubusercontent.com/87547782/126052962-b50f7fdf-937a-479e-9d74-17348662c9f6.png)
![cmd_2021-07-18_03-30-57](https://user-images.githubusercontent.com/87547782/126052970-81bdd691-61b0-4808-bdcc-501504ad9c09.png)
![jprofiler_2021-07-18_03-32-23](https://user-images.githubusercontent.com/87547782/126052990-7e460e19-7e36-471f-94ba-d92e8c28d42f.png)

When I do **iris pregen x** and **stop** the server freezes while saving. Upon the next restart, the generated world is not recognized by Essentials nor Iris (the only plugin next to iris)

**Comment by ghost** [comment]
This report hasnt used the form for a issue report and therefore cant reproduce it. Pregeneration works on 1.7.7 so this can be closed @CocoTheOwner
