### ISSUE TITLE
Issue with Parallax Features

### ISSUE THREAD

**Issue by cyberpwnn** [VolmitSoftware/Iris#428]
For some reason... Only on flatgrass parallax REGIONS are loading in 60+ X and Z coordinates when the regions -3 to 3 were generated. It's not chunk coordinates because that should mean there would be files with 90+ coords on them. Either way all I know is something in `forEachFeature` in the `EngineParallaxManager` (com.volmit.iris.engine.framework) is causing regions to load when they shouldnt.

**Comment by ghost** [comment]
@StrangeOne101 This can be closed
