### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by copyandexecute** [VolmitSoftware/Iris#429]
---
Java NullPointerException
---

**Describe the bug**
Cant generate a world this bug occurs:
https://bin.bloom.host/uneholunen

**To Reproduce**

1. Install latest Purpur-1.16.5
2. Install Iris-1.3-11.Final
3. Follow the installation guide (1.16.5 one)

**Expected behavior**
It should generate the world

**Server and Plugin Information**

- Installed plugins: 
- Iris Version: 1.3-11.Final
- Server Platform and Version [latest 1.16.5 Purpur (but my own fork)]:
- Operating System (if applicable): Debian 10

**Comment by svdgoor** [comment]
Why'd you close it?

**Comment by copyandexecute** [comment]
can you delete issues I wanna redo it lol

**Comment by svdgoor** [comment]
You can edit the original message

**Comment by copyandexecute** [comment]
I've leaked something in server logs which I dont wanna show would you be so kind to delete the issue I will create a new one

**Comment by StrangeOne101** [comment]
Issues can't be deleted. Just edit the initial message and removed the log file you don't want to share

**Comment by svdgoor** [comment]
@copyandexecute I cannot remove issue reports. Please remove and update the logs. Use [mclogs](https://mclo.gs) to hide IPs and other personal stuff

**Comment by svdgoor** [comment]
w
