### ISSUE TITLE
Treefeller support

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#43]
**Is your feature request related to a problem? Please describe.**
A treefeller plugin to properly chop down trees so issues like VolmitSoftware/Iris#178 doesnt happen or matter anymore.

**Describe the solution you'd like**
A tree recognition for a treefeller plugin will be possible when VolmitSoftware/IrisPlugin#32 will be implemented.

**Comment by svdgoor** [comment]
@cyberpwnn with the new Mantle system, which I think deserves an issue tab just like the one for V3 objects, it would be nice to store every location of ever object placed in order to be able to do this, and #48, without many issues.

**Comment by svdgoor** [comment]
#511

**Comment by NextdoorPsycho** [comment]
https://github.com/TimelostSoftware/IrisFeller
