### ISSUE TITLE
World generation aborting because exceptions are thrown.

### ISSUE THREAD

**Issue by domiehomie** [VolmitSoftware/Iris#438]
- Server version: `1.17` (same issue appeared on `1.17.1`)
- Plugin version: compiled from github, file said 1.5.4
- Logs:  [2021-07-19-2.log](https://github.com/VolmitSoftware/Iris/files/6842776/2021-07-19-2.log)

So when i run the `/iris create <worldname>` command, all these errors appear in my console.

**Comment by svdgoor** [comment]
There are no errors in this log. If you still have the issue please send the log file here or on our [Discord](discord.gg/volmit)
