### ISSUE TITLE
World generation error

### ISSUE THREAD

**Issue by alvarocc99** [VolmitSoftware/Iris#439]
I comment the error / bug.

At the time of generation of the world some biomes have dry or abrupt cuts. It does not interfere when playing (or should not) but aesthetically it does not look good.

I attach some screenshots. If you wish, I can add more screenshots in the comments of this report or simply open another report.

![image](https://user-images.githubusercontent.com/87673571/126224394-c31256c9-7e5c-46ba-aa79-488744965e28.png)
![image](https://user-images.githubusercontent.com/87673571/126224600-c260715e-6d07-4e3a-8564-367f7d3d3e20.png)
![image](https://user-images.githubusercontent.com/87673571/126224665-9b44e7df-3e0c-4c35-94dd-129b14b1a17e.png)

**Comment by svdgoor** [comment]
Thank you!
Feel free to add more.

**Comment by alvarocc99** [comment]
I add some more captures, some are of the style of yesterday.

The first one could not tell you if it is from its own game or not, Minecraft and its lighting bugs are part of it. There are also no items in the chests.

![2021-07-20_12 12 00](https://user-images.githubusercontent.com/87673571/126311070-c4f34b22-49ec-4dc7-ad67-dd61ce083566.png)
![2021-07-20_12 12 33](https://user-images.githubusercontent.com/87673571/126311102-ea3b9e14-7d53-4ea4-b405-ac1e448dadc1.png)
![2021-07-20_12 13 19](https://user-images.githubusercontent.com/87673571/126311125-a3d9eda8-adf3-4eca-a7d4-74d1a6324846.png)
![2021-07-20_12 16 56](https://user-images.githubusercontent.com/87673571/126311155-de3b830e-2daa-46a4-876d-c208c25b785b.png)
![2021-07-20_12 16 10](https://user-images.githubusercontent.com/87673571/126311180-d2651da6-bed1-4b12-9b16-c237bce94889.png)

I do not know if the sand in caves is on purpose or not but just in case.
![2021-07-20_12 20 25](https://user-images.githubusercontent.com/87673571/126311341-8b3b4ec8-c288-489c-b37c-4f2b0f5a6881.png)

In the next screenshot, blocks like sand of souls appear at the bottom of the sea, many animals also appear in the sea.
![image](https://user-images.githubusercontent.com/87673571/126311509-69031235-dbe2-4ae7-b194-c867cac4108e.png)

**Comment by svdgoor** [comment]
Straight lines will be fixed with upcoming overworld updates in light of the new generator noise changes.
Water next to caves will be worked on by @StrangeOne101
Hot and cold regions spawning side-by-side is not a big deal and will be treated as a low priority issue.
Empty chests have been reported separately and will be worked on soon
Light update improvements will not happen soon lost likely
Animals in the oceans are interesting. If you have a biome name for that, could you please open a new bug report, or just post the name here please?

**Comment by svdgoor** [comment]
https://github.com/IrisDimensions/overworld/issues/169 - straight lines on the overworld
