### ISSUE TITLE
Iris pregen not showing anything

### ISSUE THREAD

**Issue by NipNacks** [VolmitSoftware/Iris#440]
I'm quite unsure how to explain it properly but Iris pregen does not show anything for some reason. It shows no error and also no chunk updates. I did /Iris pregen stop and did /Iris pregen 2k again and sent me this error. Chunks were not loading too after.

Server logs:
https://pastebin.com/9sMjut7v

**Comment by svdgoor** [comment]
#451 and #452 may be related.

**Comment by svdgoor** [comment]
Dupe of #451
