### ISSUE TITLE
Re-enable `regen` command

### ISSUE THREAD

**Issue by 3x** [VolmitSoftware/Iris#441]
(Running Iris-1.3.9 on Airplane 9 (70a416d) with Java 11.)

When executing the command `/ir regen 1`, the following error is shown:
```
[Iris]: Iris' /regen command is currently disabled due to maintenance. Apologies.
```

What is the status on this maintenance, and is the command likely to be re-enabled at some point? 

Thank you!

**Comment by svdgoor** [comment]
Maintenance has stopped. We decided to no longer support the usage because of hardships with Iris' internals.
We could hook into worldedit to select the chunk and regenerate it through bukkit, but meh.
