### ISSUE TITLE
object priority system

### ISSUE THREAD

**Issue by RaydenKonig** [VolmitSoftware/Iris#45]
**Is your feature request related to a problem? Please describe.**
It always frustrates me when I try to put objects like abandoned houses, statues etc and these are crossed by trees or bushes

**Describe the solution you would like**
Implement a priority system between objects, that is,
that you can configure the priority that an object has before others and the one with the highest priority will overwrite the other
In this way, for example, the tree object could be put with priority 1, while the houses could be put a priority 2, in this way the leaves of the trees would not cross the structure of the house

In addition, this system also prioritizes the void air, so that the leaves do not enter inside a house.

**Additional context**
An example of the priority setting

```
        {
            "chance": 0.7,
            "Priority 1,
            "rotation": {
                "yAxis": {
                    "min": 0,
                    "max": 0,
                    "interval": 90,
                    "enabled": true
                },
                "enabled": true
            },
            "place": [
                "light-forest / tree4",
                "light-forest / tree3",
                 "light-forest / tree2",
                 "light-forest / tree1"
            ],
            "translate": {
                "x": 0,
                "y": -4,
                "z": 0
            },
           {
            "chance": 0.010,
           "priority", 2,
            "rotation": {
                "yAxis": {
                    "min": 0,
                    "max": 0,
                    "interval": 90,
                    "enabled": true
                },
                "enabled": true
            },
            "place": [
                "abandoned-house"
            ],
            "translate": {
                "x": 0,
                "y": 0,
                "z": 0
            }
        }

```

**Comment by svdgoor** [comment]
Do you mean you want A to overwrite the blocks of B or A prevents B from spawning altogether?

**Comment by RaydenKonig** [comment]
> ¿Quiere decir que quiere que A sobrescriba los bloques de B o que A evita que B se genere por completo?

that's how it is

if A has a higher priority than B

A will overwrite B and never reverse

**Comment by svdgoor** [comment]
So if A has a block inside a location in B it will replace the block? That's fairly achievable

**Comment by RaydenKonig** [comment]
Exact!

This so that, for example, if a house is generated within a forest, a priority is placed above that of a tree, therefore, if it is generated next to a tree, the wood or leaves will never pass through the structure of the house.

This should also be applied with the vacuum air so inside the house, it does not fill with leaves

**Comment by svdgoor** [comment]
You mean `bore`, yes, absolutely.

**Comment by ghost** [comment]
@cyberpwnn can this be closed? We talked about this and by filling the air with other blocks and replacing them would be a more viable solution.

**Comment by svdgoor** [comment]
@ArMiN231 how would that idea (which I'm not fully understanding) solve trees inside village buildings (objects -> jigsaw)?

**Comment by ghost** [comment]
> @ArMiN231 how would that idea (which I'm not fully understanding) solve trees inside village buildings (objects -> jigsaw)?

Basically a object priority system would prevent villages inside forests. And with the current features we can prevent trees from filling houses. Maybe a object collision system would prevent trees from spawning at the same position as jigsaw structures do.
