### ISSUE TITLE
Weird walls in Mosaic biomes.

### ISSUE THREAD

**Issue by TheDevelon** [VolmitSoftware/Iris#45]
![image](https://user-images.githubusercontent.com/28627992/96431966-8ece8380-1204-11eb-890b-332bf9c72ade.png)
Mosaic lith black

**Comment by TheDevelon** [comment]
This is not a studio world

**Comment by NextdoorPsycho** [comment]
Why is this a bug report. This is an object in the biome. It's a lith. But ok I'll remove them iguess

**Comment by TheDevelon** [comment]
And what is a lith? never thought this i a feature haha sorry
