### ISSUE TITLE
UTFDataFormatException preceding generator slowdown (pretty close to a full-stop)

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#450]
[java.io.UTFDataFormatException-java.io.DataOutputStream-368.txt](https://github.com/VolmitSoftware/Iris/files/6851365/java.io.UTFDataFormatException-java.io.DataOutputStream-368.txt)

**Comment by svdgoor** [comment]
Additionally, there are numberformatexceptions
[java.lang.NumberFormatException-java.lang.NumberFormatException-67.txt](https://github.com/VolmitSoftware/Iris/files/6851367/java.lang.NumberFormatException-java.lang.NumberFormatException-67.txt)
[java.lang.NumberFormatException-jdk.internal.math.FloatingDecimal-2054.txt](https://github.com/VolmitSoftware/Iris/files/6851368/java.lang.NumberFormatException-jdk.internal.math.FloatingDecimal-2054.txt)

Full log:
[latest.txt](https://github.com/VolmitSoftware/Iris/files/6851369/latest.txt)

**Comment by NextdoorPsycho** [comment]
this is an overworld issue, and an objects are not updated issue. but this is resolved on latest in terms of not actually spawning the object, make another issue on overworld for the version mismatch
