### ISSUE TITLE
mcaPregenerator not printing to debug chunk generation

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#451]
mcaPregenerator is not giving any type of console information in regards to generation.
I don't mind having it be regions instead of chunks, but nothing is very... little.

**Comment by svdgoor** [comment]
(When flying around it starts printing the updates again.

**Comment by Inxity** [comment]
Can also confirm, Iris 1.5.6 mcaPregenerator activated and there is no messages about pregen. Also it printed this after couple minutes
![image](https://user-images.githubusercontent.com/61350916/126492509-9ceb647c-2576-4d6f-97c2-cefd672a0e5e.png)

**Comment by svdgoor** [comment]
Yep. If you turn on debug mode you'll actually see progress updates.

**Comment by Inxity** [comment]
Is it slow? Should i use mcaPregenerator?

**Comment by ghost** [comment]
Should be fixed with this https://github.com/VolmitSoftware/Iris/commit/233a179dad9b4d9d4ebe96f8ec5a4365789f0d69
