### ISSUE TITLE
Decorations in caves under fluid being placed where should not

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#456]
### Problem

```txt
1. Install Iris
2. Go to any cave with non-solid blocks & liquids
3. Observe decorations being placed under the liquid level
```

### Solution

![image](https://user-images.githubusercontent.com/65736624/126546851-1fa85844-43d7-4667-8f54-d5a29c7471c7.png)
![image](https://user-images.githubusercontent.com/65736624/126546869-e2730aa7-7fe9-4f50-a0fb-5699fab757cb.png)
```java
if (cave.getLiquidHeight() >= decorationAboutToPlaceHeight){
  doNotPlaceDecoration()
}
```
### Minecraft Version

1.17.x

### Iris Version

1.5.6

### Log

Not important

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by StrangeOne101** [comment]
Fixed in #481
