### ISSUE TITLE
Jigsaw structures are fully broken on latest

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#457]
### Problem

```txt
1. Install Iris
2. `/ir dl overworld`
3. `/ir j p stronghold`
4. Observe the error...
https://pastebin.com/2WpsxQF6
```

### Minecraft Version

1.17.x

### Iris Version

1.5.9

### Log

https://mclo.gs/3lpoec7

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by StrangeOne101** [comment]
I found pillager outposts (no pillagers or loot) in 1.5.10 but have yet to find any other jigsaw structures. Strongholds do also not log the stronghold locations on world creation - proving they are broken

**Comment by NextdoorPsycho** [comment]
Fixed on latest, the loot is eomething to do with studio hotloading see here https://github.com/VolmitSoftware/Iris/issues/462
