### ISSUE TITLE
IOB Tile Entity Support

### ISSUE THREAD

**Issue by cyberpwnn** [VolmitSoftware/Iris#46]
This is actually very complex and will require a lot of testing but generally, this means that you can save Signs, Chests (with items in them) and Spawners to name a few and have them retain their data properly. There are multiple reasons why this is complicated but in general, 

* Iris generated with MCA is actually easy... just write NBT in the format MC needs
* Bukkit Generated is harder because bukkit hides NMS and instead requires you to use the interfaces.

I think the best approach for this is to simply support one type of tile entity at a time. Yes... this means that if 1.17 adds a new tile entity, we will have to update to support it, but it is the most reliable way to do it. (same way world edit does, just without NMS)

**Comment by svdgoor** [comment]
@StrangeOne101 Didn't you add this alr?

**Comment by ghost** [comment]
Isn’t working correctly if I remember correctly

**Comment by StrangeOne101** [comment]
We do have *basic* tile entity support. However, this doesn't include any container that can hold items and only supports NBT spigot has an interface for. Right now we support:

- Signs
- Banners
- Spawners (vanilla mob types only)

But as @ArMiN231 said, tile entities aren't working in Jigsaw placements in 1.17. They are still supported with objects though as manually placing a pillager outposts will place it with the correct banners

If we want proper tile entity support, we WILL need to use NMS

**Comment by svdgoor** [comment]
@StrangeOne101 Has there been progress on this in the meantime?

**Comment by StrangeOne101** [comment]
> @StrangeOne101 Has there been progress on this in the meantime?

There has been no progress on this

**Comment by svdgoor** [comment]
Included with The Mantle #519
