### ISSUE TITLE
Couldn't create a studio world 

### ISSUE THREAD

**Issue by jdkeke142** [VolmitSoftware/Iris#460]
### Problem
I couldn't create an iris studio world using /iris std create dynastia template=overworld, I get an error quite soon after iris try to create the studio world...

I download the overworld pack and restarted the server. I also want to note I can create a normal Iris world using the /iris create IrisWorld command

I will get this error when I try to create a studio world : https://gist.github.com/jdkeke142/aad3fa54085b0856ce47fc07a7b00bd5

### Minecraft Version

Paper version git-Paper-110 (MC: 1.17.1)

### Iris Version
1.5.7

### Logs
https://mclo.gs/hsl2Dai

**Comment by svdgoor** [comment]
Please send a full log (next time as well)
Please update to paper or purpur. I'm pretty sure this bug happens with spigot.

**Comment by svdgoor** [comment]
^that one seems resolved and there's still no log here. Closing. If you have it on latest, make another report.
