### ISSUE TITLE
Empty chests

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#462]
### Problem

1. Install Iris
2. Open a studio world or create a new world
3. Go to that world
4. Open any number of chests and observe they have no loot
5. Pretty sure @StrangeOne101 mentioned there are no NBT tileentities working either.

### Solution

Started happening after recent updates to generation: directMCA

### Minecraft Version

1.17.x

### Iris Version

1.5.8

### Log

nothing

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by StrangeOne101** [comment]
Thanks for making a proper issue. Correct; since the pregen changes around 1.5.4, loot, tile entities and lighting are not generating properly across the board. Even in non pregened areas

**Comment by svdgoor** [comment]
Lights also are not working

**Comment by NextdoorPsycho** [comment]
The loot in a studio only breaks when you hotload, and it does not happen in actual worlds
