### ISSUE TITLE
Error creating new studio world

### ISSUE THREAD

**Issue by p3sto** [VolmitSoftware/Iris#463]
### Problem

1. Start server
2. Invoke `/iris std create [name] template=overworld`
3. Observer error

Although this may be a duplicate of Issue #460, I still receive this error in the latest build that I'm using. (Paper 1.17.1-124)

### Minecraft Version

1.17.x

### Iris Version

v1.5.8

### Log

https://pastebin.com/A79fHyAf

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by svdgoor** [comment]
Are you trying to make a new pack based on the overworld, or are you trying to open a studio world using the overworld?

**Comment by p3sto** [comment]
Make a new pack based on the overworld

**Comment by cyberpwnn** [comment]
This is odd, (ignoring whatever iris is doing) it's going to try to open up a new studio world, with a new key. Basically, after it fails right here, try restarting the server, then using /iris std o <your-created-pack> and it should open up.

**Comment by p3sto** [comment]
Seems to have fixed itself with update to v1.5.9. I'll close the issue.
