### ISSUE TITLE
Block pallette in fluid selection for liquid in caves

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#464]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to be able to pick block palettes (with data) in fluids at the bottom of caves

### What are you trying to modify

The way I would implement this is by replacing the one-block option with a palette

### Alternatives

If this could not be implemented I would be unable to add custom blocks instead of liquids in the caves

**Comment by svdgoor** [comment]
@StrangeOne101 if you're working on cavegen, could you look into this as well?

**Comment by StrangeOne101** [comment]
I did think about it. But I am just wondering if it's worth it with how much it may slow down things. Not by much, but it means that every fluid block will go from just "place" to "pick a random one from the list based on weight, place"

Not to mention that changing the type of it from a block to a list of blocks will cause an issue for anyone that updates either the jar or overworld and not the other. We saw a lot of this when we changed the type of `color` (object to string)

**Comment by svdgoor** [comment]
It's not even particularly for supporting multiple different blocks, just to be able to use data for custom liquids such as idk liquid redstone

**Comment by svdgoor** [comment]
I'd say make it one block only then

**Comment by StrangeOne101** [comment]
Data should be supported in the current system. If it doesn't, that's a small bug that can be fixed

**Comment by svdgoor** [comment]
Not supported afaik.
Please, if you have a pack open, try adding data to the block thingy in fluid type in the dimensions caves

**Comment by StrangeOne101** [comment]
When I had it open today, VSCode did show a data option for it. Along with weight - although useless as it's not in a list

**Comment by svdgoor** [comment]
Strange seems to be right. It appears one entry which is normally in a list of elements was used, which is everything this issue requires to be solved. Example below:

```json

            "fluid": {
                "fluidHeight": 12,
                "fluidType": {
                    "block": "spruce_leaves",
                    "data": {
                        "persistent": true
                    }
                }
            }
```
