### ISSUE TITLE
Adding JSON verification before reading packs

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#466]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to have a check before compiling a pack that all JSON files are valid

### What are you trying to modify

The way I would implement this is is by adding a simple go-through-all-files and verify they are valid whenever something is hotloading, being downloaded, or something is being created using a pack. 

It should say something like 
```
file x is unreadable. Please install VSCode and use it to check the file.
docs.volmit.com/iris/plugin/faq#iris-tells-me-my-json-file-is-broken-how-do-i-fix-it
```

### Alternatives

If this could not be implemented I would have to help every poor soul check their JSON files for failed commas :(

**Comment by cyberpwnn** [comment]
![image](https://user-images.githubusercontent.com/10619135/127029598-0fbccfc6-1692-44b3-a41d-3b57e1b8d727.png)
