### ISSUE TITLE
Iris deposits only generate up to 2x2 cubes

### ISSUE THREAD

**Issue by Yippu** [VolmitSoftware/Iris#468]
### Problem

When Iris generates deposits of any block, they only generate up to a 2x2 size, no larger.

![image](https://user-images.githubusercontent.com/65360275/126902224-a3a039d9-6e9f-498f-8341-e005577f0c30.png)
![image](https://user-images.githubusercontent.com/65360275/126902231-006510ba-c5fc-452a-8ded-8f3e25108f55.png)

deposits in dimension file: https://pastebin.com/jMTZEw9d

### Minecraft Version

1.17.x

### Iris Version

v1.5.10

### Log

https://mclo.gs/8JH0wx8

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by cyberpwnn** [comment]
Very odd... For the sake of it, maybe try increasing the variance to 12 and the max size to 50 (just to see), and ill take a look and do some tests.

**Comment by svdgoor** [comment]
I'm confident they already did. We were testing it together and I couldn't find a way to properly solve it.

**Comment by Yippu** [comment]
Yup, as @CocoTheOwner mentioned, we tested similar values and ended with the same result.

**Comment by svdgoor** [comment]
Bump. This is causing a massive deficit of ores in the overworld dimension as we currently feature it. Only way to patch that is by adding duplicate entries of ores which is just a bad fix. Please resolve this stat.

**Comment by NextdoorPsycho** [comment]
This is intentional with the current system, makes strip mining inneffective. 
you can increase it yourself by bumping the value up. but if thats not working, then my system is not working either. bigsad

**Comment by NextdoorPsycho** [comment]
just spoke and used it. not a bug, drive numbers up. the system will be reimplemented later anyway. but this issue is closed (by the hand of cyber)

**Comment by Yippu** [comment]
Um, the issue is that driving the numbers up does nothing. This is not on the overworld pack if you are assuming it is. I have even tried ridiculous sizes and they always generate up to 2x2 cubes at most.

**Comment by svdgoor** [comment]
Can confirm this is a bug, it is happening on overworld *too*, which makes andesite diorite etc look bad as well. This should be reopened and fixed or, as you said, reimplemented.
