### ISSUE TITLE
Iris stopped pregen saying OCEAN-DEEP is missing

### ISSUE THREAD

**Issue by NipNacks** [VolmitSoftware/Iris#469]
### Problem

I am doing a pregen of my 10k radius world and encountered an error which stopped my pregen.
[08:47:51] [Iris Engine Overworld 4/INFO]: [Iris]: Failed to place objects in the following biome: Ocean Deep

I have also tried to restart the server and do /iris pregen 10k again but it says the same error. I have the latest 1.5.10 iris update and also the latest overworld pack

### Minecraft Version

1.17.x

### Iris Version

1.5.10

### Log

https://pastebin.com/aLV4J3VA

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by svdgoor** [comment]
Probably an overworld issue. We'll take a look :)

**Comment by svdgoor** [comment]
I can successfully place these objects and load the ocean-deep biome.
NextdoorPsycho managed to pregen a significant area in a world, which likely also includes the deep ocean.

If you run into this issue again, please send another bug report and perhaps mention this one, or continue below this thread, with a new log.
