### ISSUE TITLE
World edit extend for Iris wand

### ISSUE THREAD

**Issue by astrsh** [VolmitSoftware/Iris#47]
**Is your feature request related to a problem? Please describe.**
Making selections with odd shaped objects can be tedious with the Iris wand - requiring either scaffolding out to the corners (the most convenient method to me), or using one of many selection commands (which can be a pain to type out for each selection)

**Describe the solution you'd like**
Add the world edit wand extend selection mode to the Iris wand - the way this works is that left click starts a new selection, and every subsequent right click makes the selection encompass the point clicked.

With this method, you wouldn't have to use both selection commands and or scaffolding to get the desired selection

**Comment by svdgoor** [comment]
Would be nice, yes please :D

**Comment by svdgoor** [comment]
@Astrashh Can you give some examples for when WorldEdit integration would be useful, over the usage of /iris o wand?

**Comment by NextdoorPsycho** [comment]
Will  be on a commit soom :tm:

**Comment by NextdoorPsycho** [comment]
Added. 
/iris object worldedit
Copies your current into selection into a iris wand, and gives it to you
