### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by pseudoforceyt** [VolmitSoftware/Iris#475]
[Full error](https://bin.bloom.host/upugosisuw)
This error is spammed in the console periodically during pregeneration.

Steps to recreate:
0. Install Iris and setup the overworld pack
1. `/ir create world3`
2. Restart server
3. `/ir pregen 1k world3`
4. Let it pregenerate for a while
5. Restart server, [this error](https://bin.bloom.host/ekuxelifik.sql) occurs
6. `/ir pregen 1k world3` again
7.  [This error](https://bin.bloom.host/upugosisuw) can be seen periodically spammed in the console.
(`world3` is the world name i have used)

Plugins: Iris, Multiverse Core 4.3.0-SNAPSHOT, Pl3xmap

**Comment by svdgoor** [comment]
Please use the format: https://github.com/VolmitSoftware/Iris/issues/new/choose
