### ISSUE TITLE
java.io.EOFException spammed in console while pregeneration

### ISSUE THREAD

**Issue by pseudoforceyt** [VolmitSoftware/Iris#476]
### Problem

[Full error](https://bin.bloom.host/upugosisuw)
This error is spammed in the console periodically during pregeneration.

Steps to recreate:
0. Install Iris and setup the overworld pack
1. `/ir create world3`
2. Restart server
3. `/ir pregen 1k world3`
4. Let it pregenerate for a while
5. Restart server, [this error](https://bin.bloom.host/ekuxelifik.sql) occurs
6. `/ir pregen 1k world3` again
7.  [This error](https://bin.bloom.host/upugosisuw) can be seen periodically spammed in the console.
(`world3` is the world name i have used)

Plugins: Iris, Multiverse Core 4.3.0-SNAPSHOT, Pl3xmap

### Minecraft Version

1.17.x

### Iris Version

1.5.10 & 1.5.11

### Log

https://bin.bloom.host/ekuxelifik
https://bin.bloom.host/pixileligi

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by svdgoor** [comment]
Thank you :)

**Comment by cyberpwnn** [comment]
The EOF exception is unrelated to Iris, its the new buggy terminal spigot uses. However, all the errors at the bottom is because the server was stopped while iris was doing something, I can fix that, but im not sure why your server stopped in the first place.

**Comment by pseudoforceyt** [comment]
manually stopped

**Comment by NextdoorPsycho** [comment]
Fixed on latest
