### ISSUE TITLE
Find treasure crash server

### ISSUE THREAD

**Issue by HySand** [VolmitSoftware/Iris#480]
### Problem

1. Install Iris...
2. Feed a dolphin(Maybe use treasure map)
3. Server crash for a while

by the way,some treasure are invisiable

### Solution

I think paper have solved this problem，but it happens after installing iris

### Minecraft Version

1.17.x

### Iris Version

1.5.11

### Log

https://pastebin.com/eCsydMSJ

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by cyberpwnn** [comment]
I think this is because of locate? I'll have to take a look at that.

**Comment by ghost** [comment]
@HySand Cyber couldn’t reproduce that issue. Is it still present and if so could you explain how that issue is reproduced?

**Comment by svdgoor** [comment]
1. Iris worlds do not spawn treasure chest maps, and they can hence not be used in Iris worlds either
2. I have fed over 10 dolphins and did not manage to reproduce the issue you are facing

I will hence close this issue, as I think it may lie with another cause than Iris.
If you have a full log, that may change this decision, so please attach it.
If you can show a consistently reproducible way of causing this behaviour, please share it.
