### ISSUE TITLE
too many villagers and other animals

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [VolmitSoftware/Iris#488]
### Problem

too many villagers https://imgur.com/zXq2YG9

and other animals. animals spawn everywhere. even in the ocean.

### Solution

reduce the spawn of mobs by 10 times or add a quantity modifier

### Minecraft Version

1.17.x

### Iris Version

1.5.13

### Log

no need

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ghost** [comment]
Should be a thing of the past cause the whole spawn system got reworked

**Comment by svdgoor** [comment]
^

**Comment by Envel-Nikita-Gutsenkov** [comment]
> 
> 
> ^

LOL BETTER) https://imgur.com/ExSOfyu

**Comment by Envel-Nikita-Gutsenkov** [comment]
and 0 villagers

**Comment by svdgoor** [comment]
Feature, lol. Please don't comment on closed issues.

**Comment by cyberpwnn** [comment]
We just tweaked the systems in the spawns, update your overworld @Envel-Nikita-Gutsenkov
