### ISSUE TITLE
Poor Village Spawns

### ISSUE THREAD

**Issue by berowsma** [VolmitSoftware/Iris#489]
### Problem

1. Generate new world from 1.5.15
2. IR Pregen 10k world
 Observed the following
- Houses on top of each other
- Underground houses
- Poor Path/unreasonable elevation on paths.
![image](https://user-images.githubusercontent.com/88164427/127560286-afba219f-c2af-47a1-89a0-28e862120b20.png)
![image](https://user-images.githubusercontent.com/88164427/127560368-9fa77e09-7b87-44b3-9d18-694bdfe6615f.png)

### Minecraft Version

1.17.x

### Iris Version

1.5.15

### Log

https://pastebin.com/0QqkhnfZ

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by svdgoor** [comment]
Thank you for opening the issue. We'll look into it soon!

**Comment by cyberpwnn** [comment]
Oh lord that looks funny lol.

**Comment by berowsma** [comment]
Updated to latest release with newest build, 1.5.16 new world generated.
![image](https://user-images.githubusercontent.com/88164427/127674382-0789e0af-b48b-4ca5-aa74-641c247b7d39.png)
![image](https://user-images.githubusercontent.com/88164427/127674415-678354aa-cb3e-4fd7-82d7-d0324c395efa.png)
![image](https://user-images.githubusercontent.com/88164427/127674511-a48f4b62-79ce-44e3-82d3-a2499f5129b2.png)
![image](https://user-images.githubusercontent.com/88164427/127674736-cfb5e3ed-2170-45c7-87f6-3f4d71dce4fa.png)
![image](https://user-images.githubusercontent.com/88164427/127674961-83b71f64-6389-49cd-854e-aad7a151d877.png)
![image](https://user-images.githubusercontent.com/88164427/127674993-3005cbfb-0934-402f-9172-e75a584847eb.png)
![image](https://user-images.githubusercontent.com/88164427/127675023-cc4a70de-2015-4680-b77a-a697fa06dede.png)
![image](https://user-images.githubusercontent.com/88164427/127675282-3c495968-60c6-480c-a81e-12a760a0b53b.png)

**Comment by svdgoor** [comment]
Apparently jigsaw structures were placing twice in the same location.
Should be patched on 1.6.0
