### ISSUE TITLE
Jigsaw placement screwed up

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#493]
Do _/iris jigsaw place igloo_ multiple times to reproduce
![2021-08-01_15 38 41](https://user-images.githubusercontent.com/5337873/127773092-382a8080-1a2c-4588-b9a7-bd29a55956f7.png)

**Comment by svdgoor** [comment]
Is this fixed with the latest parallax fixes, @cyberpwnn ?

**Comment by svdgoor** [comment]
plz cyber

**Comment by svdgoor** [comment]
Patched on latest, @ArMiN231 ?

**Comment by ghost** [comment]
Yes that issue is fixed
