### ISSUE TITLE
World Generation does not work

### ISSUE THREAD

**Issue by Sculas** [VolmitSoftware/Iris#494]
### Problem

1. Use Purpur 1.17 and install the latest version of Iris and the latest version of the Overworld pack
2. Start the server
3. Your console will get spammed with errors
4. Restart the server
5. Start MC and connect to the server, you will see that the entire world is filled with red blocks and your console will get spammed with errors every time you generate chunks

### Solution

Looking at the error, it seems that the error starts here:
https://github.com/VolmitSoftware/Iris/blob/8820b02406041440ff2ef6ae84cb9dbd35a255cf/src/main/java/com/volmit/iris/engine/framework/EngineCompositeGenerator.java#L319

`compound` is null.

Then that error causes even more errors in:
https://github.com/VolmitSoftware/Iris/blob/8820b02406041440ff2ef6ae84cb9dbd35a255cf/src/main/java/com/volmit/iris/engine/framework/EngineCompositeGenerator.java#L571

Because, well.. `compound` is null.

I don't know why the entire world is filled with red blocks though.

This is how the red blocks look:
https://imgur.com/a/2E6fGso

### Minecraft Version

1.17.x

### Iris Version

v1.5.18 | Commit: 8820b02406041440ff2ef6ae84cb9dbd35a255cf

### Log

https://mclo.gs/Q6SO9NM

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
you did not read the getting started page did you?
Iris Plugin Support
Docs https://docs.volmit.com/iris/
Getting Started: https://docs.volmit.com/iris/getting-started
FAQ: https://docs.volmit.com/iris/plugin/faq

Properly startin the system prevents this issue, someone ran into this a while ago on the discord, and the solution they has was just re-reading the getting started

**Comment by Sculas** [comment]
Everything worked perfectly before when I was on 1.5.11. All I did was update Iris, update the Overworld pack and delete my old world. What could've gone wrong with only doing that?

**Comment by Sculas** [comment]
But I mean, sure. I'll give it another go re-reading the Getting Started but if nothing has changed there then there's not a lot for me to do. Since I haven't changed a thing there, only did these 3 things I mentioned above.

**Comment by StrangeOne101** [comment]
Getting the same thing. Made a fresh world with /iris create and I get a glazed red terracotta world. Studio worlds work fine

**Comment by StrangeOne101** [comment]
Nevermind, this seems fixed in 672870347391ed75942416c4d414b60ccd156d73

**Comment by ghost** [comment]
@CocoTheOwner according to Strangeone101 this will be fixed with the next version

**Comment by svdgoor** [comment]
ok
