### ISSUE TITLE
Strongholds do not spawn

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#495]
### Problem

Strongholds do not spawn since the latest pregeneration changes around 1.5.10. This occurs in both studio worlds and normal worlds.

This can be observed by both no console output at stronghold locations and no stronghold found by following an ender eye from 0,0 

### Minecraft Version

1.17.x

### Iris Version

1.5.18 @ 672870347391ed75942416c4d414b60ccd156d73

### Log

.

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by svdgoor** [comment]
I think it's time for a good implementation of the strongholds, instead of wacky implementations.

**Comment by StrangeOne101** [comment]
Agreed. First thing we need to do is figure out how to write structures to MCA files lol

**Comment by StrangeOne101** [comment]
Strongholds now generate. They just do not generate _properly_

**Comment by ghost** [comment]
> Strongholds now generate. They just do not generate _properly_

Ok than this can be closed? The Jigsaw system needs a rework/overhaul so his is misleading.

**Comment by StrangeOne101** [comment]
I'd say Jigsaw needs fixing but the current system is fine. I don't see how it needs an overhaul

Regardless, this can be closed

**Comment by svdgoor** [comment]
@StrangeOne101 What do you mean by `not properly`?
Does that mean there are not enough, they're only partially spawning, or is it because of the other issue

**Comment by StrangeOne101** [comment]
> @StrangeOne101 What do you mean by `not properly`?
> Does that mean there are not enough, they're only partially spawning, or is it because of the other issue

As far as I've seen, only the portal room generates. Yet if you place them manually, they're fine
