### ISSUE TITLE
Asynchronous Chunk getEntities call

### ISSUE THREAD

**Issue by barfuem** [VolmitSoftware/Iris#497]
### Problem

1. Install Iris 1.6
2. Generate a new world
3. Observe the error...

### Minecraft Version

1.17.x

### Iris Version

Iris 1.6 The Expressive Update 

### Log

https://mclo.gs/UE1esSk - Line 6288

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by svdgoor** [comment]
@barfuem I forgot to ask initially, do mobs spawn properly, or do they not spawn at all?

Note to self:
(If mobs do not spawn, make high priority and remove NMI label)

**Comment by barfuem** [comment]
mobs are spawning

**Comment by ghost** [comment]
@CocoTheOwner is this fixed in the latest?

**Comment by svdgoor** [comment]
Think so. Comment here or open new if bug resurfaces
