### ISSUE TITLE
Command support

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#498]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to (re)add MythicMobs & Citizens support

### What are you trying to modify

The way I would implement this is by adding sections to IrisEntities for MythicMobs & Citizens, with respective subsections.
For MythicMobs, the only requirement would lie with a mob name.
For Citizens, there are a few additional elements to consider such as NPC name, on-click command, and many other settings.

Since MythicMobs broke recently, and Citizens (and any other entity-spawning plugin for that matter) is likely to be updated in the future as well. For this reason, I would suggest a command-based approach, where one could configure a command input with a location. An example of this is:
```json
        "commands": [
            "/mm spawn Bear {x} {y} {z}",
            "summon enderdragon {x} {y} {z}",
            "tp @p @r"
        ]
```
prefixed /'s are removed, and {x}, {y} and {z} are replaced with the actual coordinates of the location

### Alternatives

If this could not be implemented I would use the same direct approach as before, for both MythicMobs and Citizens.

**Comment by svdgoor** [comment]
#20

**Comment by svdgoor** [comment]
Note: Execution of these commands should be when the chunk is loaded by a player, rather than when DirectMCA or other generators generate it, to prevent epic fails where something happens in unloaded chunks, or MM's or NPCs despawn immediately

**Comment by ghost** [comment]
MythicMobs was readded with this https://github.com/VolmitSoftware/Iris/commit/64ce5138e1877b7f9e0814dabaa297e1f8d78b39

**Comment by svdgoor** [comment]
@StrangeOne101 how'd you feel about citizens support?
Doesn't have to be the way as suggested above

**Comment by StrangeOne101** [comment]
@CocoTheOwner  I'm all for adding it. Just unsure what a good implementation method would look like. Would it be easier to call a denizen script to spawn the NPC?

**Comment by svdgoor** [comment]
I don't think it's a particularly g good idea to have another dependency outside of iris and the linked plugin.
I think it would hence be best to look at the way citizens are created, which setting they support and then copy those settings into a JSON config, perhaps inside the entity config

**Comment by svdgoor** [comment]
Based on Cyber's comment on #20 I think we may assume it's worth it to implement the command usage.
In this case, it needs to be remembered that these functions must still work with directMCA and should hence be scheduled for when the chunk is first loaded, instead of being ran immediately.

**Comment by ghost** [comment]
Keyword Markers

**Comment by cyberpwnn** [comment]
You can do this several ways. You can do it now with any plugin that allows you to specify a world in the command.

# Mythic Mobs example
Say i have a mob called "guard", level 3

guard.json (in `packs/YOURPACK/entities/guard.json`)
```json
{
    "type": "UNKNOWN",
    "postSpawnScripts": [
        "spawn"
    ]
}
```

spawn.js (in `packs/YOURPACK/scripts/spawn.js`)
```js
// Define your mythic mob
var type = "guard";

// Define the level of the mob (as per the docs i read... idk if this is needed though)
var level = 3;

var location = Iris.getLocation();
var sender = org.bukkit.Bukkit.getConsoleSender();
org.bukkit.Bukkit.dispatchCommand(sender, "/mm mobs spawn " + type + ":" + level + " 1 " 
    + location.getWorld().getName() + "," 
    + location.getBlockX() + "," 
    + location.getBlockY() + "," 
    + location.getBlockZ());
```

I will work on supporting just raw commands, however it's at least possible right now.

**Comment by svdgoor** [comment]
https://github.com/VolmitSoftware/Iris/pull/653
