### ISSUE TITLE
Find treasure issue

### ISSUE THREAD

**Issue by HySand** [VolmitSoftware/Iris#499]
### Problem

1. Install Iris
2. Edit Bukkit.yml to generate iris world
3. Run Server
4. Delete files in world folder as the guide do
5. Restart the server
6. /iris pregen 1000 world
7. Restart the server
8. Find an ocean
9. Spawn a dolphin with spawn egg
10. Feed it a raw fish
11. Crash

My test server file https://1drv.ms/u/s!AgZ0nf3rNQpHiCqDQdtBvoy_ZWes?e=6UdeRC

### Minecraft Version

1.17.x

### Iris Version

1.6.1

### Log

https://pastebin.com/zufefh4n

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [x] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ghost** [comment]
@Hysand The server will crash when using spawn eggs or /cmi spawnmob dolphin. With EssentialsX its working fine. Does this also happen with naturally spawning dolpings?

**Comment by HySand** [comment]
@ArMiN231 Yes,it heppens with naturally spawning dolphings and those spawned by vanilla command /summon dolphin.
By th way,my server don't use EssentialsX or CMI.

**Comment by HySand** [comment]
@ArMiN231 I tested the villagers too,if a cartographer upgrades it may sell treasure maps,it also cause crash.But i don't know if it happens with naturally spawning villagers.

**Comment by ghost** [comment]
Will be fixed with this https://github.com/VolmitSoftware/Iris/pull/500, so it can be closed @CocoTheOwner ?

**Comment by svdgoor** [comment]
Yes
