### ISSUE TITLE
Biomes borders are too smooth

### ISSUE THREAD

**Issue by HySand** [VolmitSoftware/Iris#501]
### Adding, Removing, or Changing

Changing

### Type of Modification

Make biomes borders greater

### What are you trying to modify

For  `Biome Blend` settings in `Video Settings` only affect grass block,some biomes' borders which are not consist grass blocks are unsatisfactory .
Border in vanilla world:
https://imgur.com/wNQ5SEZ
Border in Iris world:
https://imgur.com/Sru5DY3

### Alternatives

Add extra noise to border?

**Comment by ghost** [comment]
@CocoTheOwner This is a overworld "problem" aka its a matter of how you setup the noises, right?

**Comment by svdgoor** [comment]
Correct. I'll copy-paste this into an overworld issue, see [#180](https://github.com/IrisDimensions/overworld/issues/180)
