### ISSUE TITLE
reopen #488

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [VolmitSoftware/Iris#504]
### Problem

reopen issue #488

### Minecraft Version

1.17.x

### Iris Version

1.6.2

### Log

null

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ghost** [comment]
You can reopen #488 yourself. @StrangeOne101 can you close this?

**Comment by cyberpwnn** [comment]
See #488 @Envel-Nikita-Gutsenkov
