### ISSUE TITLE
Iris engine isn't initialized when the server started

### ISSUE THREAD

**Issue by moeKiwiSAMA** [VolmitSoftware/Iris#505]
##### Situation 1
Iris should have these nice, smoky particle.
![image](https://user-images.githubusercontent.com/15682954/128561037-11fbb8e0-31aa-401c-acde-22990753f21c.png)

But it only appear after the Iris engine initialize. 
If the iris engine is not initialized, these particle won't appear.

![image](https://user-images.githubusercontent.com/15682954/128561203-73284fad-fce7-4ef9-9170-dd23daabcfd4.png)

When I teleport to a location which has not been pregened, the iris engine will be initialize.

![image](https://user-images.githubusercontent.com/15682954/128561282-7d47dc8c-4245-4838-8987-59f554e3832b.png)

##### Situation 2
I want to pregen a irisworld, it wont recongize the target world, unless the engine initialized.
It seems like Iris don't know the target world is generated by itself, and, when I try to pregen the target world, I must initialize the engine first, then I could pregen it.

![image](https://user-images.githubusercontent.com/15682954/128561645-4c9bcae3-a942-4d4c-8675-ad5656d264bb.png)

## Server and Plugin Informations
- Iris: v1.6.3 1.6.2 & etc.
- Purpur 1.17.1-1313 & airplane-57 & etc.
- Ubuntu 18.04 with Oracle JDK 16

### Solution

None

### Minecraft Version

1.17.x

### Iris Version

1.6.3 1.6.2 & etc.

### Log

https://mclo.gs/JtSTZ19

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by cyberpwnn** [comment]
This is correct. The proper usage of the pregen command is `/iris pregen <size>` command. You need to create an Iris world first before pregenerating. (`/iris create <name> seed=<seed> type=overworld`)

I will tag this as an enhancement for improving the pregen / create commands

**Comment by svdgoor** [comment]
@cyberpwnn this isn't an enhancement if I understand it correctly. It looks to me as a bug with initializing the engine on worlds, that causes entity particles to not spawn.
I have a feeling this issue will also cause mobs to not spawn, events to not trigger (such as preventing the villager trades & dolphin feeds) and more, unknown, issues.

**Comment by cyberpwnn** [comment]
I need proper reproduction steps. There is a pregen command via console specifying a world which i dont know the state of.

**Comment by moeKiwiSAMA** [comment]
I shoots two videos.
Video 1: https://www.youtube.com/watch?v=Ra95IzUnp94
Video 2: https://www.youtube.com/watch?v=8ZYxUSuN59k

## Steps
Steps

Get a nice clean latest minecraft server first (Video 1 00:17)

install iris and multiverse (Video 1 01:24)

(another bug) (Video 1 01:53)

download overworld (Video 1 02:57)

create irisworld (Video 1 04:00)

just a random seed, so i can find the desert

look at these steams or smoke or whatever, every thing seems fine (Video 1 04:55)

and if i restart the server, the engine will initialize properly (Video 1 06:00)
(because loading new chunks will let iris initialize the engine)

then, i pregen a region(2k) (Video 1 06:48) (1k works fine to, but less may cause chunk grenerating when server start)

restart the server (Video 2 00:20)

And the engine wont initialize(because no new chunk was loaded) (Video 2 00:40)

and no smoke

but if i teleport to a place never generated (Video 2 02:00)

the engine will be initialized (Video 2 02:00)

and smoke appears again (Video 2 02:40)

and the world also could be pregen again (Video 2 02:50)

so, I think this is a bug

**Comment by ghost** [comment]
For me its working correctly on 1.7.7 but someone else should confirm first that its truely fixed @CocoTheOwner @StrangeOne101 @NextdoorPsycho

**Comment by ghost** [comment]
@CocoTheOwner this can be closed

**Comment by moeKiwiSAMA** [comment]
I tried iris 1.7.11, but particles still could not spawn before the iris engine hotloaded.
