### ISSUE TITLE
Random Density

### ISSUE THREAD

**Issue by NextdoorPsycho** [VolmitSoftware/Iris#507]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want random density

### What are you trying to modify

The way I would implement this is by yelling at dan to implement it

### Alternatives

no alternative to Random Density

**Comment by StrangeOne101** [comment]
Having density be a decimal would work well. Wouldn't need another value in that case

Example: 2.1 would be 2.0 90% of the time and 3 10% of the time

**Comment by cyberpwnn** [comment]
#508

**Comment by svdgoor** [comment]
Random density with a minAmount & maxAmount would be better than a decimal imo, since it gives more freedom (decimal only allows 1 difference, 2.5 gives 50% 2 and 50% 3, but you can't get more than 2 options, 1 apart, with that system.

**Comment by StrangeOne101** [comment]
Maybe both should be added then. minDensity and maxDensity. You can't get more than 2 options with decimals but you can still get more precise control than just an int min max. A min of 2 and max of 3 would still be an average of 2.5

**Comment by svdgoor** [comment]
Agreed. min and max floating point

**Comment by svdgoor** [comment]
#645 adds this feature. Once added, you can specify 
```json
"densityStyle": {
    "min": 10,
    "max": 10,
    "style": {
        "style": "BIOCTAVE_FRACTAL_BILLOW_PERLIN"
    }
},
```
in any object placement.
The style is not indicative of the locations of the objects, just the amount that are picked. Static makes it random, but something like Perlin you can make it more clustered, especially with a higher exponent.
Hopefully it works as intended :)
