### ISSUE TITLE
Spigot Async entity get throwing errors

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#509]
https://mclo.gs/Wc4tn4q

Don't fix this with just making the call sync, it'll be too slow on paper+
Make a check if spigot, Async

**Comment by NextdoorPsycho** [comment]
use PurPur

**Comment by svdgoor** [comment]
We support spigot afaik.
If not, lmk.

**Comment by svdgoor** [comment]
https://github.com/VolmitSoftware/Iris/blob/478d465cb6b988000db94fb1c46247e998a75281/src/main/java/com/volmit/iris/engine/IrisWorldManager.java#L87
Looper is async, which Spigot can't handle.
Turns out it's not as easy a fix as I originally thought, and as Cyber warned me about.
If anyone has this issue, tell them to up their server flavour from Spigot to paper (or derivative)

**Comment by cyberpwnn** [comment]
Fixed
