### ISSUE TITLE
Cartographer level 3 can cause crash + Vanilla structures findings & suggestions

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#51]
Just like with EpicWorldGenerator, upgrading a Cartographer to level 3 causes a server freeze since no Mansions can be found / generated.

Freeze log:
![afbeelding](https://user-images.githubusercontent.com/65736624/96456646-0f9a7900-121f-11eb-85fe-3284fa8e5777.png)

Full log: 
[latest.log](https://github.com/VolmitSoftware/Iris/files/5402075/latest.log)

**Comment by svdgoor** [comment]
Lastest everything

**Comment by svdgoor** [comment]
This is caused by the cartographer trying to create a map for finding mansions and / or ocean monuments.
If you would be 100% sure they spawn in the world or that /locate points at least somewhere, this bug would be auto-fixed.
It might be a good idea to prevent this crash from occuring altogether (even if the previous requirement has been met) to prevent this becoming an issue in the future.

**Comment by svdgoor** [comment]
Also:
- Mansions spawn
- Raid towers spawn
- Strongholds spawn
- Mineshafts spawn
- Buried treasure spawn
- Desert pyramids spawn when using /locate only, and spawn underground sometimes
======
- Ocean monuments do not spawn
- Igloos do not spawn
- Villages do not spawn
- Witch huts do not spawn
- Jungle pyramids do not spawn
- Ocean ruins do not spawn
- Shipwrecks do not spawn

Also - strongholds do not spawn in the correct location when entering any seed (/locate does not point to the correct location)

**Comment by svdgoor** [comment]
As long as /locate points _anywhere_ the server will not crash because of the cartographer

**Comment by cyberpwnn** [comment]
`THIS IS NOT A BUG OR A CRASH`

This is a performance issue. Im not exactly sure why the map is trying to blast that much data but gen v2 should help with this. Hmmm Iris should not be even having this issue. What version are you on?

**Comment by svdgoor** [comment]
This is the result of Minecraft iterating over the world in order to try and find a structure to point to with /locate.
Cartographers do this automatically (use the same methods as /locate).
Will check on latest

**Comment by svdgoor** [comment]
Fixed in .30
