### ISSUE TITLE
The Mantle ideas

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#511]
Would be nice to have an API for:
- Finding all objects in a location (xyz)
- Finding all objects in a chunk
- Finding all objects in a region
- Finding all objects in a radius
- Finding the nearest object from a location
- Having "easy" collision checks with objects around an area (I understand the performance requirements, but this is essential I'm afraid)

Reference this issue in issues related to The Mantle

**Comment by svdgoor** [comment]
As for a datastructure for storing this:
I think the most useful would be a per-chunk or per-region storage
In those, consider both object origins & every-block information (which can be both added, perhaps)
All information should be saved in the folder of the world (def not generated on runtime)

**Comment by StrangeOne101** [comment]
For tree fellar, itd be good if felled trees could have their object removed from the mantle "current objects" and have grown trees insert back into it

**Comment by ghost** [comment]
@CocoTheOwner can this be closed due to the new finding command?
