### ISSUE TITLE
SCOREBOARD // WORLD CREATION  //  OBJECTS  //  CHUNKGEN

### ISSUE THREAD

**Issue by NextdoorPsycho** [VolmitSoftware/Iris#524]
### Problem

1: The iris scoreboard flickers. Fic that
- The iris scoreboard is flickering

2: cant make worlds
- /iris create worldname type=overworld

3: After objects unload they are not recognized by the dust .. Spams errors
- read the hotline

4: chunkgen is 10cps slower

### Solution

Cry

### Minecraft Version

1.18.x

### Iris Version

v1.6.8-Dangerously-Unstable-Seriously-Im-Warning-You-I-Dare-You-I-Double-Dare-You-Just-Do-It-You-Wont

### Log

https://pastebin.com/uTCU8j1K

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ghost** [comment]
Should/could be fixed with the commit https://github.com/VolmitSoftware/Iris/commit/89be08bc58f912090d791735b7def5122f819ddd

**Comment by ghost** [comment]
@NextdoorPsycho close?

**Comment by ghost** [comment]
@CocoTheOwner this can be closed. Everything mentioned is fixed
