### ISSUE TITLE
Villagers + Pillagers Not Spawning 

### ISSUE THREAD

**Issue by Clenzy** [VolmitSoftware/Iris#525]
### Problem

After renaming worlds, (I had no choice but to do this) and following some support in the discord I was told to come here, and submit a bug report. As pillagers and villagers aren't spawning in their corresponding locations.  Mobs that spawn in the nether overworld biomes aren't affected by this. I updated the world generation in both Multiverse and the bukkit.yml file and it does create new Iris biomes (after exiting the pre-generated zone.) I ran this command as well, and it didn't seem to make a difference.  /mv import world -g Iris:overworld

### Solution

Renaming worlds, not entirely sure.  

### Minecraft Version

1.17.x

### Iris Version

Iris-1.5.16.jar

### Log

https://paste.dedimc.io/ukopodonic

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by cyberpwnn** [comment]
Initial spawns added, will be fixed in next update / world update
