### ISSUE TITLE
ItemsAdder support 

### ISSUE THREAD

**Issue by enjoythemomentum** [VolmitSoftware/Iris#526]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want support for ItemsAdder

### What are you trying to modify

The way I would implement custom blocks, world decors and more 

Link:
https://www.spigotmc.org/resources/✅must-have✅-itemsadder✨custom-items-huds-guis-mobs-3dmodels-emojis-blocks-wings-hats-liquids.73355/

### Alternatives

-

**Comment by ghost** [comment]
ItemsAdder won’t support Iris. Plus the fundamental way ItemsAdder is working conflicts with the way Iris is working. That’s why we recommend Oraxen cause it’s fully compatible and implemented. Therefore this can be closed. @NextdoorPsycho

**Comment by svdgoor** [comment]
We've been over this with the ItemsAdder developer.
No
