### ISSUE TITLE
Unable to find dimension type null Looking for online packs

### ISSUE THREAD

**Issue by elliotnash** [VolmitSoftware/Iris#530]
### Problem

A clean install of Iris 1.7 will produce the error shown in the logs when trying to prepare the world (using the "overriding your main world" method), and Minecraft will default to the Minecraft overworld generator

steps to reproduce:
1. Clean install Iris 1.7 (delete world folders, Iris config folder, then add Iris jar)
2. Use Iris generator for world "world" in your bukkit.yml
3. Start server

### Minecraft Version

1.17.x

### Iris Version

1.7

### Log

https://hastebin.com/biliqogoxe.sql

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by svdgoor** [comment]
Right on time #531

**Comment by StrangeOne101** [comment]
Still affects 1.7.4

**Comment by ghost** [comment]
Fixed on 1.7.7 @CocoTheOwner
