### ISSUE TITLE
Cannot find dimension in /home/container/world/iris with key overworld

### ISSUE THREAD

**Issue by elliotnash** [VolmitSoftware/Iris#532]
### Problem

(/home/container is the mc servers root folder in pterodactyl)
Iris 1.7 fails to load the generator when using override world method with error Cannot find dimension in /home/container/world/iris with key overworld

1. Clean install iris, delete world files
2. Copy overworld pack into /plugins/Iris/packs
3. set Iris as generator for world "world" in bukkit.yml
4. Watch error in console

### Minecraft Version

1.17.x

### Iris Version

1.7

### Log

https://hastebin.com/kigukuyuro.makefile

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by StrangeOne101** [comment]
Still affects 1.7.2

**Comment by ghost** [comment]
Works on 1.7.7 fine so this can be closed @CocoTheOwner
