### ISSUE TITLE
Crash when flying around Iris studio world

### ISSUE THREAD

**Issue by jaysonsperling** [VolmitSoftware/Iris#535]
### Problem

- Iris version: 1.6.7 (downloaded from Spigot on Tueday)
-  Server version: Paper version git-Paper-170 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 80650e8)
-  Plugins: AsyncWorldEdit, ClearLag, CoreProtect, Essentials, EssentialsSpawn, Iris, LuckPerms, Multiverse-Core, MythicMobs, PlaceholderAPI, ProtocolLib, Vault, WorldEdit, WorldEditSUI
-  OS: Mac OS Mojave 10.14.6 Java: java version "16.0.2" 2021-07-20 | Java(TM) SE Runtime Environment (build 16.0.2+7-67) | Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

-----

After adding a loot config to an object (see below), I start the server, jump into /iris studio open MPKCraft and once I fly around for a few moments (maybe 20-30) looking for the object, the server starts to freeze. Please see the attached gist for the logs.

beach.json biome with literaltrash2 object attempting to put loot into it:
```
{
    "name": "Beach",
    "derivative": "BEACH",
    "vanillaDerivative": "BEACH",
    "layers": [
        {
            "palette": [
                {
                    "block": "minecraft:sand"
                }
            ]
        },
        {
            "palette": [
                {
                    "block": "minecraft:dirt"
                }
            ],
            "maxHeight": 3,
            "minHeight": 2
        }
    ],
    "generators": [
        {
            "generator": "vanilla",
            "max": 1,
            "min": -1
        }
    ],
    "objects": [
        {
            "chance": 0.1,
            "density": 3,
            "place": [
                "clutter/literalgarbage1"
            ],
            "loot": [
                {
                    "name": "test-beach-treasure",
                    "exact": false,
                    "filter": [
                        {
                            "block": "minecraft:chest",
                            "debug": true
                        }
                    ],
                    "weight": 1
                }
            ]
        },
        {
            "chance": 0.05,
            "density": 4,
            "place": [
                "clutter/log"
            ]
        },
        {
            "place": [
                "clutter/camp1"
            ],
            "chance": 0.03,
            "density": 1
        }
    ]
}
```

Loot configuration:
```
{
    "name": "Test Beach Treasure",
    "rarity": 1,
    "maxPicked": 5,
    "minPicked": 2,
    "loot": [
        {
            "type": "gold_ore",
            "maxamount": 3,
            "rarity": 2,
            "slottypes": "STORAGE"
        },
        {
            "type": "diamond_ore",
            "maxamount": 4,
            "rarity": 2,
            "slottypes": "STORAGE"
        }
    ]
}

```

### Minecraft Version

1.17.x

### Iris Version

1.6.7

### Log

https://gist.github.com/jaysonsperling/7373ab80954f5552c70f6b7bfe6362d0

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by cyberpwnn** [comment]
1. `--- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-170 (MC: 1.17.1) ---`, its not a crash, your server is frozen. 
2. I think it's generating normally, you should turn off watchdog and paper's stacktrace spamming. 
3.

**Comment by ghost** [comment]
Couldnt reproduce and as cyber suggested its due to papers watchdog @CocoTheOwner
