### ISSUE TITLE
Iris causes server to go unresponsive after adding biome loot table and new chunks generating

### ISSUE THREAD

**Issue by jaysonsperling** [VolmitSoftware/Iris#537]
### Problem

- Iris version: 1.6.7 (downloaded from Spigot on Tueday)
- Server version: Paper version git-Paper-170 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 80650e8)
- Plugins: AsyncWorldEdit, ClearLag, CoreProtect, Essentials, EssentialsSpawn, Iris, LuckPerms, Multiverse-Core, MythicMobs, PlaceholderAPI, ProtocolLib, Vault, WorldEdit, WorldEditSUI
- OS: Mac OS Mojave 10.14.6 Java: java version "16.0.2" 2021-07-20 | Java(TM) SE Runtime Environment (build 16.0.2+7-67) | Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

---
Problem: I've added a loot definition to a biome (both listed below) while the server was shut down. Once I start the server up and go into the studio world (/iris studio open MPKCraft) and start to fly around, the generator will get stuck (does not generate new chunks), paper will throw "The server has not responded for X seconds! Creating thread dump" on the console, and once it hits 40 seconds, the server will die. It unloads all plugins but then gets stuck at shutting down Iris (see attached dump)

Biome definition
beach.json:
```
{
    "name": "Beach",
    "derivative": "BEACH",
    "vanillaDerivative": "BEACH",
    "layers": [
        {
            "palette": [
                {
                    "block": "minecraft:sand"
                }
            ]
        },
        {
            "palette": [
                {
                    "block": "minecraft:dirt"
                }
            ],
            "maxHeight": 3,
            "minHeight": 2
        }
    ],
    "generators": [
        {
            "generator": "vanilla",
            "max": 1,
            "min": -1
        }
    ],
    "objects": [
        {
            "chance": 0.1,
            "density": 2,
            "place": [
                "clutter/literalgarbage1"
            ]
        },
        {
            "chance": 0.05,
            "density": 4,
            "place": [
                "clutter/log"
            ]
        },
        {
            "place": [
                "clutter/camp1"
            ],
            "chance": 0.03,
            "denstity": 1
        }
    ],
    "loot": {
        "mode": "REPLACE",
        "multiplier": 1,
        "tables": ["test-beach-treasure"]
    }
}
```

Loot table definition
test-beach-treasures.json:
```
{
    "name": "Test Beach Treasure",
    "rarity": 1,
    "maxPicked": 5,
    "minPicked": 2,
    "loot": [
        {
            "type": "gold_ore",
            "maxamount": 3,
            "rarity": 2,
            "slottypes": "STORAGE"
        },
        {
            "type": "diamond_ore",
            "maxamount": 4,
            "rarity": 2,
            "slottypes": "STORAGE"
        }
    ]
}

```

### Minecraft Version

1.17.x

### Iris Version

1.6.7

### Log

https://gist.github.com/jaysonsperling/e27a40d156a153a9d7a65e8781a197a2

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
Turn off watchdog spam read FAW wiki
