### ISSUE TITLE
Created worlds not registered to multiverse

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#542]
### Problem

Creating an Iris world no longer registers it to multiverse as it did.

1. /iris create testworld101
2. Restart Server
3. /mv list
4. See that it is not loaded or even known about

### Solution

Probably fix how the create command works

### Minecraft Version

1.17.x

### Iris Version

1.7 @ 30c5a0d

### Log

-

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by StrangeOne101** [comment]
Still affects 1.7.3

**Comment by cyberpwnn** [comment]
Fixed in 1.7.4 (you need to use the mvc command, or import it later though)
