### ISSUE TITLE
Village generation and resident spawning not working on airplanepurpur

### ISSUE THREAD

**Issue by TheHappyHopper** [VolmitSoftware/Iris#549]
### Problem

1. start a new server with airplanepurpur https://ci.tivy.ca
2. create an iris overworld world
3. explore until you find a village/chunk loading error
4. notice no villagers
5. wait for as long as you like, no villagers spawn

If chunk error instead due to village bounding box

-restart server to fix chunk error
-village generates but no villagers

no errors in console when this happens

### Minecraft Version

1.17.x

### Iris Version

1.6.7

### Log

https://mclo.gs/6FyRnyI

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by cyberpwnn** [comment]
This is an issue with iris https://github.com/VolmitSoftware/Iris/issues/525
