### ISSUE TITLE
Suggesiton: add a pause option to pregen

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#55]
Adding a /iris pregen pause button would be nice if you had to do something on the server but don't want Iris to be generating at the same time.

**Comment by svdgoor** [comment]
This is mainly to prevent having to wait for iris to re-check already generated chunks because you'd be forced to /iris pregen stop and then /iris pregen <radius> again

**Comment by svdgoor** [comment]
Added in .24
