### ISSUE TITLE
Jigsaw: Entity's spawning without buildings.

### ISSUE THREAD

**Issue by TheDevelon** [VolmitSoftware/Iris#55]
**Describe the bug**
Sometimes, especially with villages near water, the village mobs just spawn inside of the ocean. I think Iris planned to place buildings there but stopped due to the underground beeing water.

**To Reproduce**
1. Open a iris world with Iris 1.3.1
2. Go to, as an example, temperate-beach
3. Search for villages
4. See villagers/pigs/sheeps swimming in water

**Expected behavior**
Mobs only spawning if the placement was successful.

**Screenshots or Video Recordings**
![image](https://user-images.githubusercontent.com/28627992/104808925-a3adb980-57e9-11eb-9584-19845cf07145.png)
![image](https://user-images.githubusercontent.com/28627992/104808980-1ae34d80-57ea-11eb-88ac-dd43db664ab0.png)

**Server and Plugin Informations**
 - Iris Version: 1.3.1
 - Server Platform and Version [eg: PaperSpigot 1.16.3 VolmitSoftware/Iris#240]: 
![image](https://user-images.githubusercontent.com/28627992/104808931-b88a4d00-57e9-11eb-93e6-a48694cbcdbc.png)

 - Operating System (if applicable): Debian

**Comment by ghost** [comment]
Needs testing if this is still the case for the dev version.

**Comment by svdgoor** [comment]
Can't be fixed by pack config.
Caused by parallax & entity populator order.

**Comment by svdgoor** [comment]
V2 pack sort of fixes this by preventing villages from spawning near water, but that's not prefferable ofc

**Comment by ghost** [comment]
Hasn’t been reported ever since so pls open this again if it still occurs
