### ISSUE TITLE
Entity spawn causing blockstate error, perhaps due to async call

### ISSUE THREAD

**Issue by enjoythemomentum** [VolmitSoftware/Iris#550]
### Problem

Sadly, I have no clue

### Solution

^

### Minecraft Version

1.17.x

### Iris Version

1.6.7

### Log

https://bin.bloom.host/oqabasehug

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by StrangeOne101** [comment]
Fixed in #555
