### ISSUE TITLE
Reimplement Initial Entity Spawns

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#551]
### Adding, Removing, or Changing

Adding

### Type of Modification

EntityInitialSpawns needs to be reimplemented. Jigsaws cannot spawn entities one time only and this isn't acceptable in its current state

### What are you trying to modify

It needs to be reimplemented because jigsaws need to have entity connectors again. Iris Spawners are too slow when waiting for mobs that HAVE to be there, and spawners will respawn mobs. Which isn't what is needed here. 

Uses for jigsaw entities that spawn one time only:
- Villages
- Ocean Monuments (Elder Guardians)
- Woodland mansions (everything)
- Pillager towers (spawn lots initially, spawn a tiny amount with spawners)

### Alternatives

-

**Comment by svdgoor** [comment]
I think I saw him do this yesterday. Please confirm @cyberpwnn

**Comment by cyberpwnn** [comment]
Implemented, use initialSpawns in any spawner.
