### ISSUE TITLE
Add GenMode: STARTUP progress status

### ISSUE THREAD

**Issue by FluffyDiscord** [VolmitSoftware/Iris#56]
**Is your feature request related to a problem? Please describe.**
VolmitSoftware/Iris#260 

**Describe the solution you'd like**
Except making the server not freeze completely (workaround is to set timeout to -1), it would be great to see progress of the first step. Right now we have nothing and it appears stuck/frozen for dozens of minutes for bigger pregens, like 30k.

For example, **30k pregen took whole 47 minutes** to finally start generating. That's like the first iris version, where it would be checking chunk/region one by one and "catching up" for such a long time/

**Describe alternatives you've considered**
Maybe there's a bug, which makes it take so long ?

**Additional context**
-

**Comment by svdgoor** [comment]
So many changes to the pregenerator as of late. This seems to have been included by default. Waiting for a second isn't too big a deal like Nowhere mentioned, I think the current way of things is fine. If you disagree, please do make a new enhancement request.
