### ISSUE TITLE
Pregen is not working properly

### ISSUE THREAD

**Issue by Nolex01** [VolmitSoftware/Iris#562]
### Problem

1. Install Iris
2. Do /iris pregen start 1k

There is no error at all.
If you do it with /iris pregen start 1k:
[22:38:22 INFO]: [Iris]: Pregen: 0 of 0 (NaN%) 0/s ETA: 0ms

https://imgur.com/a/6rD7Wtd

There is a window comes up for some second and close.

With higher number like 10k it's working for me but with 1k and lower numbers not. (I didn't tested with 2k, 3k, etc..)

### Solution

Higher numbers working

### Minecraft Version

1.17.x

### Iris Version

1.7.4

### Log

https://pastebin.com/UY6rGGrG

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ghost** [comment]
Couldnt reproduce it anymore so this can be closed @CocoTheOwner
