### ISSUE TITLE
Noise Explorer Freezes

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#564]
### Problem

The noise explorer will eventually stop moving. With static style, this can be observed within 10 seconds. Any other style is almost always frozen and does not actually move.

The explorer itself is not frozen in terms of frames. You can still move the area shown by click and dragging the mouse, but the noise itself no longer changes

### Minecraft Version

1.17.x

### Iris Version

1.8.3

### Log

.

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by svdgoor** [comment]
Intended. Move around by dragging with your mouse to re-engage it moving.

**Comment by StrangeOne101** [comment]
Not intended. Moving the noise does not change anything. Reopened.

**Comment by cyberpwnn** [comment]
This is intended, the z coordinate is no longer shifted to reduce cpu usage. IF you are talking about panning / zooming not working thats different, but they should not update / animate on their own (i know static does but only for a few seconds). If you are saying that the noise explorer is actually freezing (meaning you cant select a dropdown / pan or zoom) make a new issue about it.
