### ISSUE TITLE
Everyone getting booted to the Nether

### ISSUE THREAD

**Issue by Kurenox** [VolmitSoftware/Iris#566]
Every time I restart the server all of my players lose their previous position and are sent into the Nether.

**Comment by Felleus** [comment]
Yes. I have the same problem...

**Comment by PierreSchwang** [comment]
Is the world where your players are a studio world? When the StudioService disabled, all players are evacuated into a non-iris-world: https://github.com/VolmitSoftware/Iris/blob/630b6e6313ce76122426c26a705e37543023d999/src/main/java/com/volmit/iris/core/tools/IrisToolbelt.java#L156

**Comment by Nolex01** [comment]
I have the same issue too

**Comment by daniil5277** [comment]
I have the same problem

**Comment by ghost** [comment]
@Kurenox @Nextler @MrNolex @daniil5277 please give us more informations on how you setup everything cause we cant reproduce that issue therefore this will be closed until proven to be a bug @CocoTheOwner

**Comment by svdgoor** [comment]
Removed on 1.7.5 afaik
