### ISSUE TITLE
Crafting Recipe 6-Sided - 4-sidedlog

### ISSUE THREAD

**Issue by NextdoorPsycho** [VolmitSoftware/Iris#567]
Make the Crafting Recipe for In 6-Sided logging

**Comment by StrangeOne101** [comment]
What is this?

**Comment by ghost** [comment]
NVM they removed the receipt to get 4 sided logs out of 6 sided logs. Thx Obama

**Comment by StrangeOne101** [comment]
> Isn’t this already doable with Minecraft?

Yeah, my thoughts exactly lol

**Comment by svdgoor** [comment]
Used to be, not anymore.
Valid request.

**Comment by ghost** [comment]
https://crafting.thedestruc7i0n.ca/ @StrangeOne101 @NextdoorPsycho  @CocoTheOwner can this help maybe in any way?

**Comment by StrangeOne101** [comment]
![image](https://user-images.githubusercontent.com/2769013/133016280-bad563e7-22b4-4401-8de2-5e284edf3701.png)

I honestly got no idea what you guys are on about. It's already in vanilla. So I'm closing.
