### ISSUE TITLE
Server freeze after shutdown

### ISSUE THREAD

**Issue by jassyel** [VolmitSoftware/Iris#569]
### Problem

1. Use /stop or /restart
2. See console
3. Server freeze

### Minecraft Version

1.17.x

### Iris Version

1.7.4

### Log

https://pastebin.com/aLaDNVff

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ghost** [comment]
This doesnt occur usually just when you shutdown or restart the server while its still busy also cant see any hint that iris is the cause so this can be closed and only will be opened when you provide us informations e.g. when you restarted the server (during generation for example). @CocoTheOwner
