### ISSUE TITLE
Procedural structure placement conditions accounting for carving

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#57]
**Is your feature request related to a problem? Please describe.**
Procedural structures have spawning conditions. These spawning conditions do not seem to be taking carving into account, however.

**Describe the solution you'd like**
A (toggleable) option to have terrain conditions account for carving.

**Describe alternatives you've considered**
Have vacuum take effect after carving, which would be a suitable option as well.

**Additional context**
![image](https://user-images.githubusercontent.com/65736624/104927489-c8e52800-59a1-11eb-8e63-d34222b1cb80.png)

**Comment by NextdoorPsycho** [comment]
This is what happens when a carve happens on terrain, objects cant see this o its not going to do anything, we would need a system to see it, which is low priority

**Comment by svdgoor** [comment]
Doable with 1.6.0 expressions with one of the variables
