### ISSUE TITLE
Pregen, issue to find world

### ISSUE THREAD

**Issue by maol03** [VolmitSoftware/Iris#570]
### Problem

I'm trying to pregenerate the world, both with the new and old system. I'm getting different errors, when trying to use the command and while typing the command.

https://gyazo.com/eed6b6a48c89cffbdc33848500560703

https://gyazo.com/36d7b1515cc894b495d3986a7a69e81f

### Minecraft Version

1.17.x

### Iris Version

1.7.5

### Log

https://mclo.gs/4Dje4RB

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [x] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by maol03** [comment]
It seems that the second error happened because I already had pregenerated the world once, but with a smaller radius. Should it not be possible to pregenerate it again in the future after doing it once?

The error with /ird pregen always occurs though.

**Comment by cyberpwnn** [comment]
You are using /irisd which is a debug (experimental) command tree. Use /iris.

**Comment by maol03** [comment]
The last error in the console log is still an issue though.
