### ISSUE TITLE
Iris structure Generation failure

### ISSUE THREAD

**Issue by TheHappyHopper** [VolmitSoftware/Iris#571]
Iris version 1.7.4
Pregen headless
![2021-08-20_21 38 56](https://user-images.githubusercontent.com/66880702/130310872-0c022eba-df25-41fe-a877-f4430cda766d.png)

**Comment by ghost** [comment]
This has been fixed with 1.7.7 and couldnt reproduce it on that version so this can be closed @CocoTheOwner
