### ISSUE TITLE
Slabs where slabs shouldn't be

### ISSUE THREAD

**Issue by TheHappyHopper** [VolmitSoftware/Iris#572]
Iris version 1.7.5
No pregen
![2021-08-20_22 30 18](https://user-images.githubusercontent.com/66880702/130311664-dc0b50af-bc1b-49c8-b9ae-2b5d1220235a.png)
![2021-08-20_22 30 25](https://user-images.githubusercontent.com/66880702/130311668-a80c3e24-e0de-4c10-9d28-4512584ce712.png)
![2021-08-20_22 30 02](https://user-images.githubusercontent.com/66880702/130311670-d3e73b8d-5de5-4d24-a34e-91a27f244d93.png)

**Comment by cyberpwnn** [comment]
Post processor seems to be not doing it's job

**Comment by ghost** [comment]
Tested it and havent seen it in 1.7.7 therefore this can be closed @CocoTheOwner
