### ISSUE TITLE
Floating Items During Generation

### ISSUE THREAD

**Issue by Skizzles** [VolmitSoftware/Iris#573]
### Problem

1. Install Iris...
2. Download Overworld
3. Create new world
4. Located generation examples

![WAdERIqI07](https://user-images.githubusercontent.com/30563757/130351326-1857c02f-c7c6-442b-ba98-c5fb28ac61ac.png)
![xUjIyOni91](https://user-images.githubusercontent.com/30563757/130351328-14ca8465-dd20-4cb8-842c-ac825909440f.png)
![image](https://user-images.githubusercontent.com/30563757/130351331-043b8ccc-b753-4a45-b690-a6d51d6ad8d9.png)

### Solution

I believe these should not generate as floating items.

### Minecraft Version

1.17.x

### Iris Version

1.7.7

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
Decorator problem, this will nor be fixed until we rewrite the system (soon:tm:)
CLosing for now as its a fart of the future roadmap
