### ISSUE TITLE
Iris color gradient issue in the logs & in-game

### ISSUE THREAD

**Issue by Coffe2Go** [VolmitSoftware/Iris#576]
### Problem

1. Install Iris...
2. Open the console/logs
3. Wait for the logs to appear and look like shit and uncolored
4. Observe the error... and hope there is a fix for it
[latest.log](https://github.com/VolmitSoftware/Iris/files/7034094/latest.log)

### Solution

no solution. unless dan somehow manages to fix minimessages to support all the languages.

### Minecraft Version

1.17.x

### Iris Version

1.7.8

### Log

https://mclo.gs/SXZFwqX

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by svdgoor** [comment]
V+ your OS
