### ISSUE TITLE
Re-add undercarriage please

### ISSUE THREAD

**Issue by MaxLoadedGod** [VolmitSoftware/Iris#577]
### Adding, Removing, or Changing

Adding

### Type of Modification

Re-add undercarriage

### What are you trying to modify

Please re-add undercarriage it allowed me to make a completely void end world with asteroids but now I can't do it anymore I've been working on space stations similar to skyblock but without the void I can't use this.

**Comment by cyberpwnn** [comment]
A new carving solution will be added that covers this. The undercarriage was for multi-dimensional stacks and that's why it was removed.

**Comment by ghost** [comment]
https://github.com/cocotheowner/empty @CocoTheOwner ?

**Comment by svdgoor** [comment]
This is easily solvable now. See link above from Nowhere.
