### ISSUE TITLE
Iris Issue

### ISSUE THREAD

**Issue by EiderFC** [VolmitSoftware/Iris#578]
### Problem

I have done /iris pregen and I have closed the server but I get this:
"Still waiting to shutdown burster..."
I use 1.17.1 and Iris 1.7.9

### Minecraft Version

1.17.x

### Iris Version

Iris 1.7.9

### Log

https://mclo.gs/WZm3Afm

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ghost** [comment]
You should not stop the server while doing a pregen. You need to stop the pregen first with /iris pregen stop and than shutdown the server. If you follow this and still face this issue please reopen this.
