### ISSUE TITLE
Jigsaw placement off with decoration

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#58]
**Describe the bug**
Jigsaw placement is off/vacuum isn’t working like it should when decoration is generated under the structure so the structure is 1 block floating.

**To Reproduce**
1. Create a world with iris and join it
2. fly around and search for jigsaw structures 
3. See off placement

**Expected behavior**
Generate terrain under the structures so it won’t fly above the ground

**Screenshots or Video Recordings**
https://discord.com/channels/189665083817852928/767020043527389245/799612054394503199 and following screenshots in the discord conversation

**Server and Plugin Informations**
 - Installed plugins: Iris
 - Iris Version: 1.3.1
 - Server Platform and Version [eg: PaperSpigot 1.16.3 VolmitSoftware/Iris#240]: 428
 - Operating System (if applicable): Windows 10

**Comment by svdgoor** [comment]
(Stilt actually works, I was just blind, should be achievable. `"backupMode": "STILT"` or something like that would be useful
