### ISSUE TITLE
Add /iris goto or /iris tp to teleport to biomes, structures and / or objects

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#58]
Just like vanilla minecraft's /locatebiome allows you to to find biomes, a command for Iris which would do the same thing would be very useful for testing.
A set of /iris locate biome, /iris locate structure and /iris locate object would be best IMO, to prevent having issues with overlapping names.
If the command completion suggestions could then include the names of the biomes, structures and objects respectively it would be perfect. If that is not possible, adding /iris list biome, /iris list structure and /iris list object would be an acceptable replacement.

**Comment by svdgoor** [comment]
Addition to suggestion: Add an API for this to allow users to have it interact with other plugins, mods, etc.
Addition to suggestion (2): Add toggle for the action bar to show the name of the biome as you navigate into it.
Suggestion 2 can be achieved with suggestion 1 and placeHolderAPI quite easily, but I think adding both would be nice

**Comment by cyberpwnn** [comment]
This will be possible in V2

**Comment by svdgoor** [comment]
Possible in V2
