### ISSUE TITLE
Strongholds generating at 0, 0

### ISSUE THREAD

**Issue by themadseventeen** [VolmitSoftware/Iris#584]
### Problem

https://imgur.com/a/oZD6Duj

1. Create a world with the overworld pack (I used multiverse but I don't think it matters)
2. Go to 0, 0
3. You will find a stronghold portal 

### Minecraft Version

1.17.x

### Iris Version

1.7.11

### Log

https://pastebin.com/ZJDhY8hh

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ghost** [comment]
This is fixed
