### ISSUE TITLE
Floating Tall Grass

### ISSUE THREAD

**Issue by Skizzles** [VolmitSoftware/Iris#586]
### Problem

Install Iris...
Download Overworld
Create new world
Located generation examples
![ciCaButA27](https://user-images.githubusercontent.com/30563757/131665071-90b2b18a-fab8-4ab8-a573-33fd2093b0ea.png)

### Solution

Seems it might just need further tuning?

### Minecraft Version

1.17.x

### Iris Version

1.8

### Log

https://mclo.gs/GAG5ujb

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ghost** [comment]
Can confirm this also happens with objects (trees)
