### ISSUE TITLE
Iris metrics

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#589]
### Problem

1. Use /iris metrics
2. See the logs

### Solution

Solve it

### Minecraft Version

1.17.x

### Iris Version

1.8

### Log

https://mclo.gs/dVdYrlX

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by cyberpwnn** [comment]
We're removing metrics for now, new system will come in the future more like a timings system.
