### ISSUE TITLE
placeholders

### ISSUE THREAD

**Issue by RaydenKonig** [VolmitSoftware/Iris#59]
I think it would be great to implement IRIS placeholders
that give information such as the name of the biome in which the user is, or region
etc
I do not see it very difficult to implement since that same information is in the editor mode marker

I for example want this implementation to be able to detect when a user enters a biome for the first time to give him an achievement and execute commands with a plugin

but i need the placeholders

**Comment by svdgoor** [comment]
Soon this is going to be very easy to do by means of datapacks. That solution is all more elegant and more robust and more safe (stable) than by an API, most likely.

**Comment by ghost** [comment]
Added with https://github.com/VolmitSoftware/Iris/commit/e1e0368f8cc6218b0fd27c5d2eb4ea4b16d2111e
