### ISSUE TITLE
Iris Generated overworld is having broken regions again on the 1.8.2 via creating new world with bukkit.yml

### ISSUE THREAD

**Issue by Coffe2Go** [VolmitSoftware/Iris#594]
### Problem

1. Install Iris...
2. Configure & Run iris via bukkit.yml configuration
3. Join server and explore the biomes and wait for the crash
4. Observe the error...

![image](https://user-images.githubusercontent.com/70270225/131913150-996e1c69-847c-4fc5-80ae-674d05e16d3c.png)
![image](https://user-images.githubusercontent.com/70270225/131913173-b551bbb6-d539-469c-be1b-bd5a23e63c16.png)

### Solution

Well, here i am again sent here by coco, hopefully i wont get trashed here and given a response such as. 

"well coffee as you may know, compiled iris from our github is not necessarily stable as the one on the spigot, therefor you will have to deal with it"  cause i am aware of that but this did not happen back on 1.8.0 version with compiled from github and master, pretty sure this is a recent issue again cause i never had a crash or thread issue where it also corrupts my chest loot around the map until iris hot-loads or something.

Also yes the issue is with compiled version of iris. 

### Minecraft Version

1.17.x

### Iris Version

1.8.2

### Log

https://mclo.gs/H3Steya

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](https://discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](https://discord.gg/volmit))

**Comment by cyberpwnn** [comment]
This was fixed on 1.8.2. You are not on 1.8.2, If you built the jar yourself, next time provide the commit hash you built it on. Also, just to be sure i flew all the way to -2,827, 2,570 and still running perfectly.
