### ISSUE TITLE
Vaccum not working as intended?

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#595]
### Problem

See Screenshot
![2021-09-03_17 08 28](https://user-images.githubusercontent.com/5337873/132027627-d2119449-e114-44be-ae99-256d3e40b6f0.png)

### Solution

Fix if thats on the plugin or a misconfiguration on the pack

### Minecraft Version

1.17.x

### Iris Version

1.8.2

### Log

No logs needed

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](https://discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](https://discord.gg/volmit))

**Comment by cyberpwnn** [comment]
When you tell it to vacuum, sometimes if there is too many objects right next to each other it can cause some of them to float / be slightly underground due to nearby vacuum influences.

**Comment by svdgoor** [comment]
Can we use STILT as a fallback in case one of the 2 vacuums isn't working?
