### ISSUE TITLE
Iris 1.8.3 all ores deepslate

### ISSUE THREAD

**Issue by cades66** [VolmitSoftware/Iris#596]
### Problem

1. Install Iris
2. Make a world
3. Deepslate ores everywhere
![image](https://user-images.githubusercontent.com/57970060/132039707-5134cf46-5c77-4031-b9c5-5c40224cb373.png)

### Solution

Fix the deepslate math? idk lol

### Minecraft Version

1.17.x

### Iris Version

1.8.3

### Log

No log

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](https://discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](https://discord.gg/volmit))

**Comment by cyberpwnn** [comment]
Fixed in 1.8.5
