### ISSUE TITLE
Pointed Dripstone not properly waterlogging

### ISSUE THREAD

**Issue by Kurenox** [VolmitSoftware/Iris#597]
![2021-09-03_11 55 16](https://user-images.githubusercontent.com/86927490/132053747-ec231fdf-f82c-4f70-9b5b-84301128dd72.png)

**Comment by svdgoor** [comment]
Could you please fly right up to them to see if that updates their states + check this on the latest version?
Afaik this has been tweaked and fixed. If you find it still happens, leave a comment and we'll reopen.
