### ISSUE TITLE
Cactus breakage causing lag

### ISSUE THREAD

**Issue by Kurenox** [VolmitSoftware/Iris#598]
Lots of underwater cactuses are breaking and spawning large amounts of item entities.
![2021-09-03_11 48 41](https://user-images.githubusercontent.com/86927490/132053871-9241327e-1018-49f1-81b8-4dcf0d06c2b2.png)

**Comment by StrangeOne101** [comment]
Possible solution: Deny decorators in water caves if the decor block cannot be waterlogged.

Perhaps we should even make water caves have their own decor...? (Water grass, kelp, etc?)

**Comment by ghost** [comment]
This is a overworld pack configuration so i close this (already made a feature request there for removing cactus from cave decoration)
