### ISSUE TITLE
Iris studio breaks on remote servers

### ISSUE THREAD

**Issue by Frerduro** [VolmitSoftware/Iris#6]
When you try to use iris studio on a remote server it errors out. https://pastebin.com/ac8V0n6X

**Comment by NextdoorPsycho** [comment]
Iris studio is intended to be used locally, but should not do this.

**Comment by cyberpwnn** [comment]
I need more information on what you are doing exactly.

**Comment by cyberpwnn** [comment]
It should work fine... It looks like iris tried to close a previous project and failed to do so. Try updating, and restarting your remote server. Then use

/iris std create <newname> template=overworld

Then copy the files from the packs folder under <newname> to your system, and double click on the code-workspace file in the root of that folder. Make your edits and upload them.

My only concern is iris might hotload before your transfers complete. You should probably turn off hotloading in the settings. Ill make a manual hotload command for this use case

**Comment by Frerduro** [comment]
Ok so with a world loaded in bukkit.yml the plugin fires that error I gave before but If I remove it from bukkit.yml iris studio works fine again.

**Comment by svdgoor** [comment]
Seems resolved to me. Correct me if I'm wrong.
