### ISSUE TITLE
Ravine system

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#60]
**Is your feature request related to a problem? Please describe.**
Bleh vanilla ravines

**Describe the solution you'd like**
A system like the cave layers to create ravines in Iris worlds.

**Describe alternatives you've considered**
Screwing with caves or carving such that this is achieved, but that seems rather painful and slow

**Additional context**
Was discussed before but kinda forgotten about since Jigsaw stuff...

**Comment by NextdoorPsycho** [comment]
dooable in overworld using carving layers. dm me if you wanna see how
