### ISSUE TITLE
Incompatibility between Saber Factions v1.6.9.5-2.9.3-RC and Iris

### ISSUE THREAD

**Issue by winstonvanderpol** [VolmitSoftware/Iris#600]
### Problem

1. Starting Server on Linux Environment
2. Connecting to Server
3. Server Slow
4. Receiving Errors in Logs

### Minecraft Version

1.17.x

### Iris Version

1.8

### Log

https://mclo.gs/e2aCkYL

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](https://discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](https://discord.gg/volmit))

**Comment by svdgoor** [comment]
> Server Slow

The reason the server is slow is that you are pregenerating a world
The incompatibility does not add (a lot) to performance cost.

**Comment by winstonvanderpol** [comment]
Eventually removed Ultimate Timber, which increased the speed. The speed with Saber Factions is fine right now, still the same errors, however, the performance is fine and the plugin seems to work together.

**Comment by svdgoor** [comment]
ok?
