### ISSUE TITLE
Part of the dungeon generte in water

### ISSUE THREAD

**Issue by YKDZ** [VolmitSoftware/Iris#601]
### Problem

1. Install Iris...
2. use https://github.com/IrisDimensions/overworld to create overworld
3. fly to find this dungeon 
![2021-09-04_13 39 47](https://user-images.githubusercontent.com/69898831/132084080-660932cc-7298-4236-830c-ab4372d2d4be.png)
![2021-09-04_13 39 38](https://user-images.githubusercontent.com/69898831/132084084-59fbae26-2733-404a-80dc-0fad6e1f3fae.png)

### Minecraft Version

1.17.x

### Iris Version

1.8.3

### Log

https://mclo.gs/GUJTGWa

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](https://discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](https://discord.gg/volmit))

**Comment by ghost** [comment]
@NextdoorPsycho

**Comment by svdgoor** [comment]
this isn't fixable since jigsaw pieces don't have height stream conditionals.
This only happens very rarely + it happens in vanilla too
