### ISSUE TITLE
Holes & Vacuum Issues

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#603]
### Problem

1. Holes generate in terrain
2. Vacuum is failing far too much

Mentioning vacuum because the tower here is placed via vacuum, and another clutter object with vacuum also is fully buried in the ground.

![2021-09-04_21 37 53](https://user-images.githubusercontent.com/2769013/132090048-adc29d00-fbc8-417d-b6e3-2d127b64df95.png)
![2021-09-04_21 38 25](https://user-images.githubusercontent.com/2769013/132090052-9e88eaba-05cf-4352-b0d9-ac1615a313e5.png)

### Minecraft Version

1.17.x

### Iris Version

`.8.3

### Log

.

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](https://discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](https://discord.gg/volmit))

**Comment by svdgoor** [comment]
Fixed because we removed vacuum easy clap
