### ISSUE TITLE
Iris doesn't register created worlds to multiverse

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#604]
### Problem

Created worlds via iris are not registered to multiverse and are therefore not loaded on server restart

1. /iris create testworld type=overworld
2. Restart Server
3. /mv list
4. See that `testworld` isn't on the list

### Minecraft Version

1.17.x

### Iris Version

1.8.3

### Log

.

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](https://discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](https://discord.gg/volmit))

**Comment by cyberpwnn** [comment]
You need to use /mv import. This is intended. We're actually removing the iris create command soon.

**Comment by StrangeOne101** [comment]
> You need to use /mv import. This is intended. We're actually removing the iris create command soon.

News to be, but okay. Considering the create command used to use multiverse to create worlds if it was installed, I considered this a bug. If it's getting removed, that's fine. Although I still think having it is better than not having it, personally
