### ISSUE TITLE
Chunk borders after restarting

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#605]
### Problem

When restarting a server with a world that automatically loads, chunk borders will show on new generated chunks. The chunks are SIMILAR to the original chunks. This is possibly seed drift, but the internal seed of the world is unchanged (verified with /seed)

1. `/iris create testworld type=overworld`
2. Restart Server
3. If #604 is still unfixed, use `/mv import testworld normal -g Iris:overworld` AND restart AGAIN
4. Generate some new chunks

Screenshots
![2021-09-04_21 56 58](https://user-images.githubusercontent.com/2769013/132090578-5153e462-84df-42bc-aae4-677b1bca08f4.png)
![2021-09-04_21 58 53](https://user-images.githubusercontent.com/2769013/132090579-44dbbaa8-cf5c-4ac5-be02-f923061c9422.png)
![2021-09-04_22 01 06](https://user-images.githubusercontent.com/2769013/132090587-9709adbb-3d74-4783-ac24-7c8aab233599.png)

### Solution

Hard work

### Minecraft Version

1.17.x

### Iris Version

1.8.3

### Log

.

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](https://discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](https://discord.gg/volmit))

**Comment by cyberpwnn** [comment]
Could it be noise features duplicating / not placing before but placing after?? hmm need to test
