### ISSUE TITLE
Cave Worm generates walls on decorations

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#606]
### Problem

Worms that generate caves still generate parts of a cave on top of decorators, when they shouldn't as there is no actual cave there

See screenshot
![2021-09-04_22 03 18](https://user-images.githubusercontent.com/2769013/132090704-f3fa84d4-2f62-4cec-ad22-41ea533ee76e.png)

### Minecraft Version

1.17.x

### Iris Version

1.8.3

### Log

.

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](https://discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](https://discord.gg/volmit))

**Comment by ghost** [comment]
Duplicate of #590 or isnt it fixed?
