### ISSUE TITLE
Biome division by river (future)

### ISSUE THREAD

**Issue by RaydenKonig** [VolmitSoftware/Iris#61]
**Is your feature request related to a problem? Please describe.**
In the current generation of irises, the biomes changes more when they are between regions such as "hot" and "temperate", not to mention "hot" and "frozen" are too abrupt and tend to be very ugly

**Describe the solution you would like**
When the rivers are implemented, be able to separate the regions with the rivers
in this way, the change will look smoother and more beautiful

This is something that other add-ons or the minecraft generation itself uses and I think it would be very good

**Describe the alternatives you have considered**

**Additional context**
example
![2021-01-21_23 31 41](https://user-images.githubusercontent.com/71474946/105451523-75056800-5c5b-11eb-92fa-afae191558b5.png)

in iris 
![2021-01-21_20 00 47](https://user-images.githubusercontent.com/71474946/105451574-88b0ce80-5c5b-11eb-91f1-9b43fc2aaaea.png)

**Comment by NextdoorPsycho** [comment]
you can do this in the overworld easilly, (well not easy) but have the regionstyle, or biomestyle (or biome child style etc...) to vascular, and set that to a biome thats in this case "river" and crank the height (you can also use cellular, fractured by vasscular)
