### ISSUE TITLE
Server don't start

### ISSUE THREAD

**Issue by EiderFC** [VolmitSoftware/Iris#612]
### Problem

since I installed the new version of iris, the server does not start, it freezes

### Minecraft Version

1.17.x

### Iris Version

1.8.4

### Log

https://bin.bloom.host/umanuwobeh

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](https://discord.gg/volmit))
- [x] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](https://discord.gg/volmit))

**Comment by EiderFC** [comment]
https://pasteboard.co/KjfO6wy.png

**Comment by cyberpwnn** [comment]
It might be generating, could you turn on debug please? (settings.json in iris folder)

**Comment by EiderFC** [comment]
> It might be generating, could you turn on debug please? (settings.json in iris folder)

https://mclo.gs/l8T4k6v

**Comment by EiderFC** [comment]
How can i solve it?

**Comment by StrangeOne101** [comment]
Can you please confirm that it is Iris? If you uninstall Iris, does your server boot? I ask because you have dimensions loading at that exact time that don't seem to be handled by Iris

**Comment by EiderFC** [comment]
Yes, if I remove iris the server works and starts fine

**Comment by svdgoor** [comment]
Please try to:
- Delete any world folder that Iris made a world in /is going to delete a world in (including the `world` folder)
- Delete any mention of Iris generating worlds in your `bukkit.yml` (if you use this) or in multiverse (if you use that, delete the `multiverse` folder in the config folder)
- Delete the Iris folder in `*/plugins`
- Start the server and see if it launches
- Follow the tutorial [here](https://docs.volmit.com/iris/getting-started)

If you run into any issues with that, please send a message here.
Make sure to include your **full** log files here.
