### ISSUE TITLE
Pregen Memory Leak & Crash

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#614]
### Problem

Pregen seems to have a memory leak, because it is using waaaay too much RAM. 10-20GB is not enough, and OutOfMemoryErrors happen

### Minecraft Version

1.17.1

### Iris Version

1.8.5

### Log

https://mclo.gs/41ZIPtG

**Comment by svdgoor** [comment]
We'll need a JProfiler to run on this or a spark log for this
Logs don't give any details on ram usage apart from the errors themselves.

**Comment by svdgoor** [comment]
OK 3 people have tried, on 4+ machines, with 3+ server software types, and none could reproduce it.
Please use JProfiler and show us what's happening exactly.
