### ISSUE TITLE
Error downloading overworld

### ISSUE THREAD

**Issue by BingYanchi** [VolmitSoftware/Iris#615]
### Problem

1. Download overworld error

### Solution

![unknown](https://user-images.githubusercontent.com/36477925/132483970-ae2f86c2-5f40-4615-8cd0-7ef7b04fe23d.png)

### Minecraft Version

1.17.1

### Iris Version

1.8.6

### Log

https://mclo.gs/AOR0pFk

**Comment by svdgoor** [comment]
I cannot reproduce this issue.
For me, the command immediately resolves the right JSON listing (which is downloaded, but should be available in the Jar as well, in case it fails).
Can you try again on the latest version after deleting other stuff in the packs folder?
(Closing pending answer. If it's fixed, I won't reopen)
