### ISSUE TITLE
Chests a biome away from spawn or further are all entirely empty

### ISSUE THREAD

**Issue by Pumamori** [VolmitSoftware/Iris#617]
### Problem

1. Installed Iris 1.8.5.
2. Pre-generated world. Out of memory happened once, I upgraded the server after. No IP or file changes.
3. Finished pre-generating with more RAM. Initial one was around ~10k to 20k out of 260k, this time the rest.
4. Updated to Iris 1.8.6.
5. Found some chests around spawn with loot, but anywhere else was completely empty.
6. Updated to Iris 1.8.7.

### Minecraft Version

1.17.1

### Iris Version

1.8.7.

### Log

https://mcpaste.io/26a43412dcadd6c8

**Comment by svdgoor** [comment]
Deleting the world fixes this
The reason this is happening is because the Mantle updated, and all your mantle data became invalid
Rip
