### ISSUE TITLE
Add surface ores to stone hill biome

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#62]
![afbeelding](https://user-images.githubusercontent.com/65736624/96464750-7d976e00-1228-11eb-8512-8880edc089ba.png)

**Comment by NextdoorPsycho** [comment]
This became a bug report. 
https://i.imgur.com/k4Dbjx0.png
The surface cant have deposits.
https://i.imgur.com/RH6Sst7.png
Lava represents Coal deposits:


"deposits": [
        {
            "maxHeight": 100,
            "maxPerChunk": 3,
            "maxSize": 5,
            "minHeight": 60,
            "minPerChunk": 1,
            "minSize": 1,
            "varience": 3,
            "palette": [
                {
                    "block": "coal_ore"
                }
            ]

        }
    ],

**Comment by svdgoor** [comment]
Idea is that one can also make it such that ores can spawn on the surface

**Comment by svdgoor** [comment]
Can be done alreaedy with child biomes with different surface blocks. Not required.
