### ISSUE TITLE
Region Placement Restrictions & Rules

### ISSUE THREAD

**Issue by hellot1m** [VolmitSoftware/Iris#62]
**Is your feature request related to a problem? Please describe.**
 - No problem at all. Btw just to warn you. I suck at explaining things. So hopefully you understand and let me know if you want more info. Also obviously my method of creating regions may be really sloppy and bad for performance but I'm sure you smart people can find a way to do this efficiently :)

**Describe the solution you'd like**
 - would love to have the option to group biomes in regions. This can created by the user. When regions are made by adding biome names under region names, iris will generate the world based on region groups instead of random biome placements. As an additional option, a way to add in which region types they can generate next to and which regions they can not generate next to. 
Ex would be creating a region with all cold type biomes and then adding in the exempt region neighbor being the desert region. This way desert regions are free to generate next to any type of biome or user created region except for the special region created by the user. 

**Additional context**
 - the purpose for me is so that I can build several regions with about 2-4 different biomes each. And then block ALL regions from connecting to each other except for an ocean regions. 

**Example config layout**
Each config or json file can be it's own specific region with it's own set of restriction rules. With the first line being the region name followed by every biome in the overworld folder to be grouped in that region. The next set of lines after this can be set rules, like in my example, other regions this region is not allowed to generate next to. In this example, I added all regions I created but left out "oceans" which means that anytime troll kingdom is generated in my world, it would be forced to generate only ocean biomes/regions on all sides. Giving the sense of it being a island or continent.
```
troll kingdom:
 - hot-beach
 - hot-desert-hills
 - hot-mesa-cliffs

Restricted region neighbors
 - pineapple country
 - sam's world
 - that's what she said
```

**Comment by StrangeOne101** [comment]
This could be done by implementing a sub-region feature to regions. This would allow more control over biome placement while not requiring a complete rework of the current system.

Example: You could have, say, 4 main regions (for the overworld pack). Inside of the `hot` region, you could have `mesa`, `desert`, `savanna` subregions. Which would mean that hot biomes from different (existing) regions are more likely to be grouped next to each other. 

That's just an example; the final implementation using subregions could be done in any way for the overworld pack.

**Comment by svdgoor** [comment]
All proposed solutions apart from OP are just decreasing the chance of it happening, rather than actually fixing it, so I'd go for the OP's solution.

**Comment by NextdoorPsycho** [comment]
You can do this with a biome map, have a region of only 1 biome:
In that Biome have children (ill use your example)
Region troll kingdom:
- Main Biome:
    insert generic landbiome here (only one biome)
    generic land Children: (have children to represent the actual biomes)
        Mountain 
        Forest
        
        
All of this can be set using Region zoom, Biome zoom, ChildBiome Size/Style/Zoom with a custom generator to work i can give you an example if you want, just message me on discord, but as far as i know this is possible:
![Kqtcxb7](https://user-images.githubusercontent.com/29320316/127805497-f56c1992-9fc5-49f4-a6bc-a9be629554a1.png)
Because in each region you can share the same generic land biome used, and in sub regions(biome with children) you can have whatever you want
