### ISSUE TITLE
Unknown block data issue - blocks do not show up in world - blocks that are not able to be loaded change every time the server is started

### ISSUE THREAD

**Issue by CryptoXB** [VolmitSoftware/Iris#625]
### Problem

1. Install Iris...
2. Create world using iris
3. Observe error - `Unknown Block Data 'minecraft:insert_block'`

### Minecraft Version

1.17.1

### Iris Version

1.8.8

### Log

https://pastebin.com/br0BA3c8

**Comment by ghost** [comment]
Still present with Iris 1.9

**Comment by svdgoor** [comment]
https://cdn.discordapp.com/attachments/768582615078010910/902962179446304878/message.txt
Log given by a user that contains a stacktrace & missing blockdata entry. I think they are likely connected.
If they're not, lmk, and I'll make a new issue.

**Comment by svdgoor** [comment]
Likely related to: https://github.com/PaperMC/Paper/pull/6876
Which shows an issue with Paper's way of handling blockdata.

**Comment by PierreSchwang** [comment]
I guess a seperate issue would be better. The error provided by the user does not throw a ConcurrentModificationException and is rather a different issue.

**Comment by svdgoor** [comment]
Yeah think so too. Thanks for taking the time to look into this man! Much appreciated :)

**Comment by NextdoorPsycho** [comment]
Fixed update
