### ISSUE TITLE
Suggestion: Complete villages in mushroom biomes

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#63]
![afbeelding](https://user-images.githubusercontent.com/65736624/96464872-a15ab400-1228-11eb-8917-aa3abbe9597f.png)

**Comment by svdgoor** [comment]
They also seem to not contain any villagers

**Comment by NextdoorPsycho** [comment]
unfortunate placing, ill change it

**Comment by NextdoorPsycho** [comment]
Tweaked
