### ISSUE TITLE
Overwrite all genereation with MCA

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#63]
**Is your feature request related to a problem? Please describe.**
Sometimes the pregeneration refuses to use MCA generation because 1 or 2 chunks in a region have been generated. What I propose is a setting you enter when running the command originally to overwrite every existing region file.

**Describe the solution you'd like**
A command parameter like -o to Overwrite all existing data in MCA region files when pregenerating, effectively making DirectMCA the main pregenerator instead of slow paperasync

**Describe alternatives you've considered**
Waiting for the pregen to finish like a loser

**Comment by NextdoorPsycho** [comment]
Not going to add, already happens

**Comment by ghost** [comment]
> Not going to add, already happens

It already is working like that with the current version of Iris. So its more like already implemented.
