### ISSUE TITLE
@Required tag on fields in IObjects (anything configurable) no longer appear in VSCode

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#631]
### Problem

1. Install Iris...
2. /ir dl overworld
3. /ir s vscode (may need to run twice)
4. Remove everything from dimension file
5. Observe absence of yellow curly line indication there's a problem
![image](https://user-images.githubusercontent.com/65736624/132942210-5deb03be-ea3b-423f-8e56-904e743f0a19.png)

### Solution

Recently we switched to snippets or schema (whatever)
I think that those are either unable to include required tags or the translation to them didn't work quite as well as we wished for

### Minecraft Version

1.17.1

### Iris Version

1.8.9 (https://github.com/VolmitSoftware/Iris/pull/628)

### Log

Not important

**Comment by svdgoor** [comment]
![image](https://user-images.githubusercontent.com/65736624/132943110-02561780-85d5-4f33-a8ff-b1fc2a5a54ba.png)

Invalid entries are marked tho

**Comment by cyberpwnn** [comment]
The value can either be an object or a string, that's why. Required values have defaults, it's more of a soft required. Im leaning towards a wontfix here because its not causing any issues, i think the ws just needs to update

**Comment by svdgoor** [comment]
I am now in the empty.code-workspace for my empty project.
I emptied out the dimension's configuration file completely, and it is not showing any issue (i.e. it's "valid"), but it wont run at all
![afbeelding](https://user-images.githubusercontent.com/65736624/133989012-1e2c969f-f8c3-454f-a333-c514f122fc01.png)

We should imo readd this to prevent people from creating specific objects that require some settings, without actually specifying those settings.

**Comment by svdgoor** [comment]
If we can define default settings for every available setting this would not be a problem.

**Comment by svdgoor** [comment]
I now understand what you mean by "can either be an object or a string", snippets.
Is there not a way to add a check for if a setting is specified, regardless of what type of value it is assigned?

**Comment by NextdoorPsycho** [comment]
imma just, close this.
