### ISSUE TITLE
All leaves are set to persistent

### ISSUE THREAD

**Issue by Esronn** [VolmitSoftware/Iris#637]
### Problem

Setting preventleafdecay to false in the dimensions file does not make leaves non-persistent.

![image](https://user-images.githubusercontent.com/69452994/132994377-4a7ecb32-0faf-4754-922d-75a942e53a14.png)

### Minecraft Version

1.17.1

### Iris Version

1.8.8

### Log

https://mclo.gs/KB0LQPc

**Comment by StrangeOne101** [comment]
The option in the settings file just enforces that leaves are always persistent. If a leave block is set to persistent when the object is saved, it will still be persistent when the object is placed. But some trees do not have persistence, and the setting here just forces them to be persistent.

**Comment by svdgoor** [comment]
That's not true, search for "instanceof Leaves" or ".setPersistent(false)" in Iris source
It's set to false if the persistency setting is on "false" as well

**Comment by Esronn** [comment]
> That's not true, search for "instanceof Leaves" or ".setPersistent(false)" in Iris source
> It's set to false if the persistency setting is on "false" as well

In which config is this? I created this bug report because NextdoorPsycho asked me to.

**Comment by svdgoor** [comment]
This is not in the config. This code is on the object placer (internally in the Iris.jar file)

**Comment by svdgoor** [comment]
I asked btw :)

**Comment by cyberpwnn** [comment]
There is a plugin level settings.json option under `generator`. Set `"preventLeafDecay": false`. This option overrides what the dimension specifies (this is due to some worlds causing massive performance issues with large trees)
