### ISSUE TITLE
Feature: Support for Loot Tables on Iris Objects

### ISSUE THREAD

**Issue by TheDevelon** [VolmitSoftware/Iris#64]
**Is your feature request related to a problem? Please describe.**
I need to create loot tables for objects only, so that as an example, a trap in one of my objects can be filled with TNT. But I wont create a global loot table in the biome or region for that.

**Describe the solution you'd like**
Add a option to the object configuration section, like this:

loot: { tables: "ex1","ex2"}

So users are able to apply loot tables on iris objects only, instead of the biome/region option.

Thanks!

**Comment by ghost** [comment]
@CocoTheOwner can be closed due to how we defined objects and jigsaw structures

**Comment by StrangeOne101** [comment]
This has been implemented in Iris 1.4.3 and above
