### ISSUE TITLE
Atomic Cache Failure

### ISSUE THREAD

**Issue by peonii** [VolmitSoftware/Iris#640]
### Problem

1. Install Iris

### Minecraft Version

1.17.1

### Iris Version

1.8.10

### Log

https://pastebin.com/g53E4dGx

**Comment by cyberpwnn** [comment]
I need some extra information. Looks like iris cant read any data, OR the engine is null somehow. Send any of the following if possible.

* If you can cause this 100% of the time, please provide EXPLICIT & EXACT reproduction steps.
* If possible, zip up the WORLD/iris/pack folder and send it here or discord it to cyberpwn#1337

**Comment by peonii** [comment]
ok, i'll try to do that tomorrow

**Comment by ghost** [comment]
@querterdesu any update?

**Comment by peonii** [comment]
oh hey sorry for not doing anything, yeah ima update everything rq

**Comment by peonii** [comment]
ok now i get a different error
essentially it can't find the pack "overworld"
but the pack "overworld" exists

log:
https://cdn.discordapp.com/attachments/682980706644656151/890627616120377374/latest.log

iris folder:
https://we.tl/t-hUZyj7zv22

instructions:
i just create a new purpur server, drop iris and i can't generate a world

**Comment by TheHappyHopper** [comment]
with some investigation i have found a consistent way to replicate this issue
-generate a new world with overworld (havent tested with other generators) and make sure it generates at least a little bit
-stop the server
-introduce a new plugin (some ones of note are movecraft, gsit, towny, essentials, placeholderapi, protocollib, etc)
-start the server
-stop the server
your console will now spit out atomic cache failure! with the error message

iris version: 1.8.13
purpur version: git-purpur-1394
os version: ubuntu 21.04

**Comment by DaMrZ** [comment]
I am having the same issue and have been asked to provide my servers files by CoCo for investigation
Just to note:
Minecraft Panel: AMP Panel
OS Version: Windows Server 2019
Minecraft Version: Paper

I can't upload my server files to github as it comes up with "is not included in the list" but here is a link to the server files
https://mega.nz/file/dA8jRKBa#Pg3eIFp4zdWlYhFM507a-j_ov2MJH7lgixq9SVW5DEI

**Comment by MineForce899** [comment]
It is because Windows doesn't allow to delete opened file. When studio opens, it opens notepad with current biome and doesn't allow to delete this file.
To stop issue you just need to close notepad

**Comment by CocoTheOwner** [comment]
What?

**Comment by exiollo** [comment]
PufferPanel
Windows 10
Antivirus off
No plugins except Iris
Paper 1.17.1
Iris 1.9
Atomic Cache Failure

**Comment by svdgoor** [comment]
@MineForce899 mind adding a log please?

**Comment by exiollo** [comment]
> @MineForce899 mind adding a log please?

https://drive.google.com/file/d/1PVIDyTYWhG6DHB4grnHJAZUOliUHRqBp/view?usp=drivesdk

**Comment by exiollo** [comment]
It may be because PufferPanel/Pterodactyl limitations
I don't know what limitations could be, but iris works fine on same machine but when I boot server without PufferPanel's help

But still needs testing, maybe it is core issue necause I used paper on puffer but used purpur on machine

**Comment by exiollo** [comment]
Found a way to fix it
Go to bukkit.yml and look at last line
If there is `generator: Iris` change it to `generator: Iris:overworld`
And there you go

**Comment by ghost** [comment]
`generator: Iris` is false and `generator: iris:overworld` is correct. We don‘t provide the first one on the wiki. Don‘t know where you guys get that wrong one from.

**Comment by ghost** [comment]
Haven’t seen this in a long time so I close this and it will be reopened if it occurs again
