### ISSUE TITLE
3D Iris Spawners

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#641]
### Adding, Removing, or Changing

Adding

### Type of Modification

Iris Spawners

### What are you trying to modify

Right now, Iris spawners only spawn in 2D. They spawn on the top level of the terrain around objects.

3D spawners need to be implemented for objects. That way, mobs can be spawned with objects underground.

**Comment by cyberpwnn** [comment]
Use markers. They have been out since 1.8.9

Some object placer
```json
{
    "place": ["a", "b", "c"],
    "markers": [
        {
            "mark": [{
                "block": "minecraft:cobblestone"
            },{
                "block": "minecraft:stone"
            }],
            "marker": "villager",
            "maximumMarkers": 3
        }
    ],
}
```

In markers/villager.json

```json
{
    "removeOnChange": true,
    "spawners": ["villager"],
    "exhaustionChance": 0.75
}
```

Then ingame, use `/iris what markers villager` to see them nearby. This is how we spawn villagers in village pieces now btw.

**Comment by StrangeOne101** [comment]
I've had a look at the marker system, but it is missing some critical things.

1. Spawning within a radius of the marker
2. Removing/transforming the marker block when the object is spawned.

Example: In an ocean temple, guardians need to spawn around and in the temple in a 3D radius. Having a marker at the center of the structure, and changing the material once the monument is placed would work good.
Elder Guardians can be spawned in different positions using other marker blocks placed around the temple. Which are then turned back into prismarine after the initial spawns of the guardians.

**Comment by svdgoor** [comment]
For guardians you can appoint air blocks to be markers
For elder guardians you can put shrines in the structure, with a unique block at the top, such as an ender rod, or similar

I agree with the suggestion btw, just some workarounds

**Comment by svdgoor** [comment]
I do think the Strange has two things that would be great additions to the Marker system, which is why I'll reopen the issue.
I'll see if I can do this myself... gives me a chance to closely look at the marker system as well :)

**Comment by svdgoor** [comment]
Seeing the convo on discord I made the wrong call.
