### ISSUE TITLE
Geode Removal

### ISSUE THREAD

**Issue by Kurenox** [VolmitSoftware/Iris#647]
Now that there are entire cave systems with amethyst, I feel like amethyst geodes are no longer necessary. They also have a tendency to spawn in weird places and intersect with caves and underground structures. Getting rid of them would solve that problem

**Comment by Ccode-lang** [comment]
This happens in vanilla to.

**Comment by ghost** [comment]
This is something regarding the pack and not the plugin https://github.com/IrisDimensions/overworld
