### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by RTCFlyer** [VolmitSoftware/Iris#648]
### Problem

Server Jar Version: Purpur-1391 Minecraft 1.17.1
Iris Version: 1.8.12 (latest)

Issue: 
Iris is causing significant memory usage in which leads to the server resulting in an OOM state.

The images attached have been taken from a heap dump generated via spark and viewed using JProfiler. 
![](https://i.rcart.cc/i/bOiq99Bi8tFD.png)
![](https://i.rcart.cc/i/6yXnJUKO0FiS.png)

### Minecraft Version

1.17.1

### Iris Version

1.8.12

### Log

N/A

**Comment by KaisAhmad** [comment]
I'm currently experiencing the same issue. We pregenerated the world to 10k blocks. (Currently generating to 15k so we can temporarily disable the iris plugin)

**Comment by Sheffybarbe** [comment]
I thought I was the only one that had this issue, but clearly not. Glad to see an issue opened.

**Comment by LiannOM** [comment]
same here

**Comment by ghost** [comment]
> I'm currently experiencing the same issue. We pregenerated the world to 10k blocks. (Currently generating to 15k so we can temporarily disable the iris plugin)

Dont disable/remove iris, you wont be able to recover to the original state.

**Comment by svdgoor** [comment]
Latest update allows you to configure the wrong-doer yourself. Quote:
```
* RECOMMENDED: Set
mantleKeepAliveSeconds to 20 seconds (if its set to 60). This will reduce memory usage if you are having problems
```
Make sure to update first, and let the settings load (so the new settings are added)

**Comment by NextdoorPsycho** [comment]
Dont Close issues like this, It was not fixed yet, it was an improvement, but the problem is still there from the people that made this issue /  others. 
It is STILL an issue

**Comment by LiannOM** [comment]
Thats true!

śr., 22 wrz 2021, 00:40 użytkownik Brian Fopiano ***@***.***>
napisał:

**Comment by svdgoor** [comment]
Have these people actually tried that setting?

**Comment by Sheffybarbe** [comment]
> Have these people actually tried that setting?

We have. Memory issues still persist. Don't get me wrong, it works better, but there is still something that is eating up memory.

**Comment by cyberpwnn** [comment]
I have significantly improved it (further) in 1.9, however its not using the new databits system because its not ready yet. Test 1.9 when it comes out and see if its good enough or if you need more keep this issue open (and show tests)

**Comment by cyberpwnn** [comment]
```
In both tests
- Pregenerate 6k by 6k (65,536 chunks)
- The mantle is not allowed to save or unload anything, it must keep everything in memory
- Mantle Regions Loaded after gen: 100

Iris 1.8.13
- Took: 7.2 Minutes
- Server Memory After GC: 11.13 ~111mb/mantle region
- Mantle Disk Space After Save: 183mb (of 315mb of region data)

Iris 1.9
- Took: 9.34 Minutes
- Server Memory After GC: 3.13gb ~31mb/mantle region
- Mantle Disk Space After Save: 65.5mb (of 315mb of region data)
```

Woop!
