### ISSUE TITLE
Bug: World not properly saving after restart

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#65]
Every time I restart, all generated chunks are deleted and changed blocks are also removed.
#Before
![2020-10-19_16 43 49](https://user-images.githubusercontent.com/65736624/96466809-81c48b00-122a-11eb-8b7e-b6713469a0ab.png)
#After
![afbeelding](https://user-images.githubusercontent.com/65736624/96466781-796c5000-122a-11eb-8c08-fa97de779a98.png)

**Comment by svdgoor** [comment]
Update: Restarting the server REMOVES the world folder that I created with /iris create <WorldName>

It is then readded after startup, completely wiped

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/96467211-f8fa1f00-122a-11eb-8cfb-ca5cc6e76fed.png)
I also get this error upon startup every time

**Comment by svdgoor** [comment]
I am also subsequently put back into the main overworld upon rejoining

**Comment by svdgoor** [comment]
Uninstalling the plugin after stopping the server and then starting fixes this

**Comment by svdgoor** [comment]
Update: WTF? this is only happening when the world is called "Iris"

**Comment by svdgoor** [comment]
Tested previous theory again and again, really seems to be "Iris"-named worlds only

**Comment by NextdoorPsycho** [comment]
Iris-named worlds are generally Studio worlds, this is a bug maybe

**Comment by svdgoor** [comment]
Add bug tag
