### ISSUE TITLE
Failed to create loader! com.volmit.iris.engine.object.IrisExpression

### ISSUE THREAD

**Issue by Bubzhome** [VolmitSoftware/Iris#654]
### Problem

1. Install Iris...
2. Create a world using Multiverse
3. restart the server
4. Observe the error...
Massive lag, cpu usage spikes to 400% and ram usage increases as soon as you try to load iris chunks

### Minecraft Version

1.17.1

### Iris Version

 1.8.13

### Log

https://pastebin.com/wxdDcwCM

**Comment by cyberpwnn** [comment]
`java.lang.NoClassDefFoundError: com.dfsek.paralithic.eval.parser.Parser` Did you download this from Spigot or did you build this yourself? Just making sure since im certain we are using the right build for Paralithic but idk

**Comment by Bubzhome** [comment]
I have built it myself

**Comment by Bubzhome** [comment]
> `java.lang.NoClassDefFoundError: com.dfsek.paralithic.eval.parser.Parser` Did you download this from Spigot or did you build this yourself? Just making sure since im certain we are using the right build for Paralithic but idk

I have built it myself

**Comment by StrangeOne101** [comment]
Make sure you are building with shadowJar

**Comment by Bubzhome** [comment]
wdym? How would I do that

**Comment by StrangeOne101** [comment]
Use `gradle shadowJar` to build the plugin

**Comment by svdgoor** [comment]
Assuming Bubz managed to do this with shadowjar, closing.
If you need help with compiling go to the [discord](https://discord.gg/volmit)
