### ISSUE TITLE
Floating objects, Cutoff by decorator

### ISSUE THREAD

**Issue by enjoythemomentum** [VolmitSoftware/Iris#658]
### Problem

Floating objects, Cutoff by decorat
![unknown5](https://user-images.githubusercontent.com/43861907/134589336-9d4951a0-3483-416c-b88e-4c9934da7a46.png)
![unknown6](https://user-images.githubusercontent.com/43861907/134589342-5ab14aab-13ee-472d-be0f-53f63c9e0a8b.png)
![unknown2](https://user-images.githubusercontent.com/43861907/134589344-89f9199d-794b-47ab-80e7-00e2fc149c11.png)
![unknown3](https://user-images.githubusercontent.com/43861907/134589346-7a88c2b7-a8e5-4166-bc91-4c81010eac52.png)
![unknown4](https://user-images.githubusercontent.com/43861907/134589352-8ddd3d9a-d939-4024-885c-f9ed1c457aaf.png)
![unknown](https://user-images.githubusercontent.com/43861907/134589353-39929d65-99c2-4473-b89a-cb4872371c2c.png)
or

### Solution

none

### Minecraft Version

1.17.1

### Iris Version

1.8.13

### Log

https://mclo.gs/L5dAPcv

**Comment by StrangeOne101** [comment]
Adding more images of confirmation that it is decorators overriding objects

![](https://cdn.discordapp.com/attachments/768582615078010910/890792858804711475/2021-09-24_10.49.08.png)
![](https://cdn.discordapp.com/attachments/768582615078010910/890794920011526225/2021-09-24_11.00.40.png)

**Comment by cyberpwnn** [comment]
Fixed in 1.9
