### ISSUE TITLE
[SOLUTION] Updating worlds from packs which cause chunk errors solution.

### ISSUE THREAD

**Issue by AZFire1** [VolmitSoftware/Iris#66]
**Is your feature request related to a problem? Please describe.**
Currently, regular Iris worlds do not automatically update from packs like say studio worlds do. I was hoping for a safe way to be added for updating your existing worlds from a pack (as currently "/ir ^update-world" causes chunk errors) without getting chunk issues. The reason I'd like this added is that I would love to release my server with a smaller world, and when you all start adding new structures, fix villagers, etc. it would be nice and easy to simply just update my pack and then run the "/ir ^update-world overworld" command and have all these new updates in new chunks without any chunk errors, and a smooth transition to them.

**Describe the solution you'd like**
After talking about this to Coco, this seems like the most reasonable solution to fixing these chunk errors caused by "/ir ^update-world" without affecting generation speeds. This is what I wrote on discord 
![image](https://user-images.githubusercontent.com/67762583/107840289-46793980-6d90-11eb-8e63-6cc6243d55b6.png)

**Comment by NextdoorPsycho** [comment]
no, this will not be added.
If mojang cant do it, we wont even consider, plus er CAN do something about it, it would just smear everything and look bad.
updating will also change the shuffle, and seed of everything so preexisting biomes will just have the wrong data


Make a new world
