### ISSUE TITLE
Lily pad grow on shore

### ISSUE THREAD

**Issue by YKDZ** [VolmitSoftware/Iris#660]
### Problem

1. Install Iris...
2. use https://github.com/IrisDimensions/overworld to create overworld
3. Look around the swamp and find this
![Snipaste_2021-09-25_10-20-44](https://user-images.githubusercontent.com/69898831/134754729-d1d27216-ee15-43b8-9d26-20e4af784684.png)

### Minecraft Version

1.17.1

### Iris Version

1.8.13

### Log

no log

**Comment by cyberpwnn** [comment]
lol
