### ISSUE TITLE
Cannot convert "Irisworld" into a int

### ISSUE THREAD

**Issue by EiderFC** [VolmitSoftware/Iris#662]
### Problem

does not let me pregenerate 

https://mclo.gs/QyZ1cQT

### Minecraft Version

1.17.1

### Iris Version

Iris version 1.8.13

### Log

https://mclo.gs/tMZIyvz

**Comment by svdgoor** [comment]
wrong order of parameters. Read command descriptions more carefully please.

**Comment by StrangeOne101** [comment]
I think this should be fixed. There was no point to the command system rewrite if we can't have parameters in a different order when you literally specify what parameter it is
