### ISSUE TITLE
Deepslate ores does not generate

### ISSUE THREAD

**Issue by Dulcissimus** [VolmitSoftware/Iris#665]
### Problem

**Deepslate variants for all of the ores does not generate properly. They are instead generated with normal variant.**

I found this issue by limiting all normal variant ores generation to be above `y=15`. 
However, I found some normal ores generates in a cluster below `y=15`, with no sign of deepslate ores around:
![](https://cdn.discordapp.com/attachments/768582615078010910/892214208299675668/unknown.png)
Below is the version without deepslate blocks:
![](https://cdn.discordapp.com/attachments/768582615078010910/892232725166194738/unknown.png)

### Solution

Any `minecraft:deepslate_[orename]_ore` within the deposits generation will always generate as `minecraft:[orename]_ore`

The only solution I found is to disable the _"deepslate"_ ore cluster from generating:

- In `dimensions/overworld.json`, you can navigate to `deposits` to find these lines:

```      
       {
            "minHeight": 5,
            "maxPerChunk": 5,
            "maxHeight": 15,
            "minPerChunk": 5,
            "minSize": 8,
            "maxSize": 4,
            "palette": [
                {"block": "minecraft:deepslate_copper_ore"},
                {"block": "minecraft:deepslate_diamond_ore"},
                {"block": "minecraft:deepslate_emerald_ore"},
                {"block": "minecraft:deepslate_gold_ore"},
                {"block": "minecraft:deepslate_iron_ore"},
                {"block": "minecraft:deepslate_coal_ore"},
                {"block": "minecraft:deepslate_redstone_ore"},
                {"block": "minecraft:deepslate_lapis_ore"}
            ],
            "varience": 4
        },
```

- Change `minHeight` and `maxHeight` to 0.

### Minecraft Version

1.17.1

### Iris Version

1.9

### Log

https://mclo.gs/9D9AlV0

**Comment by svdgoor** [comment]
Due to #625
