### ISSUE TITLE
Dust tools does not work on overworld

### ISSUE THREAD

**Issue by Dulcissimus** [VolmitSoftware/Iris#666]
### Problem

**Dust tool does not work on normal overworld dimension.**

Simply spawn in the dust tools and apply it to current and new chunk's structures and objects. There will be no usual output in the chat or any indication of error on console. See video below for replication details.

### Solution

**Dust tool does works on studio world.**

This is just a temporary solution if you want to use dust tool to see what objects it is at the moment.

You can open a studio world and dust tool will behave normally to objects and structures, see video below:

https://user-images.githubusercontent.com/65392733/135139738-99f36a52-bb7c-4bed-8aa6-ba8f1602b5b4.mp4

### Minecraft Version

1.17.1

### Iris Version

1.9

### Log

https://mclo.gs/f8bUwOl

**Comment by svdgoor** [comment]
If you still have the overworld you noticed this in, could you perhaps try `/iris what biome` and tell me what that returns?

Iris can sometimes half-and-half forget about a world (or have some invalid data stored), which could cause this behaviour.
Have you seen any errors in the console around/before this happened?

**Comment by svdgoor** [comment]
If you add the requested info we will reopen this.
