### ISSUE TITLE
Iris Find - Find NOT closest biome/region

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#670]
### Adding, Removing, or Changing

Adding

### Type of Modification

Command

### What are you trying to modify

The find command can currently only find the NEAREST biome/region. This is problematic for testing in studio worlds. There should be an option to make it random. E.g.

- `iris find biome biome=temperate/plains distance=-1` for random
- `iris find biome biome=temperate/plains distance=1000` to find the nearest biome not in a radius of 1000 blocks
- `iris find biome biome=temperate/plains distance=0` Find nearest from you

**Comment by svdgoor** [comment]
https://github.com/VolmitSoftware/Iris/pull/671
added when above is merged.
