### ISSUE TITLE
Block Drops Issues

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#673]
### Problem

See https://github.com/IrisDimensions/overworld/issues/234

Assumed to be because of an Iris bug

### Minecraft Version

1.17.1

### Iris Version

1.9

### Log

-

**Comment by ghost** [comment]
I think it’s due to a misconfiguration on the overworld pack (https://github.com/IrisDimensions/overworld/pull/232)

**Comment by StrangeOne101** [comment]
@ArMiN231 I was told to put it on the Iris bugs page too

**Comment by ghost** [comment]
> @ArMiN231 I was told to put it on the Iris bugs page too

@StrangeOne101 But its fixed on the overworld. Is it in general a problem or was it just a misconfiguration?

**Comment by StrangeOne101** [comment]
It was a general problem I believe

**Comment by svdgoor** [comment]
No it was a configuration issue.
A user fixed it and made a PR for it. It was accepted about a week ago.
