### ISSUE TITLE
/iris studio [editregion / editdimension / editcave / editjigsaw]

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#675]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to be able to edit certain elements based on my current location with ease

### What are you trying to modify

The way I would implement this is exactly the same as with `editbiome`, but for the region, dimension, nearest cave, and nearest jigsaw structure as well.

### Alternatives

If this could not be implemented I would have to find the region/dimension/cave/jigsaw-structure by hand which is time consuming and error-prone.

**Comment by svdgoor** [comment]
Perhaps we can make `/iris studio edit` a category of commands

**Comment by NextdoorPsycho** [comment]
What the hell is edit dimension supposed to do lol, its a studio

**Comment by NextdoorPsycho** [comment]
ok

**Comment by NextdoorPsycho** [comment]
Ok done
