### ISSUE TITLE
Console Code break Client Colors

### ISSUE THREAD

**Issue by Kr1S-D** [VolmitSoftware/Iris#676]
### Problem

1. Install Iris...
2. Turn off ConsoleColorCodes
3. Do /iris
4. Observe the error...

[](url)

### Minecraft Version

1.17.1

### Iris Version

1.9

### Log

Client Error not Console Error

**Comment by Kr1S-D** [comment]
![2021-10-10_09 56 01](https://user-images.githubusercontent.com/83023685/136711746-04d39e27-7ec9-408d-a7c2-ea181b788045.png)

**Comment by Kr1S-D** [comment]
hello?

**Comment by svdgoor** [comment]
Hey!
This is a known bug to some degree.
We recommend turning & keeping on in-game colors because they almost always work, and turn off console colors if you are having issues with them. They have two separate settings.
This will likely not be fixed as this is the data we need to fix the issue you may be experiencing with the colors, were you to have the issue.

**Comment by Kr1S-D** [comment]
`{
    "general": {
        "commandSounds": true,
        "debug": false,
        "disableNMS": false,
        "pluginMetrics": true,
        "splashLogoStartup": true,
        "useConsoleCustomColors": false,
        "useCustomColorsIngame": true,
        "forceMainWorld": "",
        "spinh": -20,
        "spins": 7,
        "spinb": 8
    },
    "world": {
        "asyncTeleport": {
            "enabled": false,
            "loadViewDistance": 2,
            "urgent": false
        },
        "postLoadBlockUpdates": true,
        "anbientEntitySpawningSystem": true,
        "asyncTickIntervalMS": 700,
        "targetSpawnEntitiesPerChunk": 0.95,
        "markerEntitySpawningSystem": true,
        "effectSystem": true
    },
    "gui": {
        "useServerLaunchedGuis": true,
        "maximumPregenGuiFPS": false
    },
    "autoConfiguration": {
        "configureSpigotTimeoutTime": true,
        "configurePaperWatchdogDelay": true,
        "autoRestartOnCustomBiomeInstall": true
    },
    "generator": {
        "defaultWorldType": "overworld",
        "headlessPregeneration": true,
        "maxBiomeChildDepth": 4,
        "preventLeafDecay": true
    },
    "concurrency": {"parallelism": -1},
    "studio": {
        "studio": true,
        "openVSCode": true,
        "disableTimeAndWeather": true,
        "autoStartDefaultStudio": false
    },
    "performance": {
        "trimMantleInStudio": false,
        "mantleKeepAlive": 30,
        "cacheSize": 4096,
        "resourceLoaderCacheSize": 1024,
        "objectLoaderCacheSize": 4096,
        "scriptLoaderCacheSize": 512
    }
}
`

**Comment by Kr1S-D** [comment]
With this configuration, iris 1.9.2 also has the same problem

**Comment by Kr1S-D** [comment]
https://pastebin.com/7ZbLYhsW

**Comment by NextdoorPsycho** [comment]
Theres a setting to turn this off, but there's not a fix yet.
Bug

**Comment by NextdoorPsycho** [comment]
Fixed this in the console which was a real problem, dont use a modded client and expect things to work.
And try disabling the client color codes. that should not be a problem either, on a vanilla client
