### ISSUE TITLE
Deposit Redo

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#677]
### Adding, Removing, or Changing

Changing

### Type of Modification

Deposits

### What are you trying to modify

Deposits are currently FLAWED. They have the following issues

1. Don't go across chunk borders, causing less ore on average to be around the border
2. Size of ore veins isn't correct. Right now, a cube sized area is created with equal dimensions. Each dimension is `maxVeinSize ^ 0.33*`, which means a vein with a max size of 38 will be `38 ^ 0.33 = 3.32` blocks wide in each dimension. That makes a 3x3x3 cube, meaning the vein can only be a max size of 27 blocks. If we set the vein size to be 27, `27 ^ 0.33 = 2.96 = 2` blocks in each dimension (aka, a 2x2x2 cube with 8 blocks max).
3. For each block in the vein, a random block within the cube area is picked each time, with the block being placed there. However, the same block can be randomly picked more than once, leading to the vein containing less blocks than the minimum size.
4. The deepslate ore replacement feature does not work properly

Therefore, deposits need some work

It would also be good if we could specify the style of ore, too. Such as a glob (ore bundled together in a ball), snaked vein (the length of the vein is much greater than the width, with the direction being random), or random (current system). Additionally, the min and max of the x y z should be configurable.

**Comment by svdgoor** [comment]
Yes please :)

**Comment by NextdoorPsycho** [comment]
Will not be redoing Deposits, will be implementing a better system but keeping deposits
