### ISSUE TITLE
Automatic fast leaf-decay after a majority of a tree is cut down.

### ISSUE THREAD

**Issue by AZFire1** [VolmitSoftware/Iris#68]
**Is your feature request related to a problem? Please describe.**
My feature is not related to any problems. I just find it a little hard to look at walking past many floating trees with only the bottom chopped off and the top part still there since leaf decay is off.

**Describe the solution you'd like**
Since Iris has leaf-decay off for its worlds, is there a chance you could add a feature for Iris trees to automatically start decaying leaves (possibly as fast as reacts leaf decay) once a tree is cut down? This would be useful and would prevent a majority of the man-made floating trees. Most of my players don't bother cutting down the entire trees as they are all mostly huge.

**Describe alternatives you've considered**
This is a bad alternative which I will not do, but turning leaf decay on for Iris worlds.

**Comment by svdgoor** [comment]
I think #43 would be better for this, or perhaps just including this option in there.
