### ISSUE TITLE
Custom (Plugin Based) Entities Despawn Improperly

### ISSUE THREAD

**Issue by Skizzles** [VolmitSoftware/Iris#680]
### Problem

Mobs despawn even with nametags on them. 

https://www.youtube.com/watch?v=zdbGzUNq9ts

### Solution

Mobs spawned from Iris should not despawn when nametagged.

### Minecraft Version

1.17.1

### Iris Version

1.9

### Log

https://pastebin.com/TvdXRsu8

**Comment by cyberpwnn** [comment]
Fixed in 1.9.3
