### ISSUE TITLE
Iris crashes when I try to use shaders to enter a world/server

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#682]
Here is the crash report: https://pastebin.com/bVYYASxw

Here are my mods:
![image](https://user-images.githubusercontent.com/78608482/138107217-95cee110-f49f-4116-99f1-a9951d895eba.png)
![image](https://user-images.githubusercontent.com/78608482/138107226-f36381f8-1e5f-4664-ada0-d2fda53a550c.png)

**Comment by ghost** [comment]
Dunno if you can run fabric clients on spigot (based) servers but thats probably the cause of your issue. And since iris isnt supporting fabric or forge ill close this.

**Comment by svdgoor** [comment]
Report this to the developers of the shaders.
Shaders only display the world as you see it. If there is an issue in that that's not on us.

**Comment by StrangeOne101** [comment]
Sounds like your shaders don't support custom biomes. Take that up with the shader/shader mod developers
