### ISSUE TITLE
Error enabling Iris

### ISSUE THREAD

**Issue by ChromaPIE** [VolmitSoftware/Iris#683]
### Problem

Follow the Getting Started and start the server, and in the console I got https://hastebin.com/avokusuxax.yaml

### Solution

No idea

### Minecraft Version

1.17.1

### Iris Version

1.9

### Log

https://hastebin.com/sarazizude.sql

**Comment by Kichura** [comment]
Confirmed on paper 1.17.1. - The plugin itself has no clue where the required data is located at so it assumes they are non-existant.

**Comment by svdgoor** [comment]
Did you compile the plugin yourself?
I do not have this on latest paper, latest Iris version.
Plus, I can compile it myself and it still works.
Did you perhaps compile with `build` instead of `shadowJar`?

**Comment by Kichura** [comment]
> 
> 
> Did you compile the plugin yourself? I do not have this on latest paper, latest Iris version. Plus, I can compile it myself and it still works. Did you perhaps compile with `build` instead of `shadowJar`?

I have used .\gradlew build via PowerShell to compile the plugin itself using JDK-16 as provided from minecraft's built-in java data itself.

For paper, I have the version "1.17.1-349" to attempt to run the server itself while iris uses the 1.9 version of 1.17.x aswell.

**Comment by svdgoor** [comment]
Exactly.
You need to use `./gradlew shadowJar` instead.
We hope you enjoy the plugin and consider buying it to support further development.
