### ISSUE TITLE
Reporte de TPS

### ISSUE THREAD

**Issue by Verkros** [VolmitSoftware/Iris#684]
Desde que instalé el Iris estoy teniendo estos probemas con los TPS, ¿hay alguna solución? Necesito resolver esto para quitar whitelist en el server.

https://timings.pl3x.net/?id=405f973d26e5456e96f0f382d0684ae5

**Comment by ghost** [comment]
You are running an outdated version. The tps problems are already solved.

**Comment by Verkros** [comment]
To upgrade I only replace the old Iris with the new one? will not break the world that I have created?

**Comment by svdgoor** [comment]
There will be many errors in the console and some features may no longer work, but the terrain should be the same.
We recommend making a new world.
