### ISSUE TITLE
spawners in the world

### ISSUE THREAD

**Issue by Davide00** [VolmitSoftware/Iris#686]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to add spawners in the world

### What are you trying to modify

The way I would implement this is some spawners in the world

### Alternatives

If this could not be implemented I would ...

**Comment by ghost** [comment]
Do you mean the blocks that spawns entities or what are you suggesting @Davide00 ?

**Comment by Davide00** [comment]
i mean this 
![image](https://user-images.githubusercontent.com/25281342/138604463-bc845060-2129-486e-a0e1-e76c3bb3189f.png)

**Comment by ghost** [comment]
Already suggested here #46 therefore I close this
