### ISSUE TITLE
Tab completion issues & suggestions

### ISSUE THREAD

**Issue by AZFire1** [VolmitSoftware/Iris#69]
**Describe the bugs, tweaks, and suggestions**
There are several small tab completion issues/suggestions I thought I'd go ahead and let you know. I'll link a video about them, added onto the list I've made below.

**Tab completion issues (these first ones are all just spacing issues, basically all arguments of arguments have this issue):**
 - ir std(tab)
 - ir std goto(tab)
 - ir jigsaw(tab)
 - ir std noise(tab)
 - ir pregen(tab)
 - ir object(tab)
 - ir what(tab)
(Now there are a few very rare random issues that I haven't been able to recreate for this bug report. Sometimes tab completion straight up stops working for a little and a repeated error while tab completing message is sent to the player.)

**Tab completion suggestions:**
 - ir std summon (tab to list the custom mobs you can summon)
 - ir reload (tab to list the files you can reload)
 - Added onto all this, the general tab completion system in the middle of tab completing should be improved. For example tab completing half-way arguments (/ir wha(t) or /ir std goto mosa(ics)) should tab complete the rest of the argument. Currently it does not.

**Server and Plugin Informations**
 - Installed plugins: https://bin.bloom.host/odeveqorop.m
 - Iris Version: V1.3.2
 - Server Platform and Version [eg: PaperSpigot 1.16.3 VolmitSoftware/Iris#240]: Purpur
 - Operating System (if applicable): Not applicable
 - Server Logs: Irrelevant

**Video:**
https://mega.nz/file/vUkiSDSB#-sFn0dXeVVWEdWCUkFK-0YmwmJTU6oUyDebp-h_E8mE it should load, if not, you may have to download it.. :/

**Comment by svdgoor** [comment]
The autocompleter could definitely use a good ol' overwrite to support partial word completions

**Comment by svdgoor** [comment]
Autocomplete on objects, regions, biomes, among many other things, has been strongly improved with 1.5.10. I think this issue can be closed.
