### ISSUE TITLE
Bug: Studio mode not showing ores

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#69]
Reported by: @﴾ȴṅṽịḉṫḭṍȵ﴿#0510 

This is a series of messages and screenshots posted in #iris-screenshots
Here is a link:
https://discordapp.com/channels/189665083817852928/767020043527389245/767524741468520448

**Comment by NextdoorPsycho** [comment]
not an issue, the image you had was a broken gen, here is that same conversation
https://i.imgur.com/akhx4vW.png
