### ISSUE TITLE
Custom Biomes being reset to Minecraft Biomes

### ISSUE THREAD

**Issue by Skizzles** [VolmitSoftware/Iris#690]
### Problem

After changes are made to Vanilla worlds, Iris custom biomes seem to lose their biome data and reset to a Minecraft based biome. You can see here that Osaka Red turned into Savanna Plateau, Savanna, Desert, etc

![unknown-8](https://user-images.githubusercontent.com/30563757/139732805-f00d353f-7047-4c80-8709-8c1c32b26abf.png)

### Solution

A couple of things I noticed that may have triggered this issue:
- Unloading/Loading/Deleting a Multiverse world
- Resetting a world with ResourceWorld plugin.

**Both biomes are only vanilla biomes**

Links to those:
https://www.spigotmc.org/resources/multiverse-core.390/
https://www.spigotmc.org/resources/%E2%9C%85-resource-world-%E2%9C%85-never-run-out-of-resources-must-have.75994/

### Minecraft Version

1.17.1

### Iris Version

1.9

### Log

https://paste.skizzles.me/yitadatigi.yaml

**Comment by PaintsplattersMC** [comment]
can confirm this is an issue. touching entity spawning with iris in an existing iris world also seems to be problematic

**Comment by svdgoor** [comment]
#681 could help fix this, but it is ofc better to prevent than cure.

**Comment by Skizzles** [comment]
![image](https://user-images.githubusercontent.com/30563757/144228023-85f43ae7-eb61-4cb0-bc10-494bb33b6c69.png)
Originally Osaka red, confirmed this happens on resource world reset with that plugin.

**Comment by MastoryMd5** [comment]
Happened to me in just a day, yesterday i did some screenshots with shaders and today i found my spawn with biomes overwritten.

![photo_2021-12-01_00-34-42](https://user-images.githubusercontent.com/17986972/144228690-4c615a9d-f5d6-4aa0-9ac5-562a7d0081fd.jpg)
![photo_2021-12-01_12-42-01](https://user-images.githubusercontent.com/17986972/144228687-1aaa84b1-71ff-4e5e-818c-4ff163146009.jpg)


**This plugin is not usable in production as of now.**

**Comment by svdgoor** [comment]
Keep in mind that Iris is the only world generator that currently supports custom biomes (that is also configurable by the end-user)
Losing this feature doesn't make the plugin unuable in production.

**Comment by Skizzles** [comment]
I don't feel like reverting a world every month is usable in production. Nonetheless, this issue is fixed by reverting the world. Which makes no sense as in the Iris discord it was suggested that it was due to adding new biomes and how they are numbered. Wouldnt it still have different numbers if I only reverted the one Iris world?

This seems like an Iris issue.

**Comment by svdgoor** [comment]
Like I said, you don't have to, you lose the feature of the custom colors if you don't, which other options do not have.

I am not saying that Iris is not at fault, because I think it is, I'm saying to not take this to the extreme because that doesn't help anyone.

**Comment by Skizzles** [comment]
Not trying to be extreme, but when you pay for a plugin at $17 you would think that your issues would be resolved. How can your concerns and issues truly be resolved if you can't even update the plugin to fix them?

Anyways I really don't want this issue closed for being off topic or being seen as rude... because this needs to be fixed for this plugin to function as it should. At the very least the command to set biomes back would help remedy until this can be fully looked into and resolved.

**Comment by AvianAeternum** [comment]
You should only be using multiverse with iris worlds specifically, and premium software is going to have bugs, its why you support it so it can update and fix them.


> Happened to me in just a day, yesterday i did some screenshots with shaders and today i found my spawn with biomes overwritten.
> 
> ![photo_2021-12-01_00-34-42](https://user-images.githubusercontent.com/17986972/144228690-4c615a9d-f5d6-4aa0-9ac5-562a7d0081fd.jpg) ![photo_2021-12-01_12-42-01](https://user-images.githubusercontent.com/17986972/144228687-1aaa84b1-71ff-4e5e-818c-4ff163146009.jpg)
> 
> **This plugin is not usable in production as of now.**

Did anything change about your server between the two sessions? Or is your report that it completely on its own without any changes loses its datapack and thus custom biome coloring?

**Comment by AvianAeternum** [comment]
> can confirm this is an issue. touching entity spawning with iris in an existing iris world also seems to be problematic

Your custom iris package is intended to be perfected in studio mode locally before being uploaded to your server and ran as the production generation package. This includes mob spawn configuration. Updates to your exported iris package are intended to go along with a complete reload of your iris world.

However, if you do upload changes without reloading your world, previously loaded chunks may break if there is conflicts with new settings and configuration, and the changes will only fully reflect in newly generated chunks.

**Comment by NextdoorPsycho** [comment]
Closing- Update and reopen this if the problem is happening on stable PURPUR, and latest IRIS with a better pick system, and using MULTIVERSE as a world manager

**Comment by Skizzles** [comment]
Findings:
- Mv unload and mv delete do not cause any issue
- When doing /mv create name normal I found that every time there is some loss to biome data when running this command and then over time the biomes revert more and more

This seems entirely due to mv create command for worlds

**Comment by Skizzles** [comment]
Tested with mv load and got the same results, seems like when loading a world via multiverse.

Going to try to manually add a new world to the mv config and restart the server and see if we have similar results.

My theory is that it could possibly be due to the way multiverse loads world's while the server is running.

**Comment by Skizzles** [comment]
@NextdoorPsycho can this be reopened?
