### ISSUE TITLE
Entities Despawning in Iris Worlds

### ISSUE THREAD

**Issue by PaintsplattersMC** [VolmitSoftware/Iris#691]
### Problem

Nametag or breed animals spawned via iris' spawning mechanic. 
 Both the nametagged mobs and offspring despawn upon reboot. 

I cannot consistently reproduce this behavior. although https://github.com/VolmitSoftware/Iris/issues/680 may offer some insight to the custom spawning reason being the issue.

I would also check other NBT data pertaining to Persistent + true|false and whether or not iris handles all mob spawns in iris worlds via this method.

This is also happening to creative mode spawned villagers, so i would assume this is the case.

### Solution

I believe the problem lies somewhere in the way Iris handles mob spawning via any source within iris worlds.

### Minecraft Version

1.17.1

### Iris Version

1.9

### Log

No new logs

**Comment by PaintsplattersMC** [comment]
![2021-11-01_16 57 44](https://user-images.githubusercontent.com/83564809/139747612-5a83fce4-aadb-434f-bee9-d942b5885481.png)
above is a screenshot of an iris villagers NBT
below is one spawned using vanilla /summon
![2021-11-01_16 59 35](https://user-images.githubusercontent.com/83564809/139747671-e386fddd-f3c8-46c7-ab8f-cc81948aa55d.png)

**Comment by PaintsplattersMC** [comment]
Mobs spawned in via iris have the NBT tag Bukkit.persist set to 0b

However mobs via other methods such as /summon and essentials /mob dont set this tag at all

**I believe this to be the root cause**

**Comment by PaintsplattersMC** [comment]
Please DM me on discord @ Paintsplatters#8819 to inform me of any progress

**Comment by cyberpwnn** [comment]
Fixed in 1.9.3
