### ISSUE TITLE
Time and weather based effects (commands, ...)

### ISSUE THREAD

**Issue by xIRoXaSx** [VolmitSoftware/Iris#692]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to execute commands via the commandRegistry at a certain time and weather

### What are you trying to modify

The way I would implement this is like the options given in the spawner json files. E.g.:

```json
"effects": [
  {
    "timeBlock": {
      "startHour": 6,
      "endHour": 18
    },
    "weather": "NONE",
    "chance": 100,
    "volume": 1,
    "commandRegistry": {
      "rawCommands": [
        {
          "commands": [
            "command 1",
            "command 2"
          ]
        }
      ]
    }
  }
]
```

### Alternatives

Running a command from commandRegistry to a third party plugin to check time & weather.

Thanks!

**Comment by svdgoor** [comment]
#695
