### ISSUE TITLE
Config option to disable command alias

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#694]
### Adding, Removing, or Changing

Adding

### Type of Modification

Would be need to prevent conflicts with plugins that also use /ir as a command

### What are you trying to modify

The way I would implement this is by giving a option in the config file

### Alternatives

If this could not be implemented I would cry

**Comment by svdgoor** [comment]
We can't make a config option for this because it's registered on plugin startup.
The only way to make /ir not point to Iris is by removing it altogether, always.

**Comment by ghost** [comment]
Okay so this can be closed than @CocoTheOwner
