### ISSUE TITLE
Find biome command not working properly

### ISSUE THREAD

**Issue by TruongHogent** [VolmitSoftware/Iris#696]
### Problem

After updating the plugin to iris 1.9.3, I have found that the [/iris find biome biome=name/etc/etc...] command does not work for some specific biomes.

### Solution

I have tested, many times by creating new worlds, teleporting thousands of blocks a way but still can't find the biome. The biomes are probably there, just the command doesn't work since the removal of suggestion commands in 1.9.3. The ones I can't, is like 100% not able to find it at all times when doing the command, see images all the way down.

Example how the /iris find command wouldn't work if it has the same name. 
"name" + "-" + "extraname"

Example 1:

iris find biome biome=tundra/mountains
iris find biome biome=tundra/mountains-cliffs

Example 2:

iris find biome biome=tundra/forest
iris find biome biome=tundra/forest-cliffs
iris find biome biome=tundra/forest-peaks

Images:

![image](https://user-images.githubusercontent.com/80478455/142005156-4929142c-a38a-4b73-9ed7-377254425781.png)
![image](https://user-images.githubusercontent.com/80478455/142005122-f23dec55-a575-4911-8452-630a439d46ce.png)

### Minecraft Version

1.17.1

### Iris Version

1.9.3

### Log

https://pastebin.com/xFdr8pSR

**Comment by TruongHogent** [comment]
**Problem**
After some testing, the issue mentioned above seems not to be the issue. I just think that iris **1.9.3** doesn't register some biomes in the world but it does register in the region since I don't get the error of the region. If you can't use the find command for a specific command, that means the biome isn't in the world, but it is registered in region.

It's a big issue to be honest not able to find some biomes, losing 20% of the biomes. It loads up to 100%, but that's it. Nothing more.

**Minecraft Version**
1.17.1

**Iris Version**
1.9.3

**Log**
https://pastebin.com/h5cfdtv9

**Conclusion**
1.9 does not have any of these issue. Did not find a solution, cuz as the issue mentioned above with the same name problem, some biomes with the same name works, and some not.

**Comment by PaintsplattersMC** [comment]
I have the same issue. I have been unable to find any tropical biomes after our admin team flew 10s of thousands of blocks around.

I have the same issue with goto and find
 iris 1.9.3
(edited typo)

**Comment by PaintsplattersMC** [comment]
bump

**Comment by NextdoorPsycho** [comment]
Fixed, update
