### ISSUE TITLE
[Idea] Included Iris world border per-world (like WorldBorder plugin has)?

### ISSUE THREAD

**Issue by AZFire1** [VolmitSoftware/Iris#70]
**Is your feature request related to a problem? Please describe.**
This is another feature I noticed Realistic World Generator has which I thought could be a great addition to Iris.

**Describe the solution you'd like**
I understand I could already use the default world border provided by vanilla Minecraft, or directly use the WorldBorder plugin, but since Iris already has a pregeneration system, this would be the icing on the cake if it had its own (WorldBorder plugin-like) world border system. You could build on this idea by creating more arguments to say the pregen command like adding a "/ir pregen fill" to fill something right up to the border exactly. If you choose to add the different shaped world borders that the plugin World Border has, that could be nice as well as vanilla Minecraft does not provide this. You've already made an insane pregenerator for Iris which beats the pregenerator World Border has by a mile. I think it could be nice for Iris to have a world border system as well.

**Describe alternatives you've considered**
A. Use default vanilla-provided world border.
B. Use World Border plugin directly.

**Additional context**
https://www.spigotmc.org/resources/realisticworldgenerator-1-8-8-1-16-x.15905/ - Realistic World Generator
https://www.spigotmc.org/resources/worldborder-pures-fork.81706/ - World Border plugin.

**Comment by svdgoor** [comment]
Incompatible with Direct MCA generation, not very useful, quite tricky to maintain, better to do with worldborder, cutting off chunks = bad.
