### ISSUE TITLE
Add placeholder biomes, so the biome map isn't messed up on every update.

### ISSUE THREAD

**Issue by lochlanmcelroy** [VolmitSoftware/Iris#701]
By adding placeholders to the biome list, and instead of adding new biomes, you just switch it in for a placeholder, you can allow people to update their iris worlds to new ones, without a reset. (You won't find nether biomes in the overworld, or deserts in the ocean). There may still be chunk borders that look wonky, but its much better than a total restart.

**Comment by svdgoor** [comment]
Changed biomelists aren't the biggest problem with Iris updates.
The main problem is the noise maps changing
This means that an Ocean can and will spawn next to a Mountain, for example, and there would be a massive wall, unless we somehow deal with that difference.
There is not a good way to deal with that difference, and it will only take a lot of time on our end to implement this system, but not many people will be able to use the system efficiently & will be happy with the outcome. Hence why we decided not to do this.
