### ISSUE TITLE
Iris is unable to place Nether plants as decorators

### ISSUE THREAD

**Issue by farum12** [VolmitSoftware/Iris#702]
### Problem

It has been observed that Nether plants such as:
- Warped Roots
- Nether Sprouts
- Crimson Roots
cannot be used as a Decorator on Warped Nylium, despite Player's ability for manual placement.

1. Open any Iris Dimension.
2. Replace in any biome first layer to Warped Nylium.
3. Declare any of mentioned Nether plants as a Decorator.
4. Regen and Find edited biome.
5. Observe the issue, as mentioned plants will not be present.

### Minecraft Version

1.17.1

### Iris Version

1.9.3

### Log

https://mclo.gs/DoQprsJ

**Comment by NextdoorPsycho** [comment]
Fixed

**Comment by NextdoorPsycho** [comment]
i did that
