### ISSUE TITLE
PlaceholderAPI Placeholders Broken on 1.18.1 Purpur

### ISSUE THREAD

**Issue by ItsMCB** [VolmitSoftware/Iris#705]
### Problem

I followed the [getting started guide](https://docs.volmit.com/iris/getting-started) and joined the server after overriding the main world using the `bukkit.yml` method. I tried testing the placeholders with the `/papi parse me` command and found out that they don't work correctly.

![](https://i.imgur.com/nDa9j6V.png)

Env info:
This server is running Purpur version git-Purpur-1506 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 84028e2 on HEAD)
You are running the latest version

PAPI version: 2.11.1

### Minecraft Version

1.18

### Iris Version

1.9.7-1.18.X

### Log

https://mclo.gs/IuGDB8P

**Comment by NextdoorPsycho** [comment]
Did a few changes, is this happening on latest?
