### ISSUE TITLE
Colors don't work

### ISSUE THREAD

**Issue by Specthra** [VolmitSoftware/Iris#706]
### Problem

1. You create a world with Iris
2. You appear in the world and a few chunks are generated in the surroundings (When loaded by the player, they will appear correctly)
3. You initiate the pregeneration of the world
4. When you move away from the initial spawn point, you start to see biomes without color (They appear as swamp or plain mostly)

![image](https://user-images.githubusercontent.com/77130187/149831451-b7d0c86f-3993-4686-a9f2-f798a41d7fda.png)
![image](https://user-images.githubusercontent.com/77130187/149831459-92e56e7c-4019-4d5f-846a-fe1ad08b45ec.png)
![image](https://user-images.githubusercontent.com/77130187/149831476-5d888b63-4269-4d70-804a-79e97d89aadf.png)
![image](https://user-images.githubusercontent.com/77130187/149831484-a3557d6e-9401-4df7-8df0-79d8705572fd.png)
![image](https://user-images.githubusercontent.com/77130187/149831498-48cd84f0-a8f6-4916-a1a2-7dd0c62dc33f.png)
![image](https://user-images.githubusercontent.com/77130187/149831508-e2ad3e51-c06c-4971-8f69-5eb3bf331d4c.png)

### Minecraft Version

1.18

### Iris Version

V1.9.7 - 1.18.X

### Log

https://pastebin.com/5xqA0PMB

**Comment by Specthra** [comment]
No error in console, everything normal
https://pastebin.com/21uHtHS9

**Comment by Specthra** [comment]
I attach the videos with the problems, the information and the logs were sent to NextdoorPsycho

Test w/ Bukkit: https://www.youtube.com/watch?v=wujD_SyilIc
Test w/ Multiverse: https://www.youtube.com/watch?v=sRAR4FXWNJ8

**Comment by svdgoor** [comment]
I hate that custom colors & biome ID mappings break so often.... such a cool system...

**Comment by NextdoorPsycho** [comment]
https://i.imgur.com/mIfzvAB.png
