### ISSUE TITLE
Ore is not generated more than 2x2

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [VolmitSoftware/Iris#707]
### Problem

1. Install Iris
2. We are trying to set ore generation of more than 4 ore blocks (overworld.json) https://pastebin.com/Z4s8TpLp
3. Ore is generated only 2x2 max

Images: https://imgur.com/a/2ZtYSiC

### Solution

Ore should be generated more than 2x2 if it is set in the configuration

### Minecraft Version

1.18

### Iris Version

commit 3ecaaf33b684b5194bfbbdd9db6e4efc60b531ba

### Log

https://pastebin.com/WxV9cGA2

**Comment by Envel-Nikita-Gutsenkov** [comment]
?

**Comment by svdgoor** [comment]
Nextdoor Psycho has updated the ores in the most recent version of the pack. There is a new setting called "ores" now which does ores much better 
Deposits will now also work, though 
This issue was fixed, so it was closed.
