### ISSUE TITLE
Mechanics of leaf fall

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [VolmitSoftware/Iris#708]
### Adding, Removing, or Changing

Changing

### Type of Modification

Survival servers quickly become ugly when dozens of players chop down trees and all the foliage remains in the air. This spoils the impression of the generator. Removing foliage, of course, is extremely difficult. Now the leaf fall is simply disabled. Let's just change the vanilla mechanics of falling off a little to make it work?

### What are you trying to modify

Creation in iris of its own implementation of leaf fall based on vanilla, but with the support of leaves on the ground and leaves on custom trees. It may be worth checking whether there is foliage within a radius of 1 block and thus whether all the foliage is hanging in the air without support.

### Alternatives

We considered auto felling of trees, but unfortunately with such types of trees, exact removal of foliage is impossible, as is the felling of some types of trees. In any case, foliage will remain in the air and it should fall off

**Comment by NextdoorPsycho** [comment]
We plan to have a system for this, but fixing the active problems is out main concern
