### ISSUE TITLE
Mobs spawn incorrectly

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [VolmitSoftware/Iris#709]
### Problem

1. Install Iris
2. Mobs spawn incorrectly. All villagers spawned high in the air or in the trees and die. Monsters appear in the ground and also die.

### Solution

???

### Minecraft Version

1.18

### Iris Version

commit 3ecaaf33b684b5194bfbbdd9db6e4efc60b531ba

### Log

https://pastebin.com/WxV9cGA2

**Comment by Envel-Nikita-Gutsenkov** [comment]
?

**Comment by svdgoor** [comment]
The log doesn't show information regarding mob spawns. We cannot really find this issue anymore (and now see mobs spawning on the floor properly)
We'd like to see some more details on this like screenshots or perhaps even a video

**Comment by Envel-Nikita-Gutsenkov** [comment]
https://youtu.be/9_XubeFpPUU

**Comment by Envel-Nikita-Gutsenkov** [comment]
https://youtu.be/EqZgJYclONc

**Comment by Envel-Nikita-Gutsenkov** [comment]
> The log doesn't show information regarding mob spawns. We cannot really find this issue anymore (and now see mobs spawning on the floor properly) We'd like to see some more details on this like screenshots or perhaps even a video

added

**Comment by ghost** [comment]
@Envel-Nikita-Gutsenkov Should be fixed with 2.0.0 if not you can reopen this issue report
