### ISSUE TITLE
Sunken boats not waterlogged

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#71]
![afbeelding](https://user-images.githubusercontent.com/65736624/96472313-a0c61b80-1230-11eb-8188-f0a127a2129a.png)

**Comment by NextdoorPsycho** [comment]
@cyberpwnn Fix waterlogging

**Comment by svdgoor** [comment]
Cannot find duplicate. Removing label

**Comment by svdgoor** [comment]
Found duplicate VolmitSoftware/IrisPlugin#119
