### ISSUE TITLE
Iris Crashing

### ISSUE THREAD

**Issue by ZeroTwoO2** [VolmitSoftware/Iris#710]
### Problem

1. Install Iris on 1.17.1 purpur
2. Teleport to a value like 12k and 10k
3. Render a few chunks
4. Server will crash with the error attached

### Solution

None

### Minecraft Version

1.17.1

### Iris Version

1.9.5

### Log

https://mclo.gs/PiIzMBv

**Comment by ghost** [comment]
@ZeroTwoO2 Were you exploring/teleporting through the world while the server was busy pregenerating? If thats the case than thats why you got a crash!
It looks to me that thats what happend and therefore i close this. If im wrong you can open it again or reply to this message.

**Comment by ZeroTwoO2** [comment]
No, that isnt the case, i used 1.18 and did the same thing and
everything was fine.

**Comment by svdgoor** [comment]
@ZeroTwoO2 I really need the full log of your server!

**Comment by svdgoor** [comment]
[2022-01-21-5.log](https://github.com/VolmitSoftware/Iris/files/7913136/2022-01-21-5.log)
Another person's log, the exact same issue

**Comment by svdgoor** [comment]
This issue turns out to be critical to some servers. It causes a near-instant crash, only fixable by a full restart.

**Comment by ZeroTwoO2** [comment]
Yes, thats true

**Comment by NextdoorPsycho** [comment]
This SHOULD not be happening on 1.18 anymore, but if it is please reopen this issue, but one of the problems was the HOST not allocating static memory and making it dynamic or whatever someone said in discord and when they swapped it was fine. but if any of you having this issue can replicate it on your PC with your server files, send me an archive and ill get to the bottom of it if you tell me what to do. till not imma close this, but feel free to tag me in discord
