### ISSUE TITLE
Intermittent stop exception

### ISSUE THREAD

**Issue by deniszitu** [VolmitSoftware/Iris#711]
### Minecraft Version

1.18.1

### Iris Version

1.9.7-1.18.X

### Log

https://mclo.gs/OfevTu6

**Comment by NextdoorPsycho** [comment]
This is not how you make a bug report. Thats not a full log, and i have no information

**Comment by deniszitu** [comment]
> This is not how you make a bug report. Thats not a full log, and i have no information

There are no more relevant logs, there is no error, it's just an intermittent exception.
I don't know what else to say.

**Comment by svdgoor** [comment]
"Error appearing in shutdown of server. I do not see issues occurring on the server/world itself because of it, but it isn't pretty to see this as the last thing that happens on the server every time it shuts down"
And now you do!

**Comment by deniszitu** [comment]
> "Error appearing in shutdown of server. I do not see issues occurring on the server/world itself because of it, but it isn't pretty to see this as the last thing that happens on the server every time it shuts down" And now you do!

Oh, that's right.

I really need to be more assertive, thanks for your understanding.

**Comment by CocoTheOwner** [comment]
[2022-01-21-5.log](https://github.com/VolmitSoftware/Iris/files/7913130/2022-01-21-5.log)
Another person's log

**Comment by ghost** [comment]
@Fukutu Ill close this. If you it still happens than please provide a full server log and reopen this issue report.
