### ISSUE TITLE
Iris command typing sound

### ISSUE THREAD

**Issue by Souperhero** [VolmitSoftware/Iris#712]
### Adding, Removing, or Changing

Changing

### Type of Modification

Chat Sounds to apply to all typing actions, not just Iris Commands

### What are you trying to modify

I am really fond of the sound effects Iris uses when typing in the chat box during commands. It'd be cool if a config could apply this globally or a separate plugin made.

Thank you!

### Alternatives

If this could not be implemented I would ... cry

N/A

**Comment by svdgoor** [comment]
The actual sound effect used for this can be found here:
https://github.com/VolmitSoftware/Iris/blob/f28b855189b63ba04396b47b1e49205818b3f2cd/src/main/java/com/volmit/iris/util/decree/DecreeSystem.java#L149
I can take a look at getting Minecraft to tell Iris every key input and play the sound effect then.
Is that what you are looking for?
I will probably make it into a custom plugin at that point.

**Comment by Souperhero** [comment]
Yes sir, that would be awesome!

**Comment by svdgoor** [comment]
update: I cannot find an event to run code every time a character is written, nor can I find code to access the tabComplete event from other plugins or vanilla minecraft.
in normal language: I cannot (with my current knowledge, a query to Purpur developers is outstanding) find a way to access people typing... in chat, to run the sound effect code on them
I hope purpur has a solution for us.... if they do not, you will have to send that code to all your plugin developers, have them put it into their tab completion events whenever you type a new character, or make a client mod for it....
```java
package nl.codevs.sparkly;

import org.bukkit.*;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.ArrayList;
import java.util.List;

public class Sparkly extends JavaPlugin {
    public static Sparkly instance;

    public void onEnable()
    {
        instance = this;
    }
    @Override
    public List<String> onTabComplete(CommandSender sender, Command command, String alias, String[] args) {
        if(sender instanceof Player p) {
            p.playSound(
                    p.getLocation(),
                    Sound.BLOCK_AMETHYST_BLOCK_CHIME,
                    0.25f,
                    (float) Math.random() * 1.825f + 0.125f
            );
        }
        return new ArrayList<>();
    }
}
```
Here is the code for an entire plugin without other commands. If the plugin registers new commands like usual they'll have this method be called.
If I get a reply from Purpur I'll let you know. If not, you'll have to make-do with the SFX in Iris alone I'm afraid...
