### ISSUE TITLE
Strongholds often not at proper location

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#714]
### Problem

1. Install Iris
2. Create a world
3. Throw eyes of ender
4. Find nothing where they point

Also, when entering a stronghold, you get no achievement.

### Solution

Place strongholds where they should be.

### Minecraft Version

1.18

### Iris Version

1.9.8

### Log

n/a

**Comment by Maplefsnow** [comment]
Same problem， hope it can be fixed early.

**Comment by AlternativeSoap** [comment]
This was made in January, please fix it.

**Comment by svdgoor** [comment]
There's this thing called priority. We prioritized the issues that caused servers to die, worlds to get corrupted, and other bugs over this one, for good reason. We'll get to it when we do.

**Comment by AlternativeSoap** [comment]
But it's basically one of the most important thing?

**Comment by svdgoor** [comment]
Perhaps it is now, yes, but if you look back at what we've gone through you'd understand.
We'll be working on this in the very near future, and your comments are appreciated.

**Comment by NextdoorPsycho** [comment]
> But it's basically one of the most important thing?

We have fixed this numerous times, and have decided that Jigsaw just plainly needs a whole rework. we plan to remake jigsaw in its entirety using the Structure block / a maker mode. 
We will look more into this when 1.19 comes out and when we have time. 

and its working on some people's packs, and not on others, so we don't know really what the pinnacle of causation is
But like this IS on our list of issues, that we will get to. for example Stability > update > stability > fix content > add content

**Comment by Vatuu** [comment]
Fixed in next version. Criteria for the advancement is pending.
