### ISSUE TITLE
Villager Issues

### ISSUE THREAD

**Issue by materialplane** [VolmitSoftware/Iris#715]
### Problem

After installing Iris I started locating villages and teleporting to them.

Villagers need job blocks (brewing stands, blast furnace, smithing table, etc) in order to take on professions that allow them to become traders.

So far, after visiting several villages I've only seen 1 brewing stand and 1 villager that became a cleric. Is this intended this way?

None of the other villagers could become traders without player intervention. Seems like more job blocks should be spawning in villages to allow the villagers to take on professions so they can trade.

### Solution

Spawn more random job blocks in villages.

### Minecraft Version

1.18

### Iris Version

1.9..8-1.18.X

### Log

na

**Comment by ghost** [comment]
Duplicate of #53
Currently iris doesn’t have control over random so we need to wait for a overhaul of the jigsaw system to prevent that.
I therefore close this.
