### ISSUE TITLE
Player get kicked while loading Chunks (Unplayable)

### ISSUE THREAD

**Issue by JanMartenT** [VolmitSoftware/Iris#717]
### Problem

1. Install Iris...
2. Fly arround

After a very short time the players get kicked and they can´t join again...
Everything worked fine in 1.16.4.  

Error:
(before you get kicked and if you try to join)
https://pastebin.com/s80ULTwF

### Solution

This his happens only to worls, who use Iris generation, so I don´t think it is a problem from purpur... Same probleme with paper.

The strange thing is, that it don´t happen to the old world (which I imported from 1.16.4)...

### Minecraft Version

1.18

### Iris Version

v1.9.8-1.18.X

### Log

https://pastebin.com/AJD8eSJ2

**Comment by svdgoor** [comment]
you are using ViaVersion on your server, and I think that, since there is nothing in the stacktrace of the error that indicates Iris has anything to do with it, you should contact ViaVersion about this issue instead.
Please let us know what they tell you, so this issue can be resolved quickly.

**Comment by JanMartenT** [comment]
Tried it again without ViaVersion, problem still exists.

**Comment by svdgoor** [comment]
Does it happen in a specific area or just immediately when you enter the Iris world?

**Comment by JanMartenT** [comment]
Sometimes it happens if I fly 10 Seconds and load chunks, some times it needs 5min to happen

**Comment by svdgoor** [comment]
Are you able to tell which chunks (i.e. biomes) it happens in exactly?
Are you using a vanilla (normal minecraft installation) client, or something like fabric/forge/etc?
Are you using shaders?

**Comment by JanMartenT** [comment]
It doesn´t seem to happen only in one specific biome, but I will watch if it happen in a specific biome often. 
I am using normal minecraft 1.18.1 and without shaders.

It only happen to generated world by Iris.


This error also happen sometimes:
https://www.toptal.com/developers/hastebin/jahacohine.properties
The last two lines are a error by Iris, but I don´t think this is related to the problem

**Comment by svdgoor** [comment]
That should not be the issue. Can you answer the other two questions please?
> Are you using a vanilla (normal minecraft installation) client, or something like fabric/forge/etc?
Are you using shaders?

**Comment by JanMartenT** [comment]
normal vanilla client without shaders

**Comment by JanMartenT** [comment]
Strange, sine 8min the problem didn´t come up again... I will try to find out what it triggers...

**Comment by JanMartenT** [comment]
![2022-01-22_18 39 15](https://user-images.githubusercontent.com/98219579/150649504-28fac938-a714-4943-ad42-926f4d1e1e0c.png)
If I go in the next chunk, then it happen everytime. Then I have to teleport me back via console to be able to join on the server. I think it has to do sth. with the biome in the next chunk.

Seem to be that this only happen to this specific area. Its not only one chunks, there are multiple arount it liek a line where this happen. One region

**Comment by svdgoor** [comment]
Are you still experiencing this issue? You said last time it occurred less?
I have not heard of others experiencing the same issue. I will keep an eye out for similar logs!

**Comment by TheHappyHopper** [comment]
After checking the log I think it has something to do with that empires extension, it seems to be conflicting with iris somehow

**Comment by ghost** [comment]
Ill close this till @JanMartenT confirms/denies that it has to do with empires extensions. Than he/i will reopen this issue.
