### ISSUE TITLE
rivers

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [VolmitSoftware/Iris#718]
### Adding, Removing, or Changing

Adding

### Type of Modification

I would really like to see rivers "out of the box" that would allow us to implement ordinary rivers, mountain rivers, waterfalls, because this is one of the main elements of a beautiful generation. The absence of rivers or their poor implementation makes any generation somewhat boring and seemingly incomplete.

### What are you trying to modify

I can make the ocean as a river, and add the ocean as a biome, but this is strange and does not work so well.
I will provide links to screenshots from other generators for demonstration:
https://proxy.spigotmc.org/2ed1da1a1ca2d05da7c2031e26bc6304b01d93c9?url=https%3A%2F%2Fi.imgur.com%2Fh6k9Ml5.png
https://proxy.spigotmc.org/fa55b693416d1efeca92717010baf1857cd941d3?url=https%3A%2F%2Fi.imgur.com%2Fqj4BuSu.png
https://proxy.spigotmc.org/50aaa1f99e4974cbb5c73105e395b44fa1bba788?url=https%3A%2F%2Fi.imgur.com%2Foby31EA.jpg
https://proxy.spigotmc.org/899d967fcbb17d8e20e4fba264bd811b554cfb07?url=https%3A%2F%2Fi.imgur.com%2FxSAfA1H.jpg

### Alternatives

-

**Comment by ghost** [comment]
I close this in favor of #719 which is a feature that is intended to be implemented someday cause the way you tried to do it (oceans as rivers is currently the only way) is not a pleasant experience or has good results.
