### ISSUE TITLE
Update info produced by /ir capture reports, and add a wiki for how to read them

### ISSUE THREAD

**Issue by AZFire1** [VolmitSoftware/Iris#72]
**Is your feature request related to a problem? Please describe.**
It could be considered related to a problem, though not necessarily. As far as I know, currently, nobody aside from cyberpwn knows how to read the reports produced by /ir capture. I've tried looking into the reports themselves to try to find out more about them, though I noticed that added onto there being no documentation of them, the info provided by the reports are very outdated. I think the info provided by them are pre-jigsaw, so I'd love an update of the info added onto a wiki page on how to read them and what they are useful for.

**Describe the solution you'd like**
As mentioned, a wiki page on how to work with iris captures/reports as well as the info reported to be updated as they are very outdated from what it seems.

**Describe alternatives you've considered**
None, aside from not using the reports feature of Iris.

**Comment by svdgoor** [comment]
Done (wiki part, profiler isn't actually really good)
