### ISSUE TITLE
Deep dark cave type

### ISSUE THREAD

**Issue by adelando** [VolmitSoftware/Iris#721]
### Adding, Removing, or Changing

Adding

### Type of Modification

Add a new deep dark shulker biome

### What are you trying to modify

The way I would implement this is ... adding a new biome to the caves something to the effect of deep dark caves coming to 1.19, shulkers are already in the game, possible to use dark blocks. With maybe the idea of corruption in mind.

### Alternatives

If this could not be implemented I would ...

**Comment by ghost** [comment]
@adelando this is the wrong place for that. You need to use this GitHub repo for changes to the overworld pack https://github.com/IrisDimensions/overworld/issues

**Comment by adelando** [comment]
whoops sorry!
