### ISSUE TITLE
Dolphin/Structure Api

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#728]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want that someone looks at this https://github.com/PaperMC/Paper/commit/a058ac0

### What are you trying to modify

The way I would implement this is by looking at this
https://github.com/PaperMC/Paper/commit/a058ac0

### Alternatives

If this could not be implemented I would ...

**Comment by ghost** [comment]
https://github.com/PaperMC/Paper/commit/9490475
Don’t know what this is for but maybe it’s useful

**Comment by CocoTheOwner** [comment]
Considering your account has been deleted and you did not take the format seriously I will close this. Please re-open with a filled-out format, thank you.

**Comment by svdgoor** [comment]
Although the request is bad the idea is still good.
Adding a boolean toggle to structures like `dolphinTarget`, which are then stored and retrievable in the mantle for when dolphins start navigating. Should be easy.
