### ISSUE TITLE
/iris what biome does not work at all

### ISSUE THREAD

**Issue by akusei** [VolmitSoftware/Iris#729]
### Problem

1. Install Iris and generate a world
2. Login to server
3. Run `/iris what biome`
4. `IBiome: null (THE_VOID)` is displayed no matter what biome you're in

### Minecraft Version

1.18

### Iris Version

1.9.8-1.18.X

### Log

https://mclo.gs/06tJ3EO

**Comment by svdgoor** [comment]
This bug makes it unnecessarily challenging to figure out biome-specific issues on packs that you did not create.

**Comment by akusei** [comment]
> This bug makes it unnecessarily challenging to figure out biome-specific issues on packs that you did not create.

I'm using the latest master branch of the Iris overworld pack from https://github.com/IrisDimensions/overworld

**Comment by NextdoorPsycho** [comment]
Fixed on latest, reopen if needed
