### ISSUE TITLE
BlocksEvolved Full Compatibility

### ISSUE THREAD

**Issue by Happily-Coding** [VolmitSoftware/Iris#73]
Hey there, I'm the developer of an upcoming custom blocks plugin called BlocksEvolved. 
I'd love iris to be fully compatible with Blocks Evolved. They are already partially compatible, but not fully, and I'd be really happy it if we could find a way to make them fully compatible.

Basicly, my plugin  allows state-based blocks, like the usual custom block plugins (that's already supported by Iris) , but it also allows each block to have additional information which allows things like customized growing, subtypes of blocks, etc (that isn't supported by Iris yet).

In order to allow our plugins to work together, one alternative would be an additional/alternative property inside the pallete which is the string that identifies my customblocktype, and then a call to my API when a block that has that property was placed by iris, so my plugin stores all additional information linked with it on that location. The second alternative would be for Iris to simply call my api to just place the block configured inside iris's pallete, however, from what @CocoTheOwner told me in discord, the first alternative would be the best suited for Iris.

This is my API (to which additions can be made if necessairy):
https://github.com/OnyxianSoul/BlocksEvolvedAPI

It is available on jitpack:
https://jitpack.io/#OnyxianSoul/BlocksEvolvedAPI/54d4e0f523

I'll describe the steps that would be taken in order to do the first alternative (adding a blocks evolved type name property to the pallete & notifying BlocksEvolved that Iris has placed a block of a custom block type of a certain name, at a certain location):

- Add jitpack as a repository, and my plugin as a dependancy. On maven it'd look like this:
```xml
   <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
```
```xml
    <dependency>
        <groupId>com.github.onyxiansoul</groupId>
        <artifactId>BlocksEvolvedAPI</artifactId>
        <version>54d4e0f523</version>
        <scope>provided</scope>
    </dependency>
```

- Add my plugin as a soft depend on the plugin.yml

- Hook Iris and blocks evolved:
```java
//ON STARTUP---------------------
//Get the instance of my api:
BlocksEvolvedApi blocksEvolvedApi = getServer().getServicesManager().getRegistration(BlocksEvolvedApiAccess.class).getProvider().getBlocksEvolvedAPI(yourPluginInstance);
//-----------------------------------

//ON CONFIGURATION READ-------
//Verify the validity of a block type in your config dong this:
blocksEvolvedApi.isValidBlockType(configuredBlocksEvolvedType, expectedBlockData);
//Or this, if you do not have access to the block data:
blocksEvolvedApi.isIdentifiableBlockType(configuredBlocksEvolvedType);

//Optionally, store the custom block type so you don't have to request it each time you place it.
IdentifiableBlockType identifiableBlockType = blocksEvolvedApi.getIdentifiableBlockType(configuredBlocksEvolvedType);
//------------------------------------


//TO PLACE BLOCK------------------
//If you did not store the custom block type, get it.
IdentifiableBlockType identifiableBlockType = blocksEvolvedApi.getIdentifiableBlockType(configuredBlocksEvolvedType);

//If the block data to place is defined by other settings in the config, place the block directly and afterwards notify my plugin with:
identifiableBlockType.setAdditionalInfo(location, blockDataAtPlacementLocationAfterPlace) //You can null the second variable if you don't have access to it.


//Otherwise, If the custom block name of my custom block plugin, is the only definition of what block to place.
if(identifiableBlockType.areWorldChangesNecessairy(blockDataAtPlacementLocation)){ //Verify that bukkit world changes are actually necessairy
   BlockData dataToPlace = subtype.getIdentifiyingBlockData(); //Get the block data to place
   //INSERT YOUR METOD TO PLACE BLOCK DATA HERE //(Place the block data using your method)
}
//Notify BlocksEvolved to store any additional info pertinent to the customblocktype (regardless of if world changes where necessairy).
blocksEvolvedApi.getIdentifiableBlockType(id).setAdditionalInfo(location); 
//------------------------------------
```

Please let me know if that'd suit you, I'd be happy to help you out or try to find other alternatives that work better for you if you find this one inconvenient for some reason.

**Comment by svdgoor** [comment]
Maybe but Oraxen support is top-notch

**Comment by StrangeOne101** [comment]
To add to this, this would be difficult to implement right now as a lot of Iris' generation now writes directly to MCA files. We can't call external APIs to place a block at a location when that location doesn't yet exist (and won't until it's loaded by the server in the future).
