### ISSUE TITLE
Passive animal spawning issue

### ISSUE THREAD

**Issue by akusei** [VolmitSoftware/Iris#730]
### Problem

1. Install Iris and generate a world
2. Login to server
3. Wait and walk around, look for animals, spore blossoms, and drip leaf
4. You may see 1 or 2 cows, chickens, or pigs but nowhere near a normal amount

I've also tried cranking up the energy, giving infinite energy, and increasing the mob counts. Below are the files I changed for testing after I noticed the initial issue. With this configuration, I would expect there to be a lot more animals in any temperate biome but when traveling to a temperate biome and waiting, only a couple passive animals spawned and a large number of hostile mobs spawned. This may be affecting how iris decides to place plants in caves but a separate issue will be filled for that.

overworld.json
https://pastebin.com/8tk1UcAu

temperate/land-passive.json
https://pastebin.com/qugTkJMR

You can see in the logs that the temperate land-passive.json file is loaded but very few if any animal spawns at all occur. Nearly every single spawn is a hostile mob. I did travel to a couple different temperate biomes for this test, none spawned more than 1 or 2 animals. I'd expect the spawns to be at least a normal rate for vanilla MC, or at least the changes I made to the spawner file and dimension file to have any affect at all.

### Solution

This may have something to do with the other open issue #709 related to hostile mobs spawning in blocks and dying; maybe the quickly spawning and dying hostile mobs is preventing the passive mobs from spawning in correctly?

### Minecraft Version

1.18

### Iris Version

1.9.8-1.18.X

### Log

https://mclo.gs/YgMvKCH

**Comment by ghost** [comment]
> spore blossoms also seem to not spawn in caves at all and drip leaf also seemed a bit rare, not sure if these are related to the passive spawning or not, but it's just something we noticed

That isn’t related. Also don’t post multiple „issues“ on the same report.
I did „“ due to the blossoms and the drip leafs being a slight change in the overworld pack and not a plugin issue.

**Comment by akusei** [comment]
> > spore blossoms also seem to not spawn in caves at all and drip leaf also seemed a bit rare, not sure if these are related to the passive spawning or not, but it's just something we noticed
> 
> That isn’t related. Also don’t post multiple „issues“ on the same report. I did „“ due to the blossoms and the drip leafs being a slight change in the overworld pack and not a plugin issue.

This isn't multiple reports, the issue is spawning, the spore blossoms and drip leaf are having the same issues spawning as the animals are. I will edit and reword my original bug title and added my appended comment to the original post to make it clear that we're having spawning issues that are related to animals and plants. If the plants are unrelated, cool, that doesn't mean I know enough about this issue to say that animals and plants having spawn issues are 2 completely different issues

**Comment by svdgoor** [comment]
You're smart enough to realise that plants are blocks and entities are not blocks
You're also smart enough to take the comment of someone literally telling you it's two separate issues and then treating it as such.
Quite disrespectful.

It's two separate issues because the blocks do spawn properly. You should make a bug report on the Overworld dimension's issue tracker for the plants you're missing, here: https://GitHub.com/irisdimensions/Overworld/issues

**Comment by akusei** [comment]
No, I actually didn't know that plants were blocks. I don't develop mods
for Minecraft so I don't know what adds to the entity count or not. To me,
spawning is spawning and from the couple things I've read they both affect
entity count. From what I understand, entity count can prevent other things
from spawning. Thank you for clearing that up and explaining why they are
actually two  different issues.

I was responding to a disrespectful comment assuming that I knew more about
how the internals of Minecraft work than I actually do. If these are indeed
separate things, great, let me know that without the condescending
assumptions. I would also caution you against assuming how much people know
about a particular topic because I honestly did not know and you both made
me feel like **** for not knowing. Thanks

**Comment by svdgoor** [comment]
Thanks for making a new issue and thanks for removing your comment.
Lets get over ourselves and move on.
