### ISSUE TITLE
Console Error (exception)

### ISSUE THREAD

**Issue by IPECTER** [VolmitSoftware/Iris#731]
### Problem

1. Install Iris...
2. Do this...
3. Do that...
4. Observe the error...
![image](https://user-images.githubusercontent.com/80433772/151660232-6ffbd64d-76af-4816-a408-18901374db51.png)
This error is printed only once when the server is turned on.

### Solution

This error is printed only once when the server is turned on.

### Minecraft Version

1.18

### Iris Version

1.9.8-1.18.x

### Log

sry I add nextday

**Comment by svdgoor** [comment]
Please follow the compilation tutorial here instead of just winging it:
https://github.com/VolmitSoftware/Iris#building

**Comment by svdgoor** [comment]
And just upload the log immediately or hold off on creating the report next time please.
