### ISSUE TITLE
Iris downloads the correct version of the overworld 

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#732]
### Adding, Removing, or Changing

Adding

### Type of Modification

Iris should download the overworld pack for the correct version

### What are you trying to modify

Iris 1.17 version should download the GitHub release of the overworld 1.17 and not the latest.

### Alternatives

If this could not be implemented I would cry

**Comment by svdgoor** [comment]
Sorry for making you cry, but we will probably not implement this to discourage people from using old Iris versions, and we would have to release a new version of Iris right before every update to a new Minecraft version, which is sucky.

**Comment by ghost** [comment]
Just wanted to make the life of supporting easier but yea you are right
