### ISSUE TITLE
Incorrect saving and pasting of objects on 1.18.1

### ISSUE THREAD

**Issue by pustinek** [VolmitSoftware/Iris#733]
### Problem

The issue seems to be how iris is saving the object, some blocks just get 'yeeted' out of process and others blocks are shifted to it's place (more clear in the video)
1. Fresh installed iris
2. Used multverse to create new world (Iris-overworld)
3. Created a simple structure ores/stone
4. used the `/iris object wand`
5. Selected the desired area, used the command `/iris object save dimension=overworld name=test overwrite=true` (broken on none-overwrite objects also) and then pasted the object using `/iris object paste object=test`

It seems to me that there is a pattern. When it's saving the object correctly cuz some builds work perfectly while some cause the issue presented in the video

https://user-images.githubusercontent.com/21089157/151695158-972b2758-a4e3-4ae2-a8b9-f06fb4939db6.mp4

purpur version:  Current: git-Purpur-1533 (MC: 1.18.1)*

### Minecraft Version

1.18

### Iris Version

Iris v1.9.8-1.18.X by Volmit Software

### Log

No erros are thrown

**Comment by NextdoorPsycho** [comment]
This is Happening on Latest too, its a Vec issue(my guess) and being looked into

**Comment by nottapsycho** [comment]
so why is this only medium priority? it's pretty damn important

**Comment by svdgoor** [comment]
Priorities don't mean anything 
Literally

**Comment by NextdoorPsycho** [comment]
Fixed
