### ISSUE TITLE
Error and Crashes.

### ISSUE THREAD

**Issue by 0tickpulse** [VolmitSoftware/Iris#734]
### Problem

1. Get a Purpur 1.17.1 server
2. Install Iris and Multiverse
3. `/mv create NewWorld normal -g Iris:overworld`
4. `/mvtp NewWorld`
5. walk around

### Solution

Something to do with biomes

### Minecraft Version

1.17.1

### Iris Version

v1.9.5-1.17.X

### Log

https://pastebin.com/p35zRm4b

**Comment by svdgoor** [comment]
This log does not seem to show any issue with Iris. Did you perhaps upload the wrong log?
Close on 6-feb

**Comment by 0tickpulse** [comment]
Yeah I think I did, hang on I'll get a new log

**Comment by ghost** [comment]
Till we get a log this will be closed
