### ISSUE TITLE
Atomic cache failure!

### ISSUE THREAD

**Issue by SGirl-Zockt** [VolmitSoftware/Iris#738]
### Problem

Atomic cache failure!

### Minecraft Version

1.18

### Iris Version

Iris v1.9.8-1.18.X

### Log

https://mclo.gs/xZDPZfu

**Comment by NextdoorPsycho** [comment]
ACF's happen often but usually its a server problem, however i believe this in particular has been fixe on latest. reopen / tag me if otehrwise
