### ISSUE TITLE
Drip leaf and spore blossom placement

### ISSUE THREAD

**Issue by akusei** [VolmitSoftware/Iris#739]
### Problem

1. Install Iris and generate a world
2. Login to server
3. Check caves for spore blossoms and drip leaf
4. You may see a very small amount of drip leaf but you won't see any spore blossoms at all

I've also tried cranking up the energy, giving infinite energy, but I'm not sure if this actually has any affect on place spawning.

### Minecraft Version

1.18

### Iris Version

1.9.8-1.18.X

### Log

https://mclo.gs/YgMvKCH

**Comment by Envel-Nikita-Gutsenkov** [comment]
please pay attention to where you are writing. this is more related to the configuration of the overworld world than to the iris engine
