### ISSUE TITLE
Bodyless Mode (Running Iris without a server)

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#74]
**Is your feature request related to a problem? Please describe.**
Starting a server takes a lot of time, especially if one is making lots of major edits that regularly cause crashes to studio worlds, or if a Dev is making frequent edits to certain parts of the source code, it can really add up.

**Describe the solution you'd like**
A headless mode of Iris. You would be able to run Iris without a server instance.
Features to include:
- Noise maps
- Modified blue- / pl3xmap with live changes to 
- Pregenerate a world (directMCA, overwriteall)

**Describe alternatives you've considered**
The current way of things, starting a server and waiting for ages for it to boot, join the server, try the next edit you made and watch it crash, on loop.

**Additional context**
There is already a lot of framework in Iris that supports this. There is also a lot of stuff missing, however.

**Comment by svdgoor** [comment]
Headless has been implemented, but what about:

**Comment by cyberpwnn** [comment]
This is complex. We need a broken-down version of ... probably purpur with the craftdata registries loaded only.. OR our own registries that mirrors minecraft... but thats a LOT of data. Either way, this is a long way off.
