### ISSUE TITLE
Custom biome registry incompatibility of Spigot 1.18 NMS

### ISSUE THREAD

**Issue by Arasple** [VolmitSoftware/Iris#740]
### Problem

1. Build the latest spigot-1.18.1.jar
2. Install Iris
3. Configurate the bukkit.yml to generate `world` with Iris:overworld
4. Get the error

### Solution

faield to register custom biome with spigot NMS

### Minecraft Version

1.18

### Iris Version

1.9.8-1.18.X

### Log

https://paste.gg/p/anonymous/c0ead476ab44411187091bc58db6b612

**Comment by svdgoor** [comment]
Use purpur or paper like I explained to you on discord.
bruh.

**Comment by Arasple** [comment]
> Use purpur or paper like I explained to you on discord. bruh.

This is just a NMS error, why won't you guys try to fix it?
I don't think you have stressed that Iris does not support Spigot on your resource page, wiki

The latest update also clearly indicates that Iris do support Spigot, or at least did
![](https://s2.loli.net/2022/02/02/dXGHlExnSMkfBaL.png)

**Comment by ghost** [comment]
> > Use purpur or paper like I explained to you on discord. bruh.
> 
> This is just a NMS error, why won't you guys try to fix it? I don't think you have stressed that Iris does not support Spigot on your resource page, wiki

iris uses the mojang nms. The forks of that. Like every server software uses different NMS and that’s why the dev decided to get rid of that mess and just support the vanilla Minecraft once. So it’s not on us to use the spigot once. It’s on spigot to use the original Minecraft once.

**Comment by Arasple** [comment]
> iris uses the mojang nms. The forks of that. Like every server software uses different NMS and that’s why the dev decided to get rid of that mess and just support the vanilla Minecraft once. So it’s not on us to use the spigot once. It’s on spigot to use the original Minecraft once.

Thanks for the explanation. I understood

**Comment by svdgoor** [comment]
I'm also pretty sure you're not allowed to list resources on SpigotMC without also supporting spigot so we could be removed for that.
Spigot is adamant (in their usual stubborn way) to keep using the old custom NMS mappings, whereas paper and purpur made the switch to the updated NMS mappings.
Apologies for coming off as rude, it's just that I don't understand why you could not use Paper or Purpur.
