### ISSUE TITLE
incorrect work with decorators below the lava level

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [VolmitSoftware/Iris#741]
### Problem

1. Install Iris
2. Replace Iris/packs/Overworld/biomes/carving/jungle.json with https://pastebin.com/FCvucs4j (it's just better to see, in fact, it happens both in the default and in any other configuration)
3. run /iris find biome biome=tropical/jungle-denmyre and find the cave
4. Observe the bug...

https://imgur.com/mM4XvIm
https://imgur.com/V9kgeWs

### Solution

decorators should not placed below the lava level

### Minecraft Version

1.18

### Iris Version

commit 2ead5b3c40b78b49385648a35fdd08bba7bf21f5

### Log

no need

**Comment by NextdoorPsycho** [comment]
Oops

**Comment by ghost** [comment]
> Oops

Maybe a "dont place decorators at and under the lava layer" function would solve this?

**Comment by NextdoorPsycho** [comment]
aware of the issue, will have a fix in a bit, not super urgent
