### ISSUE TITLE
Horse riding issue

### ISSUE THREAD

**Issue by Corenb** [VolmitSoftware/Iris#742]
### Problem

Reproduce :
1. Install Iris-1.9.8-1.18.X
2. Enable asyncTeleport in Iris config
3. Start the server and connect on it.
4. Try to ride a horse.

Players can't ride horse, they're teleported back and can't tame it.

### Solution

This issue happens when you enable asyncTeleport in Iris configuration, disable it resolve the issue.

### Minecraft Version

1.18

### Iris Version

V1.9.8-1.18.X

### Log

https://mclo.gs/RfW9elB

**Comment by ghost** [comment]
Confirmed on 2.0.0

**Comment by NextdoorPsycho** [comment]
Don't use Ascync Tele then, use another plugin or spigot's built-in one, this is a huge backburner for us lol
