### ISSUE TITLE
Iris -64 offset problem

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#746]
### Problem

1. Generate a World
2. See that while the Fluidheight of the overworld is set to 75 it is 11 in the world

### Solution

Just add 64 to the Interpreter lol

### Minecraft Version

1.18

### Iris Version

1.9.9

### Log

No log needed

**Comment by svdgoor** [comment]
Intentional.
64 blocks from the bottom

**Comment by ghost** [comment]
> Intentional. 64 blocks from the bottom

Dont think its intended that the pack value isnt the same as the one in the actual world. This makes it really hard for new people figuring out how things really work. I know that the -64 shift is meant to get the new height changes. Which i dont want to change.

**Comment by svdgoor** [comment]
We can add a comment to the setting itself j suppose.

**Comment by svdgoor** [comment]
Why did you make this high priority?
We reserve that tag for critical issues.

**Comment by NextdoorPsycho** [comment]
This is still an issue

**Comment by NextdoorPsycho** [comment]
This should be working on latest, repoen if its not
