### ISSUE TITLE
Bug: campfire and other structures / objects spawning inside trees

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#75]
![afbeelding](https://user-images.githubusercontent.com/65736624/96472563-e97dd480-1230-11eb-831c-6bf62e9df8d8.png)
Reported by @TheDevelon

**Comment by NextdoorPsycho** [comment]
Less shading, and this is just something that can just happen

**Comment by NextdoorPsycho** [comment]
oops, did not mean to close this, fixing this is an enhancement

**Comment by svdgoor** [comment]
Did not mean to close this. This is the last 'duplicate'.
Remove duplicate
add enhancement
add low priority

**Comment by svdgoor** [comment]
Do not see this happening in V2. If anyone finds this happening again, feel free to comment here or make a new thread.
