### ISSUE TITLE
Iris unable to place blocks above 256

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#751]
### Problem

1. Install Iris
2. Modify the overworld.json
3. Change "fluidHeight" to 256
4. See screenshot
![2022-02-18_13 14 33](https://user-images.githubusercontent.com/5337873/154681174-c50171e7-a07c-4b21-a368-79118947db2d.png)

### Solution

Fix it dunno how thats up to Cybers magic

### Minecraft Version

1.18

### Iris Version

2.0.0

### Log

No logs needed

**Comment by Hrobitaillie** [comment]
up, please !

**Comment by NextdoorPsycho** [comment]
Fixed, now works based on World Height so if you have a datapack, it will magically support any height you have as long as MC Worlds support it
