### ISSUE TITLE
please add support to ItemsAdder.

### ISSUE THREAD

**Issue by MrJorman** [VolmitSoftware/Iris#755]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to ...ItemsAdder.

### What are you trying to modify

please add support to ItemsAdder.

### Alternatives

please add support to ItemsAdder.

**Comment by ghost** [comment]
As discussed with Psycho
„ Itemsadder refuses to add support for us so we refule to add support for them. Every other items plugin allows support for iris, even generator plugins... and yet itemsadder does not“
So this will be closed
