### ISSUE TITLE
[00:49:00] [Iris 1/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.core.RegistryAccess

### ISSUE THREAD

**Issue by Skjolberg** [VolmitSoftware/Iris#758]
### Problem

The errors are at server start-up.

**[00:49:00] [Iris 1/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.core.RegistryAccess**

### Minecraft Version

1.18

### Iris Version

Iris v2.0.1-1.18.X

### Log

https://pastebin.com/8VSj4U7M

**Comment by NextdoorPsycho** [comment]
you compiled yourself you did not do it right, if you did not compile it yourself, your server seems borked. lemme know

**Comment by CDFN** [comment]
I'm experiencing the same issue. I've self-compiled this plugin as specified in readme (`setup` & `iris` tasks, then use `build/libs/Iris-2.2.3-1.19-all.jar` as final jar). This is reproducible on:
```
This server is running Paper version git-Paper-61 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: cd215af)
You are running the latest version
Previous version: git-Paper-60 (MC: 1.19)
```

**Comment by CDFN** [comment]
It appears I was using wrong file. After going through build.gradle, I noticed the final jar is under `build` directory. I think that should be clarified in README, as currently it states the final jar is under `Iris` folder which is doesn't even exist after build process.
