### ISSUE TITLE
Strange Particle in the sky

### ISSUE THREAD

**Issue by moeKiwiSAMA** [VolmitSoftware/Iris#759]
### Problem

Just installed the plugin.
Particle floats in the sky.

![pic](https://i.ibb.co/JvNdMJ9/photo-2022-03-09-22-05-28.jpg)

They are not on sand.

### Minecraft Version

1.18

### Iris Version

2.0.0-1.18.X

### Log

https://mclo.gs/kATyacz

**Comment by xIRoXaSx** [comment]
Just search `particleEffect` in the pack files (e.g. VS Code `CTRL + SHIFT + F` => search all) and remove the complete JSON Object.

**Comment by ghost** [comment]
Probably due to the height shift

**Comment by NextdoorPsycho** [comment]
Fixed in next update
