### ISSUE TITLE
Pregen error 1.18.1

### ISSUE THREAD

**Issue by MrNipz** [VolmitSoftware/Iris#762]
### Problem

1. iris was working fine loading chunks and all that stuff so i started a pregen 50k by 50k
2. was working fine left it over night came back and seen this
[2022-03-11-2.log.gz](https://github.com/VolmitSoftware/Iris/files/8233492/2022-03-11-2.log.gz)
3. i cant paste the log on the sites you recommend its 3gb big in storage ill crash if i copy and paste it!

### Minecraft Version

1.18

### Iris Version

Iris-2.0.0-1.18.X.jar

### Log

https://mclo.gs/Ot4qVFU

**Comment by MrNipz** [comment]
Other info:
server Ram: 5gb
Plugins: 66
its bungeecord linked

**Comment by TheHappyHopper** [comment]
Having the same issue, persists on iris 2.0.1 with latest purpur for  1.18.1, pregen crash is inevitable when rendering large worlds, makes iris unviable for large servers however i find that if i kill the server instance then restart it and continue the pregen i am able to sort of get it to work between crashes.

**Comment by ghost** [comment]
You can just use chunky to pregen

**Comment by TheHappyHopper** [comment]
> You can just use chunky to pregen

No You cant, after a while that too will crash the server

**Comment by NextdoorPsycho** [comment]
Iris needs 4gb MINIMUM for itself if you wanna smooth pregen, you have 15+ HEAVY plugins that are doing loads of checks on generate, and you are running out of memory. try disabling all of the plugins other than iris, and generate. then consider not generating a **50 THOUSAND by 50 THOUSAND** dimension on a 5gb server. that on vanilla will not be able to support itself, let alone another generator. 

Also Check your java Args
