### ISSUE TITLE
Iris Crashing

### ISSUE THREAD

**Issue by July7th** [VolmitSoftware/Iris#765]
### Problem

1. IInstall Iris on 1.17.1 purpur
2. Teleport to Iris worlds
3. wandering around the world
4. Server crashes
_________________________________

### Minecraft Version

1.17.1

### Iris Version

1.9.5

### Log

https://paste.ubuntu.com/p/K7xVs8HBKZ/

**Comment by NextdoorPsycho** [comment]
Reopen with a full log, not a crash report. and ill look at it, or ask for help in the server

**Comment by July7th** [comment]
> 



> 使用完整日志（而不是崩溃报告）重新打开。和生病看它，或在服务器中寻求帮助

logs: https://paste.ubuntu.com/p/8gNdTpqCVP/
Nearby logs: https://paste.ubuntu.com/p/mrQpfq2C6T/
