### ISSUE TITLE
Worlds generated freshly in 1.18.2 will be entirely vanilla.

### ISSUE THREAD

**Issue by NotAShelf** [VolmitSoftware/Iris#766]
### Problem

1. Create a new folder and place your server jar into the folder
2. Start your server with `java -jar server.jar --nogui`
3. Stop your server
4. Place Iris jar in the plugins directory
5. Edit bukkit.yml to override overworld with Iris overworld
6. Start your server, restart if you'd like.
7. Join your server and see your overworld
8. profit
![2022-03-16_18 20 37](https://user-images.githubusercontent.com/62766066/158625533-9b97a171-844f-4cdf-8c17-e2783ead706a.png)

### Solution

My personal guess (and observation) is that the datapacks need to be updated for 1.18.2, as Iris does not generate custom biomes.

### Minecraft Version

1.18

### Iris Version

~~latest~~ 2.0.2-1.18.X

### Log

https://mclo.gs/J16A2ub

**Comment by NotAShelf** [comment]
@NextdoorPsycho here are the logs and the bug report, as promised

**Comment by NextdoorPsycho** [comment]
Temp fix, is to use a 1.18.1 version of purpur, 1.18.2 seems to break colors

**Comment by NotAShelf** [comment]
closing as v2.0.3 fixes this bug
