### ISSUE TITLE
Iris Crashing

### ISSUE THREAD

**Issue by July7th** [VolmitSoftware/Iris#767]
### Problem

1. Install Iris on 1.17.1 purpur
2. Teleport to Iris worlds
3. wandering around the world
4. Server crashes
————————————————————————
logs: https://paste.ubuntu.com/p/8gNdTpqCVP/
Nearby logs: https://paste.ubuntu.com/p/mrQpfq2C6T/

### Minecraft Version

1.17.1

### Iris Version

1.9.5

### Log

https://paste.ubuntu.com/p/8gNdTpqCVP/

**Comment by NextdoorPsycho** [comment]
Try on Latest, This issue was resolved i believe
