### ISSUE TITLE
Server randomly crash

### ISSUE THREAD

**Issue by Broascaa** [VolmitSoftware/Iris#770]
### Problem

Sometimes the server randomly crash when players are exploring new chunks.. I already talked with the support team but we couldn't find a fix..

Crash report:
> Time: 3/17/22, 7:11 PM
> Description: Exception in server tick loop
> 
> java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
> 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
> 	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58)
> 	at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91)
> 	at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146)
> 	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: net.minecraft.ReportedException: Exception generating new chunk
> 	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$35(ChunkTracker.java:1249)
> 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
> 	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1230)
> 	... 9 more
> Caused by: java.util.ConcurrentModificationException
> 	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
> 	at java.base/java.util.HashMap$KeyIterator.next(Unknown Source)
> 	at org.bukkit.craftbukkit.v1_18_R1.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:216)
> 	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:125)
> 	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus.java:342)
> 	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:273)
> 	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$35(ChunkTracker.java:1232)
> 	... 11 more

You can find the full log bellow.

Thanks!

### Solution

Chunk generation? I don't know

### Minecraft Version

1.18

### Iris Version

Iris v2.0.1-1.18.X by Volmit Software

### Log

https://mclo.gs/vv3Iwf8

**Comment by NextdoorPsycho** [comment]
I dont see the crash or anything that would suggest an issue, but im going to close this. Please try on latest if you can, and if you are able to do it, Tag me on Discord, or open another issue, as we changed a bit for the latest
