### ISSUE TITLE
vanilla mob spawn blocks and spawn eggs do nothing

### ISSUE THREAD

**Issue by Apophissss** [VolmitSoftware/Iris#771]
### Problem

try to use a spawn egg or mob spawner?

### Solution

no idea?

### Minecraft Version

1.18

### Iris Version

2.0.2

### Log

https://www.toptal.com/developers/hastebin/abaficikan.yaml

**Comment by NextdoorPsycho** [comment]
Give me a log and try it with JUST iris and like rift or whatever your preferred world manager is (even bukkit if you want) and try and post that log please
