### ISSUE TITLE
Jigsaw editor doesn't render the object

### ISSUE THREAD

**Issue by rglautaro** [VolmitSoftware/Iris#773]
### Problem

This issue was reproduced in my local environment with "Purpur 1.17.1 + Iris 1.9.5" and with "Purpur 1.18.1 + Iris 2.0.2"

### Piece creation scenario
2. Create any object `/iris object save name=test ...`
3. Create a jigsaw piece `/iris jigsaw create object=test ...`
4. The jigsaw editor paints the particules around where the border of the object should be, but the object itself is not rendered

### Piece edition scenario
1. Create a jigsaw piece using 1.16 version of minecraft (Iris 1.3.11-FINAL), where the jigsaw editor works
2. Copy your jigsaw piece inside you 1.17/1.18 dimension
3. Edit the jigsaw piece `/iris jigsaw edit piece=test`
4. The jigsaw editor paints the particules around where the border of the object should be, but the object itself is not rendered

![image](https://user-images.githubusercontent.com/14943102/159170427-115c5a56-d87b-47ae-9e9c-8048ab0f0781.png)

### Minecraft Version

1.18

### Iris Version

1.9.5 / 2.0.2

### Log

https://pastebin.com/raw/kEqeKPX0

**Comment by StealthMuskrat** [comment]
Got same problem, created some objects then after running the jigsaw create command got an error and got the outline of the object to appear like in the above pic.

https://pastebin.com/raw/jmJyNRXw

**Comment by NextdoorPsycho** [comment]
The latest update should have helped fix that, we are going to readd the old Jig system and redo this one so for now we have bandaid patches
