### ISSUE TITLE
Bonemeal'd tree growth replaces existing blocks

### ISSUE THREAD

**Issue by tomasgareau** [VolmitSoftware/Iris#774]
### Problem

In an Iris-generated world, I tried creating the tree farm described in this video:

https://www.youtube.com/watch?v=6MLc1RaySfg

A cross-section of the farm looks like so:

```
[P]
[P]
[P]
[P]
[P]
[S][D]
```

where [P] = piston, [S] = stone, [D] = dirt.

The farm works by planting an **oak** sapling in the dirt, slapping some bonemeal on it, and using the pistons to push out the trunk after it grows. This is expected to grow something like this:

```
[P][T]
[P][T]
[P][T]
[P][T]
[P][T]
[S][D]
```

However, in this Iris world, the trunk grew much wider & _replaced_ a bunch of the farm's blocks:

```
[T][T]
[T][T]
[T][T]
[T][T]
[T][T]
[S][D]
```

I understand if this kind of farm might not be doable with Iris's tree generation (fair enough) but would expect the tree growth not to replace existing blocks -- thought I'd post here to see if you guys had any thoughts!

### Environment
Minecraft 1.18
Paper version `git-Paper-66 (Git: dce79f3)`
Iris commit c3cac7d

**Comment by NextdoorPsycho** [comment]
Report this on the Overworld Pack please, Iris jar not the place for Pack issues

**Comment by svdgoor** [comment]
Except that the plugin is the one placing the trees and hence replacing/breaking the blocks

**Comment by NextdoorPsycho** [comment]
Its the objects and how im placing them in the pack, stop opening this issue

**Comment by svdgoor** [comment]
Trees placed by Iris should not replace blocks. What do you mean that's a pack problem?
