### ISSUE TITLE
Critical generation bugs with any packs!

### ISSUE THREAD

**Issue by Schlawongel** [VolmitSoftware/Iris#776]
### Problem

Hello,

1. I have installed **Iris v2.0.3-1.18.2** on a new fresh **git-Purpur-1603** server on a **hosted Debian 11 VPS** (mc-server was in offline mode to use waterfall network)

2. I have tried both generation options:
    - first: replacing default world (no other plugins installed)
    - second: generating a world with the Rift plugin (only Iris and Rift installed)
    The following bug appears in both tries.
 
3. First time I startet the mc-server with Iris installed it was restarted automatically by Iris
    (I think to get the Iris datapacks, second start - works fine/77 custom biomes)

4. I entered the world and saw that some small structures like trees and logs are generating in the air 
    (all about height 180-195 ( about 50 sometimes to 100 blocks above the ground))

![2022-03-29_18 02 33](https://user-images.githubusercontent.com/102612341/160720749-2998ee91-5baf-45d1-afdf-be45c2d3468e.png)

![2022-03-29_18 03 37](https://user-images.githubusercontent.com/102612341/160720781-949341ff-976f-4514-92a5-fa9f10156cab.png)

5. I asked for help in the iris-support dc channel and a normal user responded (Fluffy kirby#3947) and we tried some things.
    - He said the bug also appears to him with the same Iris and Purpur version (but only at the spawn region) 
 
6. I've changed spawn protection in server.properties to 0, restarted the server and generated a new world with Rift...
(btw generating Iris:overworld with Rift doesnt work for me (no ":" work). I can only use /rift create <NAME> Iris (but i also tried with no plugins by replacing default world) - That doesn't fixed it.

7. I've traveled a bit around a saw a hole forrest flying in the air... (so I think its not only the spawn region)

![2022-03-30_00 43 10](https://user-images.githubusercontent.com/102612341/160720827-a757e71f-c8a2-4ff0-be13-acee16e91a8c.png)

The user I met in the support channel said he uses Iris 2.0.3 and git-Purpur-1602 and it works, but he said it could be luck.

I hope this gets fixed asap because Iris is a wonderful piece of code! I rlly love it!

My Discord: レ丹尸工亡廾凵#3567 / 612336917304049715
The user: Fluffy kirby#3947 / 533614041663537173

### Solution

Maybe some kind of 1.18 world generation thing?
(Cause the structures are generating all almost at the same height (just way to high)

### Minecraft Version

1.18

### Iris Version

2.0.3-1.18.2

### Log

https://pastebin.com/PuzhYB5m

**Comment by Schlawongel** [comment]
Pregenerating a new world with Chunky or Iris doesn't change anything

**Comment by NextdoorPsycho** [comment]
Can you Try on LATEST, everything? With Just Iris installed (and any world managers you might have) Absolute Minimum, and latest everything

**Comment by H9912** [comment]
Coco from the Support Staff told me that the spigot version wasn't bugged, so i tried and it works for me
![image](https://user-images.githubusercontent.com/77928587/161401400-e1a2e4f1-70e3-4021-9869-c6690798a9b2.png)
(Same version : Iris 2.0.3)

**Comment by XINGO0123** [comment]
Did you solve it? I also met this situation on purpur1.18.2.

**Comment by Schlawongel** [comment]
> Can you Try on LATEST, everything? With Just Iris installed (and any world managers you might have) Absolute Minimum, and latest everything

I tried again with latest Iris and Purpur (and rift as world-mgm installed): same bug...
I tried again with latest Iris and SPIGOT (and rift again) and this happened:

![image](https://user-images.githubusercontent.com/102612341/161405554-6ed18bd5-c580-4b5b-93b1-6463e4a6b0a8.png)

This time there are also some error-messages in the console but I thinks that's normal cause it isn't a paper/purpur server right?

**Comment by Schlawongel** [comment]
BTW THE BUG DOES NOT APPEAR IN IRIS VERSION 2.0.2-1.18.X !
-------------------------------------------------------------------
(This was already said I discord but I just wanted to put this information here as well)

**Comment by Schlawongel** [comment]
I also tried with the "new horizon" pack - same bug

**Comment by svdgoor** [comment]
This very issue has reportedly not occured on any servers running the official version from Spigot. Perhaps try that.

**Comment by Schlawongel** [comment]
> This very issue has reportedly not occured on any servers running the official version from Spigot. Perhaps try that.

You mean the paid version? I thought this is the same (just to support).

**Comment by svdgoor** [comment]
Yes, I mean the paid version.

**Comment by Schlawongel** [comment]
Okay then I will wait for more user reports cause I don't wanna pay for a buggy plugin.
But I'm sure I'll buy Iris when the bug is really fixed or I have proof that the spigot version works.

**Comment by NotAShelf** [comment]
I can confirm for you that spigot version *does* work. I've encountered the same issue and switching to the spigot version fixed the issue.

**Comment by NextdoorPsycho** [comment]
> Okay then I will wait for more user reports cause I don't wanna pay for a buggy plugin. But I'm sure I'll buy Iris when the bug is really fixed or I have proof that the spigot version works.

try latest Git, but thanks for your words of encouragement, tested myself, it was an issue i made, like right after making the spigot version that i assumed would be a non-issue 
Latest dev branch*
