### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by LudovicAns** [VolmitSoftware/Iris#779]
### Problem

1. Installed Iris
2. Pre generate the world
3. Look `/spark heapsummary` every 10 minutes and see ...

+300 MB in less of 10 minutes (this not happen when I remove Iris from the server)
![heapsummary](https://user-images.githubusercontent.com/64146252/161563173-2a2a2f36-96b3-4ec8-bb64-8cab9ca076ec.png)

Few hours later :
![heapsummary2](https://user-images.githubusercontent.com/64146252/161609863-0dc0892d-cdd0-451e-8109-6639b37231f4.png)

### Solution

No idea but I'm sure it come from Iris plugin. If I remove the plugin I have no more leaks on my server.

### Minecraft Version

1.18.2

### Iris Version

2.0.3-1.18.2

### Log

https://mclo.gs/P7UadNh

**Comment by NextdoorPsycho** [comment]
if you are using the Studio/making worlds/teleposting into and out of worlds There will be a memory leak, thats just how MC works not sure if we can do anything, as those leaks could just be the Iris overwritten Mc systems, ill look into it / pass it on, thanks for the report

**Comment by WillFP** [comment]
More information about memory leaks: Iris makes up anywhere from 40-80% of my memory usage (it's garbage collected easily, however with a lot of players I can easily see this causing OOM errors) - rising anywhere between 600MB (after a GC, as in this heap dump) to 6-7GB (before a GC, unfortunately spark can't generate heap dumps without GCs)

I've uploaded the pre-GC heap dump here if you want to have a look at it: https://mega.nz/file/38FjUYpJ#IEDkdMLpE5ECahY5u0NVTLdcqsirAATmOVx4SKsaxOA

And a link to a couple heap summaries: one pre-gc, one post-gc
Pre-GC heap summary: https://spark.lucko.me/11mRFBGuDl
Post-GC heap summary: https://spark.lucko.me/ZCZPGVyDxc

Some screenshots of the post-GC heap dump:
![image](https://user-images.githubusercontent.com/38837418/170031606-e9897a95-dafd-4b8b-8063-76bc295c0b90.png)
![image](https://user-images.githubusercontent.com/38837418/170031630-7e5ebe47-02f0-4193-9ea6-97a0d83989b3.png)
![image](https://user-images.githubusercontent.com/38837418/170031636-b08def83-a8d5-4061-b3a8-e99f95679b30.png)

And some of the pre-GC ones (unfortunately much more memory usage, looks like it wasn't too long after another GC, and it's too big to upload to mega)
![image](https://user-images.githubusercontent.com/38837418/170031925-b50b610c-bd2c-4ac9-a4a7-3e512c4eb2c9.png)
![image](https://user-images.githubusercontent.com/38837418/170032044-074b8568-e7f3-4a42-8f8e-7bc648eaae43.png)

**Comment by WillFP** [comment]
Additional info: this is on a 20k x 20k **fully pregenerated** world - and I've seen other users get OOM crashes, so I'm pretty sure this should be high priority

**Comment by Skjolberg** [comment]
I have the same problem as Will. Version: 2.1.1 (last). I can't keep the server open for 30 min at least with online players.

**Comment by itorz7** [comment]
my version 2.1.1 has the same problem :((

**Comment by NextdoorPsycho** [comment]
Actively Looking at this

**Comment by Skjolberg** [comment]
Best of luck to the team! This is a very serious and worrying bug for those of us who have a server with this version at the moment.

**Comment by NextdoorPsycho** [comment]
@Skjolberg  i Added you on discord btw

**Comment by NextdoorPsycho** [comment]
If any of you are willing to try this please let me know on discord and I'll give you a jar. Assuming that you have a way to reliability cause it

**Comment by NextdoorPsycho** [comment]
https://github.com/VolmitSoftware/Iris/releases/tag/2.1.2-1.18.2
If you still have a memory leak AFTER this version, reopen this or make a new issue, but this was a pretty big one. Thanks @Skjolberg @itorz7 @WillFP and @LudovicAns 
Lemme know if it persists
