### ISSUE TITLE
Bug: Floating structure

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#78]
![afbeelding](https://user-images.githubusercontent.com/65736624/96472780-25b13500-1231-11eb-9c8e-1a12f54d4e50.png)

**Comment by NextdoorPsycho** [comment]
i dont know where this is, or what it is

**Comment by svdgoor** [comment]
https://discordapp.com/channels/189665083817852928/767020043527389245/767876738993750067

**Comment by svdgoor** [comment]
Not enough information
