### ISSUE TITLE
dust of revealing broken

### ISSUE THREAD

**Issue by nottapsycho** [VolmitSoftware/Iris#783]
### Problem

running a fresh install of iris 2.0.5 on the latest build of purpur. the dust doesn't do anything except make a sound.

### Minecraft Version

1.18

### Iris Version

2.0.5

### Log

n/a

**Comment by NextdoorPsycho** [comment]
Bandaid fixed, itll tell you what the object is, just not glow.
Expect this fix soon on update 2.1.0
