### ISSUE TITLE
Please return Oraxen support!

### ISSUE THREAD

**Issue by Soupborsh** [VolmitSoftware/Iris#784]
### Adding, Removing, or Changing

Adding

### Type of Modification

Please return Oraxen support!

### What are you trying to modify

I need this plugin because of Oraxen, I don't need this plugin without Oraxen support. Please do it faster

### Alternatives

Return Oraxen support faster please if you can

**Comment by svdgoor** [comment]
It's working right now. New version will release to Spigot after initial bugtests complete.
