### ISSUE TITLE
Prevent updating Iris when worlds exist made with older versions

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#792]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to prevent people from updating, breaking their worlds, and crying about it later

### What are you trying to modify

The way I would implement this is storing in each world what Iris version made it and stopping the server if a different Iris versions tries to load them, unless a setting in the config is set to true.

### Alternatives

If this could not be implemented I would have to help every poor chap that didnt make a backup and then destroyed their world by giving them a shoulder to cry on.

**Comment by NextdoorPsycho** [comment]
no, read staff chat papi
