### ISSUE TITLE
EcoEnchants Chests Loot

### ISSUE THREAD

**Issue by Dani3lFTW** [VolmitSoftware/Iris#797]
### Adding, Removing, or Changing

Adding

### Type of Modification

Chests Loot

### What are you trying to modify

I would really appreciate it if you could add support for ecoenchants so that the enchantments are generated in the chests loot.

**Comment by svdgoor** [comment]
![image](https://user-images.githubusercontent.com/65736624/171194499-3ee31c7e-6227-47f7-b2dd-3b6ae7434262.png)
