### ISSUE TITLE
Upgrade from a previous version on an already generated world breaks find command for strongholds and eyes of ender points to wrong places

### ISSUE THREAD

**Issue by IncognitoAnkh** [VolmitSoftware/Iris#799]
### Problem

Inclusive if the upgrade is an small jump like in this case (2.1.1 to 2.1.2) things break in already generated worlds like the find command. 

1- Create a world on a previous iris version (2.1.1) using the new overworld generator
2- use command find to find an stronghold
3- upgrade to iris 2.1.2
4- try to use find command again to find an stronghold and you will se it teleports you to a wrong place, eyes of ender point to this wrong places so it's not an option. 

### Minecraft Version

1.18

### Iris Version

2.1.2

### Log

https://mclo.gs/e1RQumj

**Comment by svdgoor** [comment]
Then don't update. We have this very clearly everywhere
Sorry that this happened but there is not something we can do about it. More info on the wiki

**Comment by IncognitoAnkh** [comment]
![IMG_20220620_092453](https://user-images.githubusercontent.com/50669359/174624195-d94c188c-82e2-457d-a3fc-03232f7615cb.jpg)

![IMG_20220620_092522](https://user-images.githubusercontent.com/50669359/174624265-2e5b2c7e-d504-43ce-830f-4d60ba2a5aa2.jpg)

![IMG_20220620_092655](https://user-images.githubusercontent.com/50669359/174624409-1898202e-45b2-4319-ba63-85720f28dbdc.jpg)

![IMG_20220620_092827](https://user-images.githubusercontent.com/50669359/174624482-9227d1cf-4ee7-465a-bfe8-48d6c6b8bded.jpg)

![IMG_20220620_092853](https://user-images.githubusercontent.com/50669359/174624538-0ea6e2b6-e020-4a5c-b198-1a523db7a39d.jpg)

I already read the wiki and was aware of the update issue, that's why I consulted with support and this is the answer I received.

Well... thanks for giving me that fantastic solution and making me feel stupid for nothing I guess, have a nice day.

**Comment by svdgoor** [comment]
@NextdoorPsycho you're up pal

**Comment by Senkai350** [comment]
Same problem but stuctures don't spawn generally, on clean server without updates. (ender's eye don't work too)
version: Iris-2.2.5-1.19
![изображение_2022-07-23_184209052](https://user-images.githubusercontent.com/89925616/180612215-16645bf5-8c47-46ae-ae42-37f48db313d8.png)

**Comment by ghost** [comment]
Most likely this is happening due to this problem https://github.com/VolmitSoftware/Iris/issues/714
Therefore i think this is a duplicate

**Comment by Vatuu** [comment]
Strongholds are fixed in the next version, thus this should be resolved as well.
