### ISSUE TITLE
Bug: Spawning ruins are too large (In my and @TheDevelon's opinions)

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#80]
![afbeelding](https://user-images.githubusercontent.com/65736624/96474239-e257c600-1232-11eb-8d66-e44f6cb788fc.png)

One of many occurances of overly large ruined village structures.
Would be nice to have the size reduced, if possible.

**Comment by TheDevelon** [comment]
![image](https://user-images.githubusercontent.com/28627992/96474767-71fd7480-1233-11eb-8e4d-896645a6e7b3.png)

**Comment by NextdoorPsycho** [comment]
if you are submitting a bug please remove shaders so i can see whats going on
