### ISSUE TITLE
Cave Generation 

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#805]
### Problem

1. Install Iris...
2. make a cave large cave in vscode 
3. test it and see 
4. Observe the caves...
![Schermafbeelding 2022-06-15 om 09 27 18](https://user-images.githubusercontent.com/107539181/173774736-2a09441c-84e1-4a58-b6ff-3ef05e73e230.png)
![image](https://user-images.githubusercontent.com/107539181/173774855-6c23994f-4d2b-4a5b-8ff2-00b55d22e082.png)

( idk for sure but I think this bug effects maxdistance as well cave setting )

### Minecraft Version

1.18

### Iris Version

Iris version: 2.1.3

### Log

*

**Comment by Vatuu** [comment]
After rigorous testing, were unable to replicate. Seems to be fixed in 1.19?
