### ISSUE TITLE
Iris Studio

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#806]
### Problem

1. Install Iris...
2. Do /iris studio ( doesn't matter )
3. Do /iris studio close ( before it hits 100% )
4. The loading message freezes in ur screen and won't disappear 

### Minecraft Version

1.18

### Iris Version

iris 2.1.3 

### Log

*

**Comment by svdgoor** [comment]
Confirm

**Comment by RePixelatedMC** [comment]
![Schermafbeelding 2022-06-15 om 12 51 40](https://user-images.githubusercontent.com/107539181/173810361-83d5ddb8-d43d-4b7b-a64f-def98a32896c.png)

**Comment by NextdoorPsycho** [comment]
Wont fix, dont kill it midway through, this is backburner as far back as it can go
maybe later we'll fix, in the mean time dont eject the CD's midway through

**Comment by svdgoor** [comment]
But what if you make an edit in VSCode, forget to save, open a studio world and then notice a shit ton of errors, and then have to wait for 2 minutes before your server is ready again?

**Comment by RePixelatedMC** [comment]
> But what if you make an edit in VSCode, forget to save, open a studio world and then notice a shit ton of errors, and then have to wait for 2 minutes before your server is ready again?

You get it thats exactly my issue

**Comment by NextdoorPsycho** [comment]
> But what if you make an edit in VSCode, forget to save, open a studio world and then notice a shit ton of errors, and then have to wait for 2 minutes before your server is ready again?



> > But what if you make an edit in VSCode, forget to save, open a studio world and then notice a shit ton of errors, and then have to wait for 2 minutes before your server is ready again?
> 
> You get it thats exactly my issue

Have less plugins on your server, this should be on your local and if you have 75plugins on your server and you are trying to make a NEW world and make a ton of changes removing plugins would help speed that up too. just restart the server

**Comment by svdgoor** [comment]
I literally have 5.

But that's besides the point. If you really need to kill your studio, I usually just kill the server and let it autoboot again

But regardless of all that, why do we not make a pack integrity check when we boot up the studio (and while hotloading too)? It would save everyone a lot of restarts and force kills of the server.

Also - this could help with identifying issues ("failed to parse 'lo' biome at x y z" flashbacks)

**Comment by NextdoorPsycho** [comment]
> I literally have 5.
> 
> But that's besides the point. If you really need to kill your studio, I usually just kill the server and let it autoboot again
> 
> But regardless of all that, why do we not make a pack integrity check when we boot up the studio (and while hotloading too)? It would save everyone a lot of restarts and force kills of the server.
> 
> Also - this could help with identifying issues ("failed to parse 'lo' biome at x y z" flashbacks)

Working in the studio is the integrity check. Like if you are using VSCode and the studio as intended the integrity check is the red underlines and flashy colors that the studio does. 

If you want to fix this you can, and ill pull it, but if you are actively preventing something from doing an automated task the unintended way and complaining that there is a problem, that's not our problem, restart, reload, or use the software as intended as referenced in the Getting started lol
