### ISSUE TITLE
Iris PlaceholderAPI placeholders do not parse.

### ISSUE THREAD

**Issue by RealTriassic** [VolmitSoftware/Iris#807]
### Problem

1. Install Iris & PlaceholderAPI.
2. Run `/papi parse me %iris_biome_name%`.
3. Observe the problem.

### Minecraft Version

1.18

### Iris Version

v2.1.3-1.18.2

### Log

https://mclo.gs/95PeorO

**Comment by svdgoor** [comment]
I think it's `%iris_biome%` but I'm not sure on that. In either case it's probably better to simply get the biome found in f3 as well, since that is more (dependent on the Iris plugin)

**Comment by Vatuu** [comment]
Fixed in the next version.
