### ISSUE TITLE
Spawning future feature idea

### ISSUE THREAD

**Issue by CeeVeeR** [VolmitSoftware/Iris#809]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to control mob spawns with zones (other than biomes) after the spawning system rework.

### What are you trying to modify

The way I would implement this is a way for iris to handle specific spawn locations for mobs. Other than biomes and random image maps or vanilla derivities. 

It might exceed the scope of iris as an engine. Maybe it would be better as an addon idea, but let me explain the concept further.

I am sure a big part of iris packs is the abillity to create immersion, thus, replicating nature would be a good attempt.

Specific groups of mobs can be assigned "rotations". Just like migrating birds, mob groups can be assigned a biome they migrate to (depending on the moon phases https://minecraft.fandom.com/wiki/Moon)

Why should you make this work in iris? Because outside implemintations would cause a lot of lag, defining polygonal shapes is hard for the common plugin drag and drop enjoyer. Thats why noise maps could be used for this,  or region/biome locations

This might be very nieche, but it might be an interessting addition to Iris.

### Alternatives

If this could not be implemented I would ask for this to be a plugin or maybe write something independed.

**Comment by svdgoor** [comment]
This would indeed be better for an add-on. You can very easily hook Iris into something else using Scripts, which still allows you to do very complex polygon math without significant slowdown. If you need more help with that contact us on Discord.
