### ISSUE TITLE
Issue with Iris when enabling the server

### ISSUE THREAD

**Issue by SundayMC** [VolmitSoftware/Iris#812]
### Problem

1. Install Iris :p
2. Enable the server

### Solution

/

### Minecraft Version

1.18

### Iris Version

2.1.3-1.18.2

### Log

https://mclo.gs/BtMrr8Z

**Comment by SundayMC** [comment]
I had forgotten to remove another generation plugin
here is another version of the log : https://mclo.gs/OVudGVd

**Comment by svdgoor** [comment]
You have to use paper or purpur (recommended) with Iris.
Spigot is incompatible.
Please contact us through discord first next time for faster help.

**Comment by svdgoor** [comment]
Or just read the wiki ofc. It says the same thing.
