### ISSUE TITLE
Vines Can't be placed correctly 

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#815]
### Problem

Just load some chunks in overworld and find some vines and you'll see them incorrect placed.
This isn't probably just a overworld issue cause I have the same issue in my own pack as well.

Ignore Minecraft version below I can't select the option 1.19

### Solution

*

### Minecraft Version

1.18

### Iris Version

Iris 2.2.0 ( spigot ) 

### Log

*

**Comment by NextdoorPsycho** [comment]
ill need to see an image

**Comment by RePixelatedMC** [comment]
![2022-07-05_09 37 48](https://user-images.githubusercontent.com/107539181/177275331-5f413077-5175-4e50-b6ec-3060a1b0d1c4.png)

**Comment by Vatuu** [comment]
Fixed in 2.2.4
