### ISSUE TITLE
Advancement

### ISSUE THREAD

**Issue by Comquister** [VolmitSoftware/Iris#818]
### Adding, Removing, or Changing

Adding

### Type of Modification

add advancement to worlds

### What are you trying to modify

I would put it as an addon/complementation

Datapack Exemple: [Here](https://www.planetminecraft.com/data-pack/blazeandcave-s-advancements-pack-terralith-version/)

**Comment by RePixelatedMC** [comment]
The are plugins for this it doesn’t fit iris ngl

**Comment by NextdoorPsycho** [comment]
We aren't a data pack-driven Content maker, we generate worlds and that's it. anything more is out of courtesy like pregenning or auto doing data packs to stitch colors.
