### ISSUE TITLE
Out of Bound

### ISSUE THREAD

**Issue by NotZer0Two** [VolmitSoftware/Iris#822]
### Problem

1. Put iris on the server
2. make it generate World

### Minecraft Version

1.18

### Iris Version

2.2.3

### Log

https://mclo.gs/95pbSVj

**Comment by NotZer0Two** [comment]
The version is 1.19 but i selected the latest possible

**Comment by NotZer0Two** [comment]
the log is 40 minutes long but i didn't put the same thing again continues for 40 minutes all that out of bound

**Comment by NextdoorPsycho** [comment]
Don't use the 1.19 jar on 1.18?
and you get out of bounds as of 1.19 for data packs needing to be updated. we are setting bounding boxes differently on 1.19 the jar version IS critical for your issues to be resolved. however as of LATEST jar and latest game the problems are gone
