### ISSUE TITLE
World creation off main thread

### ISSUE THREAD

**Issue by CDFN** [VolmitSoftware/Iris#825]
Hey, I was wondering if we can generate worlds completely off main thread. I tried running creator in other thread, however Iris seems to be internally falling back to main. I used following code:
```kt
            plugin.schedule(SynchronizationContext.ASYNC) {
                val world = IrisToolbelt.createWorld()
                    .name(data.id.toString())
                    .dimension("overworld")
                    .pregen(PregenTask.builder()
                        .center(Position2(0, 0))
                        .width(10)
                        .height(10)
                        .build()
                    )
                    .create()
                switchContext(SynchronizationContext.SYNC)
                sender.teleport(world.spawnLocation)
            }
```

Synchronous world generation (at least that first stage) causes insane lag for few seconds which is unacceptable in my use case. Is there any possibility to have it working off main thread?

**Comment by NextdoorPsycho** [comment]
Because of how bukkit does things, we are required to do it this way, as we need to use the container to force the world to be made so doing it in the background is not feasible for us at least in the current state. Feel free to reopen if i got anything wrong  / if i misunderstood

**Comment by svdgoor** [comment]
From my understanding Iris 3 will do this better.
I think we may store block data ourselves and then - when the server requests pregenned chunks - provide the already-ready data.
