### ISSUE TITLE
Caves half generated 

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#831]
<img width="1680" alt="Schermafbeelding 2022-07-22 om 13 55 37" src="https://user-images.githubusercontent.com/107539181/180434638-36b94494-d510-44a4-99b5-2eaa16a91ae7.png">
 Iris 2.2.4 1.19 

Pack:
[Abyss.zip](https://github.com/VolmitSoftware/Iris/files/9167519/Abyss.zip)
 
Note: it looks like it only happens at specific conditions I can't recreate them at will it happens randomly

**Comment by svdgoor** [comment]
Known issue. Likely to be only resolved in Iris 3. Thanks for the report, I think we didn't have this in here before.

**Comment by NextdoorPsycho** [comment]
Known, Duplicate:
https://github.com/VolmitSoftware/Iris/issues/805
We're working on it, just dont know how to consistently cause it
