### ISSUE TITLE
Sculk veins Bug out in objects when on walls

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#833]
### Problem

<img width="1680" alt="Schermafbeelding 2022-07-25 om 18 28 26" src="https://user-images.githubusercontent.com/107539181/180828721-c7261c17-5ed8-4ef6-b9fa-8c23f0d4c40d.png

### Solution

*

### Minecraft Version

1.19

### Iris Version

Iris 2.2.4 

Edit: This is kinda a big issue for me cause this makes my whole pack basically unusable 

Oh and if I do /iris objects paste etc it works without any issues

**Comment by NextdoorPsycho** [comment]
Thank you!
We are probably going to need to make a PR to Craftbukkit for this lol
Or we are doing something wrong

**Comment by svdgoor** [comment]
Fixed on latest

**Comment by svdgoor** [comment]
(latest github release, not yet on spigot, will be soon tm)

**Comment by RePixelatedMC** [comment]
Im so happy actually i can finally get back to my dimension en work further on it cant wait to release it will probably take a lot of time tho. 

Edit: A sorry just realized that i revived this topic

**Comment by svdgoor** [comment]
@Vatuu why

**Comment by Vatuu** [comment]
@CocoTheOwner Because it is not fixed yet.

**Comment by Vatuu** [comment]
Fixed in 2.2.6.
