### ISSUE TITLE
ForceBlock doesn't work

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#834]
### Problem

There is not much explaining to do right? 
![Schermafbeelding 2022-07-26 om 13 41 04](https://user-images.githubusercontent.com/107539181/180997502-73860a8d-d07c-49ab-9573-c8e557e15412.png)

Vscode I tried with force place but that didn't work as well 
<img width="1136" alt="Schermafbeelding 2022-07-26 om 13 41 48" src="https://user-images.githubusercontent.com/107539181/180997802-e5d8fd46-6aa6-41d9-83b1-c99607d38330.png">

### Solution

*

### Minecraft Version

1.19

### Iris Version

Iris 2.2.5 

### Log

*

**Comment by NextdoorPsycho** [comment]
Interesting, will look into

**Comment by svdgoor** [comment]
@RePixelatedMC Did you also enable `forcePlace`? It's a prerequisite.

**Comment by RePixelatedMC** [comment]
I literally said that lol i have tried that as well

**Comment by Vatuu** [comment]
Please verify that this is still an issue in 2.2.17.

**Comment by RePixelatedMC** [comment]
All fixed rn thx
