### ISSUE TITLE
msg error

### ISSUE THREAD

**Issue by dinobossytnew** [VolmitSoftware/Iris#835]
### Problem

1. Install iris yes.
2. software paper 1.19
4. [Observe the error...
](https://mcpaste.io/506c0bd7f560cd0b)

### Solution

not se...

### Minecraft Version

1.19

### Iris Version

v2.2.5-1.19

### Log

https://mcpaste.io/506c0bd7f560cd0b

**Comment by ghost** [comment]
> ### Problem
> 1. Install iris yes.
> 2. software paper 1.19
> 3. [Observe the error...
>    ](https://mcpaste.io/506c0bd7f560cd0b)
> 
> ### Solution
> not se...
> 
> ### Minecraft Version
> 1.19
> 
> ### Iris Version
> v2.2.5-1.19
> 
> ### Log
> https://mcpaste.io/506c0bd7f560cd0b

What’s petal? This is clearly not paper

**Comment by NextdoorPsycho** [comment]
> ### Problem
> 1. Install iris yes.
> 2. software paper 1.19
> 3. [Observe the error...
>    ](https://mcpaste.io/506c0bd7f560cd0b)
> 
> ### Solution
> not se...
> 
> ### Minecraft Version
> 1.19
> 
> ### Iris Version
> v2.2.5-1.19
> 
> ### Log
> https://mcpaste.io/506c0bd7f560cd0b

Send a full log, 
And use either Spigot or purpur (purpur recommended)

**Comment by svdgoor** [comment]
Dude just get the plugin from spigot. Or learn how to read plaintext. Smh.
