### ISSUE TITLE
Support Advanced Slime World Manager | Error on world saving

### ISSUE THREAD

**Issue by wzieciak** [VolmitSoftware/Iris#836]
### Problem

1. Install Iris...
2. Install Slime World Manager
3. Try to pregenerate world
4. Observe the error...

### Minecraft Version

1.19

### Iris Version

Iris v2.2.5-1.19 by Volmit Software

### Advanced Slime World Manager VErsion

2.9.0

https://github.com/Paul19988/Advanced-Slime-World-Manager

### Log

https://mclo.gs/W9ST1WJ

**Comment by svdgoor** [comment]
Did the developer of Slime tell you this was on us? There's no iris in the stack trace.
Better to stop slime from saving the world while pregenerating, and then re-enable it after its done.
Please let us know if the Slime Dev gives you more information.

**Comment by NextdoorPsycho** [comment]
This is a third Party plugin, that does chunk loading and management. Iris needs to be in control of this. If they have an api MAYBE, but this is NOT something on our radar as its not used by the 99%

But we can revisit this in Iris 3

**Comment by Vatuu** [comment]
Slime format is not designed to be used for natural generation. We will not be adding this.
