### ISSUE TITLE
Iris pack versions per MC release version

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#839]
### Adding, Removing, or Changing

Changing

### Type of Modification

I want to change the way the default Overworld pack is picked

### What are you trying to modify

The way I would implement this is by selecting (in the Iris source, or rather through the listing) a precise pack version for Iris to use on a certain release. For example, instead of using latest release for all MC versions, use only X for 1.18, Y for 1.19 and Z if all else fails.

An extra request I have is that Iris does not boot if it is installed on the wrong version. Plenty of people installing 1.19 iris on 1.18 and then complaining.
Lmk if you want a separate issue for that.

### Alternatives

If this could not be implemented I would have to keep taking the extra step of downloading the right pack, placing it in the right folder, and unzipping it, and explain how to do that to everyone that drops by support in need for legacy installation.

**Comment by ghost** [comment]
Afaik iris is currently downloading the overworld pack with a specific tag which is set in the plugin.

see this commit https://github.com/VolmitSoftware/Iris/commit/41477e4aa61bc39056ff228eb40970e14a7215e3

**Comment by svdgoor** [comment]
Oh gr8
