### ISSUE TITLE
Sculk Vines in objects act weird with paint mode

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#841]
### Problem

![2022-07-30_17 55 14](https://user-images.githubusercontent.com/107539181/181925021-b6a1ec84-91ca-4b68-bb6f-495a6c92c157.png)

@Vatuu 

### Solution

Don't use paint mode

### Minecraft Version

1.19

### Iris Version

Iris 2.2.6 Spigot 

### Log

*

**Comment by Vatuu** [comment]
Should be fixed in the next version.
