### ISSUE TITLE
fast max height and max height not functioning as intended.

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#842]
### Problem

![Schermafbeelding 2022-07-30 om 18 12 00](https://user-images.githubusercontent.com/107539181/181925739-d8a541dc-8204-4ed7-8162-ff833dabef4f.png)

 "objects": [{
        "place": ["SmallRuins/Ruin1"],
        "bore": true,

        "chance": 0.05,
        "mode": "MAX_HEIGHT", 
        "carvingSupport": "SURFACE_ONLY",
        "edit": [{
                "find": [{"block": "minecraft:glass"}],
                "replace": {"palette": [{"block": "minecraft:void_air"}]}
            }]

        }]

( maybe im doing something wrong but I don't think so )

### Solution

*

### Minecraft Version

1.19

### Iris Version

iris 2.2.6 Spigot 

### Log

*

**Comment by NextdoorPsycho** [comment]
this is working as intended.
Fast MaxHeight is:
![image](https://user-images.githubusercontent.com/29320316/183158611-963cbf8e-1d7e-4958-ad52-5367e95135de.png)
Unless im missing something. you might want MinHeight or Paint
