### ISSUE TITLE
/iris studio download "Dimensions"

### ISSUE THREAD

**Issue by corrompu-github** [VolmitSoftware/Iris#844]
### Problem

Not really a bug just we can't download any dimension like it's supposed to be. 

### Solution

We always have to specify a branch because Iris it's looking for branch "Master" by default. And many of your dimensions are on "Stable" or "Main" branch instead. 

### Minecraft Version

1.19

### Iris Version

2.2.6

### Log

no log required

**Comment by svdgoor** [comment]
You can specify the branch as a parameter.
Use the branch found on GitHub.
