### ISSUE TITLE
Objects spawn together weirdly 

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#848]
### Problem

Just see the picture if you have 2 objects in the same biome under each other in vscode this will happen
![2022-08-12_18 19 35](https://user-images.githubusercontent.com/107539181/184400669-d323a74a-2675-4e25-9122-5032086f2e24.png)

{
    "name": "Rough Plains",
    "derivative": "PLAINS",
    "vanillaDerivative": "PLAINS",
    "layers": [{
        "palette": [{"block": "minecraft:grass_block"}],
        "maxHeight": 3,
        "slopeCondition": {"maximumSlope": 4}
    }],
    "wall": {"palette": [
        {"block": "minecraft:andesite"},
        {"block": "minecraft:stone"}
    ]},
    "objects": [{
        "place": [
            "Trees/Oak/antioch1",
            "Trees/Oak/antioch2",
            "Trees/Oak/antioch4",
            "Trees/Oak/antioch5",
            "Trees/Oak/antioch6",
            "Trees/Oak/antioch7",
            "Trees/Oak/antioch8",
            "Trees/Oak/antioch9",
            "Trees/Oak/antioch10",
            "Trees/Oak/antioch11",
            "Trees/Oak/antioch12",
            "Trees/Oak/antioch13",
            "Trees/Oak/troofed1",
            "Trees/Oak/troofed2",
            "Trees/Oak/troofed3",
            "Trees/Oak/troofed4",
            "Trees/Oak/troofed5",
            "Trees/Oak/troofed6",
            "Trees/Oak/troofed7",
            "Trees/Oak/troofed8",
            "Trees/Oak/troofed9",
            "Trees/Oak/troofed10"

            ],
        "carvingSupport": "SURFACE_ONLY",
        "chance": 0.5,
        "mode": "CENTER_STILT",
        "rotation": {
                "yAxis": {
                    "min": 0,
                    "max": 0,
                    "interval": 90,
                    "enabled": true
                },
                "enabled": true
        },
         "edit": [{
                "find": [{"block": "minecraft:oak_leaves",  "data": {}}],
                "chance": 0.005,

                "replace": {
                    "style": {
                        "style": "PERLIN",
                        "zoom": 0.2

                    },
                    "palette": [
                        {"block": "minecraft:bee_nest"}
                    ]
                }
            }]

    },
    {
         "place": [
            "Rocks/boulder1",
            "Rocks/boulder2",
            "Rocks/boulder3",
            "Rocks/boulder4",
            "Rocks/boulder5",
            "Rocks/boulder6",
            "Rocks/boulder7",
            "Rocks/boulder8",
            "Rocks/boulder9",
            "Rocks/boulder10",
            "Rocks/boulder11",
            "Rocks/boulder12",
            "Rocks/boulder13",
            "Rocks/boulder14"

         ],
         "chance": 0.01,
         "bore": true,
         "mode": "FAST_MAX_HEIGHT",
         "carvingSupport": "SURFACE_ONLY"
    }],
    "decorators": [
        {
            "chance": 0.2,
            "variance": {
                "style": "CELLULAR",
                "zoom": 0.25,
                "fracture": {
                    "style": "SIMPLEX",
                    "zoom": 0.2,
                    "multiplier": 10
                }
            },
            "style": {
                "style": "SIMPLEX",
                "zoom": 0.2,
                "fracture": {
                    "style": "STATIC",
                    "multiplier": 8
                }
            },
            "palette": [
                {"block": "minecraft:dandelion"},
                {"block": "minecraft:poppy"},
                {"block": "minecraft:blue_orchid"},
                {"block": "minecraft:allium"},
                {"block": "minecraft:azure_bluet"},
                {"block": "minecraft:red_tulip"},
                {"block": "minecraft:orange_tulip"},
                {"block": "minecraft:white_tulip"},
                {"block": "minecraft:pink_tulip"},
                {"block": "minecraft:oxeye_daisy"},
                {"block": "minecraft:cornflower"},
                {"block": "minecraft:lily_of_the_valley"}
            ]
        },
        {
            "chance": 0.01,
            "palette": [{"block": "minecraft:tall_grass"}]
        },
        {
            "chance": 0.5,
            "palette": [{"block": "minecraft:grass"}]
        }
    ],
    "generators": [{
        "generator": "ExtreemLands",
        "max": 50,
        "min": -15
    }]
}

### Solution

looking into it 

### Minecraft Version

1.19

### Iris Version

2.2.7 Iris Spigot 

### Log

*

**Comment by NextdoorPsycho** [comment]
make the chance more varied, if you use the same chance for everything it overlaps.
