### ISSUE TITLE
World start

### ISSUE THREAD

**Issue by burak-105** [VolmitSoftware/Iris#852]
### Problem

I have been waiting for half an hour, still says initializing engine
(starting from a fresh new world)

### Minecraft Version

1.17.1

### Iris Version

1.17.1

### Log

Initializing Engine: World/overworld (256 height) Seed: 4187184881828324637

**Comment by ghost** [comment]
@noulalu You need to provide a full server log using https://mclo.gs otherwise it isnt doable to know the cause and help you properly

**Comment by Vatuu** [comment]
Please update to the latest version and let us know if issues still persists.
