### ISSUE TITLE
enchantments in loot tables don't work 

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#853]
### Problem

 {
            "type": "golden_chestplate",
            "lore": ["Amenhotep's Heart\nHeart of the king"],
            "enchantments": [{
                "enchantment": "binding_curse",
                "minLevel": 1,
                "maxLevel": 1
            }],
            "attributes": [{
                "attribute": "GENERIC_MAX_HEALTH",
                "maxAmount": 5,
                "minAmount": 3,
                "name": "AmenhotepHeart",
                "operation": "ADD_NUMBER"
            }]
        },

this is a example of the overworld pack and everything works fine besides that enchantment part 

### Solution

*

### Minecraft Version

1.19

### Iris Version

Iris 2.2.7 Spigot

### Log

*

**Comment by Vatuu** [comment]
Fixed in upcoming version.
