### ISSUE TITLE
Iris object unable to reach folders deeper than 2 folders

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#858]
### Problem

1. Do /iris object paste object=jigsaw/stronghold
2. See that it wont help with autocompletion
3. If you type it down complete it wont be placed

Chat message is

"Cannot convert "village/desert/houses/animal_pen_1" into a String
Unkown Iris Command

### Solution

Fix it?

### Minecraft Version

1.19

### Iris Version

LATEST

### Log

https://mclo.gs/vn7OXfE

**Comment by RePixelatedMC** [comment]
I got this issue as well I thought that it was a vscode bug when seeing that error but its a iris one apparently ( error in vscode didnt look in console )
