### ISSUE TITLE
Command /iris what biome broken

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#859]
### Problem

1. Do /iris what biome
2. See message IBiome: null (THE_VOID)

Studio mode displayes the correct Biome at the scoreboard thou

### Solution

Fix it

### Minecraft Version

1.19

### Iris Version

LATEST

### Log

No log needed

**Comment by Armin231** [comment]
This could be due to the util biome that is only used for the ruined portals but overrides the IBiome for the /iris what biome command
This should be further invested by the devs

**Comment by Vatuu** [comment]
Fixed in upcoming version.
