### ISSUE TITLE
Mantle not maintained through restarts for Object Placements

### ISSUE THREAD

**Issue by NextdoorPsycho** [VolmitSoftware/Iris#864]
### Problem

The mantle objects that are in the mantle are not persistent through server restarts or updates
Makes it problematic for things like IrisFeller and other mantle dependent systems

### Solution

cry

### Minecraft Version

1.19

### Iris Version

"Latest"

### Log

no

**Comment by ghost** [comment]
Those issues are probably related to this #799 and #714

**Comment by ghost** [comment]
Still an issue on Iris 2.2.14

**Comment by NextdoorPsycho** [comment]
Should be fixed
