### ISSUE TITLE
Space in server folder results in atomic cache failure

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#865]
### Problem

See (https://docs.volmit.com/iris/plugin/faq#atomic-cache-failure)

### Solution

Fix if possible

### Minecraft Version

1.19

### Iris Version

Latest

### Log

No log needed

**Comment by NextdoorPsycho** [comment]
should be fixed on latest maybe? Vatuu made the function recursive lemme know

**Comment by ghost** [comment]
> should be fixed on latest maybe? Vatuu made the function recursive lemme know

I’ll test it and let you know

**Comment by ghost** [comment]
Ok looks fine. Ill close this
