### ISSUE TITLE
Change Decree the command System to edict

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#867]
### Adding, Removing, or Changing

Changing

### Type of Modification

I want to remove decree and get back to a more robust system like edict

### What are you trying to modify

The way I would implement this is remove decree and get back to a better way more powerful and working system

### Alternatives

If this could not be implemented I would cry cause decree is a mess

**Comment by svdgoor** [comment]
Working on it, see edict
Progress is about as consistent as Iris but I'll get back to it some time.

**Comment by ghost** [comment]
I like the idea of decree/edict but I’m regards of iris it doesn’t fit well in my option. The commands need to be robust and not fancy. Most people don’t really use any command other than /iris create

**Comment by svdgoor** [comment]
Robustness is the main design principle of Edict. It'll be more robust than implementing commands directly because of the elimination of the need for manual transformation of string to objects. The cosmetics are of secondary importance.

**Comment by ghost** [comment]
Ok that sounds great and a welcoming change to the current system
