### ISSUE TITLE
Speeding the checking process in second pregens

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#868]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to speed the check process up

### What are you trying to modify

The way I would implement this.
Iris generates mca regions in spirals. Iris could check only for missing chunks in the last created mca region in the worlds folder and started generate from that one.
https://dinnerbone.com/minecraft/tools/coordinates/
this would drastically speed things up cause it won’t need to check everything mca region

### Alternatives

If this could not be implemented I would shrug

**Comment by svdgoor** [comment]
If you explore a bit and then resume the pregen it'll skip too much.
Best way is to mark finished MCA regions in a registry text file which you store with the MCA regions, or something similar.
Of course you still need the option to overwrite that.

**Comment by ghost** [comment]
Was just an idea how to speed things up. Like if server owners are doing a 10k pregen, create world borders for it and want to expand that to 15k. They need to check the 10k first before getting iris to actually generate new chunks. Therefore a simple check system would be nice. Iris currently is just starting and checking everything to prevent chunk holes which should be the case for the center mca regions

**Comment by svdgoor** [comment]
Oh yeah no I understand and agree with the idea, the implementation wasn't perfect though, that was what I was commenting on.
Love the idea-spree!

**Comment by NextdoorPsycho** [comment]
The speed on latest trivializes this
