### ISSUE TITLE
F3 Showing Incorrect Biome

### ISSUE THREAD

**Issue by TheekshanaA** [VolmitSoftware/Iris#869]
### Problem

Steps to replicate:
1. Gen a iris world with custom region files with set of biomes

Issue:
In studio the region and the biomes show up fine but once generated it shows up in F3 as vanilla biomes and does not show the correct biome

### Minecraft Version

1.19

### Iris Version

2.2.8

### Log

No Logs Applicable

**Comment by NextdoorPsycho** [comment]
?iris what biome should be working on latest
