### ISSUE TITLE
Issues with generated ItemsAdder block s

### ISSUE THREAD

**Issue by BarniDW** [VolmitSoftware/Iris#870]
### Problem

Generated objects that contains itemsadder blocks are buggy, because if you mine them, they drop note blocks, if you right click on the blocks, the texture turns into a note block.
![Capture](https://user-images.githubusercontent.com/35395766/186264763-8dd7236d-068e-4b62-9a7a-c1d92fde20d5.PNG)

### Minecraft Version

1.19

### Iris Version

2.2.11-1.19-2

### Log

-

**Comment by NextdoorPsycho** [comment]
this seems like an issue with Itemsadder's implementation

**Comment by NextdoorPsycho** [comment]
I haven't heard back so im going to close this issue, Let me know if this is still a problem.
And send me the setup you are using to cause it and we can fix it in a day
