### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Specthra** [VolmitSoftware/Iris#874]
### Problem

Having Iris among my plugins causes a memory leak

**Plugins**
![image](https://user-images.githubusercontent.com/77130187/186738645-e1ba0110-e907-4f09-843b-6c4b1d4e3b65.png)

**Version**
![image](https://user-images.githubusercontent.com/77130187/186738702-6599fdc0-29f4-4e2a-97c0-23ef504002e3.png)

**Below I leave tests that I did removing some plugins, including Iris in the last test**

**Excluded plugin groups**
Group 1 = https://spark.lucko.me/ySGd4ZhbXt CLEAR
Advancedhelp
AdvancedTeleport
AngelChest
AnimatedScoreboard
AuctionHouse
BuycraftX
ChatSentry

Group 2 = https://spark.lucko.me/Lpwvn3WhwN CLEAR
Chunky
Citizens
CMILib
Codex
ColoredSigns
ConditionalEvents
CoreProtect
CustomCrafting

Group 3 = https://spark.lucko.me/nqeHT3yj6D CLEAR
DeadlyDisasters
DeluxeCombat
DeluxecombatWGA
DiscordSRV
Dynmap
eco
EcoEnchants
EcoEnchantsGUI

Group 4 = https://spark.lucko.me/qLvf6zNsU3 CLEAR
Elevator
EssentialsX
EssentialsAntiBuild
EssentialsChat
EssentialsProtect
EssentialsSpawn
ExcellentCrates
FriendsPremium

Group 5 = https://spark.lucko.me/FxgolJcAm4 CLEAR
Hamster
Holographic
Images
InsaneAnnouncer
InvisibleItemframes
IPWhitelist
ItemEdit
Jobs

Group 6 = https://spark.lucko.me/h4RTQpVJJ0 CLEAR
Lands
LibsDisguises
LiteBans
LootChest
LPC
MCPets

Group 7 = https://spark.lucko.me/q0UftwJOMH CLEAR
ModelEngine
MultiverseCore
MythicCrucible
MythicMobs
NexEngine
PAPI
PlayerKits

Group 8 = https://spark.lucko.me/lzdrSQZTVD CLEAR
PlayTime
ProtocolLib
Safari
SBSpigot
Shopkeepers
SimplePortals
SkinRestorer

Group 9 = https://spark.lucko.me/Or0GCEDUZm CLEAR
StatTrackers
TAB
TradeSystem
TutorialCreator
UltimateShop
ViaBackwards
ViaVersion
VillagerTrade

Group 10 = https://spark.lucko.me/eSfvDZWTUx CLEAR
VotingPlugin
Vulcan
WolfyUtilities
WorldEdit
WorldGuard

Group 11 = https://spark.lucko.me/a1EATyCIsy
Iris

### Minecraft Version

1.19

### Iris Version

2.2.12-1.19.2

### Log

https://mclo.gs/xKazutJ

**Comment by NextdoorPsycho** [comment]
Sparks are not great / they dont give us the information we need to diagnose / dix this problem. can you use a Memory Profiler and get it to create a memory leak (and explain to us what the heck you are doing to cause it) and if you can send me those two things we can have a fix out asap

**Comment by NextdoorPsycho** [comment]
I still need this information. Try latest and get back to me @Specthra
