### ISSUE TITLE
Sculk veins don't appear correctly on the ground

### ISSUE THREAD

**Issue by eugeniodevv** [VolmitSoftware/Iris#875]
### Problem

1. Make a sculk vein decorator (the expected output, a sculk vein on the ground)
2. In the world, it appears like this: https://media.discordapp.net/attachments/768582615078010910/1012523168000381029/unknown.png.

### Minecraft Version

1.19

### Iris Version

v2.2.11-1.19.2

### Log

https://mclo.gs/rW7PkJ0

**Comment by Vatuu** [comment]
Fixed in 2.2.14
