### ISSUE TITLE
Iris seems to be uneffected by settings

### ISSUE THREAD

**Issue by PhileasFogg3** [VolmitSoftware/Iris#878]
### Problem

Iris seems to be unaffected by settings.json

After setting `effectSystem` , `anbientEntitySpawningSystem` and `markerEntitySpawningSystem` all to false I have observed the following:

- Particle effects are still spawned in the overworld
- Vanilla mob spawning rules are not enforced, instead, iris spawning rules are. 

### Minecraft Version

1.19

### Iris Version

2.2.13

### Log

https://pastebin.com/WnrWeejy

**Comment by svdgoor** [comment]
Pretty sure particles should be stopped, unless they are part of the datapack for a biome, or part of the underlying vanilla biome.
Entities are overwritten regardless of the settings you mentioned, so that behaviour is expected. You turned off markers, which is only a small subset of entity spawning rules.

**Comment by PhileasFogg3** [comment]
Thank you for your reply! 

I was instructed to make this bug report after speaking to support members of staff in the discord server, they instructed me that the setting for `anbientEntitySpawningSystem` would stop Entities spawning with the iris engine, and use Vanilla spawning rules instead. Mob spawning was impacted, for a time, and mobs spawned following the vanilla spawning rules, however, it suddenly changed to using the iris one again, without me changing anything in the settings.json file. 

Also, the particles are not vanilla ones and I have no datapack that impacts them, other than the default iris packs.
