### ISSUE TITLE
Paper Watchdog

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#881]
### Adding, Removing, or Changing

Changing

### Type of Modification

Due to the change of the paper.yml directory iris should change it so it’s automatically changed like it used to

### What are you trying to modify

The way I would implement this is by changing the path or however that function has handled it in the past

### Alternatives

If this could not be implemented I would cry cause I always have to do this
Server/config/paper-global, 
```
watchdog:
  early-warning-delay: 18000000
  early-warning-every: 500000
```

**Comment by Vatuu** [comment]
Please verify that this is still a issue, it seems to work for me.

**Comment by ghost** [comment]
> Please verify that this is still a issue, it seems to work for me.

Atleast iris isn't changing these
```
watchdog:
  early-warning-delay: 180000
  early-warning-every: 5000
```
in this directory server/config/paper-global.yml

My system is fast enough so I won't get the paper watchdog warnings but it could appear on low spec systems

**Comment by NextdoorPsycho** [comment]
Try on latest as of when i make the update
