### ISSUE TITLE
Objects spawn together

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#885]
### Problem

![2022-09-04_11 19 27](https://user-images.githubusercontent.com/107539181/188306495-0377e9d9-6d6a-4ecf-8692-893c01a477d2.png)

 "objects": [

        {
        "place": [
            "BetterTerrain/SpruceTrees/pine1",
            "BetterTerrain/SpruceTrees/pine2",
            "BetterTerrain/SpruceTrees/pine3",
            "BetterTerrain/SpruceTrees/pine4",
            "BetterTerrain/SpruceTrees/pine5",
            "BetterTerrain/SpruceTrees/pine6",
            "BetterTerrain/SpruceTrees/pine7",
            "BetterTerrain/SpruceTrees/pine8",
            "BetterTerrain/SpruceTrees/pine9",
            "BetterTerrain/SpruceTrees/pine10",
            "BetterTerrain/SpruceTrees/pine11",
            "BetterTerrain/SpruceTrees/pine12"

            ],
        "carvingSupport": "SURFACE_ONLY",
        "chance": 1,
        "mode": "CENTER_STILT",
        "stiltSettings":{"yMax": 4, "yRand": 1},
        "rotation": {
                "yAxis": {
                    "min": 0,
                    "max": 0,
                    "interval": 90,
                    "enabled": true
                },
                "enabled": true
        }
    },
    {
        "place": [
            "BetterTerrain/Misc/pumpkins1",
            "BetterTerrain/Misc/pumpkins2",
            "BetterTerrain/Misc/pumpkins3",
            "BetterTerrain/Misc/pumpkins4",
            "BetterTerrain/Misc/pumpkins5",
            "BetterTerrain/Misc/pumpkins6"

            ],
        "carvingSupport": "SURFACE_ONLY",
        "chance": 0.1135,
        "smartBore": true,
        "mode": "PAINT",
        "translate":{"y": 1},
        "rotation": {
                "yAxis": {
                    "min": 0,
                    "max": 0,
                    "interval": 90,
                    "enabled": true
                },
                "enabled": true
        }

    }

    ],

i suppose that this is a bug or im doing something wrong ..

### Minecraft Version

1.19

### Iris Version

Iris 2.2.15 Spigot 

### Log

*

**Comment by NextdoorPsycho** [comment]
Try latest, we changed a lot about how the random scalar works. 
Please for the love of god, stop SmartBor'ing Pumpkins
Dont Translate Pumpkins
Change the chance of the trees to 0.5 and a density of 2

**Comment by RePixelatedMC** [comment]
1: i did smartbore just to test if that would fix the issue idk why lol

2: i need to translate them otherwise the will spawn in the ground ( i messed smth up most likely)

3: okey Lol 


Il try latest il update and close it if it got fixed

**Comment by RePixelatedMC** [comment]
isnt fixed still happens in 2.3.0 
![Schermafbeelding 2022-09-18 om 10 52 35](https://user-images.githubusercontent.com/107539181/190894054-39c90b0a-80b3-421a-9e9b-ad21cdc7e1a4.png)

**Comment by NextdoorPsycho** [comment]
Actually do what i told you and then let me know
