### ISSUE TITLE
Iris Noise Generators 

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#888]
### Problem

Its weird basically: if I create a gen it just won't work when I select it it will just create a flat area and I have no idea what may causing this..

this issue happens with all packs where I want to add a new gen in ( like medium size ones ) 

{
    "interpolator": {
        "horizontalScale": 4,
        "function": "BICUBIC"
    },
    "seed": 129,

    "composite": [{
        "seed": 141,
        "style": {
            "style": "IRIS_HALF",
            "zoom": 0.93
        }
    }]
}
 
Current: git-Purpur-1774 (MC: 1.19.2)

### Minecraft Version

1.19

### Iris Version

2.2.15

### Log

*

**Comment by ghost** [comment]
> 

You should provide way more information than that. Like how does your generators all look like (code wise) etc

**Comment by RePixelatedMC** [comment]
Sorry, i wasn't paying attention i added it all in now

**Comment by Vatuu** [comment]
![image](https://user-images.githubusercontent.com/21113232/194110444-2be6702b-7714-46e4-91cf-4d92c6cdff2c.png)
Unable to replicate the issue, try to reset your pack as much as you can and attempt it again. The generator config works as seen above.

**Comment by RePixelatedMC** [comment]
My bad it was fixed in Iris 2.3 should have closed it earlier
