### ISSUE TITLE
Fish Do not spawn

### ISSUE THREAD

**Issue by TheHappyHopper** [VolmitSoftware/Iris#891]
### Problem

Iris uses vanilla fish spawning system but due to increased world height oceans are significantly higher than they would be in vanilla, this causes fish to be unable to spawn in the overworld

Issue report requested by NextdoorPsycho on discord

### Solution

Handle fish spawning in iris instead of allowing vanilla spawning behavior

### Minecraft Version

1.19

### Iris Version

2.2.16

### Log

NA

**Comment by NextdoorPsycho** [comment]
Try latest, i lowered height should see fish

**Comment by TheHappyHopper** [comment]
> Try latest, i lowered height should see fish

Now fish do spawn but only in caves, needs to be done a bit more
