### ISSUE TITLE
Snow taking priority over other blocks

### ISSUE THREAD

**Issue by TheHappyHopper** [VolmitSoftware/Iris#892]
### Problem

floor snow is being given higher priority from other blocks during generation causing floating trees and structures
![2022-09-12_10 54 45](https://user-images.githubusercontent.com/66880702/189725079-90d96497-8174-4241-8662-94c763ad3a98.png)
![2022-09-12_10 54 52](https://user-images.githubusercontent.com/66880702/189725110-2b389f12-fc2c-4e6a-aeb9-3f87911dd260.png)
![2022-09-12_11 07 07](https://user-images.githubusercontent.com/66880702/189725247-e6314c13-709d-43f0-9315-81530a5fd27e.png)

### Solution

Lower snow placement priority

### Minecraft Version

1.19

### Iris Version

Iris-DEV (brian's jar)

### Log

NA

**Comment by NextdoorPsycho** [comment]
Fixed on 2.3.2
