### ISSUE TITLE
Prepare for Papers Rewrite of the chunk system

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#895]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to prepare for this https://github.com/PaperMC/Paper/pull/8177

### What are you trying to modify

Dunno. You guys do the math https://github.com/PaperMC/Paper/pull/8177

### Alternatives

If this could not be implemented I would cry

**Comment by NextdoorPsycho** [comment]
not needed lol
