### ISSUE TITLE
Floating clutter objects

### ISSUE THREAD

**Issue by TheHappyHopper** [VolmitSoftware/Iris#896]
### Problem

Ice clutter floats one block in the air in iris 2.2.19 (all snowy biomes)
![2022-09-13_09 32 50](https://user-images.githubusercontent.com/66880702/189959721-e6d714ff-7d6d-4bd3-bc63-9addaf8c4cd9.png)

### Solution

Potentially fixing #892 or just lowering the clutter by one

### Minecraft Version

1.19

### Iris Version

2.2.19

### Log

NA

**Comment by NextdoorPsycho** [comment]
Its the same thing with snow
