### ISSUE TITLE
IrisToolbelt Returning Incorrect Biome

### ISSUE THREAD

**Issue by TheekshanaA** [VolmitSoftware/Iris#897]
### Problem

Hi there, 
We are having some issues fetching the biome of the player. We keep getting the incorrect biome returned with the following code. Sometimes we get the correct biome other times we just get "A biome"
![image](https://user-images.githubusercontent.com/10327965/190174306-87414219-1c0d-4a43-89d4-2bbe6253ef29.png)

### Minecraft Version

1.19

### Iris Version

2.2.17

### Log

No Errors in Console

**Comment by Vatuu** [comment]
Should be fixed in the next version.
