### ISSUE TITLE
Tropical Mountain Detecting as Extreme Mountains

### ISSUE THREAD

**Issue by TheekshanaA** [VolmitSoftware/Iris#898]
### Problem

Hi there,
The tropical_mountain biome is detecting as extreme biomes with IrisToolbelt method getSurfaceBiome() 

![image](https://user-images.githubusercontent.com/10327965/190344938-380000d3-42a4-455d-91ef-ab4dd23e5fbb.png)
![image](https://user-images.githubusercontent.com/10327965/190344952-03913fde-8fbc-4c9c-b8c3-7921a72c7ed5.png)

### Minecraft Version

1.19

### Iris Version

2.2.17

### Log

No Logs Applicable

**Comment by NextdoorPsycho** [comment]
this can happen, the spit that you are standing is like a hodgepodge of 5 different biomes, so there is a chance that a biome will be 1 block, #procedural
