### ISSUE TITLE
Content Enhancements

### ISSUE THREAD

**Issue by NextdoorPsycho** [VolmitSoftware/Iris#9]
ADD+
- Vanilla structures (villages to end etc...)
- Chunky Support? (if not already) https://www.spigotmc.org/resources/chunky.81534/
- PAPI support (placeholder Api)
      - Supported PAPI style hooks for biome identification (%biome%) etc...

**Comment by cyberpwnn** [comment]
Chunky support added in the iris pregenerator (more specifically, iris does what chunky does if you have paperspigot in its the pregenerator. you dont need chunky) https://www.spigotmc.org/resources/iris-world-gen-the-dimension-engine.84586/update?update=366215

**Comment by cyberpwnn** [comment]
@NextdoorPsycho do not merge issues. Make individual ones please
