### ISSUE TITLE
Iris Pregenerator using wrong estimation for days

### ISSUE THREAD

**Issue by TheHappyHopper** [VolmitSoftware/Iris#900]
### Problem

As we all know iris has had wacky generation estimations since the day it came out. However it would seem that iris actually knows exactly how long its going to be generating and just isnt showing it properly.
![Capture](https://user-images.githubusercontent.com/66880702/190837221-ec537215-a7f1-42c1-bfb2-3515ff6eb0cd.png)

As we can see here Iris is estimating 81.03 days to generate this world, which seems wacky at first until you realize that the server is actually just listing days as 24 minutes long instead of 24 hours

Take 81.03 days and multiply that by 24 you get 1944.72 minutes, divide that by 60 to get hours and you get 32.4 hours, just about 1.4 days which looks much more believable than the 81 days iris currently estimates.

### Solution

change the day estimation from 24 minutes to 1440 minutes (one day)

### Minecraft Version

1.19

### Iris Version

2.3.0

### Log

N/A

**Comment by Vatuu** [comment]
Fixed in the next version
