### ISSUE TITLE
"downfallType": "none", doesn't work

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#902]
### Problem

"downfallType": "none", doesn't work it will still rain/snow 

### Solution

*

### Minecraft Version

1.19

### Iris Version

iris 2.3.0 spigot

### Log

*

**Comment by NextdoorPsycho** [comment]
This is not on us, the Custom Derivatives are just Iris Allowing you to use the MOJANG Codec, NONE is usually affiliated with the Derivative of Desert, and that's the only place its used, if you are using it in any other place, it wont work. as that's just #Mojang for you
