### ISSUE TITLE
Iris pregen Broken for everything under 1100 radius

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#903]
### Problem

iris pregen breaks when entered a value under 1100 radius

message: pregen started in test of 2048 x 2048

recreate this by doing for example */ir pregen start name=(name) radius=500*

### Solution

*

### Minecraft Version

1.19

### Iris Version

Iris 2.3.0 Spigot 

### Log

*

**Comment by ghost** [comment]
> ### Problem
> iris pregen breaks when entered a value under 1100 radius
> 
> message: pregen started in test of 2048 x 2048
> 
> recreate this by doing for example _/ir pregen start name=(name) radius=500_
> 
> ### Solution
> 
> ### Minecraft Version
> 1.19
> 
> ### Iris Version
> Iris 2.3.0 Spigot
> 
> ### Log

There is no use to pregen a world that is smaller than 2048x2048. The smallest size to generate is 4x4 mca regions (cause iris is generating in mca regions. It's hardcoded. Means this isn't a bug it's intended. Can you close this @RePixelatedMC

**Comment by RePixelatedMC** [comment]
Okey
