### ISSUE TITLE
iris is not working

### ISSUE THREAD

**Issue by FqllenGod** [VolmitSoftware/Iris#904]
### Problem

iris is not working on paper 1.18.2

### Minecraft Version

1.18

### Iris Version

2.3.0

### Log

https://mclo.gs/UhWd7hJ

**Comment by svdgoor** [comment]
Could not load 'plugins\Iris-2.3.0-1.19.2.jar' in folder 'plugins'
What do you think the minecraft version number in the name of the jar means?
Look on version history on spigot. Smh.
