### ISSUE TITLE
Rarity

### ISSUE THREAD

**Issue by Domm1** [VolmitSoftware/Iris#917]
### Problem

I was told by Nex to open bug report. Changing rarity in regions or biomes doesn't have effect.

### Solution

I am not entirely sure.

### Minecraft Version

1.19

### Iris Version

Iris v2.3.6-1.19.2 by Volmit Software

### Log

I can share log privately. Discord: Domzzo#5443

**Comment by Vatuu** [comment]
Rarity works fine, as tested on 2.3.7. It's a weight, not a perceptual chance. Also, the maximum is 512.
