### ISSUE TITLE
Need to make Iris's world load before many other plugins like Towny to prevent some problems

### ISSUE THREAD

**Issue by ColdTearsYY** [VolmitSoftware/Iris#918]
### Problem

**Excuse me but please see the related issue(https://github.com/TownyAdvanced/Towny/issues/6258) before check this one.
The bug, the way to show it, and logs are all in this issue.**

1. Install Iris and Towny.
2.set an outpost or set your homeblock in a world created with Iris. You can teleport to it using commands. Works very well.
3.restart the server
4.You can't teleport to them.It says that There are no outpost spawns set for this town.It seems that data lost.

### Solution

Towny told me to use a world-loader like Multiverse or make Iris load your non-loaded World earlier. But I didn't know how to...

### Minecraft Version

1.19

### Iris Version

2.2.14-1.19.2

### Log

https://paste.ubuntu.com/p/t8bgDtXkYB/

**Comment by LlmDl** [comment]
Towny is unable to load the Locations of the spawns, outposts because the recorded World for that location is not present when Towny is loading the database. This is why ColdTearsYY needs to have their world loaded earlier.

**Comment by NextdoorPsycho** [comment]
you cant use Multiverse to load Iris Worlds it breaks.

Towny needs to Softdepend on Iris to load first because we cant pull them into Engine Startup Phase

**Comment by LlmDl** [comment]
We already tried the softdepend trick, @ColdTearsYY says that didn't work.

**Comment by NextdoorPsycho** [comment]
Then they will or we will need to make a compatibility patch for each
other. Or you can try using multi-verse. That we wouldn’t recommend it.
