### ISSUE TITLE
Spawner exposed to sky don't spawn mobs & The surface of the worlds not created by Iris don't spawn mobs.

### ISSUE THREAD

**Issue by chenyx94** [VolmitSoftware/Iris#919]
### Problem

1. Install Iris...(Spigot 1.19.2, Paper 1.19.2)
2. Create a new world named Resource
3. place a spawner in another world using command: setblock ~ ~1 ~ spawner{SpawnData: {entity: {id: "minecraft:zombie"}}, MaxNearbyEntities: 6s, MinSpawnDelay: 200s, y: 97, id: "minecraft:mob_spawner", SpawnPotentials: [], x: -59, SpawnRange: 4s, MaxSpawnDelay: 800s, RequiredPlayerRange: 16s, SpawnCount: 4s, z: 21, Delay: 115s}
5. **1) The spawner spawns the mob only on the block with sky light <=12 even if the block light == 0. In another world, a spawner which is placed on a flatland don't spawn mobs at night.** 
6. **2) The surface of worlds that are not created by Iris don’t spawn mobs. But exceptions can be observed under trees. (where the sky light is lower than 15)**
7. I have tested this in pure 1.19.2 sever and the spawner spawns mobs at night as is expected.
8. I haved deleted Resource, iris and the datapacks made by Iris in the other world folders, unfortunately, none of the operations works. I'm trying to change the datapack settings but I can't because Iris will remake the datapack to the world folders when the server is set up.

### Solution

The problem ii is confirmed by NextdoorPsycho. I've been told that the issue is height-related.
I think the two problems are the same. When spawning mobs, Minecraft computes the light of a block, when the block light level is lower than a certain number (like 7, or 1 in 1.19), it is possible to spawn a mob, as well as blocks around a spawner (7, or 12 in 1.19). According to the problem description, light-level<=12 blocks spawn mobs (by the spawner), and the number 12 is Minecraft Mechanic.
But what if we count sky-light in the computation? At night, the sky-light is still 15, so an exposed block's light-level is 15, ignoring the 0 block-light-level, then no mob will spawn on this block.

### Minecraft Version

1.19.2

### Iris Version

2.2.10-1.19.2

**Comment by NextdoorPsycho** [comment]
im not sure what i can do to remedy this other than adding roofs to things lol

**Comment by NextdoorPsycho** [comment]
Should be fixed on latest i redid the datapack structure
