### ISSUE TITLE
Minecraft /place structure command not working

### ISSUE THREAD

**Issue by alexey-va** [VolmitSoftware/Iris#921]
### Problem

1. Install Iris 2.3+
2. Create a world with /iris create command
3. Try placing a structure (/place structure minecraft:stronghold)
4. It doesnt work

If I delete world folder after creating a world and regen it the command works fine but biomes are gone (everything is minecraft:plains).

Sometimes minecraft just crashes when using place command. Here is jvm crash log:
[hs_err_pid1673204.log](https://github.com/VolmitSoftware/Iris/files/9928043/hs_err_pid1673204.log)

### Minecraft Version

1.19

### Iris Version

2.3.7

### Log

https://mclo.gs/ArHWXPm

**Comment by svdgoor** [comment]
You're not allowed placing structures yourself because of issues with vanilla registering locations of those.
You can use /iris jigsaw place instead
