### ISSUE TITLE
All spawners are pig spawners

### ISSUE THREAD

**Issue by Kubister11** [VolmitSoftware/Iris#923]
### Problem

All spawners in dungeons are pig spawners and do not work

[https://i.imgur.com/yfeHBi5.png](url)

### Minecraft Version

1.19

### Iris Version

2.3.7

### Log

I have no errors

**Comment by NextdoorPsycho** [comment]
Use Iris Dust
/iris o Dust
and right click the spawner and blocks nearby. if we know the ID's we can fix it

**Comment by CrazyDev05** [comment]
Skeleton, Zombie and Spider Spawners are Pig Spawners

**Comment by CrazyDev05** [comment]
dungeon-skeleton
dungeon-zombie
dungeon-spider

**Comment by NextdoorPsycho** [comment]
Will be fixed on latest
