### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Puk3p** [VolmitSoftware/Iris#924]
### Problem

Hi ! When I’m trying to regen an area using Iris it doesn’t work. It regenerates my area but without the pack (as if it doesn't exist or ignores it). It’s so strange. I pregenerated the map because when I asked on discord I was told that it has absolutely no problem. I’ll attach 2 photos. The second one it’s from trying regenerating the first one.
![932931F5-F912-422C-9EAF-B98334971833](https://user-images.githubusercontent.com/117625145/200239458-f8dbd6d9-9dd6-4244-b47e-a38cb69cfdcf.png)
![826E9CD8-D0C8-428A-9ABB-A7EFB6C60538](https://user-images.githubusercontent.com/117625145/200239482-8e14f7f1-2ad7-4b0c-ba14-43deeef17aed.png)

### Minecraft Version

1.19

### Iris Version

Iris-2.3.0-1.19.2.jar

### Log

https://mclo.gs/mfuV8sL

**Comment by NextdoorPsycho** [comment]
if you regen you should do it before you are updating. there is not much i can say to do. other than:
- Don't update, unless you need to and are willing to risk it (or make a backup)
- Regen is a DANGEROUS WORLD ALTERING COMMAND THAT MAY GO WRONG
- you should always make a backup
