### ISSUE TITLE
Per player loot

### ISSUE THREAD

**Issue by CrazyDev05** [VolmitSoftware/Iris#925]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to make the natural generated loot player specific

### What are you trying to modify

The way I would implement this is maybe add a tag to the container, so a plugin could generate a player specific virtual inventory (with the same loot table as the clicked container) that opens when the owner (player) tries to open the container

### Alternatives

If this could not be implemented I would make a plugin that gives a tag to player placed blocks and a uuid to natural generated chest (when first opening a container) saving the content of the chest to a database and cloning this. Then when a player accesses the container it checks if the player already has opened it and opens the saved player specific inventory, if not it clones the inventory from the database and opens it. When a player closes the inventory the content gets saved to a database

**Comment by NextdoorPsycho** [comment]
This is not something we can control, we make the worlds, we make the loot, we don't manage what players have in chests. There are plenty of plugins that have blocks that iris hooks into that you can propagate in placed where OUR chests are and you can specify what you want. This is WAYYY Outside our scope
