### ISSUE TITLE
all the spawners are pig spawners and stonghold did not spawn

### ISSUE THREAD

**Issue by Bearcraft02** [VolmitSoftware/Iris#928]
### Problem

pregened the world on 2.3.7
now runing on 2.3.8
spawners are pig spawners and the stonghold did not spawn

### Minecraft Version

1.19

### Iris Version

2.3.8-1.19.2

### Log

https://pastebin.com/5XmbkU1M

**Comment by NextdoorPsycho** [comment]
Should be fixed on latest when i make an update
