### ISSUE TITLE
Bug with ItemsAdder blocks

### ISSUE THREAD

**Issue by Zemenus** [VolmitSoftware/Iris#932]
### Problem

Ok, so, when you trying to make IA blocks generating trough biome settings like for example if you replace deepslate in amethyst caves in overworld pack with custom block - just noteblocks will spawn.

But! If you add custom block to the dimension - it generates your custom blocks... well... almost. It generates only the noteblocks with texture of your custom block, but when you update these blocks they would just transform into noteblocks (similar to this guy's problem: https://github.com/VolmitSoftware/Iris/issues/870)

By the way I got ItemsAdder of verison 3.2.5-r3 and BlocksInjector 0.0.6

### Solution

ItemsAdder and Iris got some updates and minor fixes with optimizations, so it could break things. Also blockinjector got an update too.

I'm not the dev of these plugins, neither a pro at plugin development, so probably my solution will be: get in contact with LoneDev and solve this problem together, please. Really like IA and Iris, and waited for compatibility for so long, please do not abandon it.

### Minecraft Version

1.19

### Iris Version

2.3.8

### Log

https://pastebin.com/uihYjrM6

**Comment by NextdoorPsycho** [comment]
we just add it into the autocomplete, and in the world on generation. if IA's blocks arent registered but ARE showing up there is nothing on my end that can be done. feel free to reference this issue on their board and if you do feel free to inform him to contact me or any of us. 

But send him an Environment where you are able to replicate it. like an iris world, with IA blocks and just those Three plugins. and he might be able to help / i can etc... (don't upload the jars however unless its in a private DM or something akin to that)

**Comment by Zemenus** [comment]
> we just add it into the autocomplete, and in the world on generation. if IA's blocks arent registered but ARE showing up there is nothing on my end that can be done. feel free to reference this issue on their board and if you do feel free to inform him to contact me or any of us.
> 
> But send him an Environment where you are able to replicate it. like an iris world, with IA blocks and just those Three plugins. and he might be able to help / i can etc... (don't upload the jars however unless its in a private DM or something akin to that)

I already reported that on BlockInjector github issues, but I didn't get proper answer from him. He said that he has no idea why this is not working

Here is a link by the way: https://github.com/ItemsAdder/ItemsAdderBlocksInjector/issues/6

Also thanks for the help @NextdoorPsycho

**Comment by LoneDev6** [comment]
@Zemenus send here a zip file containing the a configuration folder of Iris for me to reproduce the issue with a simple custom block in the generators, I will test it.
Also include your Iris version information.

**Comment by NextdoorPsycho** [comment]
No Response, Feel free to reopen it and ill pass it on lol
