### ISSUE TITLE
Heads/item frames/armor stands don't copy with iris wand.

### ISSUE THREAD

**Issue by brandcrystal** [VolmitSoftware/Iris#934]
### Problem

1. Open an existing obj,
2. Place any custom object you wish, painting, custom head (head database), armor stand, item frame.
3. Create a save of this file and reopen it.
4. Heads are now steve basic skulls, everything else has gone.

### Solution

Capture unique NBT and entities during the time of copying.

### Minecraft Version

1.19

### Iris Version

v2.3.8-1.19.2

### Log

https://mclo.gs/BjBIsFu

**Comment by NextdoorPsycho** [comment]
Iris Objects aren't Copying Entities. 
This is planned for the eventual rewrite for iris, but not now.
