### ISSUE TITLE
100k+ entities for 80 tiles loaded (anyway very few tiles)

### ISSUE THREAD

**Issue by Broascaa** [VolmitSoftware/Iris#935]
### Problem

I don't really know what can i describe here beside of those entities.. Just watch the attached photo.
The "world_normal' is the Iris world
![image](https://user-images.githubusercontent.com/86567732/205511989-4b0ee371-18f5-45ee-8cef-8b76bd138aec.png)

### Solution

I tried MCA Selector and i filtered the chunks where are over 1k entities and this is what i found, but idk what can be there
![image](https://user-images.githubusercontent.com/86567732/205512092-00387d77-e3bc-47cf-99b0-4c848f0baa8b.png)

### Minecraft Version

1.19

### Iris Version

Iris v2.3.5-1.19.2

### Log

https://mclo.gs/r8o5dBG

**Comment by Broascaa** [comment]
Update, wrong photo on MCA Selector, this is the good one..
So 3 chunks have over 1k entities within them.. I think that this is the zone that crash the server too
![image](https://user-images.githubusercontent.com/86567732/205512283-3c81409a-2a2e-41f7-83ba-9851914ba1df.png)

**Comment by Broascaa** [comment]
UPDATE

On singleplayer i deleted those chunks and now i got this beatifule chunk error (ik what i mean :D).
Before i deleted the chunks i traveled with survival on that area (i couldn't execute any command) and i saw some animals in dying state (like they were red are flipped) but they never died and the map never saved and quit (i had to end task minecraft)

However, i can't upload on my live server something like this.. There has to be a solution without deleting the chunk..
![image](https://user-images.githubusercontent.com/86567732/205512890-02a4b0e0-dca2-4af3-b4c4-872dede93b7b.png)

**Comment by Broascaa** [comment]
Any updates please?
I need to delete those chunks every week.. The map has over 60 GB

**Comment by QuartzWarrior** [comment]
Nah bro, you've got all these entities while none are spawning on my server

**Comment by AdrijanPY** [comment]
> Nah bro, you've got all these entities while none are spawning on my server

**Same**

**Comment by svdgoor** [comment]
This should have been solved with the update on 4/7/23. If this is not the case please contact us on discord.
