### ISSUE TITLE
RealBiomeCondition - Update

### ISSUE THREAD

**Issue by Acrozi** [VolmitSoftware/Iris#936]
### Problem

I'm trying to get custom mobs spawns in overworld with Iris on my 1.19.2 but the plugin RealBiomeCondition supporting only 1.18.2. I did not find other solution to so i hope it's okay with you di write here.

Thank you for your work!

### Minecraft Version

1.19

### Iris Version

-

### Log

-

**Comment by NextdoorPsycho** [comment]
no, it works without needing realbiome as they merged it into mmobs
