### ISSUE TITLE
Iris pregenerator not completing as expected

### ISSUE THREAD

**Issue by ChipWolf** [VolmitSoftware/Iris#939]
### Problem

1. Install Iris v2.3.9-1.19.2 _(I used the prebuilt server zip available in the Iris wiki for repeatability's sake)_
2. Run `iris pregen start 3072 center=0,0 world=Iris_Server`
3. Wait for the pregeneration to complete.
4. Either observe region file sizes or complete a map render; then evaluate the lack of pregenerated chunks where you'd expect to see them.

![firefox_2022-12-17_11-49-52](https://user-images.githubusercontent.com/3164166/208240421-0c83b895-320d-4e43-9e6a-065bc67c2277.png)
![explorer_2022-12-17_11-53-12](https://user-images.githubusercontent.com/3164166/208240510-11e9bf20-7473-4e38-8a94-29716d2669ed.png)
![firefox_2022-12-17_11-53-29](https://user-images.githubusercontent.com/3164166/208240522-f8cec2f3-1c2d-4fef-8365-128370d7d483.png)

### Minecraft Version

1.19

### Iris Version

v2.3.9

### Log

N/A

**Comment by NextdoorPsycho** [comment]
Perhaps try NOT setting a few things, as that might be a problem and if so I can fix it.

For example, join the world and type
`/iris pregen start 3k`
or whatever
and tell me if that causes the same problem
