### ISSUE TITLE
Iris not detecting MythicMobs mobs in vscode 

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#945]
### Problem

Just open hop in ur studio environment and try to add a mm mob like a angry sludge you will see that it works perfectly fine but vscode/iris says otherwise..  
![Screenshot_20230105_162302](https://user-images.githubusercontent.com/107539181/210816833-dfce458c-8f7a-4def-a679-b56a0c6df166.png)

like its only in vscode everything works fine ingame 

OS: windows 11 

### Solution

Try to ignore it and realize that its impossible and then cry 

### Minecraft Version

1.19

### Iris Version

Iris 2.3.8 - 1.19.2  

### Log
[latest.log](https://github.com/VolmitSoftware/Iris/files/10353582/latest.log)

**Comment by NextdoorPsycho** [comment]
? it should work? Send me a MMobs settings or creature thing and ill try
