### ISSUE TITLE
Smaller chance for deposits than one per chunk

### ISSUE THREAD

**Issue by lukipukix** [VolmitSoftware/Iris#946]
### Adding, Removing, or Changing

Adding

### Type of Modification

Modification of deposits' rarity

### What are you trying to modify

I really need to make ore deposits on my server much more **rarer** than this is actually possible in Iris configuration. I want to make ore deposits on my server bigger but **rare** to make strategic points (renewable ores). This is server with nations and claiming territories, fighting for them - I need to make people fighting each other for something, give them some purpose.

My idea is to add one option in deposits' settings named something like "**chance**" to be able to make deposit appear less frequent than 1 deposit per 1 chunk. Ofc I am talking about deposits' settings in file: _\plugins\Iris\packs\overworld\dimensions\overworld.json_

### Alternatives

About alternatives... I don't really see any alternative option for this.

**Comment by RePixelatedMC** [comment]
Like this isnt a issue its with the engine and this is already possible to change just give me a ping at volmits discord server and il assist you further 

- RepixelatedMC

**Comment by NextdoorPsycho** [comment]
it is an issue with the engine, I for whatever reason set it to be min = 1. Fixed
