### ISSUE TITLE
Suggestion: Add functionality to be able to re-join studio worlds

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#95]
When leaving a studio world through /mv tp world, for example, there is no way to get back to said world without re-creating the studio. This takes a bunch of server time to set-up, which is why this would be very useful.

**Comment by cyberpwnn** [comment]
I usually used /world <TAB> to find it, but yeah ill add something for it

**Comment by cyberpwnn** [comment]
Added in 1.0.21 as /iris std tp (or /iris studio tp)
