### ISSUE TITLE
Caves with water when fluid palette = ice

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#955]
### Problem

![2023-02-08_08 40 37](https://user-images.githubusercontent.com/107539181/217465849-7c80ac4c-ce24-4c85-98ba-3427ca52a28f.png)

I dont think that i really need to explain more than this.. it can be problematic like when creating a nether dimension and you will get water pockets in there for example

### Solution

*

### Minecraft Version

1.19

### Iris Version

Iris - 2.3.14 

### Log

*

**Comment by NextdoorPsycho** [comment]
iirc you can specify the fluid and you can just set it to ice
