### ISSUE TITLE
Oraxen compatibility giving problem when pregen

### ISSUE THREAD

**Issue by SalomonPicos** [VolmitSoftware/Iris#956]
### Problem

Hello.

I was trying to pregen a Iris world using Oraxen to import 3 custom ores in the world but it's just impossible.

The server keep crashing because it runs out of memory and it uses A LOT of cpu.

As soon as i remove the oraxen blocks from the dimensions it works smoothly and without problems.

Hope you can give it a look, i really need to pregen the world  asap since we're going to release the new gamemode in a week.

### Solution

Problably messing up with oraxen and trying a bunch of things lmao

### Minecraft Version

1.19

### Iris Version

Iris v2.3.14-1.19.3

### Log

https://mclo.gs/xCYAR28

**Comment by NextdoorPsycho** [comment]
reworked it entirely please try on latest
