### ISSUE TITLE
Add seeds when creating iris world,New generated biome changed to 'Plains' after restarting the server

### ISSUE THREAD

**Issue by Illusionika** [VolmitSoftware/Iris#957]
### Problem

Steps to replicate this bug:
1. Install purpur-1.19.3-1912, start the server, stop the server
2. Install the Iris-2.3.14-1.19.3 plugin, start the server, automatically install the datapackage v2100, and automatically stop the server

3. Start the server, Use "/iris create name=XXX seed=XXX" create the iris world , and stop the server
* This seed must be added, like seed=1111 (do not use the default seed 1337), otherwise the bug cannot be replicate.

4. Start the server again, and then the new chunk is not normal ,all new biomes changed to plains

![3](https://user-images.githubusercontent.com/46653839/218606209-bec6dd54-ea54-4722-9d90-762199b4cb9f.png)
![4](https://user-images.githubusercontent.com/46653839/218606248-c295703b-e651-4500-ae33-cd586b5c89d9.png)

### Solution

A bug in the seed system ?

### Minecraft Version

1.19

### Iris Version

2.3.14

### Log

https://mclo.gs/jZJPf65
https://mclo.gs/AuU8y29

**Comment by NextdoorPsycho** [comment]
Please try on latest 2.5.0
