### ISSUE TITLE
Trees can spawn on top of caves' carving holes

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#965]
### Problem

Generate an Iris world
Find a cave that has a carved out area on the surface, larger is better, in a place with a lot of trees is best
Observe trees spawning ontop of the carved out area as follows:
![image](https://user-images.githubusercontent.com/65736624/220992236-17ebb599-aec7-4ec2-a711-32cde1119b63.png)
![image](https://user-images.githubusercontent.com/65736624/220992297-5445162a-f6b6-44fe-99bb-492ed84eb303.png)

Note that it is clear these objects are not spawning on a small 1x1 block that the carving missed.

### Solution

I'm looking at the code to generate everything, which looks like this:
```java
        registerStage(burst(
                sGenMatter,
                sTerrain
        ));
        registerStage(burst(
                sCave,
                sPost
        ));
        registerStage(burst(
                sDeposit,
                sInsertMatter,
                sDecorant
        ));
        registerStage(sPerfection);
```
From what I can see, `sCave` is not dependent on `sGenMatter`, but is dependent on `sTerrain`. `sGenMatter` generates the objects in the world. Neither sCave nor sPost is dependent on objects placed, but `sDeposit` and `sDecorant` are. Do you think it would be possible to change it to this:
```java
        registerStage(burst(
                sTerrain
        ));
        registerStage(burst(
                sCave,
                sPost
        ));
        registerStage(burst(
                sGenMatter
        ));
        registerStage(burst(
                sDeposit,
                sInsertMatter,
                sDecorant
        ));
        registerStage(sPerfection);
```
and then make `sGenMatter` be dependent on the result of cave generation, as to not place objects & jigsaw right above caves.
That way we could even make a setting for objects to only place in caves / at the height of the cave carving.

### Minecraft Version

1.19

### Iris Version

2.4.1-1.19.3

### Log

Nah

**Comment by NextdoorPsycho** [comment]
if you can get this to work feel free to, but iirc i explained the problems to you with this already
