### ISSUE TITLE
Hover over commands not working

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#968]
### Problem

1. Install Iris...
2. `/iris`
3. hover over with your mouse
<nothing>

### Solution

Not sure. Perhaps the AdventureAPI is just outdated or broken or it's an MC issue, idk.

### Minecraft Version

1.19

### Iris Version

2.4.1-1.19.3

### Log

Nah

**Comment by NextdoorPsycho** [comment]
Will be fixed in the next upodate :)
