### ISSUE TITLE
Sculk veins brake in paint mode 

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#969]
### Problem

![2023-02-26_19 59 55](https://user-images.githubusercontent.com/107539181/221431082-483b1e8a-5aaa-4670-b99b-fc81208264f6.png)

Not much explaining to do lol

### Solution

just not using paint or veins 

### Minecraft Version

1.19

### Iris Version

2.3.14 Iris

### Log

*

**Comment by NextdoorPsycho** [comment]
read other issues before you make your own
