### ISSUE TITLE
Bug: Iris studio mode occasionally popping in different chunks

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#97]
![afbeelding](https://user-images.githubusercontent.com/65736624/96598183-e6491e00-12ee-11eb-947e-b56c0de03e2e.png)

We saw a couple blocks of this in earlier tests together. Not too high priority I'd say, but you do you.

**Comment by svdgoor** [comment]
(If this prevents a crash, keep it)

**Comment by svdgoor** [comment]
Update: seems to be caused by hotloading & generating chunks at the same time

**Comment by cyberpwnn** [comment]
It only happens during hotloading. If iris needs to generate it has to give something. It would crash if you wanted this gone. Im working on better locking mechanisms so hotloading waits for an opening to refresh the generator.
