### ISSUE TITLE
Iris cave biomes cant generate caves 

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#971]
### Problem

Try to set carving in cave biomes it simply wont work. It would be nice to have it so it would be possible to make a deepdark etc

### Solution

Just dont use it and use instead the traditional "put the carving in regions" thing. 

### Minecraft Version

1.19

### Iris Version

Iris 2.4.1

### Log

*

**Comment by NextdoorPsycho** [comment]
use your solution, i dont know what this issue means because you have given me so little information
