### ISSUE TITLE
Iris Studio vscode

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#972]
### Problem

Iris studio vscode wont work on 1.76+ it wont autocomplete / just not even showing up.

### Solution

Downgrade version

### Minecraft Version

1.19

### Iris Version

Iris 2.4.1

### Log

*

**Comment by NextdoorPsycho** [comment]
1.76 of what?

**Comment by RePixelatedMC** [comment]
> 1.76 of what?

Vscode version
