### ISSUE TITLE
Memory leak by Sven#8036

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#976]
### Problem

1. Install Iris
2. Run the server.
3. Notice the server's RAM running full after simply exploring the Iris world (from 4GB to 8GB consumed).

### Solution

I cannot figure out this memory leak based on his [heap dump](https://we.tl/t-qWZ2KujGGw).

### Minecraft Version

1.19

### Iris Version

v2.4.1-1.19.3

### Log

[message(2).txt](https://github.com/VolmitSoftware/Iris/files/10889567/message.2.txt)

**Comment by NextdoorPsycho** [comment]
cant see the heap dump

**Comment by svdgoor** [comment]
Asked if he can provide it again.

**Comment by belzzebuh** [comment]
I have the same problem, iris uses too much RAM, I will try to find my dump and share it as it happened to me about 1 week ago and I deleted it.

**Comment by belzzebuh** [comment]
I think this may give you more information:

https://www.mediafire.com/file/zt0ldwu66gs0pni/heap-2023-03-06_00.19.10.hprof/file 

@NextdoorPsycho

**Comment by NextdoorPsycho** [comment]
Please try on latest
