### ISSUE TITLE
/iris object paste not working

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#977]
### Problem

1. Install Iris...
2. Run /iris object paste object=clutter/arbusto1 (the first suggestion)
3. Observe nothing is placed & an error appearing in the log

### Solution

Not sure

### Minecraft Version

1.19

### Iris Version

2.4.1-1.19.3

### Log

https://mclo.gs/vg1KG5n#L246

**Comment by RePixelatedMC** [comment]
same issue

**Comment by NextdoorPsycho** [comment]
this is a decree issue, ill look into it

**Comment by svdgoor** [comment]
Only partially, @NextdoorPsycho. There's an NPE on a method if you look a bit further down the stacktrace.

**Comment by svdgoor** [comment]
Looks like it's in my new code. Wasn't expecting an argument to be null randomly sometimes, but I can see how it makes sense (you cannot poll slope stuff when just placing an object). I have made a check for if the data is null and opened a PR [here](https://github.com/VolmitSoftware/Iris/pull/986).
Looks like every other instance where `rdata` may be null is never triggered in the event the object is pasted. Please annotate your methods better, Dan.
