### ISSUE TITLE
Slope Condition Doesnt exist on Objects anymore

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#979]
### Problem

Only "rotateTowardsSlope": , shows up not slopecondition it was there before i dont know if it was intentionally removed or not.

### Solution

*

### Minecraft Version

1.19

### Iris Version

2.4.3-1.19.3

### Log

*

**Comment by NextdoorPsycho** [comment]
Will be in next update 2.5.1 probably

**Comment by RePixelatedMC** [comment]
Coco alr fixed it he even gave me the jar
