### ISSUE TITLE
Bug: Big error with playerinteractevent

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#98]
https://pastebin.com/Y3JUR9SB

Log by @Roy! in Discord
I had this happen to me too, but forgot to post (I can try reproducing it if need-be)

**Comment by roy** [comment]
I didn't log anything ;)

**Comment by svdgoor** [comment]
@roy Unless you are Roy!#2121 on Discord, my apologies for the ping. Fijne dag nog :)

**Comment by roy** [comment]
Haha no worries, this handle gives me a lot of spam.

Jij ook een fijne dag toegewenst ;)

**Comment by cyberpwnn** [comment]
This was already fixed in 1.0.20 (update)
