### ISSUE TITLE
Compilation fails for v2.5.0

### ISSUE THREAD

**Issue by Vilican** [VolmitSoftware/Iris#987]
### Problem

1. Run `gradlew setup`
2. Run `gradlew iris`

### Minecraft Version

1.19

### Iris Version

2.5.0-1.19.4

### Log

https://pastebin.com/raw/vbpmZcGi

**Comment by jeffl1ma** [comment]
I have the same compilation problem, when starting gradlew iris gives error in CompileJava

**Comment by NextdoorPsycho** [comment]
fixed
