### ISSUE TITLE
Add support for MythicCrucible Custom Blocks

### ISSUE THREAD

**Issue by The-Nyla** [VolmitSoftware/Iris#991]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to be able to add MythicCrucible custom blocks.

### What are you trying to modify

Mainly I just want to be able to use MythicCrucible for custom blocks, as the MythicCrucible/Mythicmobs plugins are more stable than IA or Oraxen, and so I prefer using Crucible for my custom blocks.

### Alternatives

Use IA or Oraxen

**Comment by CrazyDev05** [comment]
If you want you can contact me on discord, then I can give you a test version with MythicCrucible implementation

**Comment by The-Nyla** [comment]
I don't have discord, if you can send me a copy here I'd be happy to test it, but if not I'd just like to know if it is planned or not. Thank you!

**Comment by CrazyDev05** [comment]
Sry for the late response, i wasn't at my pc the last week.
Here is my test file [Redacted]
You first need to extract the zip cause github doesn't allow jar files

**Comment by NextdoorPsycho** [comment]
> Sry for the late response, i wasn't at my pc the last week. Here is my test file  You first need to extract the zip cause github doesn't allow jar files

I appreciate the sharing, but next time please make a PR, and i can even merge it. but don't distribute the JAR here on github, or anywhere else for that matter. Iris is opensource, but we have had a few situations where malware was being spread this way. if you PR your solution ill gladly implement it.

**Comment by CrazyDev05** [comment]
i understand, sorry

**Comment by NextdoorPsycho** [comment]
> i understand, sorry

thats ok, no harm done, i looked over the jar and it was fine, but you get what i mean.
However, if you would like to make a PR you are more than welcome to! but for now closing this
