### ISSUE TITLE
[Question] Iris loot generation event

### ISSUE THREAD

**Issue by fnrcum** [VolmitSoftware/Iris#993]
Does Iris fire any events when generating loot in chests based on the defined loot tables?

To be more precise, Vanilla fires a LootGenerate Event when this happens which can be intercepted to do certain things. If I would want to inject something from my plugin into that loot table that's about to be added to a chest, can I do that? 

Also if there are such events, are they separated by custom structure like Vanilla?

**Comment by NextdoorPsycho** [comment]
no, but if you have a plugin you can add it to the item system we have that adds support for custom items and you can add it to preexisting or make your own loot tables in the pack's discretion
