### ISSUE TITLE
DNS Resolution Issue Preventing Access to Plugin Documentation

### ISSUE THREAD

**Issue by GuilhermeWerner** [VolmitSoftware/Iris#997]
### Problem

I am experiencing difficulties accessing the VolmitSoftware/Iris repository due to a DNS resolution problem with the associated websites. Both https://volmit.com and https://docs.volmit.com are failing to resolve their DNS, even after attempting to change my DNS settings and accessing them through a 4G connection. This issue persists even for external websites attempting to access the mentioned URLs.

## Steps to Reproduce:

1. Attempt to access https://volmit.com or https://docs.volmit.com via a web browser.
2. Note that the websites fail to resolve the DNS, resulting in a connection timeout error.
3. Confirm the issue by trying to access the websites through different DNS settings or a different network connection.
4. Additionally, check if external websites or tools can successfully access the mentioned URLs.

## Expected Behavior:
The websites associated with the Iris repository, should resolve their DNS and be accessible without any issues.

## Actual Behavior:

Both are failing to resolve their DNS, rendering them inaccessible. This issue persists even after attempting to change DNS settings and accessing them through a different network connection. External websites or tools also face the same issue when attempting to access the mentioned URLs.

![image](https://github.com/VolmitSoftware/Iris/assets/26710260/22b1d595-f992-4eac-be3e-f4008464b9c4)
![image](https://github.com/VolmitSoftware/Iris/assets/26710260/50717e1d-4dab-49d7-8dc0-358d605c0c41)
![image](https://github.com/VolmitSoftware/Iris/assets/26710260/508ab7d5-9cf6-4eda-a3e1-2c47ff0330a2)

## Additional Information:
Operating System: Windows 11 and Android
Web Browser: Google Chrome
DNS Settings: Google 8.8.8.8 and Cloudflare 1.1.1.1

Other troubleshooting steps attempted: 

### Digital Ocean DNS Lookup

![image](https://github.com/VolmitSoftware/Iris/assets/26710260/98cfa511-aba6-409e-838d-eb5719cd2fb7)

### DNS Checker Lookup

![image](https://github.com/VolmitSoftware/Iris/assets/26710260/790369b3-6165-416a-b6f5-785df634f836)
![image](https://github.com/VolmitSoftware/Iris/assets/26710260/c0c45c66-de4c-4109-930d-dfc4c7a6f72b)

### NsLookup.io

![image](https://github.com/VolmitSoftware/Iris/assets/26710260/18eda3d2-a1d2-4f94-bf03-c421064ee224)

### Solution

Upon investigating the DNS resolution issue for the VolmitSoftware websites, it appears that there may be a misconfiguration in the domain setup.

### Minecraft Version

1.18

### Iris Version

ANY

### Log

ERR_NAME_NOT_RESOLVED

**Comment by svdgoor** [comment]
Solved. docs.volmit.com/iris/getting-started.
