### ISSUE TITLE
Animals do not seem to spawn

### ISSUE THREAD

**Issue by haappi** [VolmitSoftware/Iris#998]
1. Install Iris.
2. Pregen a reasonable amount to test with
3. Move around a bit and try teleporting to animals.
4. Observe that no animals seem to spawn (only monsters)

# Minecraft Version
1.20.1
# Iris Version
Iris v2.7.1-1.20.1
# Log
https://mclo.gs/We2z95y

**Comment by svdgoor** [comment]
This should have been fixed as of 4/7/2023. If the issue still persists in that version please contact us on Discord so we can see if we can find a solution.
