### ISSUE TITLE
Iris crash on startup

### ISSUE THREAD

**Issue by EEize** [VolmitSoftware/Iris#999]
### Problem

1. Install Iris...
2. Start the server
3. Observe the crash

### Minecraft Version

1.19

### Iris Version

2.7.2-1.20.1

### Log

https://mclo.gs/4eXXfoU

**Comment by RePixelatedMC** [comment]
give a proper log please

**Comment by EEize** [comment]
> give a proper log please

here https://mclo.gs/6OD3tD9

**Comment by Minecon724** [comment]
same error

**Comment by RePixelatedMC** [comment]
compiled or bought

**Comment by EEize** [comment]
> compiled or bought

compiled

**Comment by vigil33t-cmd** [comment]
same error

**Comment by svdgoor** [comment]
You cannot load Iris 1.20 on 1.19 people, you need another version, see [this discord message with an explanation](https://discord.com/channels/189665083817852928/1057283703258239016/1058430139039485993).
Also we do not provide support with compiling the plugin. If you are experiencing an issue while we are not, you're out of luck unless you can fix it yourself.

**Comment by Minecon724** [comment]
I am on paper 1.20 tho

**Comment by svdgoor** [comment]
Then the second part of the comment I left applies to you.
